### ISSUE TITLE
"startY" doesn't apply consistently when adding HorizontalPageBreak 

### ISSUE THREAD

**Issue by MariKcuda** [simonbengtsson/jsPDF-AutoTable#1004]
This becomes a problem when adding headers to the PDF. As you can see in the screenshots the table overlaps the heders when using HorizontalPageBreak on the second page. 

<img width="531" alt="Screenshot 2023-10-11 at 5 22 36 PM" src="https://github.com/simonbengtsson/jsPDF-AutoTable/assets/102396025/5617daa3-5ce6-40d2-8b0c-bcf5210e5f8a">

Is there a way to apply a custom position on all pages when using HorizontalPageBreak?

 https://github.com/simonbengtsson/jsPDF-AutoTable/blob/4c04f6a089b9dea919e84fee5fff649552cd49b8/examples/examples.js#L654-L662

_Originally posted by @mmghv in https://github.com/simonbengtsson/jsPDF-AutoTable/issues/690#issuecomment-1743460468_

**Comment by mmghv** [comment]
`startY` is used to offset the first page _only_ in situations where you want to start printing after previous page content, but for repeating headers use `margin: {top: 30}`

https://github.com/simonbengtsson/jsPDF-AutoTable#other-options
