### ISSUE TITLE
JavaScript string+\n not fitting well cell space using JavaScript data

### ISSUE THREAD

**Issue by AlexGoMa** [simonbengtsson/jsPDF-AutoTable#1009]
[Related to issue 979:](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/979)

Looking at fitcontent function in widthCalculator.ts, in the overflow: 'linebreak' option it is called **splitTextToSize**:

```
if (cell.styles.overflow === 'linebreak') {
        // Add one pt to textSpace to fix rounding error
        cell.text = doc.splitTextToSize(
          cell.text,
          textSpace + 1 / doc.scaleFactor(),
          { fontSize: cell.styles.fontSize },
        )
      }
```

From what I have read in jspdf documentation, [splitTextToSize](https://www.euritmia-ocupacional.org/Plugins/html2pdf-js/jsPDF-master/docs/module-split_text_to_size.html#~splitTextToSize) doesn't have in consideration \n , so maybe that's the reason  why when halign="center" is set, the text occupies the vertical space without line breaks, but if there are line breaks the content is overwritten.

What I have not still found, is why if halign = "left" is applied to styles, the text overrides \n and fits content.

**Comment by simonbengtsson** [comment]
Do you have an example with the issue you are researching? Do you mean that something like does not fit cell space in some way?

```js
autoTable(doc, {
  styles: { halign: 'center' },
  body: [['Demo content \n line break character']]
})
```
