### ISSUE TITLE
Exporting an SVG element

### ISSUE THREAD

**Issue by manuraj17** [simonbengtsson/jsPDF-AutoTable#101]
Hello,

I have a pie chart and bar graph generated as SVG elements. Would it be possible to export them along with the table, adding them before the table starts in the PDF? 

Thanks,
Manu

**Comment by simonbengtsson** [comment]
If you can add them using jspdf, you can add them with this plugin. Simply use the `afterContent` or `beforeContent` hooks.

**Comment by manuraj17** [comment]
Oh okay, alright. Also am struggling a bit with the hooks. How do I control the styling inside the hooks,any small snippet to explain?

**Comment by simonbengtsson** [comment]
You can check the examples for more info on the hooks. Especially interesting for you is probably the custom styles example.

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to reopen if you are still having issues.

**Comment by ALFRED-Guillaume** [comment]
Hello,

Is it possible to export SVG elements inside data ? I'm trying to have a column that should show a a bar graph for each rows.

Something like : 
<svg width="value" height="30px">
    <g class="bars"> 
        <rect fill="#4cae4c" width="value" height="15"></rect>
    </g> 
</svg>

Is there a solution for that using jsPDF-AutoTable ?

Thanks in advance.

**Comment by simonbengtsson** [comment]
If you mean that you have a svg element in the html table cell you can access it something like this:

`cell.raw.querySelector("svg")`

`cell.raw` is set to the html element since version `2.2` released yesterday.

**Comment by ALFRED-Guillaume** [comment]
Thank you @simonbengtsson 

Actually, I pass my data to autoTable : 
doc.autoTable( columns, data, {
            ...
        });

**Comment by ALFRED-Guillaume** [comment]
I have tried to pass an HTMLElement containing my svg to my data but couldn't make it work :(

**Comment by simonbengtsson** [comment]
Aha! Then you can probably do something like this:

```js
doc.autoTable(cols, data, {
    createdCell: function(cell, data) {
        var elem = cell.raw.querySelector("svg");
        cell.text = elem.textContent;
    }
});
```

**Comment by ALFRED-Guillaume** [comment]
I'm sorry but I can't make it work :-(

I have tried a lot of different ways to create my SVGElement but textContent is always empty. I have tried to get values from other properties of cell.raw but without more sucess.

**Comment by simonbengtsson** [comment]
Can you post the html of your svg element?

**Comment by ALFRED-Guillaume** [comment]
Sure, 
`<svg width="50px" height="30px"><g class="bars"><rect fill="#cb4d3e" x="0" width="50" height="15"></rect></g></svg>`

**Comment by simonbengtsson** [comment]
There is no support for printing svg natively in jspdf as far as I know. But if you find a way to do it with jspdf you could do it something like this with this plugin:

```js
doc.autoTable(columns, data, {
    drawCell: function(cell) {
        doc.rect(cell.x, cell.y, cell.width, cell.height);
        let svgElem = cell.raw;
        // Here you have to find a way to print the svg element to the pdf 
        return false;
    }
});
```
