### ISSUE TITLE
inline css not apply in get html table

### ISSUE THREAD

**Issue by nileshjadhav8897** [simonbengtsson/jsPDF-AutoTable#1014]
getReport()
  {
    const report = new jsPDF('p', 'pt', 'a4');
    autoTable(report,{html:'#table',tableId:'table'})
  report.output('pdfobjectnewwindow')
  }
  <table id="table">
            <thead>
              <tr>
                <th >header1</th>
                <th>header2</th>
                <th style="color: aqua;">header3</th>
              </tr>
             </thead>
             <tbody>
               <tr>
                 <td>text1.1</td>
                 <td>text1.2</td>
                 <td>text1.3</td>
               </tr>
               <tr>
                 <td>text2.1</td>
                 <td>text2.2</td>
                 <td>text2.3</td>
               </tr>
               <tr>
                 <td style="color: aqua;">text3.1</td>
                 <td>text3.2</td>
                 <td>text3.3</td>
               </tr>
               <tr>
               </tr>
            </tbody>
          </table>
[download.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/13583725/download.pdf)

**Comment by simonbengtsson** [comment]
Looks like you are using values not supported by the plugin.

**Comment by nileshjadhav8897** [comment]
> Looks like you are using values not supported by the plugin.

how to apply CSS in table
