### ISSUE TITLE
Font Awesome Icons Not Displayed in PDF

### ISSUE THREAD

**Issue by SnRoma5** [simonbengtsson/jsPDF-AutoTable#1016]
Hello,

I've been using jsPDF-autotable for years to save HTML tables as PDF, and it has been working seamlessly. Thank you for that!

However, I have Font Awesome icons, specifically checkbox icons (checked and empty), in my HTML table. Unfortunately, these icons are not displayed in the generated PDF file.

Is jsPDF-autotables capable of supporting multiple fonts simultaneously?

Thank you for your assistance!

**Comment by simonbengtsson** [comment]
Interesting question. If it works in jspdf it should work in autotsble. I have not tried it though so if you do let me know how it goes!
