### ISSUE TITLE
Control of width of every column?

### ISSUE THREAD

**Issue by AppWerft** [simonbengtsson/jsPDF-AutoTable#102]
How can I solve it. I did found a option parameter. RTFM?

**Comment by simonbengtsson** [comment]
Haha... There is the columnWidth style you can use for that.

**Comment by AppWerft** [comment]
Oh, I see: 'dataKey'

**Comment by AppWerft** [comment]
I'm back again ;-)
My question: if I use the object form of headers with dataKey do I need to use the object form of datas – or can I use mixed?

**Comment by simonbengtsson** [comment]
I thinks it checks it row by row so should be fine. If you have further usage questions I would recommend posting on stackoverflow. In the future I will try to keep Github issues to bugs or other issues with the plugin.
