### ISSUE TITLE
Como puedo cambiar la localizacion de la tabla en el eje x?

### ISSUE THREAD

**Issue by fermin23** [simonbengtsson/jsPDF-AutoTable#1024]
I am trying to change the left margin that by default is added to the tables when they are created but I cannot do it in any way, I define the left margin at 0 but it continues to appear in each table that I create, I should be able to change that property at will but not how to do it

**Comment by mmghv** [comment]
You can easily change the left margin:

```js
autoTable(doc, {
  //
  margin: {left: 0},
})
```
