### ISSUE TITLE
you can apply RTL and use Arabic font finally 

### ISSUE THREAD

**Issue by muhamedhsn92** [simonbengtsson/jsPDF-AutoTable#1025]
first I want to thanks who work on this amazing library . 
my journey to solve this problem to can write arabic and use this library to generate table take long time so I will give you last notes .
first you can use font with JSPDF and load it by using addFileToVFS using this stackoverflow link 
https://stackoverflow.com/questions/66650516/using-arabic-characters-in-jspdf
and use converter to convert font file to code then use it inside jspdf by using this method 
you can store code generated from converter website inside file and import it inside this method 
addFileToVFS
like this 

        jspdf.addFileToVFS(  'file_name_generated_from_converter_website.ttf',  font_code_imported_from_file_you_created   );
then 
 doc.addFont('alfont_com_Ubuntu-Arabic_R-normal.ttf', 'alfont_com_Ubuntu-Arabic_R', 'normal');
        doc.setFont('alfont_com_Ubuntu-Arabic_R');

here is the magic comming 

     autoTable(doc.setFont('alfont_com_Ubuntu-Arabic_R'), {
            head: [columns],
            body: tableData,
            startY: 90,
            headStyles: {
                halign: 'right'
            },
            bodyStyles: {
                halign: 'right'
            },
            styles: {
                font: 'alfont_com_Ubuntu-Arabic_R',

                // direction: 'rtl',
            }

        })
you can set font to jspdf used inside autoTable and set heade style halign to right and body style halign to right 
the you will get table with 
arabic support and direct to right 
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/35297160/9c71ac6a-1e89-4df9-8780-677b612f424d)

**Comment by mmghv** [comment]
thanks for sharing, hope this helps someone.

**Comment by 0xelsherif** [comment]
can you provide the full code snippet @muhamedhsn92 if you please case i have the same issue?
