### ISSUE TITLE
Using jsPDF autoTable Change cell coloring in pdf file.

### ISSUE THREAD

**Issue by SanjuLax** [simonbengtsson/jsPDF-AutoTable#103]
Using jsPDF autoTable how can I change a cell color based on another cell value in the same row.. Please help! Great plug-in by the way..

**Comment by simonbengtsson** [comment]
Thanks! Using the `drawCell` hook you get the data from the other cells in the same row in the `data.row.cells` or `data.row.raw` variables. In general you can check the contents of data parameter and you will hopefully find what you are looking for.

**Comment by SanjuLax** [comment]
Thanks Simon!
I am able to access the values of the adjacent  cells. But my conditions involve accessing column names too.. 
Basically I need to color a cell with a condition (that involves both cell value and its column name).
I tried to access column names in drawCell but been unsuccessful.. Can you please advice!

Thank a bunch..

**Comment by simonbengtsson** [comment]
Okey! Try `data.table.headerRow.cells`.

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to reopen if you are still having issues.

**Comment by brahimkra** [comment]
How can i change color background  of second column??

**Comment by Muhammadsher** [comment]
` createdCell: function(cell, data) {
            if (data.column.dataKey === "columnDataKey") {
                {
                        cell.styles.fillColor = [r,g,b]
                }
            }
    }`

**Comment by ankit-sirpi** [comment]
How can I change style of a column of a row based on value of another column of the same row?
