### ISSUE TITLE
HTML Entities or HEX Code issues for symbols

### ISSUE THREAD

**Issue by MROVIC** [simonbengtsson/jsPDF-AutoTable#1035]
I found issues with some html entities (or am I wrong?)

In jsPDF here are just few symbols/chars that don't work, in my case:
≥ (Greater-Than or Equal To) : no way found;
≤ (Less-Than or Equal To) : no way found;
∼ (Tilde Operator) : it can be read as char or ASCII (not as html entity) .

For the above I tried the standard char, ASCII, html entity, html and hex codes:
the result is always the same, they are rendered wrongly (here attached a test screenshot).

They're important: I need them because my tables are chemical specification sheets and limit values must be expressed with these symbols.
Any suggestion please? Thank you.

![symbols_test ](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/39498395/ecde869e-b98e-4698-be92-cf292e916bd2)

**Comment by MROVIC** [comment]
UPDATE:
After several tests, among the few symbols that are not interpreted correctly by jsPDF, I was only able to resolve for the "Tilde Operator" symbol with &#126;
in cases where jsPDF does not read utf-8 or html correctly, it reads ASCII correctly: too bad that the other symbols (such as ≥ or ≤) are not present in the ASCII table.
(Thank you)

**Comment by MROVIC** [comment]
![symbols_in_fonts](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/39498395/1d115db9-a125-4523-836f-31c7aa9494a4)

**Comment by simonbengtsson** [comment]
Weird! Since I believe this is related to jsPDF and not this plugin I'll tag as question.

**Comment by MROVIC** [comment]
@simonbengtsson you're right, in fact I sent it also to jsPDF, correct to tag this here as question (sorry).
yes, it is very strange indeed: actually jsPDF 2.5.1 readme.md says:
" The 14 standard fonts in PDF are limited to the ASCII-codepage. ", and actually "_Greater-Than Or Equal To_" and "_Less-Than Or Equal To_" are **NOT** included in ASCII table.
But:
1) the issue affects also the "_Tilde Operator_", which is in ASCII (actually read as ASCCI and not html entity)
2) if only ASCII, why for the other symbols jsPDF reads hex, html entity, all?

These are my questions.
Given the case, I guess that my only solution is to add base64 for the missing symbols.
But if someone can suggest me a better solution, welcome with thanks !

**Comment by MROVIC** [comment]
nobody replied in Parallax: I minimized a "calibri" font to the strictly necessary and added a second font as base64 to have those symbols): only way, because the jsPDF standard are based on ASCII, i.e. they miss some symbol ... for me this should be an official issue, but it seems nobody cares of this detail
(compliments for autoTable: it is great!)
