### ISSUE TITLE
表格项合并时表格项与表头信息不对应

### ISSUE THREAD

**Issue by 18795891073** [simonbengtsson/jsPDF-AutoTable#1049]
自定义了如下的表格数据：arr = [
  [
    { content: '1', colspan: 1, rowspan: 1 },
    { content: '1', colspan: 1, rowspan: 1 },
    { content: '1', colspan: 1, rowspan: 1 },
  ],
  [{ content: '1', colspan: 1, rowspan: 1 }, { content: '1', colspan: 1, rowspan: 1 }, { content: '1', colspan: 1, rowspan: 1 },]
];结果会按照colspan和rowspan的值绘制当前单元格，但发现并不是真的合并，而是将原单元格向后挤压了一个位置，导致表格错位

**Comment by mmghv** [comment]
English please!

I only see `colspan` & `rowspan` of 1 here, which is the default value anyway, so this shouldn't result in any merging of cols or cells.
