### ISSUE TITLE
first column has padding which is impossible to remove

### ISSUE THREAD

**Issue by PruthviKumarBK** [simonbengtsson/jsPDF-AutoTable#105]
HI, 

Great library, Thanks for helping the world with nightmare of dealing with tables and PDF conversion. 

I have this wierd issue where first column's contents are not getting left aligned at all. There is some amount of padding flowing in despite me wanting to! I have tried many ways to have it removed but cant get through.

Here is the hardcoded table and Screen print of what i get:

<table id="idTbl_Cftc_Fig1" class="display">
                      <thead>
                        <tr>
                           <th id="idTh1_Cftc_Fig1"> Contracts ('000)* </th>
                           <th id="idTh3_Cftc_Fig1"> 12-Jan-16 </th>
                           <th id="idTh3_Cftc_Fig1"> 5-Dec-16 </th>
                           <th id="idTh3_Cftc_Fig1"> Weekly Change </th>                           
                           <th id="idTh4_Cftc_Fig1"> Z Score*** </th>
                        </tr>                       
                      </thead>
                      <tbody>
                        <tr id="idTr1_Cftc_Fig1" class="tbl_rowBorder">
                          <td id="idTr1Td1_Cftc_Fig1" style="font-weight:bold;">
                            Currencies - Majors
                          </td>
                          <td id="idTr1Td2_Cftc_Fig1">
                            
                          </td>
                          <td id="idTr1Td3_Cftc_Fig1">
                            
                          </td>
                          <td id="idTr1Td4_Cftc_Fig1">
                            
                          </td>
                          <td id="idTr1Td5_Cftc_Fig1">
                            
                          </td>
                        </tr>
                        <tr id="idTr2_Cftc_Fig1" class="tbl_rowBorder">
                          <td id="idTr2Td1_Cftc_Fig1">
                            EUR
                          </td>
                          <td id="idTr2Td2_Cftc_Fig1">
                            -107.9
                          </td>
                          <td id="idTr2Td3_Cftc_Fig1">
                            -119.1
                          </td>
                          <td id="idTr2Td4_Cftc_Fig1">
                            11.2
                          </td>
                          <td id="idTr2Td5_Cftc_Fig1">
                            -0.15
                          </td>
                        </tr>
                        <tr id="idTr2_Cftc_Fig1" class="tbl_rowBorder">
                          <td id="idTr2Td1_Cftc_Fig1">
                            JPY
                          </td>
                          <td id="idTr2Td2_Cftc_Fig1">
                            -0.2
                          </td>
                          <td id="idTr2Td3_Cftc_Fig1">
                            -24.4
                          </td>
                          <td id="idTr2Td4_Cftc_Fig1">
                            24.2
                          </td>
                          <td id="idTr2Td5_Cftc_Fig1">
                            2.33
                          </td>
                        </tr>

table continues on the same lines.

I have used data table to render it upfront and code for auto table init is as follows:

 pdfTblObj.autoTable(getJsonObjForAutotable['columns'],getJsonObjForAutotable['rows'],{tableWidth: 'wrap',
            styles: {overflow:'linebreak',columnWidth:'wrap'},
            headerStyles: {rowHeight: 15, fontSize: 7,valign:'middle',halign:'center'},
            bodyStyles: {rowHeight: 1, fontSize: 6,valign:'middle',halign:'right'},
            columnStyles : {0:{columnWidth: 'auto',halign:'left'}},
            pageBreak: 'avoid'           
          });
          pdfTblObj.save('table.pdf');

result obtained:

![image](https://cloud.githubusercontent.com/assets/11025372/12388244/c1e0f7fa-bdf7-11e5-8725-aa0818e89d17.png)

What is wrong with the first column!!! 

Thank you for your help

Best,
Pruthvi

**Comment by simonbengtsson** [comment]
Can you share the output of `getJsonObjForAutotable` and `getJsonObjForAutotable` so that it becomes easier for me to reproduce this? The best would be if you can use the codepen linked in the readme to reproduce the issue.

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to reopen if you are still having issues.
