### ISSUE TITLE
Cannot Read html tags

### ISSUE THREAD

**Issue by awyaawya** [simonbengtsson/jsPDF-AutoTable#1052]
cannot read html tags like <u>Underline Me</u>.
It displays as it is in the output it does not underline the words.

when using:

import jsPDF from 'jspdf'
import 'jspdf-autotable'

const doc = new jsPDF()
doc.autoTable({ html: '#my-table' })
doc.save('table.pdf')

**Comment by mmghv** [comment]
Underline is not supported by AutoTable, only [supported styles](https://github.com/simonbengtsson/jsPDF-AutoTable#:~:text=the%20columns%20property-,StyleDef,-%3A) are parsed.
