### ISSUE TITLE
Merge Cell Inside the body of the table

### ISSUE THREAD

**Issue by bonbonsiregar** [simonbengtsson/jsPDF-AutoTable#1054]
Is there a built in function for merging cells inside the body of autotable? In header we can do that using rowspan and colspan and set halign and valign value, but i can't seem to find a workaround to modify the cells.

this is what i managed to do
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/24790743/ea2b759c-3c4d-4224-af34-48fc48ae6b94)

and this is what i expected
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/24790743/621c77c4-8d6c-4a94-b61b-8c9dbd3cf897)

I don't need the excess horizontal line if the cell is empty.

**Comment by mmghv** [comment]
You can do the same for the body cells as the header

Example: 
https://simonbengtsson.github.io/jsPDF-AutoTable/#spans

Docs:
https://github.com/simonbengtsson/jsPDF-AutoTable#:~:text=Usage%20with%20colspan%2C%20rowspan
