### ISSUE TITLE
Inconsistent Table Width Across Pages When Exporting Using jsPDF-AutoTable

### ISSUE THREAD

**Issue by Brunapupo** [simonbengtsson/jsPDF-AutoTable#1057]
Could you help me configure the horizontal margin so that the table size remains consistent on all pages in HTML when exporting? I am using jsPDF-AutoTable for this purpose.

I'm using jsPDF-AutoTable to export tables, and I'm facing an issue with configuring the horizontal margin. The problem is that the table width is not consistent across all pages. When there is extra space, I want the table size to remain the same on each page.

Could someone please guide me on how to configure the horizontal margin to achieve consistent table width across pages? 

```
const exportarParaPdf = (rows) => {
    if (!columns || columns.length === 0 || !rows || rows.length === 0) {
      console.error("Tabela não encontrada para exportação.");
      return;
    }
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "pt",
      format: "a4",
    });
    const tableColumn = ["#", ...columns.map((col) => col.header)];
    const tableRows = rows.map((row, index) => [
      index + 1, // Adiciona o número da linha
      ...columns.map((col) => row.getValue ? row.getValue(col.accessorKey) : row.original[col.accessorKey])
    ]);
    
    const totalPagesExp = "{total_pages_count_string}";
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    const larguraPagina = doc.internal.pageSize.getWidth();
    const alturaPagina = doc.internal.pageSize.getHeight();
    const margem = 60;
    const titulo =
      "ESTADO DE SANTA CATARINA\nSECRETARIA DE ESTADO DA SAÚDE\nSUPERINTENDÊNCIA DE SERVIÇOS ESPECIALIZADOS E REGULAÇÃO\nCENTRAL ESTADUAL DE TELEMEDICINA\n\nRelatórios de Dados ";
    
      doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      columnStyles: { halign: 'center' }, 
      horizontalPageBreak: true,
      horizontalPageBreakRepeat: 0,
      margin: { top: 130, right: margem, bottom: 40, left: margem },
      tableWidth: larguraPagina - 2 * margem,
      didDrawPage: (data) => {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(titulo, larguraPagina / 2, 30, { align: "center" });
        let textoRodape = "Página " + data.pageNumber;
        if (typeof doc.putTotalPages === "function") {
          textoRodape = textoRodape + " de " + totalPagesExp;
        }
        doc.text(textoRodape, larguraPagina - margem - 100, alturaPagina - 10);
      },
    });
    if (typeof doc.putTotalPages === "function") {
      doc.putTotalPages(totalPagesExp);
    }
    doc.save("table_data.pdf");
  };  
```

**PDF EXPORT:** [table_data (27).pdf](https://github.com/user-attachments/files/15688108/table_data.27.pdf)

**Comment by simonbengtsson** [comment]
Have you tried removing the tableWidth property? The behavior wanted should be the default.

**Comment by Brunapupo** [comment]
I tried removing the tableWidth property, but it remains the same; nothing has changed in the table

**Comment by simonbengtsson** [comment]
Weird. If the demo looks like you want it to you might want to start with the example code and add back your code step by step and see where things go wrong.

**Comment by Brunapupo** [comment]
I will try to perform the debugging as you suggested.

I have a question about these issues.

I'm using a table and PDF export in a parallel project via an iframe. I am receiving data via props through window.Listener communication and extracting the data through state. Could this be causing an issue with the table margins in the PDF, making them irregular in size?

Currently, the only issue is that I want all pages of the table to render with the same size. I believe this is related to the margins. Is it possible to define these margins via HTML without using the autotable parameters?

Here are the codes I am working with:

Parent component (receiving the iframe):

`import React, { useRef, useEffect, forwardRef, useImperativeHandle } from 'react';
import useStyles from './MaterialReactTableStyle';

const MaterialReactTable = forwardRef((props, ref) => {
    const { data, meta, enableRowNumbers } = props;
    const classes = useStyles();
    const iFrame = useRef(null);

    useEffect(() => {
        if (iFrame?.current?.contentWindow) {
            const metaJSON = JSON.stringify(meta);
            iFrame.current.contentWindow.PAYLOAD = { data, meta: metaJSON, enableRowNumbers };
            iFrame.current.contentWindow.NODE_ENV = 'production';
        }
    }, [data, meta, enableRowNumbers]);

    useImperativeHandle(ref, () => ({
        enviarEventoExportarPDF: () => {
            const iFrameRef = iFrame.current;
            if (iFrameRef?.contentWindow) {
                iFrameRef.contentWindow.postMessage({
                    action: "EXPORTAR_PDF"
                }, "*");
            }
        }
    }));

    const totalLinesStyle = {
        color: '#2a3f6f',
        fontSize: '0.875rem',
        fontWeight: 'bold',
        lineHeight: '1.375rem',
        textAlign: 'right',
        paddingRight: '20px',
    };

    return (
        <div>
            <div style={totalLinesStyle}>Total de Linhas: {data.length - 1}</div>
            <iframe
                className={classes.iFrameMaterialReactTableContainer}
                allowFullScreen={true}
                ref={iFrame}
                referrerPolicy="unsafe-url"
                src={`/iframes/analise-table/index.html?version=${global.gConfig?.modulo_versao}`}
                width="100%"
                height="100%"
                id="iframeid"
            />
        </div>
    );
});

export default MaterialReactTable;
`

Child component (implementing the table and exporting the PDF):

`import React, { useEffect, useRef, useState } from "react";
import { MaterialReactTable } from "material-react-table";
import { MRT_Localization_PT_BR } from "material-react-table/locales/pt-BR"
import { Box, Button } from "@mui/material";
import FileDownloadIcon from "@mui/icons-material/FileDownload";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./MaterialReactTable.css";

function ReactTable({ data, meta, enableRowNumbers }) {
  const rowVirtualizerInstanceRef = useRef(null);
  const [tableData, setTableData] = useState([]);
  const [columns, setColumns] = useState([]);
  const [mensagemRecebida, setMensagemRecebida] = useState("");
  const tableInstanceRef = useRef(null);

  const tableStyles = {
    root: {
      width: "100%",
      overflowX: "auto",

    },
  };

  useEffect(() => {
    const [header, ...rows] = data;
    const dataKeys = Object.keys(data[0]);
    const metaObject = JSON.parse(meta);
    const headerTable = dataKeys.map((key) => ({
      accessorKey: key,
      header: metaObject[key].rotulo,
    }));
    setTableData(rows);
    setColumns(headerTable);
  }, [data]);
  
  const exportarParaPdf = (rows) => {
    if (!columns || columns.length === 0 || !rows || rows.length === 0) {
      console.error("Tabela não encontrada para exportação.");
      return;
    }
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "pt",
      format: "a4",
    });
    const tableColumn = ["#", ...columns.map((col) => col.header)];
    const tableRows = rows.map((row, index) => [
      index + 1, // Adiciona o número da linha
      ...columns.map((col) => row.getValue ? row.getValue(col.accessorKey) : row.original[col.accessorKey])
    ]);
    
    const totalPagesExp = "{total_pages_count_string}";
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    const larguraPagina = doc.internal.pageSize.getWidth();
    const alturaPagina = doc.internal.pageSize.getHeight();
    const margem = 60;
    const titulo =
      "ESTADO DE SANTA CATARINA\nSECRETARIA DE ESTADO DA SAÚDE\nSUPERINTENDÊNCIA DE SERVIÇOS ESPECIALIZADOS E REGULAÇÃO\nCENTRAL ESTADUAL DE TELEMEDICINA\n\nRelatórios de Dados ";
    
      doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      columnStyles: { halign: 'center' }, 
      horizontalPageBreak: true,
      horizontalPageBreakRepeat: 0,
      margin: { top: 130, right: margem, bottom: 40, left: margem },
      didDrawPage: (data) => {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(titulo, larguraPagina / 2, 30, { align: "center" });
        let textoRodape = "Página " + data.pageNumber;
        if (typeof doc.putTotalPages === "function") {
          textoRodape = textoRodape + " de " + totalPagesExp;
        }
        doc.text(textoRodape, larguraPagina - margem - 100, alturaPagina - 10);
      },
    });
    if (typeof doc.putTotalPages === "function") {
      doc.putTotalPages(totalPagesExp);
    }
    doc.save("table_data.pdf");
  };  
    useEffect(() => {
        console.log("CRIOU O EVENTO DE ESCUTA PARA ESSE IFRAME");
        const handleMessage = (e) => {
          if (!e.origin.includes(window.location.host)) return; 
          if(e.data?.action === "EXPORTAR_PDF") {
              const rows = tableInstanceRef.current?.getPrePaginationRowModel().rows;
              exportarParaPdf(rows);
          };
        };
        window.addEventListener("message", handleMessage);
        return () => {
            window.removeEventListener("message", handleMessage);
        };
    }, [tableData, columns]);

  const sortColumnId = columns.length > 0 ? columns[0].accessorKey : null;

  return (
    <MaterialReactTable
      columns={columns}
      data={tableData}
      enableColumnResizing
      enableBottomToolbar={false}
      enablePagination={false}
      enableRowNumbers={true}
      enablePinning
      enableRowVirtualization={true}
      enableFullScreenToggle={false}
      muiTableContainerProps={{ sx: { maxHeight: "600px" } }}
      muiTableHeadProps={{
        sx: {
            color: '#0a6fb8',
            fontSize: '0.875rem',
            fontWeight: 'bold',
            lineHeight: '1.375rem',
        },
      }}
      rowVirtualizerInstanceRef={rowVirtualizerInstanceRef}
      rowVirtualizerProps={{ overscan: 8 }}
      localization={MRT_Localization_PT_BR}
      initialState={{
        isFullScreen: true, // Ativa o modo fullscreen
        columnVisibility: { description: false },
        density: "compact",
        showGlobalFilter: true,
        enableRowVirtualization: true,
        sorting: [{ id: sortColumnId, desc: false }],
      }}
      classes={tableStyles}
      tableInstanceRef={tableInstanceRef} // Armazena a referência da tabela
      renderTopToolbarCustomActions={({ table }) => (
        <Box
          sx={{
            //display: "flex",
            gap: "16px",
            padding: "8px",
            //flexWrap: "wrap",
          }}
        >
          <p>{mensagemRecebida}</p>
          <Button
            disabled={table.getPrePaginationRowModel().rows.length === 0}
            onClick={() =>
              exportarParaPdf(table.getPrePaginationRowModel().rows)
            }
            startIcon={<FileDownloadIcon />}
          >
            Exportar Todas as Linhas
          </Button>

        </Box>
      )}
    />
  );
}

export default ReactTable;
`

PDF : 
[table_data.27 (2).pdf](https://github.com/user-attachments/files/15743858/table_data.27.2.pdf)


Thanks for your help Simon

**Comment by Brunapupo** [comment]
I will try to perform the debugging as you suggested.

I have a question about these issues. I'm using a table and PDF export in a parallel project via an iframe. I am receiving data via props through window.Listener communication and extracting the data through state. Could this be causing an issue with the table margins in the PDF, making them irregular in size?

Currently, the only issue is that I want all pages of the table to render with the same size. I believe this is related to the margins. Is it possible to define these margins via HTML without using the autotable parameters?

Here are the codes I am working with:

Parent component (receiving the iframe):

```
import React, { useRef, useEffect, forwardRef, useImperativeHandle } from 'react';
import useStyles from './MaterialReactTableStyle';

const MaterialReactTable = forwardRef((props, ref) => {
    const { data, meta, enableRowNumbers } = props;
    const classes = useStyles();
    const iFrame = useRef(null);

    useEffect(() => {
        if (iFrame?.current?.contentWindow) {
            const metaJSON = JSON.stringify(meta);
            iFrame.current.contentWindow.PAYLOAD = { data, meta: metaJSON, enableRowNumbers };
            iFrame.current.contentWindow.NODE_ENV = 'production';
        }
    }, [data, meta, enableRowNumbers]);

    useImperativeHandle(ref, () => ({
        enviarEventoExportarPDF: () => {
            const iFrameRef = iFrame.current;
            if (iFrameRef?.contentWindow) {
                iFrameRef.contentWindow.postMessage({
                    action: "EXPORTAR_PDF"
                }, "*");
            }
        }
    }));

    const totalLinesStyle = {
        color: '#2a3f6f',
        fontSize: '0.875rem',
        fontWeight: 'bold',
        lineHeight: '1.375rem',
        textAlign: 'right',
        paddingRight: '20px',
    };

    return (
        <div>
            <div style={totalLinesStyle}>Total de Linhas: {data.length - 1}</div>
            <iframe
                className={classes.iFrameMaterialReactTableContainer}
                allowFullScreen={true}
                ref={iFrame}
                referrerPolicy="unsafe-url"
                src={`/iframes/analise-table/index.html?version=${global.gConfig?.modulo_versao}`}
                width="100%"
                height="100%"
                id="iframeid"
            />
        </div>
    );
});

export default MaterialReactTable;

```

```
import React, { useEffect, useRef, useState } from "react";
import { MaterialReactTable } from "material-react-table";
import { MRT_Localization_PT_BR } from "material-react-table/locales/pt-BR"
import { Box, Button } from "@mui/material";
import FileDownloadIcon from "@mui/icons-material/FileDownload";
import jsPDF from "jspdf";
import "jspdf-autotable";
import "./MaterialReactTable.css";

function ReactTable({ data, meta, enableRowNumbers }) {
  const rowVirtualizerInstanceRef = useRef(null);
  const [tableData, setTableData] = useState([]);
  const [columns, setColumns] = useState([]);
  const [mensagemRecebida, setMensagemRecebida] = useState("");
  const tableInstanceRef = useRef(null);

  const tableStyles = {
    root: {
      width: "100%",
      overflowX: "auto",

    },
  };

  useEffect(() => {
    const [header, ...rows] = data;
    const dataKeys = Object.keys(data[0]);
    const metaObject = JSON.parse(meta);
    const headerTable = dataKeys.map((key) => ({
      accessorKey: key,
      header: metaObject[key].rotulo,
    }));
    setTableData(rows);
    setColumns(headerTable);
  }, [data]);
  
  const exportarParaPdf = (rows) => {
    if (!columns || columns.length === 0 || !rows || rows.length === 0) {
      console.error("Tabela não encontrada para exportação.");
      return;
    }
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "pt",
      format: "a4",
    });
    const tableColumn = ["#", ...columns.map((col) => col.header)];
    const tableRows = rows.map((row, index) => [
      index + 1, // Adiciona o número da linha
      ...columns.map((col) => row.getValue ? row.getValue(col.accessorKey) : row.original[col.accessorKey])
    ]);
    
    const totalPagesExp = "{total_pages_count_string}";
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    const larguraPagina = doc.internal.pageSize.getWidth();
    const alturaPagina = doc.internal.pageSize.getHeight();
    const margem = 60;
    const titulo =
      "ESTADO DE SANTA CATARINA\nSECRETARIA DE ESTADO DA SAÚDE\nSUPERINTENDÊNCIA DE SERVIÇOS ESPECIALIZADOS E REGULAÇÃO\nCENTRAL ESTADUAL DE TELEMEDICINA\n\nRelatórios de Dados ";
    
      doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      columnStyles: { halign: 'center' }, 
      horizontalPageBreak: true,
      horizontalPageBreakRepeat: 0,
      margin: { top: 130, right: margem, bottom: 40, left: margem },
      didDrawPage: (data) => {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(titulo, larguraPagina / 2, 30, { align: "center" });
        let textoRodape = "Página " + data.pageNumber;
        if (typeof doc.putTotalPages === "function") {
          textoRodape = textoRodape + " de " + totalPagesExp;
        }
        doc.text(textoRodape, larguraPagina - margem - 100, alturaPagina - 10);
      },
    });
    if (typeof doc.putTotalPages === "function") {
      doc.putTotalPages(totalPagesExp);
    }
    doc.save("table_data.pdf");
  };  
    useEffect(() => {
        console.log("CRIOU O EVENTO DE ESCUTA PARA ESSE IFRAME");
        const handleMessage = (e) => {
          if (!e.origin.includes(window.location.host)) return; 
          if(e.data?.action === "EXPORTAR_PDF") {
              console.log("EXECUTANDO A LÓGICA DE EXPORTAR: " + e.data?.action);
              // TODO lógica quando ele receber informações via iframe
              const rows = tableInstanceRef.current?.getPrePaginationRowModel().rows;
              exportarParaPdf(rows);
          };
        };
        window.addEventListener("message", handleMessage);
        return () => {
            window.removeEventListener("message", handleMessage);
        };
    }, [tableData, columns]);

  const sortColumnId = columns.length > 0 ? columns[0].accessorKey : null;

  return (
    <MaterialReactTable
      columns={columns}
      data={tableData}
      enableColumnResizing
      enableBottomToolbar={false}
      enablePagination={false}
      enableRowNumbers={true}
      enablePinning
      enableRowVirtualization={true}
      enableFullScreenToggle={false}
      muiTableContainerProps={{ sx: { maxHeight: "600px" } }}
      muiTableHeadProps={{
        sx: {
            color: '#0a6fb8',
            fontSize: '0.875rem',
            fontWeight: 'bold',
            lineHeight: '1.375rem',
        },
      }}
      rowVirtualizerInstanceRef={rowVirtualizerInstanceRef}
      rowVirtualizerProps={{ overscan: 8 }}
      localization={MRT_Localization_PT_BR}
      initialState={{
        isFullScreen: true, // Ativa o modo fullscreen
        columnVisibility: { description: false },
        density: "compact",
        showGlobalFilter: true,
        enableRowVirtualization: true,
        sorting: [{ id: sortColumnId, desc: false }],
      }}
      classes={tableStyles}
      tableInstanceRef={tableInstanceRef} // Armazena a referência da tabela
      renderTopToolbarCustomActions={({ table }) => (
        <Box
          sx={{
            //display: "flex",
            gap: "16px",
            padding: "8px",
            //flexWrap: "wrap",
          }}
        >
          <p>{mensagemRecebida}</p>
          <Button
            disabled={table.getPrePaginationRowModel().rows.length === 0}
            onClick={() =>
              exportarParaPdf(table.getPrePaginationRowModel().rows)
            }
            startIcon={<FileDownloadIcon />}
          >
            Exportar Todas as Linhas
          </Button>

        </Box>
      )}
    />
  );
}

export default ReactTable;
```

PDF : 
[table_data.27 (2).pdf](https://github.com/user-attachments/files/15743858/table_data.27.2.pdf)
