### ISSUE TITLE
Link / Href support

### ISSUE THREAD

**Issue by trevordowdle** [simonbengtsson/jsPDF-AutoTable#106]
Are **links** supported with jsPDF-AutoTable?

e.g. create links in a pdf from html or manually?

Thanks

**Comment by simonbengtsson** [comment]
Hyperlinks are poorly supported by jspdf as far as I understand. It seems that if you spell out the entire url it becomes clickable. If you don't want that some people have gotten it to work by simply hiding the link and place text over it. You might have luck with this using the hooks with this plugin, however it isn't something I can recommend after I made some attempt at it now.

**Comment by trevordowdle** [comment]
Hey thank you for looking into it and getting back to me Simon.  Appreciate the tips, i'll try them out and make the best of it!
