### ISSUE TITLE
Table Border is off and value is not displayed when the first column is having large rowSpan.

### ISSUE THREAD

**Issue by urenpatelce** [simonbengtsson/jsPDF-AutoTable#1060]
We are having tables which have many large rowSpans for many columns and when we have the data like below mentioned 2 images then the table border and value is not coming up properly in the output PDF.

![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/33483635/32404930-788b-4f6e-a6e4-117b62e79641)

![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/33483635/c3d7ffbc-0f38-4671-a73e-218a54cc11d6)

Below mentioned are 2 output PDFs:
As you can see that for portrait page layout, the report looks good because we have the space to fit the rowSpan column. But for landscape, as soon as the rowSpan is larger then the page size then the issue is reproducible.

[Portrait.pdf](https://github.com/user-attachments/files/15924278/Portrait.pdf)

Issue with first column and value "**autoARAdmin**":

[Landscape.pdf](https://github.com/user-attachments/files/15924288/Landscape.pdf)

Please consider this defect and at least correct borders and value should be repeated in the next page so that user don't have to scroll up to check the first column value. Also current output looks broken and weird. 

Thanks for your time and for creating this library and really works great.

- Uren.

**Comment by simonbengtsson** [comment]
Sounds like a bug! Could you create a minimal example with test data that highlights the issue?

**Comment by urenpatelce** [comment]
@simonbengtsson sure i will try to create one.. with sample data. If you have any codepen link which generates the report from html then please pass it here. I will update the same. 
Its just that first column is having large rowSpan which isn't possible to fit in single page then this issue is reproducible.

**Comment by urenpatelce** [comment]
Attaching the sample HTML which you can use to generate the issue.

[sample.zip](https://github.com/user-attachments/files/15968240/sample.zip)

**Comment by simonbengtsson** [comment]
Hmm, not sure I understand what the issue is in the submitted sample. Could you clarify?

**Comment by urenpatelce** [comment]
@simonbengtsson check below imge. The first cell should have the border with blank cell. This doesn't looks good and looks like its broken for the first cell. We alredy got comments form many users regarding this. If the cell is empty with white background then at least it is clearly stating that there is no value or there is still rowSpan going on. Let me know if you need more details.

![image](https://github.com/user-attachments/assets/405eb1c0-afcd-4e52-8f4f-da209f3fc002)

**Comment by mmghv** [comment]
This is a duplicate of #809
