### ISSUE TITLE
How to set specific startY even after page break

### ISSUE THREAD

**Issue by galih9** [simonbengtsson/jsPDF-AutoTable#1063]
Hello, I want to ask how to set the start of the autotable to be always on specific coordinate, I already tried setting up the autotable to always start at specific coordinate but when it got too much of a content, it get pushed to a new page but at the start of the page, how to set if the content was pushed to a new page but not at the start of the page, so even if it was pushed to a new page, it always stays at the start of the startY coordinate? Im sorry for my bad english, but this is roughly my current code and some screenshot to help you understand my issue and my goal.

```
const tableOption: UserOptions = {
      startY: 10,
      theme: "plain",
      body: generateHeaderRow(element.dataList[currentIdx], element.memberName),
      rowPageBreak: "avoid",
      pageBreak: "avoid",
      didDrawCell: (c) => {
        if (
          c.row.section === "body" &&
          c.row.index === rowIndexContent &&
          c.column.dataKey === 0
        ) {
          for (let j = 0; j < element.dataList.length; j++) {
            console.log(c.doc.lastAutoTable.finalY, c.cell.y);
            currentIdx += 1;
            const fragments = element.dataList[j];
            // console.log("test called", c.column);
            autoTable(doc, {
              theme: "plain",
              body: generateRow(fragments),
              foot: [[], [], []],
              didDrawPage: () => {},
              rowPageBreak: "avoid",
              pageBreak: "auto",
              startY: 133,
            } as UserOptions);
          }
        }
      },
    };

    autoTable(doc, tableOption);
```

<img width="667" alt="Screenshot 2024-07-26 at 19 45 13" src="https://github.com/user-attachments/assets/523f0f5b-c185-42f7-9091-2dcf301ad9a6">

Thank you for the attention

**Comment by mmghv** [comment]
`startY` is only intended for the first page, for all pages use `margin: { top: 133 }` instead.
