### ISSUE TITLE
There is console.log in cssParser

### ISSUE THREAD

**Issue by eunyeong-j** [simonbengtsson/jsPDF-AutoTable#1068]
Hi Team!

I have been using your library well and I appreciate it.
However, there is one fix in the latest version that I am raising as an issue.

cssParser.ts has a console.log that needs to be deleted.

* version: 3.8.2
* line: 65
* code: console.log(result.lineWidth)

Thank you :)

**Comment by mmghv** [comment]
It was removed earlier in https://github.com/simonbengtsson/jsPDF-AutoTable/commit/8cb5cf74e9c42d9715e7d8a588b36dbb2a291679 but no release was published since then.

@simonbengtsson Could you published a new release please?

**Comment by eunyeong-j** [comment]
I really appreciate your help!
