### ISSUE TITLE
autoTableEndPosY() after 'auto' page break

### ISSUE THREAD

**Issue by vdewit** [simonbengtsson/jsPDF-AutoTable#107]
I am using the afterPageContent option to add some text after the table. Unfortunately the autoTableEndPosY() takes the cell position of the last row of the first table split ('auto' page break ). The text is added two times: at the top of the page after the table split and after the second table part. 
[SOLVED]

**Comment by simonbengtsson** [comment]
Can you share the code you used both when you had the issue and when you solved it? I'm going to mark this as solved until an issue can be confirmed.
