### ISSUE TITLE
halign on column headers

### ISSUE THREAD

**Issue by MartinPerrie** [simonbengtsson/jsPDF-AutoTable#1070]
Is it possible to have different horizontal alignment on the column headers? For example, I want most of the column headers to be left aligned. There are three columns that contain currency values. Ideally both the headers and values in these columns should be right aligned. 

headStyles can take an halign property that applies to all column headers. And columnStyles can take an halign per column that will apply to the contents.

But I can't see an obvious way of applying different alignments to different column headers. Is there a way of doing this?

Thanks.

**Comment by simonbengtsson** [comment]
Yes! You can accomplish this with cell styles or hooks.

**Comment by CSFelix** [comment]
> Yes! You can accomplish this with cell styles or hooks.

Hey there Symon, how is it going? May you tell what am I doing wrong? I'm trying to align both body and header, but only the body alignment is working. This is my options object:

```js
const options = {
  willDrawPage: (data) => header()
  , didDrawPage: (data) => footer(data)
  , margin: { top: 45, bottom: 20 }
  , headStyles: { 0: { halign: "left" }, 1: { halign: "center" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } }
  , columnStyles: { 0: { halign: "left" }, 1: { halign: "center" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } }
  , bodyStyles: { 0: { halign: "left" }, 1: { halign: "center" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" } }
  , showHead: "everyPage"
  , showFoot: "everyPage"
 };
```

---

I've tried keeping only headStyles, columnStyles and bodyStyles, but it didn't work though. `headStyles` only worked when I aligned the header without passing the columns index.

I'm using the following versions with react:

```json
"jspdf": "^2.5.2",
"jspdf-autotable": "^3.8.4",
```
