### ISSUE TITLE
hebrew characters are not displayed correctly 

### ISSUE THREAD

**Issue by vladpopovici-opswat** [simonbengtsson/jsPDF-AutoTable#1071]
when generating a table in some cells i have hebrew characters that in some cases are not displayed correctly. When encountering on the html the tags &lrm;&ensp; there is a little arrow that appears showing the direction from left to right

**Comment by simonbengtsson** [comment]
Probably an issue with jsPDF and not this plugin. If you are able to draw those characters with jsPDF but not this plugin feel let me know and I'll take a look!
