### ISSUE TITLE
Increase line height of text inside jspdf-autotable cells

### ISSUE THREAD

**Issue by ArsenOganisyan** [simonbengtsson/jsPDF-AutoTable#1077]
I'm trying to increase the line height of text displayed inside cells using jspdf-autotable. The text is plain and is automatically split and drawn by autotable.

![image](https://github.com/user-attachments/assets/3f7d8fb7-ca80-4d56-9df6-df556ce818b2)

One possible solution I've considered is adding empty entries ("") between lines in the willDrawCell hook, but this seems excessive for a small line height adjustment.

Is there a more elegant solution to adjust line height inside a cell? Ideally, I'm looking for a method that allows for fine-tuning of the line spacing without altering the existing text content or cell structure.

Any suggestions or alternative approaches would be greatly appreciated.

**Comment by simonbengtsson** [comment]
Does it work if you use "setLineHeightFactor" on jspdf doc before calling autotable?

**Comment by ArsenOganisyan** [comment]
@simonbengtsson  Yes! That is what I looked for, thank you!
