### ISSUE TITLE
Issue with 'linebreak'

### ISSUE THREAD

**Issue by tnbharris** [simonbengtsson/jsPDF-AutoTable#108]
When I set the style for overflow: 'linebreak', I receive the following error:

TypeError: b.match is not a function

If I remove the overflow: 'linebreak' then the error goes away.

**Comment by simonbengtsson** [comment]
Check the long text example in `/examples/examples.js` or the demo of it [here](https://simonbengtsson.github.io/jsPDF-AutoTable/#long). It should work. If you can't get it to work, feel free posting the code you are using.

**Comment by tnbharris** [comment]
Here is my code. I am still getting the TypeError above in jsPDF.

var doc = new jsPDF('l', 'pt');
var tbl = doc.autoTableHtmlToJson($.parseHTML(myTable)[0]);
doc.text("Overflow 'linebreak'", 10, doc.autoTableEndPosY() + 30);
doc.autoTable(tbl.columns, tbl.data, { startY: doc.autoTableEndPosY() + 45, styles: {overflow: 'linebreak' }, bodyStyles: {valign: 'top'}, columnStyles: {}});
doc.save("TEST.pdf");

**Comment by tnbharris** [comment]
Also, how could I make the table break horizontally across multiple pages? I have some tables that are dynamically generated based on the columns the user selects to view. Some of these columns could have very long text. Is there a way to set maximum columns per page or some other way of forcing a page break if the width is going to be too much for a single page?

**Comment by simonbengtsson** [comment]
I tried the code and it works for me. Can you repeat the issue on codepen? You can use the template linked in the readme. Unfortunaletly horizontal breaks or not suppueted. However I have solved that problem before by printing two pdfs with half the columns each.

**Comment by simonbengtsson** [comment]
If you are still having issues with this, feel free to reopen.
