### ISSUE TITLE
Release version compatible with jspdf 1.1

### ISSUE THREAD

**Issue by axos88** [simonbengtsson/jsPDF-AutoTable#109]
Or just weaken the dependency definition

**Comment by simonbengtsson** [comment]
The plugin works fine with version 1.1. However even if it should work with all features of this plugin I remember experiencing some unrelated pdf bugs with it. It states on github that it is a prerelease and it is not published on npm. You do get version 1.1 when you install jspdf using bower though. This confusion makes me reluctant to use it. Github states that the only change between 1.0 and 1.1 is `Numerous fixes to HTML plugin, including context2d support`. Is that why you are using it? Have you experienced any bugs with 1.1?

**Comment by axos88** [comment]
No, I had some incompatibility issues with jspdf 1.0 and the webjars & our backend server for some reason that eludes me. I never investigated the issues in full, and just went ahead and upgraded to 1.1. The issues disappeared, I was happy, until now :)

**Comment by simonbengtsson** [comment]
Okey! I think i will keep the version requirement of 1.0 for now, until jspdf makes an official release. However everything should work just fine with version 1.1 if you choose to use that.

**Comment by simonbengtsson** [comment]
`jspdf` was just officially updated to version 1.2. When installing this plugin with npm or bower this version will now be used.
