### ISSUE TITLE
Overflow: Linebreak still cutting off characters

### ISSUE THREAD

**Issue by mattkyleuk** [simonbengtsson/jsPDF-AutoTable#110]
Hi Simon,

Great work with autotables, it's by far the best solution out there. 

The only issue I am experiencing is that even with linebreak set, my cells are getting cut off. It tends to be when the line should be broken in the middle of a word.

Please see this screenshot: http://imgur.com/fsa9u6j

The code for the table is as follows:

```
var res = doc.autoTableHtmlToJson(document.getElementById("tablemissing"));
    	doc.autoTable(res.columns, res.data, {
        startY: doc.autoTableEndPosY() + 40,
		margin: {horizontal: 20},
        styles: {overflow: 'linebreak', font: 'arial', fontSize: 10, cellPadding: 8},
		headerStyles: {fillColor: [65, 85, 99], valign: 'middle'},
        bodyStyles: {valign: 'middle', fillColor: [255, 255, 255]}
    });
```

I have tried numerous font sizes and cell padding to no avail.

**Comment by simonbengtsson** [comment]
Thanks! I tried your code in a codepen now and it seems to work. It might be something with your data though. Could you fork this [codepen](http://codepen.io/someatoms/pen/EKaLKM?editors=1010), update it with data so the error shows and send the link to me?

**Comment by simonbengtsson** [comment]
Closing for now, feel free to reopen if you are still having issues.
