### ISSUE TITLE
Cell data is not align properly in pdf

### ISSUE THREAD

**Issue by neerajlad** [simonbengtsson/jsPDF-AutoTable#112]
// ================lib
<'script type="text/javascript" src="PDFlib/jspdf.plugin.autotable.js"></script>
<'script type="text/javascript" src="PDFlib/jspdf.min.js"></script> **---- Commented**

**Note : When i use jspdf.min.js then while downloading pdf is empty shows "Failed - No file error"**

**HTML code :**
<'table id="tabprocesslist">
 <'tr  align="left"  >
          <'th >
                  <'label id="clickable" name="txtname"><%= process.getprocess()%></label>                            
          <'/th>                    
           <'td >
                   <'label  id="clickable" name="txtTo"><%= process.getto() == null ? "" : process.geto()%><'/label>
           <'/td>
<'/tr>
<'/table>

**Note : <'> is used to print html tag -- hence ignore it**
//============== js script

    var elem = document.getElementById("tabprocesslist");
                pdf.text("Overflow 'linebreak'", 10, pdf.autoTableEndPosY() + 30);  
                var res = pdf.autoTableHtmlToJson(elem);
                pdf.autoTable(res.columns, res.data, {
                startY: pdf.autoTableEndPosY() + 40, 
                theme: 'grid',
                margin: {horizontal: 10},
                styles: {overflow: 'linebreak'},
                bodyStyles: {valign: 'top'},
                columnStyles: {email: {columnWidth: 'wrap'}},
            });

Please find the sample image screenshot

![image](https://cloud.githubusercontent.com/assets/9249575/13730525/d3155a42-e977-11e5-8ad2-eef918922cce.png)

**Comment by simonbengtsson** [comment]
Hi @neerajlad! Could you make this easier to reproduce? This could be done by either creating a full example that I can copy and paste and see the the result in your screenshot.

**Comment by neerajlad** [comment]
Hi simonbengtsson,
just early morning got some idea and tried that, explain you in below image,

**Early html was :**
![image](https://cloud.githubusercontent.com/assets/9249575/13732711/c15a12a2-e9ae-11e5-81a5-06b7e07a6a99.png)

**Updated HTML is :**

![image](https://cloud.githubusercontent.com/assets/9249575/13732713/df186f64-e9ae-11e5-8ad2-4a12207a519d.png)

Can you see the difference between these two images,
The problem was space between <'td> and <'label> tag in code
if you remove that and keep writing <'td> and <'label> in same line then your table will print.

I think in jspdf-autotable, this condition is not handle. 

following is the output of pdf table

![image](https://cloud.githubusercontent.com/assets/9249575/13732789/b12da578-e9af-11e5-8133-e94cfd659347.png)

**Note : removed the table contains due to privacy **

**Comment by simonbengtsson** [comment]
Interesting! Will look into that!

**Comment by simonbengtsson** [comment]
Fixed this now in version `2.0.22`.
