### ISSUE TITLE
createdCell  change rowHeight?

### ISSUE THREAD

**Issue by marcdakar** [simonbengtsson/jsPDF-AutoTable#114]
Hello SImon, this plugin is excellent done.
i try to change the rowHeight, when cell.text is empty, but no luck

createdCell: function (cell, data) {
if (cell.text === '') {   rowHeight=14; } 
}

btw what is the meaning of cell.raw

thank you very much
marc

**Comment by simonbengtsson** [comment]
Hi! Try `cell.styles.rowHeight = 14`. Raw is the unchanged value passed to the plugin. If for example the string displayed for a cell is shortened to fit its width, raw will contain the unshortened string.

**Comment by marcdakar** [comment]
thank you simon, but it seems its not affected to the row.
i call the property with alert (cell.styles.rowHeight + " " + cell.text) in every cell of the row and it returns 14, but no change at all
so i think its not working...
greetings marc

**Comment by simonbengtsson** [comment]
My bad, use `drawCell` instead. Styling changes made in createdCell is overridden.

**Comment by marcdakar** [comment]
hi simon, perhaps i make something wrong,
drawCell or/and drawRow - no success
so i helped me out with another table, with rowHeight:14 in the style section and headerrow disabled
perhaps you can look over sometimes, my skills are not  good enough to do it myself
many greeting and thanks for your help

**Comment by simonbengtsson** [comment]
Damn, I must have been tired. Of course you can use `createdCell` as you started doing. Instead of setting the rowHeight style on the cell, set it on the row. 

```js
doc.autoTable(data.columns, data.rows, {
  createdCell: function(cell, opts) {
    opts.row.styles.rowHeight = 100;
  }
});
```

Here is a working codepen http://codepen.io/someatoms/pen/dMWGOy?editors=1010

**Comment by marcdakar** [comment]
this works perfect !! :)

**Comment by svankamamidi** [comment]
Above example no more works :(

**Comment by simonbengtsson** [comment]
Update example

**Comment by chanduBS** [comment]
doc.autoTable(data.columns, data.rows, {
       styles: { overflow: 'linebreak', columnWidth: 'wrap' },
       columnStyles: {
        sno: {
          columnWidth: 35
          // columnWidth: 'auto'
        },
        productname: {
          // columnWidth: 230,
        }
      },
});


This might help your problem

**Comment by chanduBS** [comment]
![githubtextwrapping](https://user-images.githubusercontent.com/22656960/44228280-8efd0f80-a1b2-11e8-9eca-c539291dceea.PNG)

**Comment by dasa1012** [comment]
> doc.autoTable(data.columns, data.rows, { styles: { overflow: 'linebreak', columnWidth: 'wrap' }, columnStyles: { sno: { columnWidth: 35 // columnWidth: 'auto' }, productname: { // columnWidth: 230, } }, });
> 
> This might help your problem

Muchas Gracias por la solución!!!
