### ISSUE TITLE
Running on server?

### ISSUE THREAD

**Issue by luixal** [simonbengtsson/jsPDF-AutoTable#115]
Hi,

Just starting to use this lib in a Meteor app, any way to use it on the server? My intention was to generate pdf files in the server and then sending them by email (or whatever).

_PS: I've seen an older issue that makes the trick by calling an upload action, but was looking for a cleaner solution._

**Comment by simonbengtsson** [comment]
Unfortunately `jspdf` doesn't support use on the server. As you mentioned you could get around it by generating the pdf client side and then send it to the server with ajax. I would recomend that you took a look at [pdfmake](https://github.com/bpampuch/pdfmake) for server side rendering however. It has built in table support.

**Comment by luixal** [comment]
What a pity, you're lib really makes this simple (and also creates good looking tables).

I can't apply the commented solution because the pdf files are generated from a cronned proccess on the server. Right now I'm using PhantomJS to render a template as a PDF file and it's working fine, but I though of this as a cleaner solution.

I saw pdfmake some time ago but never tried, I'll give it a chance, thanks!

**Comment by simonbengtsson** [comment]
Yeah would be awesome if jspdf supported the server! At least for simple pdfs like the ones generated by this plugin.

I think pdfmake is better and more mature than jspdf in most ways with the exception it's declarative api and jspdf's support for plugins. Too bad both projects is basically abandoned now however.

**Comment by SimonOdell** [comment]
jspdf does support server side with the node-jspdf package
