### ISSUE TITLE
Rendering inner objects

### ISSUE THREAD

**Issue by luixal** [simonbengtsson/jsPDF-AutoTable#116]
Hi,

When rendering a table with an inner object, something like this:
```javascript
    var columns = [
      {title: "ID", key: "seqId"},
      {title: "NIF", key: "nif"},
      {title: "Name", key: "name"},
      {title: "Street", key: "address.street"},
      {title: "City", key: "address.city"},
      {title: "Postal Code", key: "address.cp"},
      {title: "Phone", key: "phone"},
      {title: "eMail", key: "email"},
      {title: "Creation Date", key: "createdAt"}
    ];
```
I get something like this:

![seleccion_004](https://cloud.githubusercontent.com/assets/615268/14188925/18faec0e-f78b-11e5-9fa4-543dcbe80983.png)

Those cells show no content.

Can that be done without having to map those fields so they're not in an inner object?

Thanks!

**Comment by simonbengtsson** [comment]
Do you wish to hide the three columns without content?

**Comment by luixal** [comment]
Yes, maybe I wasn't very clear, sorry for that.

I have an object that represents a client, is something like this (as you can see, ```address``` is an inner object containing ```street```, ```city``` and ```cp```:
```javascript
{
  "_id" : "HsQLqwCwH7DSA4jYd",
  "seqId" : 1,
  "nif" : "10078528C",
  "name" : "Luis Alberto Perez Garcia",
  "address" : {
    "street" : "Calle Enebros 173",
    "city" : "San Agustín de Guadalix",
    "cp" : "28750"
  },
  "phone" : "630712142",
  "email" : "luixal@gmail.com",
  "accountNumber" : "123412341241234",
  "active" : true,
  "createdAt" : ISODate("2016-02-28T00:56:17Z"),
  "updatedAt" : ISODate("2016-03-09T20:23:03.222Z"),
}
```
I want to render some fields in a table using jsPDF, so I defined columns like this:

```javascript
    var columns = [
      {title: "ID", key: "seqId"},
      {title: "NIF", key: "nif"},
      {title: "Name", key: "name"},
      {title: "Street", key: "address.street"},
      {title: "City", key: "address.city"},
      {title: "Postal Code", key: "address.cp"},
      {title: "Phone", key: "phone"},
      {title: "eMail", key: "email"},
      {title: "Creation Date", key: "createdAt"}
    ];
```

got my rows content from a Meteor collection this way:

```javascript
var rows = Clients.find().fetch();
```

and then generate the PDF file using this code:

```javascript
var doc = new jsPDF('p', 'pt');
doc.autoTable(columns, rows);
doc.save('clients.pdf');
```

and got the PDF with the table in the screenshot above, with the fields corresponding to the address inner object shown blank.

Any ideas?

**Comment by simonbengtsson** [comment]
Aha! The plugin doesn't support inner objects so you would either have to flatten the object or use for example the `drawCell` hook to dynamically set the cell data. The simplest would probably be to use a loop. Is it a reason part from requiring extra code that you would like to avoid this?

It sounds like a great idea and something that would be easy to implement so I'll add it to the todo list of the plugin. No time plan however.

**Comment by luixal** [comment]
That was what I was thinking. No other reason, was only about efficiency. Mapping those fields this way works like a charm:

```javascript
var columns = [
      {title: "ID", key: "seqId"},
      {title: "NIF", key: "nif"},
      {title: "Name", key: "name"},
      {title: "Street", key: "address_street"},
      {title: "City", key: "address_city"},
      {title: "Postal Code", key: "address_cp"},
      {title: "Phone", key: "phone"},
      {title: "eMail", key: "email"},
      {title: "Creation Date", key: "createdAt"}
    ];

    var rows = Clients.find().map(function(client) {
      client.address_street = client.address.street;
      client.address_city = client.address.city;
      client.address_cp = client.address.cp;
      return client;
    });
```

Was just wondering if it could be done but I was doing it in a wrong way.

Thanks!
