### ISSUE TITLE
jspdf.plugin.autotable.js:10 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by itsvaibhavmittal** [simonbengtsson/jsPDF-AutoTable#117]
I have downloaded the files **jspdf.js** and **jspdf.debug.js** from the original link in my project along with **jspdf.min.js** and **jspdf.plugin.autotable.js** from your github link.

Whenever I start my project I encounter the following error:
**jspdf.plugin.autotable.js:10** Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
How to solve this error ?

These files are included in my app file as mentioned below:
define([
	'jquery',
	'jspdf',
        'jspdf.debug',
	'jspdf.min',
	'jspdf.plugin.autotable',
],....

The version for jspdf.pugin.autotable is v2.0.24

**Comment by simonbengtsson** [comment]
You should only include jspdf once. Try to remove the other ones something like this and report back.

```js
define([
    'jquery',
    'jspdf.debug',
    'jspdf.plugin.autotable',
],....
```

**Comment by itsvaibhavmittal** [comment]
I tried by including only the files mentioned by you, but the same error persists.
```
define([
    'jquery',
    'jspdf.debug',
    'jspdf.plugin.autotable',
],....
```

**Comment by simonbengtsson** [comment]
Does the problem persist if you try without using `requirejs`?

**Comment by itsvaibhavmittal** [comment]
I am yet to try it without requirejs as it is a complicated legacy code, but just to let you know I tried with autotable version 2.0.21 and the error was:
`jspdf.plugin.autotable.js:10 Uncaught ReferenceError: jsPDF is not defined`

This was the reason I moved to the latest version.

**Comment by itsvaibhavmittal** [comment]
This is fixed. I mentioned the order of loading in requirejs shim config file as mentioned below:
`'jspdf.plugin.autotable' : ['jspdf.debug', 'jspdf', 'jspdf.min']`

It works fine after this.

**Comment by simonbengtsson** [comment]
Glad it worked for you! Did you change something in the plugin to make it work?

**Comment by itsvaibhavmittal** [comment]
Nothing changed in the plugin. All the files are as it is. I had a sequence issue with some other plugin as well. "undefined" error led me to specify the load sequence and it worked.

**Comment by simonbengtsson** [comment]
Okey sweet!
