### ISSUE TITLE
How to set border color to jspdf autotable. 

### ISSUE THREAD

**Issue by Omkarmhaiskar** [simonbengtsson/jsPDF-AutoTable#118]
I have used jpdf autotable plugin to to create pdf. 
Below is my code.

```js
var columns = ["Col1", "Col2", "Col3", "Col4", "Col5", "", "   ", "   ", "  "];
var data = r.d;

var array = JSON.parse("[" + r.d + "]");
var doc = new jsPDF('p', 'pt', 'letter');
doc.setFontSize(12);
doc.setFontStyle('bold');

doc.text('Water Soluble Phosphorus', 250, doc.autoTableEndPosY() + 30);
doc.autoTable(columns, array, { startY: doc.autoTableEndPosY() + 40, theme: 'grid',
  columnStyles: {first_name: {fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold'}}
});

doc.save('Test.pdf');
```

I am getting data array through ajax call. 
It is genrating the pdf, but when i tried to  print pdf border not displaying correctly on print, border disappers in pdf. 

I want to set dark black border to autotable.
How can i set dark black color border to each column of table. 

Please Help me. 

Thanks In advance. 
Omkar

**Comment by simonbengtsson** [comment]
Could you recreate the issue in a codepen? You can base it on [this template](http://codepen.io/someatoms/pen/EjwPEb). When a tried similar code it worked fine.

**Comment by simonbengtsson** [comment]
If you are still having issues, feel free to reopen.

**Comment by prabusendhil** [comment]
In latest version(v2.1.0) border removed from autotable. If i need to set or change border color means what should i do?

**Comment by simonbengtsson** [comment]
Are you using the`lineColor` and `lineWidth` styles?

**Comment by prabusendhil** [comment]
var doc = new jsPDF('p', 'pt', 'a4',true);

                var totalPagesExp = "{total_pages_count_string}";
                var val = [];
                doc.setFontSize(defaults.pdfFontSize);
                var res = doc.autoTableHtmlToJson(document.getElementById("testTablePDF"),false);
                var base64data;
                var pageContent = function (data) {
                    // HEADER
                    doc.setFontSize(18);
                    doc.setTextColor(40);
                    doc.setFontStyle('normal');
                    //doc.addImage(imgData, 'PNG', data.settings.margin.left, 10, 75, 25);
                    if (options.data.location) {
                        var Branch = "Branch - " + options.data.location;
                        doc.setFontSize(9);
                        doc.setTextColor(40);
                        doc.text(Branch, data.settings.margin.left, 50);
                    }
                   
                    if (options.data.startDate) {
                        var startDate = "Start Date - " + options.data.startDate;
                        doc.setFontSize(9);
                        doc.setTextColor(40);
                        var xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(startDate) * doc.internal.getFontSize() / 2);
                        doc.text(startDate, xOffset, 50);
                    }
               
//                    if (options.data.financialYear) {
//                        var financialYear = "Financial Year - " + options.data.financialYear;
//                        doc.setFontSize(9);
//                        doc.setTextColor(40);
//                        var xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(financialYear) * doc.internal.getFontSize() / 2);
//                        doc.text(startDate, xOffset, 50);
//                    }
                    if (options.data.month) {
                        var month = "Month - " + options.data.month;
                        doc.setFontSize(9);
                        doc.setTextColor(40);
                        var xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(month) * doc.internal.getFontSize() / 2);
                        doc.text(month, xOffset, 50);
                    }
                    if (options.data.endDate) {
                        var endDate = "End Date - " + options.data.endDate;
                        doc.setFontSize(9);
                        doc.setTextColor(40);
                        var xOffset = (doc.internal.pageSize.width - 10) - (doc.getStringUnitWidth(endDate) * doc.internal.getFontSize() / 2);
                        doc.text(endDate, xOffset- 80, 50);
                    }
                    if (options.data.year) {
                        var year = "Year - " + options.data.year;
                        doc.setFontSize(9);
                        doc.setTextColor(40);
                        var xOffset = (doc.internal.pageSize.width - 10) - (doc.getStringUnitWidth(year) * doc.internal.getFontSize() / 2);
                        doc.text(year, xOffset-60, 50);
                    }

                    
                    var text = options.data.heading;
                    var xOffset = (doc.internal.pageSize.width / 2) - (doc.getStringUnitWidth(text) * doc.internal.getFontSize() / 2);
                    doc.setFontSize(13)
                    doc.text(text, xOffset-10, 30);
                    
                    // FOOTER
                    var str = "Page " + data.pageCount;
                    // Total page number plugin only available in jspdf v1.0+
                    if (typeof doc.putTotalPages === 'function') {
                        str = str + " of " + totalPagesExp;
                    }
                    doc.setFontSize(10);
                    if (options.data.datas.city)
                    doc.text("Copyright (c) Innoart Technologies. All rights reserved.", data.settings.margin.left, doc.internal.pageSize.height - 30);
                    var xOffset = (doc.internal.pageSize.width - 10) - (doc.getStringUnitWidth(str) * doc.internal.getFontSize() / 2);
                    if (!options.data.datas.city)
                    doc.text("Copyright (c) Innoart Technologies. All rights reserved.", data.settings.margin.left, doc.internal.pageSize.height - 30);
                    var xOffset = (doc.internal.pageSize.width - 10) - (doc.getStringUnitWidth(str) * doc.internal.getFontSize() / 2);
                    doc.text(str, xOffset, doc.internal.pageSize.height - 30);
                    
                };

                doc.autoTable(res.columns, res.data, {
                    theme: 'striped',
                    //startY: doc.autoTableEndPosY() + 20,
                    addPageContent: pageContent,
                   drawRow:function(row){
                        if((row.index >0 && row.index % 20) === 0){
                            doc.autoTableAddPageContent();
                        }
                    },
                    margin: {top: 70},
                    styles: {
                        cellPadding: 3,
                        fontSize: 8,
                        valign: 'middle',
                        
                        overflow: 'linebreak',
                        tableWidth: 'auto',
                        //fileColor: [30, 30, 30],
                        lineWidth: 0,
                    },
                    headerStyles: {
                        //columnWidth: 'wrap',
                        cellPadding: 2,
                        lineWidth: 0,
                        valign:'top',
                        fontStyle: 'bold',
                         halign: 'left',    //'center' or 'right'
                        fillColor: [250, 152, 95],
                        //textColor: [78, 53, 73], //Black     
                        textColor: [255, 255, 255], //White     
                        fontSize: 8,
                        
                        rowHeight:20
                    },
                    bodyStyles: {
//                        textColor: [30, 30, 30]
                    },
//                    columnStyles: {
//                        1: {columnWidth: 150}
//                    }

                });



                if (typeof doc.putTotalPages === 'function') {
                    doc.putTotalPages(totalPagesExp);
                }
                console.log()
                var fileName = options.data.heading.replace(/ /g,"_")
                console.log("fileName")
                console.log(fileName)
                console.log(options.data.heading)
                // Output as Data URI
                //doc.output('save', fileName+'.pdf'); //Try to save PDF as a file (not works on ie before 10, and some mobile devices)
                // doc.output('datauristring');        //returns the data uri string
                // doc.output('datauri');              //opens the data uri in current window
                // doc.output('dataurlnewwindow');     //opens the data uri in new window
                doc.output('dataurlnewwindow');

**Comment by prabusendhil** [comment]
Above is my code in this have some problem i will explain one by one plz help me simon
1. Yes i am using lineWidth = 0 in style . and how to change border color also?
2.In header some columns border is not display.
3.Raised on issue like col Span and row Span issue. You  told me to refer #85 . Can you give idea how to use that code with this code.
4.I am using common header and footer. To limit page content i am using doc.autoTableAddPageContent() within drawrow hook. It says that function is undefined

**Comment by simonbengtsson** [comment]
1. If you are using 0 it is the same as saying that no border should be shown? Try setting it to 1 or more.
2. Probably same problem as 1
3. There is an colspan and rowspan example in examples/examples.js.
4. If you want to have the same header and footer for multiple tables you should do like this: `doc.autoTableAddPageContent(pageContent)` where pageContent is the function you defined above.

**Comment by prabusendhil** [comment]
Thanks a lot Simon. I like your quick response.

**Comment by prabusendhil** [comment]
Table width is fine when i am not using columnWidth. If i use columnWidth table with is extended to out of box in right side . Is there any faulty setting i have in my code?

**Comment by simonbengtsson** [comment]
Sounds like a bug. Can you submit a new issue with a small example that reproduces the issue?

**Comment by prabusendhil** [comment]
Hmm k Simon.

**Comment by prabusendhil** [comment]
If i am using below format

   drawRow:function(row){
                        if((row.index >0 && row.index % 20) === 0){
                            doc.autoTableAddPageContent(pageContent);
                        }
                    },
It shows error in command prombt like this (I am using v2.0.1)
Error: doc.autoTableAddPageContent is not a function
.tableExport/<.drawRow@http://localhost:9000/theme/js/tableExport.js:577:29

**Comment by brahimkra** [comment]
hi, how can i change color of  second column in jspdf-autotable??

**Comment by vignesh-vthink** [comment]
Hi, how to add background color in the full page of pdf ?

**Comment by kimcyrusraymundo** [comment]
How to add border only at the bottom of each cell?
