### ISSUE TITLE
How to get `dataKey` from object

### ISSUE THREAD

**Issue by marioidival** [simonbengtsson/jsPDF-AutoTable#121]
```js
var columns = [
  {title: 'Test', 'dataKey': 'address.test'}
  // ...
];

var data = [
  {address: {test: 'value'}},
  {address: {test: 'value 2'}},
];
```

**Comment by simonbengtsson** [comment]
I'm not sure what you mean. Could you provide more details?

**Comment by marioidival** [comment]
@simonbengtsson I want get `address.test` value in `data` object.

**Comment by Purush0th** [comment]
Or do a map @marioidival 

```javascript
var exportData = data.map(function(item){
return item.address;
});
```

```javascript
var columns = [
  {title: 'Test', 'dataKey': 'test'}
  // ...
];
```

**Comment by simonbengtsson** [comment]
Where do you want to get `adress.test`? 

By the way, `{title: 'Test', 'dataKey': 'address.test'}` will match `var data = [{'address.test': {test: 'value'}}]`.

**Comment by marioidival** [comment]
@simonbengtsson will match `var data = [{'address': {test: 'value'}}]` ???

**Comment by simonbengtsson** [comment]
Nope it matches what I posted above. You would have to flatten your object before passing it to the plugin.

**Comment by simonbengtsson** [comment]
If you are still having problems, let me know!

**Comment by amidevk** [comment]
I've utilized @Purush0th's suggestion to a good effect. Thats the way to go if you happen to have a situation where you have nested object property which you have to use as the dataKey.
