### ISSUE TITLE
Put the page in landscape

### ISSUE THREAD

**Issue by Alorse** [simonbengtsson/jsPDF-AutoTable#122]
Hello,
How do I create PDF pages in landscape?

Thank you.

**Comment by simonbengtsson** [comment]
Hi! For pdf questions, checkout the jspdf docs.

**Comment by pavithramaduranga** [comment]
Since I got directed to here..
`var doc = new jsPDF('l', 'mm', 'a4');`

**Comment by northernbeacheswebsites** [comment]
Why is this closed? This is a legit question in regards to jsPDF-AutoTable...I don't see any clear documentation on this.

**Comment by ayushmankd** [comment]
@northernbeacheswebsites @pavithramaduranga has given the solution.
