### ISSUE TITLE
autoTableHtmlToJson hidden columns

### ISSUE THREAD

**Issue by masteratt** [simonbengtsson/jsPDF-AutoTable#124]
Hello,

I have a grid with 5 columns but only 3 that is actually displayed.

When I call this on that table:

    var res = doc.autoTableHtmlToJson(document.getElementById("widget2Table"));

The res.column and res.data grabs all columns and data including the hidden ones (all 5 instead of the visible 3).

Is there any way to make it so autoTableHtmlToJson only gets the visible data?

Thanks.

**Comment by simonbengtsson** [comment]
Not currently. Hidden rows will be ignored by default however. I'll keep this open until this feature is added.

**Comment by masteratt** [comment]
That'll be great Simon, thank you. I'm looking forward to a solution where the PDF renders just exactly what is on the screen.

**Comment by masteratt** [comment]
For Google users - For now, I have managed a solution like this. Mind you, this is using jqGrid. However most of these are generic functions for a grid library (i.e: getting which column is hidden etc):

Loop through the columns, and make an array of ones that are not hidden.

`var columnsForPdf = [];
        var columnsToRemove = []; //this ends up being redundant but I like to keep track anyway
        var columns = $(curWidget.object.grid).jqGrid("getGridParam", "colModel");
        for (var columnModelIndex in columns) {
          if (columns.hasOwnProperty(columnModelIndex)) {
            var columnModel = columns[columnModelIndex];
            if (!columnModel.hidden) {
              columnsForPdf.push(columnModel.name);
            } else {
              columnsToRemove.push(columnModel.name);
            }
          }
        }`

And then get all rows, and using the array of visible columns constructed above, get the data matching that column key (i.e: so only the visible column data is populated):

` var rowData = $(curWidget.object.grid).jqGrid("getRowData");
          dataForGrid = [];
          var valueToPush = [];

          //loop through the data and build a new array only of columns that are visible (identified by key)
          $.each(rowData, function(rIndex, rValue) {
            valueToPush = [];
            $.each(columnsForPdf, function(cIndex, cValue) {
              valueToPush[cIndex] = rowData[rIndex][cValue];
            });
            dataForGrid.push(valueToPush);
          });

          doc.autoTable(columnsForPdf, dataForGrid, {
            startY: startYsetting,
            pagebreak: "avoid",
            bodyStyles: { rowHeight: 12, fontSize: 8, valign: "middle" },
            styles: { overflow: "linebreak", columnWidth: "auto" }
          });`

This leaves you with an array of data for the visible columns in the right order and everything (so no data misalignment). Tested it with various tables and all worked ok.

**Comment by simonbengtsson** [comment]
Glad you manage hack your way out. One potentially easier solution might have been to use the `autoTableHtmlToJson` function and then filter the results from the function though.

**Comment by masteratt** [comment]
If I understand you correctly, I could not use autoTableHtmlToJson because it returns array with int keys instead of the column model's unique string keys (that the "getRowData" returns and I use as "cValue") so it was very difficult to identify which data was part of which column.

**Comment by simonbengtsson** [comment]
Good point! If you would use autoTableHtmlToJson you would have had to hard code which column index should not be included which might not be desirable.

**Comment by simonbengtsson** [comment]
Added support for this now in version `2.0.25`. It works by checking if the header cell has the style `display: none` if it has, the column is removed from the pdf table, otherwise it is shown. Is this as expected?

**Comment by masteratt** [comment]
That sounds like a potentially great solution but two problems: 

**1.** 
When I use the new 2.0.25 jspdf.plugin.autotable.js, I get an error: ".autoTableHtmlToJson is not a function". Reverting back to old jspdf.plugin.autotable.js doesn't cause this.

**2**
Say I use this: 

        var res = doc.autoTableHtmlToJson(document.getElementById(selectorWithoutHash));

res.columns won't work because jqgrid uses 'name' instead of 'title' (what the autoTable looks for) so  res.column is just a bunch of empty strings. Is there a way to get it to look for .name instead of .title? 

_Note: I can't mix and match gathering data form res and the columns using my own method above as that will cause misalignment._

Thanks.

**Comment by simonbengtsson** [comment]
My bad! Fixed in 2.0.26.

**Comment by Pushpamurugesan** [comment]
Hi,
   I want to display the hidden rows which is not visible in UI in some tables and in few tables the child rows are displayed by clicking on parent row. So, is there any solution for this using jspdf. If so kindly let me know.

**Comment by michaeli1** [comment]
doc.autoTableHtmlToJson(table, true) is used to display hidden rows

**Comment by Pushpamurugesan** [comment]
I'm getting this error - A HTMLTableElement has to be sent to autoTableHtmlToJson.

**Comment by michaeli1** [comment]
You need to pass the table element that you are trying to render as an argument in "autoTableHtmlToJson"
