### ISSUE TITLE
How to change the color of the cell borders

### ISSUE THREAD

**Issue by muneebpandith** [simonbengtsson/jsPDF-AutoTable#125]
Is there any provision to change the border color of the cells. (NOT the header row). There are facilities to change the style of header row but that is not what is concerning me. I wonder of I can set a darker color to the cell BORDERS of the rest of the table (NOT the header row) . Please reply.

**Comment by simonbengtsson** [comment]
Sure! If you are using the grid theme you can simply change the color of the body border using something like this:

        doc.autoTable(columns, data, {
            theme: 'grid',
            bodyStyles: {lineColor: [0, 0, 0]}
        });

**Comment by muneebpandith** [comment]
Perfect.  Works for me. 
Thanku.

**Comment by prometeomcclellan** [comment]
hello, how can I clear the table header color from every table to generate the pdf ?

thanks in advance

**Comment by shubhamyugtia001** [comment]
how to set outer of the table more dense than the rest of the table @simonbengtsson 

thank you

**Comment by shubhamyugtia001** [comment]
like this 


![image](https://user-images.githubusercontent.com/44402764/61714373-482b7880-ad78-11e9-9b18-092295d5ef0a.png)

**Comment by vilashkumar** [comment]
Thank you so much it worked for me
