### ISSUE TITLE
autoTableHtmlToJson columns by .name

### ISSUE THREAD

**Issue by masteratt** [simonbengtsson/jsPDF-AutoTable#127]
Hi again Simon,

I didn't want to derail the other thread so I thought I'll mention it here. 

So if I use something like this:

`var res = doc.autoTableHtmlToJson(document.getElementById("widget2Table"));`

The res.columns is an array of empty strings because jqgrid (the grid framework I use) uses 'name' property for column header instead of 'title' (which is what the autoTable looks for from what I gather).

Is there any way to change it to grab columns by .name? 

Thanks.

**Comment by simonbengtsson** [comment]
Looked quickly into `jqgrid` and it doesn't seem like it is using a html table in dom? Therefore the `autoTableHtmlToJson` won't work. A better idea is probably to send the data you are passing to `jqgrid` directly to `autoTable`.
