### ISSUE TITLE
Height property of the generated table in PDF

### ISSUE THREAD

**Issue by sycho007** [simonbengtsson/jsPDF-AutoTable#128]
Is it possible to get to know the height of the table in the PDF? 

This can be useful if there needs to be text below the table and need to keep track of the height of the page to know if a next page is needed or not.

**Comment by simonbengtsson** [comment]
Did you solve it?

**Comment by sycho007** [comment]
Yes i solved it by looking at the examples. I use the autoTableEndPosY method to determine where I am in the PDF document.

Nice extension for jsPDF!

**Comment by simonbengtsson** [comment]
Sweet! I have been thinking about that as well! I don't have any projects using this plugin and typescript at the moment however. If you would like to write it I'll gladly accept a pull request.

**Comment by sycho007** [comment]
if I find the time in the weekend I will try to do that. :)

**Comment by afifalfiano** [comment]
I have the same issue, can i look your code about this issue?
