### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by avn4986** [simonbengtsson/jsPDF-AutoTable#129]
I'm trying to load Autotables through RequireJS which gives the above stated error. Following is my priority of loading: 
jquery
jspdf
autotable

**Comment by simonbengtsson** [comment]
If you try and create a pdf with jspdf without this plugin, does requirejs load it correctly?

**Comment by avn4986** [comment]
Yes it does. 
I tried loading old versions of autotable to check whether it was my wring that was causing the issue. I found out that this problem occurs after v2.21

**Comment by dcrystalj** [comment]
i have same problem. I followed instructions to download and include this 2 scripts
```
    <script src="js/jspdf.min.js"></script>
    <script src="js/jspdf.plugin.autotable.js"></script>
```

I also tried to install with npm and require but it didn't work

**Comment by avn4986** [comment]
Use older version. It'll work. It did for me.

**Comment by dcrystalj** [comment]
older version didn't help. I managed to solve problem with requiring this 2 lines in package.json:
```    
"jspdf-browserify": "*",
"jspdf-autotable": "*",
```

then in javascript 
```
var jsPDF = require("jspdf-browserify");
var jspdf_autotable = require("jspdf-autotable");
```

**Comment by simonbengtsson** [comment]
I added an example of how to use requirejs with this library in `examples/requirejs.html` now. Are you using some other config then what I have their? The `Uncaught TypeError` you described probably comes from that jspdf was not loaded properly. What version of jspdf are you using?

@dcrystalj Currently jspdf doesn't natively support requirejs or commonjs module loaders so forks such as `jspdf-browserify` are necessary. I sent a pull request fixing module loader issues, but we have to wait for a new npm release for those changes to take affect.

**Comment by avn4986** [comment]
i am using an external config file to wire my dependencies. You think that is the root cause?

**Comment by simonbengtsson** [comment]
Should work with that as well. Can you post it here?

**Comment by simonbengtsson** [comment]
Did you guys get it working? Otherwise can you post your config here?

**Comment by Transhallow** [comment]
I would really appreciate it if you could share it, I just want the html code to render, cause they are tables and background color that I have to apply inside the pdf.

**Comment by dcrystalj** [comment]
When i figured out dependencies i had some problems with page numberings etc... so i switched to [pdfmake](http://pdfmake.org/). That is all i can remember, thank you anyway.
