### ISSUE TITLE
Header and footer for each page instead of each table

### ISSUE THREAD

**Issue by venkateshpenchala** [simonbengtsson/jsPDF-AutoTable#130]
I have a scenario to use multiple tables where data is dynamic(can span across multiple pages or none). I also want to have fixed header and footer in every page. what I did is,

```
 for (var j = 0; j < 6; j++) {
         doc.autoTable(columnsData[j], rowData[j], {
                   beforePageContent: header,
                    afterPageContent: footer,
                    startY: doc.autoTableEndPosY() + 30,
                    margin: {
                        top: 180
                    },
                    pageBreak: 'avoid',
                    overflow: 'linebreak',
                    overflowColumns: false
                });
            }
```

With the above code it is adding header and footer with every table making multiple headers and footers for the each page. Is there any work around to specify header and footer to pages instead of tables?

**Comment by simonbengtsson** [comment]
Sounds like that would be a rather common requirement. It is not supported out of the box however. It would be possible to do by keeping track of the pages that the footer and header has been drawn in variable in an outside scope. And then only draw the header or footer if it has not already been drawn.

It would be nice with built in support though at somepoint. Do you have any suggestions for what that api could look like?

**Comment by simonbengtsson** [comment]
In version 2.1 tge helper method autoTableAddPageContent which takes a function which will be called on every page there is a autotable. Should fix this issue. Let me know if other use cases exist.

**Comment by landrit** [comment]
Any news on this?

**Comment by unigawa** [comment]
is there any update about this issue? I also need fix header and footer for every page not just every table.
