### ISSUE TITLE
module load error

### ISSUE THREAD

**Issue by SamEBae** [simonbengtsson/jsPDF-AutoTable#131]
I have bower getting the auto table library:
"jspdf-autotable": "^2.0.0"

in my html:
    <script src="scripts/vendor/jspdf.debug.font-save.fixed.js"></script>
<script src="scripts/vendor/jspdf.plugin.autotable.js"></script>

I get the error:
jspdf.debug.js:18839 Uncaught Error: Mismatched anonymous define() module: function (jsPDF) {
    'use strict';
....

just a note that I modified one of the functions in jspdf but it should still work fine...

**Comment by SamEBae** [comment]
I had it including the plugin before including the jspdf,

however, I ran into issue with  the export

`typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('jspdf')) :
    typeof define === 'function' && define.amd ? define(['jspdf'], factory) :
    (factory(global.jsPDF));`
It wouldn't do a global export so I had to comment out the first two lines. Just letting you know

(I'm using typescript)

**Comment by simonbengtsson** [comment]
Aha! Glad you got it working. For the second issue, are you using a module bundler?

**Comment by SamEBae** [comment]
I dont believe I am using a module bundler

**Comment by simonbengtsson** [comment]
The code you hade to comment out is [UMD](https://github.com/umdjs/umd). Most likely you have included requirejs included making it trying to use that to bundle the library. Could also be that you are using a dependency that is including requirejs. The latest version of jspdf do for example so you would have to use a special version.
