### ISSUE TITLE
Hide row in jspdf autotable(colspan)

### ISSUE THREAD

**Issue by aksanaivanova** [simonbengtsson/jsPDF-AutoTable#132]
Hello. I try to create pdf from html with autotable, but every time when i have 'notes' in the record line i have to put them in the next row to make document more readable, what I did:
```js
var doc = new jsPDF('landscape', 'pt');
    var res = doc.autoTableHtmlToJson(document.getElementById("table_pdf"));
    doc.autoTable(res.columns, res.data, {
           drawRow:function(row, data){
                if (row.cells[0].raw.substring(0,11) == 'NOTES') {
                       doc.rect(data.settings.margin.left, row.y, data.table.width, 15, 'S');
                        doc.autoTableText(row.cells[0].raw, 25, row.y + row.height / 2, {
                            halign: 'left',
                             valign: 'middle'
                        });
                      data.cursor.y += 15;
}
```
its draw me new line where i put my 'notes', but right next record my notes appears again in the normal line.
I think that must be different ways to solve this problem:
-- get another way to make colspan in the pdf table
-- hide the record  after i put my notes to the drawing cell

thank for any help!!!

**Comment by simonbengtsson** [comment]
To understand your problem better it would be helpful if you would create a codepen. There is a template linked in the readme that you can use. That said, your issue might be related to #111. Does it work if you use `drawCell` instead of `drawRow`?

**Comment by aksanaivanova** [comment]
if i draw a new cell problem will be the same, the original line will appears any way

**Comment by aksanaivanova** [comment]
its working fine... thank you
drawCell: function (cell, data) {
			if (data.row.cells[0].raw.substring(0,4) == 'NOTES') {
				if (data.column.dataKey === 0) {
					doc.rect(data.settings.margin.left, data.row.y, data.table.width, 15, 'S');
					doc.autoTableText(cell.raw, cell.x + 5, cell.y + cell.height / 2, {
						halign: 'left', valign: 'middle'});
					}
				return false;
				}
			},
