### ISSUE TITLE
Getting pagecount across document

### ISSUE THREAD

**Issue by eddie1459** [simonbengtsson/jsPDF-AutoTable#134]
I am creating a document and needing the page count on each page.  The problem is when I combine multiple tables like so:

 ```
array.forEach(function (items) {
                doc.autoTable(columns, items, {
                    afterPageContent: footer,
                    pageBreak: 'avoid',
                    theme: 'grid'
                });
                beginningPos = doc.autoTableEndPosY();
            });

```
in my footer function I have it set up like most examples:

```
var footer = function (pdfResultsData) {
                var str = "Page " + pdfResultsData.pageCount;
                // Total page number plugin only available in jspdf v1.0+
                if (typeof doc.putTotalPages === 'function') {
                    str = str + " of " + pdfResultsData.pageCount;
                }
                doc.setTextColor(0, 0, 0);
                doc.text(str, pdfResultsData.settings.margin.left, doc.internal.pageSize.height - 30);            };
```

But I discovered that the "pageCount" is only the count of the pages that the current table spans.  Is there a way to get the pagecount of the document as a whole?

**Comment by eddie1459** [comment]
I updated my footer function to look like this, its a hack but it works:

var footer = function (pdfResultsData) {
                if (curPos >= pdfResultsData.cursor.y) {
                    doc.pageCount++;
                }
                var str = "Page " + doc.pageCount;
                // Total page number plugin only available in jspdf v1.0+
                if (typeof doc.putTotalPages === 'function') {
                    str = str + " of " + doc.pageCount;
                }
                if (curPos >= pdfResultsData.cursor.y) {
                    doc.setTextColor(0, 0, 0);
                    doc.text(str, pdfResultsData.settings.margin.left, doc.internal.pageSize.height - 30);
                }
                curPos = pdfResultsData.cursor.y;

                if (doc.pageCount == 1) {
                    doc.text(str, pdfResultsData.settings.margin.left, doc.internal.pageSize.height - 30);
                }
            };

**Comment by simonbengtsson** [comment]
Glad you solved it, will keep this open until it's fixed better.

**Comment by simonbengtsson** [comment]
See solution in #144
