### ISSUE TITLE
HTML Content

### ISSUE THREAD

**Issue by Transhallow** [simonbengtsson/jsPDF-AutoTable#135]
I have a smart text implied to my program and the problem is when i want to render the codes from it using autoTableHtmlToJson it just ignores it completely. Am I supposed to use a different method, or Am I doing something wrong.

**Comment by simonbengtsson** [comment]
What do you mean with smart text? Can you post an example?

**Comment by Transhallow** [comment]
so i store the data in a html format like "<h2><span style="color:#FF0000">adsfasdfasdfadfads</span></h2>" , in jspdf there was a format where I would use fromHTML, and replace the var source with the html string, but for autotable I cant seem to find anything. Any help?

**Comment by Transhallow** [comment]
var source = "<p> Hello </P><p> test </p> ";
					doc.fromHTML(
					source,
					15,
					15,
					{
					'width': 180,'elementHandlers': elementHandler
					});

**Comment by simonbengtsson** [comment]
The `fromHTML` method is a part of the standard jspdf library which means you don't need this plugin for it. However if you wish to use this plugin, use it like this:

```js
var doc = new jsPDF('p', 'pt');
doc.text("From HTML", 40, 50);
var res = doc.autoTableHtmlToJson(document.getElementById("basic-table"));
doc.autoTable(res.columns, res.data, {startY: 60});
doc.save("table.pdf");
```

**Comment by Transhallow** [comment]
yeah i tried that, but whenever i change the document.getElementById("basic-table") into my string, it just comes out blank.

**Comment by simonbengtsson** [comment]
You need to send a javascript table element node to the  `autoTableHtmlToJson` function, not a string. You'll need to set an id on your table and then replace `basic-table` with it. Or did I misunderstand something?

**Comment by Transhallow** [comment]
Yeah thats the deal, with jspdf. I just send a string which contains html code inside. And from there it will render it. Most of my data are in html code, I am not trying to capture the html code from the html file, which is the method you showed me up there.

**Comment by simonbengtsson** [comment]
There is no method to turn an html string into a table with this plugin. You either have to pass in raw javascript objects or use the autoTableHtmlToJson function which takes an javascript table dom node. Checkout the examples for how this can be done in the readme or the `examples in examples/examples.js`.

**Comment by Transhallow** [comment]
Even if it cant render tables, is there away for it to read <font size="3" color="red">? and apply the html code inside the pdf

**Comment by simonbengtsson** [comment]
Nope, this plugin is strictly for tables and all styles has to be specified using the settings object. At least for now.

**Comment by sudarshan211** [comment]
Is it possible to add extra content after table in pdf please help..
