### ISSUE TITLE
Options are not working

### ISSUE THREAD

**Issue by THPubs** [simonbengtsson/jsPDF-AutoTable#138]
Hi, I just tried to customize the pdf. Unfortunately, non of the options I pass work. I get the right data in the table but not the right styles I added in the options. How can I fix this?

I use this in my Meteor app. Here's my code :

    let doc = new jsPDF('p', 'pt');

    const header = function (data) {
      doc.setFontSize(20);
      doc.setTextColor(40);
      doc.setFontStyle('normal');
      doc.text('Report', data.settings.margin.left + 35, 60);
    };

    const totalPagesExp = '{total_pages_count_string}';
    const footer = function (data) {
      let str = 'Page ' + data.pageCount;
      // Total page number plugin only available in jspdf v1.0+
      if (typeof doc.putTotalPages === 'function') {
        str = str + ' of ' + totalPagesExp;
      }
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 30);
    };

    const options = {
      beforePageContent: header,
      afterPageContent: footer,
      margin: {top: 80}
    };

    // Only pt supported (not mm or in)

    doc.autoTable(countryPdfTableHeaderColumns, countries, options);
    doc.save('tabled.pdf');

**Comment by simonbengtsson** [comment]
Seems to work for me: http://codepen.io/someatoms/pen/bZvEvd?editors=1010. Can it be an issue with you metor config? Seems strange though.

Feel free to reopen if you are still having issues.

**Comment by bernfarr** [comment]
@simonbengtsson I see that the total number of pages plugin isn't working correctly in your example. I'm currently having problems invoking this. It seems as if the plugin isn't getting installed. I'll enter a note in the jsPDF page.

**Comment by RekaRajendran** [comment]
@simonbengtsson . I saw the code  http://codepen.io/someatoms/pen/bZvEvd?editors=1010 . 
In footer total_pages_count_string is not working correctly in your example. can you help me?

**Comment by simonbengtsson** [comment]
Oops my bad, turns out I forgot to add the actual call to `putTotalPages()`. Fixed it in that codepen now. In the future, feel free to write on stackoverflow with the tag `jspdf-autotable` if you are having issues.
