### ISSUE TITLE
Borders only table

### ISSUE THREAD

**Issue by ayozebarrera** [simonbengtsson/jsPDF-AutoTable#141]
Is possible? set only table borders and not cell borders

**Comment by simonbengtsson** [comment]
Nope, that feature is not available. Sounds like a good feature though so will keep this issue open until it's implemented. No time line though. 

That said, you can probably get it to work using the hooks and draw your own borders.

**Comment by ayozebarrera** [comment]
Ok, will try on hooks :)

Good job & thanks, mate

**Comment by ayozebarrera** [comment]
Thanks @simonbengtsson
