### ISSUE TITLE
startY seems not working

### ISSUE THREAD

**Issue by andretrial** [simonbengtsson/jsPDF-AutoTable#142]
Hi, I'm trying to use the startY property in order to set the y-coordinate from which start to print the table.
But in seems that this parameter it is not applied at all on the pdf.

Any suggestion?

Thanks

**Comment by andretrial** [comment]
Debugging the code, it seems that the variable is only assigned in the getDefaults()  function, and for this reason it never step into the check : 
`        
if (settings.pageBreak === 'always' && settings.startY !== false || settings.startY !== false && minTableBottomPos > pageSize.height) {
            this.addPage(this.addPage);
            cursor.y = settings.margin.top;
        }
`

And it will be printed without taking care of this parameter.

**Comment by andretrial** [comment]
I fixed the problem adding a simple assignation of this value in the initSettings function
`
                 if (typeof userOptions.styles.startY !== 'undefined') {
                    settings.startY =  userOptions.styles.startY;
                }
`
I think the problem is that the assign method merges different structures:
`  var settings = Object.assign({}, getDefaults(), userOptions); `
The structure generated (and used in the script) by getDefaults is different from the one defined and passed as userOptions.
In fact, as we can see in my quick fix, startY in defaults is **settings -> startY** instead of **settings -> styles -> startY.**
Maybe this issue will happen also on others settings e.g pageBreak.

So the final fix would be or to unify the structures, either change in the script  **settings.startY**  to  **settings.styles.startY**

**Comment by simonbengtsson** [comment]
Can you show the code you are using when the problems appear? It works in the examples.
