### ISSUE TITLE
page numbering

### ISSUE THREAD

**Issue by funflyer** [simonbengtsson/jsPDF-AutoTable#144]
hi,

when producing a pdf with multiple tables and the footer as specified in the example, it seems as if the footer was added again with every table thats drawn. also the page numbering is incorrect.

```
var footer = function (data) {
                doc.setFontSize(10);
                doc.setFontStyle('normal');
                var str = "Page " + data.pageCount;
                str = str + " of " + totalPagesExp;
                doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 30);
                var today = new moment().format("YYYY-MM-DD");
                doc.text(today, right, doc.internal.pageSize.height - 30, 'right');
            };
```

```
doc.autoTable(columns, [], {
                        startY: doc.autoTableEndPosY(),
                        afterPageContent: footer,
                        headerStyles: {
                            fillColor: 255,
                            textColor: 0,
                            fontStyle: 'bold',
                            rowHeight: 20
                        }
                    });

```
page 1

![image](https://cloud.githubusercontent.com/assets/1750778/16750395/c7dd24ee-47d1-11e6-9cff-ef9cbb6370a3.png)

other pages 

![image](https://cloud.githubusercontent.com/assets/1750778/16750403/d478b66e-47d1-11e6-8e02-53a22fa4150c.png)

last page (6)

![image](https://cloud.githubusercontent.com/assets/1750778/16750416/e7036360-47d1-11e6-8fab-1d4735019523.png)

**Comment by funflyer** [comment]
i realized, that the table.pageCount was reset to 1 at the creation at every new table:

```
var Table = function Table() {
        babelHelpers.classCallCheck(this, Table);

        this.height = 0;
        this.width = 0;
        this.contentWidth = 0;
        this.rows = [];
        this.columns = [];
        this.headerRow = null;
        this.settings = {};
        **this.pageCount = 1;**
    };

```
and then increased if that table was drawing on the next page
```

function addPage(jspdfAddPage) {
        settings.afterPageContent(hooksData());
        jspdfAddPage();
        table.pageCount++;
        cursor = { x: settings.margin.left, y: settings.margin.top };
        settings.beforePageContent(hooksData());
        if (settings.drawHeaderRow(table.headerRow, hooksData({ row: table.headerRow })) !== false) {
            printRow(table.headerRow, settings.drawHeaderCell);
        }
    }
```
i came up with a quick fix, by implementing a global page count. i recommend to implement it. nevertheless it wont work if youre adding new pages manually.


fix (plugin):
```
**var globalpagecount = 1**

    var Table = function Table() {
        babelHelpers.classCallCheck(this, Table);

        this.height = 0;
        this.width = 0;
        this.contentWidth = 0;
        this.rows = [];
        this.columns = [];
        this.headerRow = null;
        this.settings = {};
        **this.pageCount = globalpagecount;**
    };

function addPage(jspdfAddPage) {
        settings.afterPageContent(hooksData());
        jspdfAddPage();
        table.pageCount++;
        **globalpagecount++;**
        cursor = { x: settings.margin.left, y: settings.margin.top };
        settings.beforePageContent(hooksData());
        if (settings.drawHeaderRow(table.headerRow, hooksData({ row: table.headerRow })) !== false) {
            printRow(table.headerRow, settings.drawHeaderCell);
        }
    }
```

and in the app.js

```
var currentpage = 0;

            var footer = function (data) {

                if (currentpage < data.pageCount) {

                    doc.setFontSize(10);
                    doc.setFontStyle('normal');

                    var str = "Page " + data.pageCount;
                    str = str + " of " + totalPagesExp;


                    doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 30);
                    currentpage = data.pageCount;
                }


            };
```

**Comment by simonbengtsson** [comment]
I have seen people posting about this before so it is indeed confusing. Will think about how to change this in the next release. Will leave this issue open until something is done.

**Comment by funflyer** [comment]
ok i found a permanent fix. just calling the footer function at every table generation and use the jspdf.numberofpages() function to print the actual page nr. no need to change the autotables api:

```
var currentpage = 0;

            var footer = function (data) {

                if (currentpage < doc.internal.getNumberOfPages()) {

                    doc.setFontSize(10);
                    doc.setFontStyle('normal');

                    var str = "Page " + doc.internal.getNumberOfPages();
                    str = str + " of " + totalPagesExp;
                    doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 30);
                    var today = new moment().format("YYYY-MM-DD");
                    doc.text(today, right, doc.internal.pageSize.height - 30, 'right');
                    currentpage = doc.internal.getNumberOfPages();
                }
            };
```

**Comment by simonbengtsson** [comment]
True!

**Comment by BenBabu** [comment]
I tried the above fix. But where can i get the value for "totalPagesExp"?. I couldn't find it any where.

**Comment by simonbengtsson** [comment]
The totalPagesExpression can be any string but i would recommend something like "{{total_pages}}".

**Comment by BenBabu** [comment]
Thats okay. But where can we get the total pages?. Is it in the pdfOptions object?

**Comment by kwalski** [comment]
for anyone who reaches here like me trying to figure out what is totalPagesExp it is a placeholder string replaced by jsPDF's putTotalPages(totalPagesExp).

I spent fair bit of time searching for clues in jsPDF-Autotable code and didn't find anything :smile:

**Comment by jwmann** [comment]
Also for reference, you don't really need a page counter variable.
This is my barebones version for anyone else's future reference.

```
const totalPagesExp = "{total_pages_count_string}";

doc.autoTable(columns, data, {
  addPageContent: data => {
    let footerStr = "Page " + doc.internal.getNumberOfPages();
    if (typeof doc.putTotalPages === 'function') {
      footerStr = footerStr + " of " + totalPagesExp;
    }
    doc.setFontSize(10);
    doc.text(footerStr, data.settings.margin.left, doc.internal.pageSize.height - 10);
  }
});

if (typeof doc.putTotalPages === 'function') {
  doc.putTotalPages(totalPagesExp);
}
```

**Comment by DCZ23** [comment]
Thanks a lot @jwmann , this solution worked great for me. My pages are being created dynamically, so I just added this to the "doc.autoTableSetDecaults" hook and it works like a charm now. I had the issue where it was saying "Page 1 of 2" on BOTH pages, instead of "Page 2 of 2" on the dynamically created additional page. 

Just wanted to say thanks!

**Comment by Martwall** [comment]
Had a problem with this as well and I think that [this solution](https://github.com/MrRio/jsPDF/issues/109#issuecomment-610840510) could also work when dynamically generating pages.

**Comment by zseijas** [comment]
> Also for reference, you don't really need a page counter variable. This is my barebones version for anyone else's future reference.
> 
> ```
> const totalPagesExp = "{total_pages_count_string}";
> 
> doc.autoTable(columns, data, {
>   addPageContent: data => {
>     let footerStr = "Page " + doc.internal.getNumberOfPages();
>     if (typeof doc.putTotalPages === 'function') {
>       footerStr = footerStr + " of " + totalPagesExp;
>     }
>     doc.setFontSize(10);
>     doc.text(footerStr, data.settings.margin.left, doc.internal.pageSize.height - 10);
>   }
> });
> 
> if (typeof doc.putTotalPages === 'function') {
>   doc.putTotalPages(totalPagesExp);
> }
> ```

it is worked for me!

**Comment by paikinit** [comment]
I'm trying to access the total number of pages count to see if i can add some additional text in the last page, inside the `didDrawPage` function.

Is there any workaround for the same?

**Comment by mikeantonelli** [comment]
For a dynamically created pages, I was able to solve this by iterating over each page after the table is rendered:

```ts
  // Draw the footer with the page number on each page
  const totalPages = doc.getNumberOfPages()

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    const pageSize = doc.internal.pageSize
    doc.setFontSize(10)
    doc.text(`Page ${i} of ${totalPages}`, pageSize.getWidth() - 100, pageSize.getHeight() - 20)
  }
```
