### ISSUE TITLE
Cannot export more than 2500 rows of table Data into a PDF.

### ISSUE THREAD

**Issue by RashmiNalwad** [simonbengtsson/jsPDF-AutoTable#145]
I am trying to export a table with data having more than 2500 rows into a PDF using jsPDF plugin. But it hangs with no exception and no PDF is generated.

Any kind of work around or help is appreciated.

**Comment by simonbengtsson** [comment]
I once tried generating longer pdfs without much success. Dont remember if it was this plugin or jspdf that broke though. For I can't be of much assistant unfortunately.

**Comment by simonbengtsson** [comment]
Exactly 2500 btw?

**Comment by RashmiNalwad** [comment]
I have data around 2700 rows, But when tested even for smaller numbers even 1000 rows is not loading.

**Comment by simonbengtsson** [comment]
The limit seems to be somewhere around 1000 rows. I have yet to find the reason. If someone decides to look into it it would be much appreciated.

**Comment by simonbengtsson** [comment]
I successfully tried now with 100 000 rows (3000 pages and 74 MB). I saved it with `doc.save("table.pdf")` and it took around 10 seconds. Something that did not work however was to display those big pdfs in an iframe in the browser. There seem to be some kind of byte size maximum for this.

If you run into this, it would be much appreciated if you posted here with some code.

**Comment by santukumar2017** [comment]
**This is working fine for me.**
Use 'bloburl' instead of 'datauristring'.

**Javascript/jquery:**

$("#pdf_preview").attr("src", doc.output('bloburl'));

**html**

<iframe id="pdf_preview" type="application/pdf" style="border:1px solid #666CCC" title="PDF Records" frameborder="1" scrolling="auto" height="520" width="100%"></iframe>

best of luck...

**Comment by simonbengtsson** [comment]
Awesome! Will check it out!

**Comment by ginanjarnugroho** [comment]
please help me, i have same error. any solution?

**Comment by zodman** [comment]
Here some stats:

```
calling autoTable 50,000 records  20600.31278400123 ms 
calling autoTable 150,000 records  67905.41418499872 ms 
200,000 records blowup! not return ...- JavaScript heap out of memory
```

using nestjs(backend) 12cpu with 16Gb of ram.

**Comment by mamshan** [comment]
this worked for me  (2000+ rows)


const blobUrl = doc.output('bloburl');
window.open(blobUrl, '_blank');
