### ISSUE TITLE
Cannot read property '0' of undefined: createdHeaderCell() when used with webpack

### ISSUE THREAD

**Issue by chadi-kazan** [simonbengtsson/jsPDF-AutoTable#146]
using version 2.0.28(also had it with 2.0.26) with jspdf 1.2.61 with webpack, i get this error in my prod environment. It's as if webpack is not uglifying the library properly. my webpack version is 1.13.1 with babel 5.8.35.

my webpack config related to this is below

`plugins: [`
        `new webpack.optimize.OccurenceOrderPlugin(),`
       ` ...(!DEBUG ? [`
            `new webpack.DefinePlugin({`
               ` 'process.env': {`
                    `NODE_ENV: JSON.stringify('production')`
                `}`
            `}),`
            `new webpack.optimize.LimitChunkCountPlugin({maxChunks: 1}),`
            `new webpack.optimize.DedupePlugin(),`
            `new webpack.optimize.UglifyJsPlugin(),`
            `new webpack.optimize.AggressiveMergingPlugin()`
       ` ] : [])`
    `],`

anyone had this before?

**Comment by simonbengtsson** [comment]
I have now fixed some module bundler issues in version `2.0.32` so first update and test if that solves your issue. That said, your issue seems to be related to how you are using autotable. Do you still get the issue if you test your code without webpack?

**Comment by simonbengtsson** [comment]
Closing for now, feel free to ropen if you are still having issues.
