### ISSUE TITLE
Choice when to show header

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#149]
Add a `showHeader` option that makes it easy to choose header behavior. The following values should be accepted:
- `'always'|true` Show the header on every new page. The current behavior in `2.x`.
- `'once'` Show header only on the first page. Might look better for small tables.
- `'never'|false` Never show header.

**Comment by arnabk** [comment]
+1

**Comment by simonbengtsson** [comment]
Just added this now. Will be included in the next version (v2.2).
