### ISSUE TITLE
autoTableText overflow

### ISSUE THREAD

**Issue by ayozebarrera** [simonbengtsson/jsPDF-AutoTable#154]
Hi,

I'm trying to control the overflow of autoTableText but I can't achieve it.

This is my actual output:
![citec-hor1](https://cloud.githubusercontent.com/assets/6180188/17296297/64c30496-57f8-11e6-9f60-5393a6469e4e.png)
(check the text at the right border.. should be inside of the blue rect)
And I'm having this
```js
...
doc.setFillColor(0, 255, 255);
doc.rect(cell.x, cell.y, cell.width*2, cell.height*2, 'F');
doc.autoTableText(d.notes[0].note, cell.x + 5, cell.y + cell.height / 2, {
  halign: 'left',
  valign: 'middle',
  overflow: 'linebreak'
});
...
```

How I should do it?

**Comment by simonbengtsson** [comment]
`autoTableText` does only support the `valign` and `halign` styles, not `overflow`. To make the text fit the box you can use the jspdf function `splitTextToSize` and `getStringUnitWidth`.

**Comment by ayozebarrera** [comment]
As you can see on my reaction... <3 thanks

**Comment by ayozebarrera** [comment]
Oops, If any user need this...I solved it using splitTextToSize and passing the array to autoTableText
