### ISSUE TITLE
Programmatically change row height

### ISSUE THREAD

**Issue by razorrazor** [simonbengtsson/jsPDF-AutoTable#155]
I would like to change row height when some condition occurs.
For example, I try the following:

```
var createdCell = function(cell, data) {
	if (data.column.dataKey == 6 && cell.raw != '') {
               cell.styles.rowHeight = 42;
	}
}
```
But this does not work. I've also tried the same in drawCell event, with no success.
Please help. Thanks in advance!

**Comment by razorrazor** [comment]
I answer myself:

```
var drawRow = function(row, data) {
    if (data.table.rows[data.row.index].cells[6].text != '') {
        row.height = 34;
    }
}
```

**Comment by simonbengtsson** [comment]
Glad you solved it! Styles can't be changed in the hooks currently. I'm thinking of either giving a warning or enable this feature in the future however.

**Comment by Mmferry** [comment]
Have you solve it?
