### ISSUE TITLE
Possible enhancement: autoTableHtmlToJson() might return inner HTML text inside cells

### ISSUE THREAD

**Issue by razorrazor** [simonbengtsson/jsPDF-AutoTable#156]
Sometimes, the content of a table cell is not plain text, but HTML. However, on those cases autoTableHtmlToJson() function returns blank string.

Don't worry. It's very easy to fix this misbehaviour.
At line 1998 in version 2.0.33, simply change this one:
    `var val = cell ? cell.textContent.trim() : '';`
by this other:
    `var val = cell ? cell.innerHTML.trim() : '';`

In future versions of AutoTable, it would be nice to have a third param for autoTableHtmlToJson() function, something like "HTML = false" in case you want to get only text content, or "HTML = true" in case you want to get all the raw content.

When HTML = true, after calling autoTableHtmlToJson() you could get whatever you want from the HTML data retrieved of those cells that contains HTML. For the cells with only plain text, you do not need to do anything.

For instance:

```
var res = pdf.autoTableHtmlToJson(document.getElementById("table_cust"), true, true);  // note the third param here! Inner HTML will be returned.

// Now, we are going to do some things with the data
for (i = 0; i < res.data.length-1; i++) {
	// Get image path of column 6
	if (res.data[i][6] != '')
		res.data[i][6] = $(res.data[i][6]).attr('src');  // Originally, this table cell contained <img alt='' src='../../img/test1.png' />
	// Force to put blank string for column 7
	if (res.data[i][7] != '')
		res.data[i][7] = '';
}
// Last row has formatted total values in columns 1 and 5 (i.e. <div class='text-center'><b>1.250,00€</b></div>). But we only need the text:
res.data[res.data.length-1][1] = $(res.data[res.data.length-1][1]).text();
res.data[res.data.length-1][5] = $(res.data[res.data.length-1][5]).text();
```

Regards!

**Comment by simonbengtsson** [comment]
For complex html tables it would probably be easier to replace `autoTableHtmlToJson` with a custom built one. A have noticed that a lot of people (maybe a majority) utilize this function however. Therefore I have been thinking about improving the html import for some time and created a ticket for it now #157.

In terms of the issue you mentioned I think it should be `textContent` and not `innerHTML`. [Mdn](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) state the following `The Node.textContent property represents the text content of a node and its descendants.`. And these are the results I get when testing in chrome/safari/firefox.

```js
var node = document.createElement("div");
node.innerHTML = "<strong>Bold</strong> text";
node.textContent; // "Bold text"
node.innerHTML; // "<strong>Bold</strong> text"
```

What browser are you using when textContent gives you an empty string? It should be supported in IE9+.

**Comment by razorrazor** [comment]
I used it on Explorer, Firefox, Opera and Chrome, and the result is the same.

My workaround `var val = cell ? cell.innerHTML.trim() : '';` did the trick.

**Comment by simonbengtsson** [comment]
So if you run each of those lines in the console you get another result than me?
```js
var node = document.createElement("div");
node.innerHTML = "<strong>Bold</strong> text";
node.textContent; // Outputs: "Bold text"
node.innerHTML; // Outputs:  "<strong>Bold</strong> text"
```

**Comment by simonbengtsson** [comment]
Could you post the html that does not work for you?

**Comment by razorrazor** [comment]
Ok. I know what you mean, but when you need some information of an html, for example the 'src' inside `<img src='/img/temp01.png' alt='image 1'>` there is no way of getting text. Do you understand?

**Comment by simonbengtsson** [comment]
Aha you want to access the attributes. No you are right. Currently there is no way of doing that without parsing the html yourself without autotablehtmltojson. I have been thinking of the best way to solve this and I have come with two different alternatives.

The first would be to make it possible to send in a optional parse function to the autotablehtmltojson like this:

’’’js
doc.autoTableHtmlToJson(tableElem, function(tr, td) {
    return tdCell.querySelector("#image").alt;
})
’’’

The second is to add the element object to the cell in autotable. Would be used something like this:

’’’js
doc.autoTable(rows, columns, {
    createdCell: function(cell, data) {
        cell.text = cell.element.querySelector("#image").alt
    }
})
’’’

Which one do you prefer?

**Comment by razorrazor** [comment]
I think it would be better the second one. On the other hand, you might consider to add a third param to autoTableHtmlToJson(), as I mentioned in my first post:

Example:
```
autoTableHtmlToJson(tableElem, includeHiddenElements, showInnerHtml) {
...
var val;
if (showInnerHtml === true)
    val = cell ? cell.innerHTML.trim() : '';
else
    val = cell ? cell.textContent.trim() : ''
...
}
```

**Comment by simonbengtsson** [comment]
And parse out the html tags yourselves from the string? Sounds cumbersome to me? Or how would you go about it?

**Comment by razorrazor** [comment]
That's not a trouble to me, but your second alternative sounds good. In that case, it would be easy to get any attribute value on createdCell event using querySelector (I didn't know of the existence of this function).
You're the master. It's up to you ;)

**Comment by simonbengtsson** [comment]
Further discussions around improvements to the html parsing can be held in #157.

**Comment by tbiinfotech** [comment]
Can I use html under autoTable cell or there is no way to do it?
