### ISSUE TITLE
Enhanced html import

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#157]
It is my understanding that many users are using the `autoTableHtmlToJson`. It would be nice to support html convert better as the current function is simplistic.
- [x]  Alternative way to get text from table cell (originally proposed in #156)
- [x] Set `cell.raw` to the html cell element to enable custom parsing if needed
- [x]  Add `useCssStyles` option to parse some basic css
- [x] Add `includeHiddenHtml` option
- [x] Deprecate `autoTableHtmlToJson` and use a `fromHtml` option instead that can take either a css selector string or an HTMLTableElement

Feel free to post here with further suggestions or comments.

**Comment by funkyduke** [comment]
razorrazor said to replace textContent with innerHTML, but like you said, that's not a good idea. 

But there's a simple solution to accept for example a <br />. Change textContent with innerText. Since FF45 this is now supported for some elements. It's a good start. 

https://bugzilla.mozilla.org/show_bug.cgi?id=264412

**Comment by simonbengtsson** [comment]
You are right, innerText indeed sounds like a better option. Will update to it straight away.

> While textContent gets the content of all elements, including <script> and <style> elements, the IE-specific property innerText does not.

> innerText is aware of style and will not return the text of hidden elements, whereas textContent will.

https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by simonbengtsson** [comment]
Done. Will be included in version 3.0.

**Comment by bhgames** [comment]
@simonbengtsson I've been toying around with a fork of the v3 branch on my local. It's cool that the from HTML works so well but what I'm finding is that it's not actually rendering indentation properly. I've got cells that have <ul> and <li> tags inside(for further indentation within the cell) and while these are picked up fine by Chrome's Print as PDF, the fromHTML option in the new v3 branch ignores them.

I'm not sure if this is intended or not, or if you have any suggestions. I'd be happy to go in and make changes but I'm not sure where best to do it to achieve my goal.

**Comment by simonbengtsson** [comment]
You are right, the fromHtml option does not parse li or ul tags. It is an interesting feature to consider but for now you can access the HTML element cell in the hooks by the cell.raw property and then you can parse it manually and add manual indentation.

**Comment by bhgames** [comment]
Could I do that without altering the library, and could I do it with the more stable, released version? I think there is a hook for "adding a new row."
