### ISSUE TITLE
Column Height

### ISSUE THREAD

**Issue by jjsquad** [simonbengtsson/jsPDF-AutoTable#159]
How I can set custom column/columns height?

My example:

![captura de tela 2016-08-08 as 02 05 00](https://cloud.githubusercontent.com/assets/12722517/17469750/9f65e974-5d0c-11e6-80d9-74d3c2a5e850.png)

I set the fontSize to 20, but the column wont "grown" with text.

Thanks!

**Comment by simonbengtsson** [comment]
You can set the rowheight for the entire row using the styles, but you cannot set the rowheight for a specific column. You could change the rowheight with the hooks however. You can checkout the colspan and rowspan example in example/examples.js for än example of how it can be acconplished.

**Comment by simonbengtsson** [comment]
Closing for now, feel free to reopen if you have further issues.
