### ISSUE TITLE
Image rendering

### ISSUE THREAD

**Issue by ayozebarrera** [simonbengtsson/jsPDF-AutoTable#160]
Hi

I needed to put an image on a header so I checked your ```header-footer``` example. All was ok except instead of the image it renders a black square. 

After a while, I noticed my image was a png so I converted to jpg and voilà!

It seems like PNG doesn't have full support ? see you

**Comment by simonbengtsson** [comment]
Interesting! I guess it doesn't work with pure jspdf either however?

**Comment by ayozebarrera** [comment]
I think so ^^. This issue is just for your interest :stuck_out_tongue_winking_eye: 

See ya, and good job!
