### ISSUE TITLE
Table Header with several rows and Footer

### ISSUE THREAD

**Issue by Grendizr** [simonbengtsson/jsPDF-AutoTable#161]
Hi.

I tried to reopen [a related issue which is closed](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/89), but didn't seem to work, so here I am.

I have a table with header made of two rows. I want both rows to be exported as part of the header, with same style. Currently only the last header row is exported.

I have updated you basic table from the sample. Note that the color display down here is not correct as both row headers should be displayed the same way.

On top of that, the table footer `<tfoot>...</tfoot>` does not seem to be exported at all

<table id="basic-table" style="display: none;">
    <thead>
    <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Country</th>
        <th>IP-address</th>
    </tr>
     <tr>
        <th>&nbsp</th>
        <th colspan="2">Name</th>
        <th>Email</th>
        <th colspan="2">Location</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Donna</td>
        <td>Moore</td>
        <td>dmoore0@furl.net</td>
        <td>China</td>
        <td>211.56.242.221</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Janice</td>
        <td>Henry</td>
        <td>jhenry1@theatlantic.com</td>
        <td>Ukraine</td>
        <td>38.36.7.199</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Ruth</td>
        <td>Wells</td>
        <td>rwells2@constantcontact.com</td>
        <td>Trinidad and Tobago</td>
        <td>19.162.133.184</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Jason</td>
        <td>Ray</td>
        <td>jray3@psu.edu</td>
        <td>Brazil</td>
        <td>10.68.11.42</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Jane</td>
        <td>Stephens</td>
        <td>jstephens4@go.com</td>
        <td>United States</td>
        <td>47.32.129.71</td>
    </tr>
    <tr>
        <td>6</td>
        <td>Adam</td>
        <td>Nichols</td>
        <td>anichols5@com.com</td>
        <td>Canada</td>
        <td>18.186.38.37</td>
    </tr>
    </tbody>
<tfoot><tr><td colspan="6" style="font-size:10px">I am the table footer, and I want to be exported as well cause I am part of the table !!!</td></tr></tfoot>
</table>

Thanks in advance for your quick feedback.

**Comment by simonbengtsson** [comment]
Have you tried using the hooks? It might be a bit tricky but should be possible both having two rows as header and to add a footer. Lets keep this issue open as a feature request though. How would you like the api to look like for this?

**Comment by Grendizr** [comment]
Haven't figure out a way of doing this properly with the hooks.

Would make much more sense to include it as default. Does not sounds too complicated. I would replace the property headerRow:Row with headerRows:Row[]

The headerRow is used to defined the columns of the table, so you can keep doing that by using the last header row of the array. And on top of that you add all previous rows as defined in original table.
In order not to have a breaking change you can check the headers parameter which is provided and create a single or multiple row array.

For footer, just grab the <tfoot> from original table if there and add it as is in the generated table ...

What do you think ?

**Comment by simonbengtsson** [comment]
Sounds good, will probably make it that way when and if it is implemented. Feel free to submit a PR for it.

If want pointers to how to draw multiple headers, I made an example a while back here: http://stackoverflow.com/a/35382414/827047. Basically what I did was first increasing the height of the default header, then simply draw the secondary header in the space that was freed because of it.

Here is a jsfiddle: https://jsfiddle.net/someatoms/tbz8p79j/6/
The pdf ends up something like this:

![image](https://cloud.githubusercontent.com/assets/3586691/17811243/072e5406-6622-11e6-89d0-660fec1a2616.png)

**Comment by Grendizr** [comment]
Thanks for the details. It looks good except some css details cause it almost look like a regular row with the alternate colors.

**Comment by simonbengtsson** [comment]
You should just be able to set the fill color to the same blue to achieve the same styling.

**Comment by simonbengtsson** [comment]
Support for multiple headers and footers now in master. Will be released in version 3.0.

**Comment by padryn** [comment]
Is there a timeline for for when 3.0 will be released?

**Comment by simonbengtsson** [comment]
During easter most likely!
