### ISSUE TITLE
Add option to insert image (graphic element) inside a cell.

### ISSUE THREAD

**Issue by Purush0th** [simonbengtsson/jsPDF-AutoTable#162]

**Comment by simonbengtsson** [comment]
It can be done with the drawCell hook today. However it sounds like a good idea to provide a way to make it easier. Do you have any suggestion of an api for it?

**Comment by simonbengtsson** [comment]
See #93 for an example of how it can be done today.

**Comment by Purush0th** [comment]
Thanks @simonbengtsson!

I was hitting with ```drawCell```'s cell API. This trick really works, getting co-ordinates from drawCell and update the cells with ```afterPageContent```.



```javascript
var images = [];
//...
        drawCell: function(cell, opts) {
          if (opts.column.dataKey === 5) {
            images.push({
              url: imgElements[i].src,
              x: cell.textPos.x,
              y: cell.textPos.y
            });
            i++;
          }
        },
        afterPageContent: function() {
          for (var i = 0; i < images.length; i++) {

            doc.setLineWidth(1);
            doc.setDrawColor(0);
            doc.setFillColor(255, 0, 0);
            doc.circle(images[i].x, images[i].y, 5, 'FD');
          }
//...
```

**Comment by simonbengtsson** [comment]
What do you mean by ` access to graphic element APIs in drawcell`?

**Comment by Purush0th** [comment]
In drawCell callback we have ```cell``` argument. Which doesn't have method (or access) for graphic elements like circle, rectangle etc..

Circle is a method of ```doc```.

```doc.circle(10, 10, 5, 'FD');```

**Comment by simonbengtsson** [comment]
I am considering that a bug. Not really sure why it doesnt work. Will look into it at some point.
