### ISSUE TITLE
dataKey

### ISSUE THREAD

**Issue by omaribr27** [simonbengtsson/jsPDF-AutoTable#164]
Afternoon, i was wondering if there's a way to catch the data value and hide the column. The problem is that i need that value but i don't want to show it on the pdf file.

// Long data - shows how the overflow features looks and can be used
examples.long = function () {
    var doc = new jsPDF('l', 'pt');
    var columnsLong = getColumns().concat([
        {title: shuffleSentence(), **dataKey**: "text"},
        {title: "Text with a\nlinebreak", **dataKey**: "text2"  ¿¿ **hidden:true** ??}
    ]);

Best regards,

**Comment by simonbengtsson** [comment]
If you omit the column in the columns, and only provide it as data for the rows it should work.

**Comment by omaribr27** [comment]
I'll try it today, thanks mate !!
