### ISSUE TITLE
Last row

### ISSUE THREAD

**Issue by erperejildo** [simonbengtsson/jsPDF-AutoTable#165]
First of all thanks for this awesome library, works perfectly.

I was wondering if it has an option to add different style to the last row on a table.
My last row on my table is a total summary and I would like to add a font-weight style just to this line.

Could be possible? Thanks

**Comment by simonbengtsson** [comment]
Sure! You can use the drawRow hook like this:

```js
doc.autoTable(cols, data, {
    drawRow: function (row, data) {
        if (row.index === data.table.rows.count) {
            doc.setFontStyle('bold');
        }
    }
}
```

**Comment by simonbengtsson** [comment]
I tested it know and because of #111 this is what the code should look like:

```js
drawCell: function (cell, data) {
    if (data.row.index === data.table.rows.length - 1) {
        doc.setFontStyle('bold');
    }
}
```

Sorry about the confusion. I updated the above in my prev answer to not confuse other people.

**Comment by erperejildo** [comment]
Perfect, thank you

**Comment by andrellgrillo** [comment]
> First of all thanks for this awesome library, works perfectly.
> 
> I was wondering if it has an option to add different style to the last row on a table.
> My last row on my table is a total summary and I would like to add a font-weight style just to this line.
> 
> Could be possible? Thanks

Hello, how did you do the total row?
