### ISSUE TITLE
Is it possible to insert hyperlinks into autotable

### ISSUE THREAD

**Issue by azakordonets** [simonbengtsson/jsPDF-AutoTable#167]
Hi, I'm using your library to generate tables into pdf, but I can't figure out how to insert hyperlinks into cells. I have 4 columns and one of the contains a hyperlink to Jira issues. Is it possible to specify somehow that type of cell data is a hyperlink and properly display it ? 
 I found one example on [Codepen](https://codepen.io/someatoms/pen/vLYXWB) where the image was put into the cell. Can be it done same way for hyperlinks?

**Comment by simonbengtsson** [comment]
There is no official support at the moment. Will probably look into adding image and hyperlinks support at some point in the future however. You are right that you can do something similar to that codepen example. I modified it slightly with hyperlinks in this [codepen](https://codepen.io/someatoms/pen/vXOLVB?editors=1010).

**Comment by kamov** [comment]
Your example on codepen doesn't show how to add images.
Do you have an idea?
Thanks

**Comment by simonbengtsson** [comment]
Look at the example codepen posted in #93. Here is the link https://codepen.io/someatoms/pen/vLYXWB

**Comment by kamov** [comment]
Awesome!, thanks. Let me try now..

**Comment by royalvincent** [comment]
Have anyone be able to accomplish this?

**Comment by rahulrawat17** [comment]
var generateData = function(amount) {
  var result = [];
  var data = {
    coin: "Sno.",
    game_group: "    ",
    game_name: "XPTO2",
    game_version: "25",
    machine: "20485861",
    vlt: "0"
  };
  for (var i = 0; i < amount; i += 1) {
    data.id = (i + 1).toString();
    result.push(Object.assign({}, data));
  }
  return result;
};

function createHeaders(keys) {
  var result = [];
  for (var i = 0; i < keys.length; i += 1) {
    result.push({
      id: keys[i],
      name: keys[i],
      prompt: keys[i],
      width: 65,
      align: "center",
      padding: 0
    });
  }
  return result;
}

var headers = createHeaders([
  "id",
  "coin",
  "game_group",
  "game_name",
  "game_version",
  "machine",
  "vlt"
]);

var doc = new jsPDF({ putOnlyUsedFonts: true});
doc.textWithLink("click here!!", 28, 20, {
  pageNumber : 2
});
doc.table(1, 1, generateData(10), headers, { autoSize: true });

doc.addPage();
doc.text("Page 2", 10, 10);
doc.text("Placeholder text", 20, 20);
doc.text("Placeholder text", 30, 30);
doc.text("Placeholder text", 40, 40);
doc.text("Placeholder text", 50, 50);
doc.text("Placeholder text", 60, 60);
doc.text("Placeholder text", 70, 70);
doc.text("Placeholder text", 80, 80);

**Comment by rahulrawat17** [comment]
> var generateData = function(amount) { var result = []; var data = { coin: "Sno.", game_group: " ", game_name: "XPTO2", game_version: "25", machine: "20485861", vlt: "0" }; for (var i = 0; i < amount; i += 1) { data.id = (i + 1).toString(); result.push(Object.assign({}, data)); } return result; };
> 
> function createHeaders(keys) { var result = []; for (var i = 0; i < keys.length; i += 1) { result.push({ id: keys[i], name: keys[i], prompt: keys[i], width: 65, align: "center", padding: 0 }); } return result; }
> 
> var headers = createHeaders([ "id", "coin", "game_group", "game_name", "game_version", "machine", "vlt" ]);
> 
> var doc = new jsPDF({ putOnlyUsedFonts: true}); doc.textWithLink("click here!!", 28, 20, { pageNumber : 2 }); doc.table(1, 1, generateData(10), headers, { autoSize: true });
> 
> doc.addPage(); doc.text("Page 2", 10, 10); doc.text("Placeholder text", 20, 20); doc.text("Placeholder text", 30, 30); doc.text("Placeholder text", 40, 40); doc.text("Placeholder text", 50, 50); doc.text("Placeholder text", 60, 60); doc.text("Placeholder text", 70, 70); doc.text("Placeholder text", 80, 80);

Paste the above code here for demo: --->>> http://raw.githack.com/MrRio/jsPDF/master/index.html#

**Comment by Marcus-Shah** [comment]
Have anyone been able to accomplish this?
