### ISSUE TITLE
Add option to insert hyperlinks in cells

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#168]
Currently there is no easy way to add hyperlinks to the table with this plugin. It can be done however as outlined in #167.

**Comment by simonbengtsson** [comment]
I have not find a satisfactory way of doing this. It will be easier to use jspdf's `textWithLink` after the hooks are improved in version 3.0.

**Comment by tedarencn** [comment]
Is it possible to add a link to the word or button? likes,  click button _**Product name**_ to add a link in the table.

**Comment by viniciusdeliz** [comment]
@simonbengtsson can you elaborate a bit more on this issue?
