### ISSUE TITLE
No header table

### ISSUE THREAD

**Issue by eduSanfio** [simonbengtsson/jsPDF-AutoTable#169]
Hi, 
First thank for you library. I'm looking to draw a header-less table. But cant find how to. Also is theres any way to modify the whole row fillColor in the createdCell hook ? I only have to do this when a cell value matches another value but in that hook I don't have the reference for the current row. Any help would be appreciated.

**Comment by simonbengtsson** [comment]
You can create a header-less table by returning false in the drawHeader hook. You have access to the current row by doing `data.row`. If you want to ask any questions in the future stackoverflow is a better option. Make sure you add the tag `jspdf-autotable`.
