### ISSUE TITLE
examples.js examples.spans function and next page table continuation

### ISSUE THREAD

**Issue by piersstorey** [simonbengtsson/jsPDF-AutoTable#170]
Regarding, [examples.js](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/examples/examples.js )

When the example rows are increased to overflow next page, the conditional row logic does not cater for the page break.

**Comment by piersstorey** [comment]
examples.spans within example.js

**Comment by simonbengtsson** [comment]
Thanks for reporting!
