### ISSUE TITLE
How can i add images into cell ?

### ISSUE THREAD

**Issue by aelharrak** [simonbengtsson/jsPDF-AutoTable#171]
Hello,

Can you please provide me an example to add an image for every cell ( the pictures is dynamique ) something like : 

cell.styles.property = src !!

BR,
@mine

**Comment by simonbengtsson** [comment]
Hi! You can check the header and footer example. If you have a more specific question, feel free to create a question with more info on stackoverflow with the tag jspdf-autotable.
