### ISSUE TITLE
Add image into table

### ISSUE THREAD

**Issue by kamov** [simonbengtsson/jsPDF-AutoTable#173]
hi,
I have a html table with images inside.
I want to export in pdf and table is correctly exported.
only images is not added on pdf.
what is missing?
thanks

**Comment by simonbengtsson** [comment]
Check discussion in #93 or this code pen example https://codepen.io/someatoms/pen/vLYXWB

**Comment by kamov** [comment]
I get below error:

Error: Supplied data is not a JPEG 	  
...{var e=t[0]<<8|t[1];if(65496!==e)throw new Error("Supplied data is not a JPEG");.

But image is JPG converted...

**Comment by kamov** [comment]
work fine only if I use your image base64, but not with normal image path..

**Comment by simonbengtsson** [comment]
Have you tried with another image? It sounds like something might be wrong with that particular one. Also does it work without loading this plugin only using jspdf? If it does, I would suggest writing a question on stackoverflow with some steps to reproduce it and tag it `jspdf`.

**Comment by simonbengtsson** [comment]
What do you mean with image path? As far as I know you have to convert your image to base64 before using it with jspdf?

**Comment by kamov** [comment]
> As far as I know you have to convert your image to base64 before using it with jspdf?

Ah ok, I got it... 
Is required to convert image to base64.
converting image to base64 work fine.

**Comment by simonbengtsson** [comment]
Glad it worked out for you!

**Comment by kamov** [comment]
Any idea how to resize font or make text of cell in multiline? now text are truncated as below screenshot:

![screen shot 2016-11-15 at 13 27 47](https://cloud.githubusercontent.com/assets/2345000/20305748/536ef442-ab37-11e6-987e-596cc0c7c8ed.png)

**Comment by simonbengtsson** [comment]
Have you checked the readme? There are styles for both.

**Comment by kamov** [comment]
Yes, but can't find how to avoid that text is get truncated as you can see on screenshot (with three dot on the end)

**Comment by simonbengtsson** [comment]
Check out the `overflow` style.

**Comment by kamov** [comment]
Thanks! Work perfectly 

styles: {overflow: 'linebreak'},

**Comment by Rohit-chapter** [comment]
Hi simonbengtsson , 

I use code of codepen given link in react project  but images are still not showing 
var doc = new jsPDF('p', 'pt');
      var elem = document.getElementById('table');
      var imgElements = document.querySelectorAll('#table tbody img');
      var data = doc.autoTableHtmlToJson(elem);
      console.log(data, "json")
      var images = [];
      var i = 0;
      doc.autoTable(data.columns, data.rows, {
         bodyStyles: { minCellHeight: 30 },
         drawCell: function (cell, opts) {
            if (opts.column.dataKey === 5) {
               images.push({
                  url: imgElements[i].src,
                  x: cell.textPos.x,
                  y: cell.textPos.y
               });
               i++;
            }
         },
         didDrawPage: function () {
            for (var i = 0; i < images.length; i++) {
               doc.addImage(images[i].url, images[i].x, images[i].y, 20, 20);
            }
         }
      });
      doc.save("table.pdf")

Please help me as soon as possible 

Thanks

**Comment by KibikaJ** [comment]
Hi simonbengtsson, 
Kindly, could you check for this when you are free. Thank you in advance. 
[https://stackoverflow.com/questions/62140561/jspdf-autotable-not-displaying-images-with-original-dimensions-properly-in-pdf](url)
