### ISSUE TITLE
Suggestion: add hook to be called whenever jsPDF.addPage() is called

### ISSUE THREAD

**Issue by martinwaugh** [simonbengtsson/jsPDF-AutoTable#174]
I have a document with several tables, some of which may flow across page boundaries. I want to present the page number at the bottom of each page. However, the data.pageCount variable seems to reset at the  beginning of each table, and I need to track it throughout the document.

I suggest adding another hook as follows:

in getDefaults(), add:

	 afterPageAdd: function afterPageAdd(data) {}

And modify addPage like:

	function addPage(jspdfAddPage) {
	    settings.afterPageContent(hooksData());
	    jspdfAddPage();
	    
	    settings.afterPageAdd(hooksData());
	    
	    table.pageCount++;
	    cursor = { x: settings.margin.left, y: settings.margin.top };
	    settings.beforePageContent(hooksData());
	    if (settings.drawHeaderRow(table.headerRow, hooksData({ row: table.headerRow })) !== false) {
	        printRow(table.headerRow, settings.drawHeaderCell);
	    }
	}

This allows me to track the global page number myself.

**Comment by simonbengtsson** [comment]
Sounds good! Are you up for creating a pull request?

**Comment by betsonserviceportal** [comment]
Stupid question, but how would I use (listen for) this hook/event?  I'm having trouble setting a background image for my pages and then autoTable overtop.  It seems the sequence of events is to create the table then place the image.  I found that if I addPage, addImage and then do the autoTable it's okay.  I'd like to listen for the addPage by autoTable for the automatic page breaks.   If any of that makes sense?
