### ISSUE TITLE
Remove table/cell border

### ISSUE THREAD

**Issue by hitolonen** [simonbengtsson/jsPDF-AutoTable#180]
Hi,

how do you completely remove any table/cell borders? Currently this is our setup:

```
doc.autoTable(columns, rows, {
styles: {
cellPadding: 0,
rowHeight: 10,
fillStyle: 'S',
halign: 'center',
valign: 'middle',
fontStyle: 'bold', 
lineWidth: 0.01,
fontSize: 10,
textColor: 0,
},
margin: [68, 0, 0, 140] ,
tableWidth: width / 2 - 4,
bodyStyles: {
lineColor: [0, 0, 0, 0]
},
drawHeaderRow: function() {
return false;
},
beforePageContent: function(data) {
doc.addImage(imgData, 'JPEG', 0, 0, width, height);
}
});
```

The above seems to work with mac/ios safari and ff but mac chrome adds a thin white border. Tried also with: 
lineWidth: 0.00,
lineWidth: 0.0,
lineWidth: 0,

What we need to achieve is have a background image with the table but no table backgrounds or borders.

**Comment by simonbengtsson** [comment]
Have you tried the `plain` theme?

**Comment by hitolonen** [comment]
Yes and same thing with mac chrome showing the thin white border but mac ff and safari not showing it. Code:

```
doc.autoTable(columns, rows, {
theme: 'plain',
styles: {
cellPadding: 0,
rowHeight: 10,
fillStyle: 'S',
halign: 'center',
valign: 'middle',
fontStyle: 'bold', 
lineWidth: 0.01,
fontSize: 10,
textColor: 0,
},
margin: [68, 0, 0, 140] ,
tableWidth: width / 2 - 4,
bodyStyles: {
lineColor: [0, 0, 0, 0]
},
drawHeaderRow: function() {
return false;
},
beforePageContent: function(data) {
doc.addImage(imgData, 'JPEG', 0, 0, width, height);
}
});
```

**Comment by simonbengtsson** [comment]
Sounds strange! So you are seeing a border in the `plain` theme in the demo as well? https://simonbengtsson.github.io/jsPDF-AutoTable/#themes

I use chrome on mac and can't see it. Can you post a screenshot?

**Comment by hitolonen** [comment]
No not seeing the borders on the plain demo but granted the background is white and we have the image background.

Mac chrome, with borders:
<img width="307" alt="pdf-mac-chrome" src="https://cloud.githubusercontent.com/assets/20572314/19524547/cab08c94-9626-11e6-8297-b14b0554a986.png">

Mac ff, no borders:
<img width="336" alt="pdf-mac-ff" src="https://cloud.githubusercontent.com/assets/20572314/19524548/cab2f484-9626-11e6-8b73-c4226d1574fe.png">

**Comment by simonbengtsson** [comment]
This was a bug. Fixed it now in version `2.0.36`. If you specify the style `lineWidht: 0` no border will show. You don't need to do that with the plain style set however as that is the default.

**Comment by hitolonen** [comment]
Ah, thanks for the heads up. We were loading the script from <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.0.16/jspdf.plugin.autotable.js"></script> per read me's "It is also available on cdnjs:" but just DL'd the latest version and all good.

Closing topic.

**Comment by simonbengtsson** [comment]
Oh! My bad, updated the readme with the latest version now.
