### ISSUE TITLE
Auto Table Header and cell borders

### ISSUE THREAD

**Issue by gadamshetty** [simonbengtsson/jsPDF-AutoTable#181]
Hello, Can someone pl. help on the following.

1) Is there a way to merge two header cells into one cell but I want the data to be into two cells
2) Is there way to remove the grid lines and have only the border to outer table only.

Thanks,

**Comment by simonbengtsson** [comment]
1. I'm not sure I completely understand, but take a look at the col and rowspan example.
2. Not natively, but maybe after some work with the hooks. See #141

**Comment by gadamshetty** [comment]
I was able to do Item 1 with empty header cell
Item 2, Just draw the square with static x, y

thanks, we can close this
