### ISSUE TITLE
Styles not working with Meteor

### ISSUE THREAD

**Issue by 2JN** [simonbengtsson/jsPDF-AutoTable#183]
I have been trying to change the Default style from the client with different options, but it doesn't seems to apply any change.

**Comment by simonbengtsson** [comment]
Could you post some code? I have successfully used motor with the lib before.

**Comment by 2JN** [comment]
@simonbengtsson this is [my project](https://github.com/2JN/scv/blob/liquidacion/imports/ui/components/nombramientoPDF/nombramientoPDF.jsl), I'm using the autotable in lines 77 and 100. I'd appreciate your help

**Comment by simonbengtsson** [comment]
I tried your code and it seem to work. Which style doesn't work? You only have the `valign` set, have you tried something else? Can you post an image on what is failing?

**Comment by 2JN** [comment]
The problem is that the styles doesn't apply to end result... maybe I don't have all the dependencies required... here is the PDF generated from the above code
![screenshot from 2016-11-02 17-27-46](https://cloud.githubusercontent.com/assets/5906378/19951334/051d0c16-a123-11e6-9b4b-ddeaaa5b5cd7.png)

**Comment by simonbengtsson** [comment]
If you replace `descargarPDF` with the code below, do you get red text? What I did when it worked for me was creating a new meteor app and called that function in `main.js`.

```js
function descargarPDF() {
    var doc = new JsPDF('p', 'pt');
    
    let columnsc = [
      {title: "Dependencia", key: "dependencia"},
      {title: "Municipio", key: "municipio"},
      {title: "Departamento", key: "departamento"}
    ];

    let rowsc = [];
    rowsc.push({dependencia: 'dependencia', municipio: 'municipio', departamento: 'departamento'});
    rowsc.push({dependencia: 'dependencia', municipio: 'municipio', departamento: 'departamento'});
    rowsc.push({dependencia: 'dependencia', municipio: 'municipio', departamento: 'departamento'});
    rowsc.push({dependencia: 'dependencia', municipio: 'municipio', departamento: 'departamento'});

    doc.autoTable(columnsc, rowsc, {
      styles: {textColor: [255, 0, 0]}
    });

    doc.save('nombramiento.pdf');
  }
```

**Comment by simonbengtsson** [comment]
Found your issue! You are using version `1.3` of the library. The latest is `2.1`. Try installing the library with `npm install jspdf-autotable` instead of `meteor add`. I will look into updating the package on meteor but don't hold your breath...
