### ISSUE TITLE
autoTable.addPage() is not called correctly when table is beyond end of page in constructor

### ISSUE THREAD

**Issue by martinwaugh** [simonbengtsson/jsPDF-AutoTable#184]
To reproduce:
1. Add autoTable() with startY > pagesize - margin.bottom and supplying beforePageContent and afterPageContent.
2. beforePageContent and afterPageContent are not called when autoTable adds the new page.

I believe that the issue is the call to this.addPage() in the constructor should be to this.autoTableAddPage() instead:

```
    if (settings.pageBreak === 'always' && settings.startY !== false || settings.startY !== false && minTableBottomPos > pageSize.height) {
        this.autoTableAddPage(this.addPage);
        cursor.y = settings.margin.top;
    }
```

**Comment by simonbengtsson** [comment]
You are right! I can't really decide if this is expected behavior or not though. If I understand you correctly you basically want the hooks to fire even if the table is not drawn on the first page? Can you give some context for what you are trying to achieve?

**Comment by martinwaugh** [comment]
Yes, indeed, I ran into this in a document where I have a header and footer. I gave the minimal steps to reproduce that I could think of, but it also happens on a page with other elements on it. In my real document the first page has some text and a couple of autoTables on it. When my code goes to add the third autoTable the cursor is already very near the bottom of the page. What happens is the table appears on a new page without the header or footer. 

So, it isn't really just a "first table on the first page" issue; it seems to be anytime the table doesn't initially fit on the page given the current cursor position.

**Comment by simonbengtsson** [comment]
That sounds like a bug indeed. However I cannot reproduce it, how does your code differ from this test case? https://jsfiddle.net/someatoms/c47cL6mn/

**Comment by martinwaugh** [comment]
Change the third autoTable call to (set startY to height):

	  doc.autoTable(res.columns, res.data, {
	    startY: height,
	    afterPageContent: function(data) {
	      doc.setFontSize(20)
	      doc.text("After page content", 50, height - data.settings.margin.bottom - 20);
	    }
	  });

In this case, the third table appears on the second page, but the "After page content" does not appear on the first page.

**Comment by simonbengtsson** [comment]
Okey I think I understand the issue. You want the same header and footer but with many tables. So for example if you had 10 small tables with mixed content you would like to have the same header and footer on every page?

**Comment by martinwaugh** [comment]
Yes. Well said. The document is one coherent entity with a variety of elements in it, some of which are autoTables. As I add elements to the document, I want it to paginate as needed, with consistent headers and footers.

**Comment by simonbengtsson** [comment]
What do you think of adding a new helper function that will be called everytime autotable adds a new page independtely of which tables causes the page add? It could be used something like this 

```js
doc.autoTablePageContent(function(data) {
  doc.text("header/footer for all tables", 50, 50);
})
```

**Comment by martinwaugh** [comment]
What you suggest is quite similar to the afterPageAdd() hook that I added in the pull request that I made a couple of weeks ago. I now believe that I am filing a bug against that very change!

I believe that my mistake was to not also add a call to that hook in the autoTable constructor where it adds a page if there is not room to start the table on the current page.

So, I propose adding a call to the afterPageAdd() hook as follows:

	    if (settings.pageBreak === 'always' && settings.startY !== false || settings.startY !== false && minTableBottomPos > pageSize.height) {
	        this.addPage(this.addPage);
	        cursor.y = settings.margin.top;
		    settings.afterPageAdd(hooksData());
	    }

**Comment by simonbengtsson** [comment]
That is not needed as the internal `addPage` function calls all hooks. But the hooks for adding page content are confusing now. I propose the following changes.

Replace `afterPageContent`, `beforePageContent` and `afterPageAdd` with one hook named `addPageContent`. So no matter if you want to add a footer, header or something else you can do it with this hook. It will be called on each page the autoTable spans.

To complement the `addPageContent` hook I also propose adding a new helper function called `autoTableAddPageContent` which can be used to set a function that will be called on every page that any autoTable is present.

Let me know what you think.

**Comment by martinwaugh** [comment]
Perhaps a minor point, but my original observation here was that the call to `this.addPage(this.addPage);` in the constructor does not, in fact, call `autoTable.addPage()`, rather it calls `jsPDF.addPage()`. So, none of the hooks are called in the case that autoTable adds a page when the cursor is near the bottom margin (more accurately, when` minTableBottomPos > pageSize.height`).

But, to your point:

Yes, having one hook makes sense, particularly since "before" and "after" content don't really mean anything - the hooks can place elements anywhere on the page they'd like, not just above or below the active table. 

So, `addPageContent` would be called whenever autoTable adds a page and `autoTableAddPageContent` would be called whenever autoTable adds any content to a page?

**Comment by simonbengtsson** [comment]
True, fixed that.

> So, addPageContent would be called whenever autoTable adds a page

It would also be called on the first page (even if autoTable never adds a page)

>  and autoTableAddPageContent would be called whenever autoTable adds any content to a page?

Yes, on every page there is a autoTable table

**Comment by martinwaugh** [comment]
Sorry, I'm a little dense. Do I have this right:

`addPageContent` is called once for each page that autoTable touches, whether or not it puts a table on that page (because it wouldn't fit, presumably).

`autoTableAddPageContent` is called once for each page that autoTable actually adds content to.

**Comment by simonbengtsson** [comment]
`addPageContent` will ba called only on pages that actually has the autoTable on it. It would be used like this:

```js
doc.autotable(columns, rows, {
  addPageContent: function(data) {
    doc.text("Header", 50, 50);
  }
}
```

`autoTableSetPageContentHook` will be called once on any page that has any autoTable on it. It would be set something like this:

```js
doc.autoTableSetPageContentHook(function(data) {
  doc.text("Header 2", 100, 50);
})
```

**Comment by martinwaugh** [comment]
Ah. I get it now. Thanks. Yes, that all sounds like it will work just fine.

BTW, thanks for you work on this tool. It is very handy for what I'm doing.

**Comment by simonbengtsson** [comment]
Just released version `2.1.0` with this change now.

**Comment by martinwaugh** [comment]
I folded it into my code it works just like I want it to. Thanks!

**Comment by simonbengtsson** [comment]
Sweet!

**Comment by Mateus-D** [comment]
hello simon could you tell me how can I leave a logo fixed on the header in all pages of the pdf? I already researched everything.
