### ISSUE TITLE
Reset cursor

### ISSUE THREAD

**Issue by juliobetta** [simonbengtsson/jsPDF-AutoTable#186]
I'm using React and every time I generate a PDF, `cursor.y` is set based on the last one created.
I've managed to solve this problem creating a method that resets the variable `cursor`, so every time I call the jsPDF's `save` or `output`, I call `resetCursor`.

`src/main.js`

    jsPDF.API.resetCursor = function () {
        cursor = {};
    }

**Comment by simonbengtsson** [comment]
Everytime `doc.autoTable` is called `cursor` should be set to the following:

```js
    cursor = {
        x: settings.margin.left,
        y: settings.startY === false ? settings.margin.top : settings.startY
    };
```

That is not the case?

**Comment by juliobetta** [comment]
no... in my case, this is not enough.  Somehow, it's accumulating the previous value.

**Comment by simonbengtsson** [comment]
Can you post some code or explain how your setup is differing from a default one. I have tried react before with the library and should pose no issues.

**Comment by peters** [comment]
@simonbengtsson 

jsPDF-AutoTable version: 2.1.0
jsPDF: 1.3.2

Run this code twice and it will demonstrate the problem:

```js
var columns = [
	{ title: "A", dataKey: "A" },
	{ title: "B", dataKey: "B" },
	{ title: "C", dataKey: "C" }
];

var rows = [
	{ A: "A", B: "B", C: "C" },
	{ A: "A", B: "B", C: "C" }
];

var doc = new jsPDF('p', 'pt');
doc.setFontSize(20);
doc.setTextColor(40);
doc.setFontStyle('normal');
doc.text("YOLO", 10, 20);
doc.text("YOLO2", 10, 50);

doc.autoTable(columns, rows, {
	startY: doc.autoTableEndPosY() + 70,
	margin: { horizontal: 10 },
	styles: { overflow: 'linebreak' },
	bodyStyles: { valign: 'top' },
	columnStyles: { email: { columnWidth: 'wrap' } },
	theme: "striped"
});

doc.save('repro.pdf');
```

**Comment by simonbengtsson** [comment]
Okey got it! What do you think of adding a function like `doc.autoTableReset()`? 

Meanwhile, one solution is to call `doc.autoTable();` once without the `startY` parameter in settings.

A simpler repro:

```js
var columns = [
	{ title: "A", dataKey: "A" },
	{ title: "B", dataKey: "B" },
	{ title: "C", dataKey: "C" }
];

var rows = [
	{ A: "A", B: "B", C: "C" },
	{ A: "A", B: "B", C: "C" }
];

for(var i = 0; i < 20; i++) {
    var doc = new jsPDF('p', 'pt');
    doc.autoTable(columns, rows, {
	startY: doc.autoTableEndPosY() + 10
    });
    doc.autoTable(columns, rows, {
	startY: doc.autoTableEndPosY() + 10
    });
    doc.save('repro.pdf');
}
```

**Comment by peters** [comment]
@simonbengtsson 

> Okey got it! What do you think of adding a function like doc.autoTableReset()?

That would be nice :)

**Comment by simonbengtsson** [comment]
Found a way to automatically reset the cursor after creating a new jspdf document. Should no longer be a need for adding a `doc.autoTableReset()` or similar.

**Comment by vladpke** [comment]
I'm still having the same problem at the moment. I have version 2.3.0 installed.

**Comment by vladpke** [comment]
I'm using version 2.3.1 and I'm still having the same problem.

**Comment by simonbengtsson** [comment]
I'll take a look again.

**Comment by vladpke** [comment]
I create a new instance of jspdf, I add a few tables, I save the pdf. I then create another instance of jspdf and add another table with startT set to doc.autoTableEndPosY() + 40. doc.autoTableEndPosY() returns the endY of the last table in my first pdf instead of 0.

**Comment by vladpke** [comment]
It feels like setting `this.autoTable.previous` to false on new instance creation would fix the problem.

**Comment by simonbengtsson** [comment]
Updated this now. Fix will be available in version 3.0 released after some more testing.

**Comment by bsionixxtech** [comment]
I still see that v2.3.2 is the latest release...

**Comment by landrit** [comment]
Still got this problem in Ionic 2

**Comment by landrit** [comment]
Nevermind got it.
what i did:
doc.Autotable.previous = 0;

**Comment by shubhamyugtia** [comment]
@simonbengtsson can you please help me i want to add to table in same row with different
[https://i.stack.imgur.com/Cz9A3.png](url)
