### ISSUE TITLE
Center text in fields

### ISSUE THREAD

**Issue by erperejildo** [simonbengtsson/jsPDF-AutoTable#187]
Hi @simonbengtsson, thanks for this awesome library  ;)

I'm trying to find something in the documentation and here in "issues" related with this.
Can I center when I export the table even if I don't have that cell with any align in my table? 

Thanks!

**Comment by simonbengtsson** [comment]
I interpret your question as "Can I center text in the pdf table despite it not being centered in the html table?". If so, yes. In fact, the library do not care about the alignment of text in the html table. You have to use the "halign" style.

**Comment by erperejildo** [comment]
Sorry for the delay and thanks for your support @simonbengtsson !
