### ISSUE TITLE
custom font faces

### ISSUE THREAD

**Issue by gadamshetty** [simonbengtsson/jsPDF-AutoTable#189]
custom fonts are not working for me, I tried the following

var doc = new jsPDF('p', 'pt');
doc.setFont("roboto"); --> name of the font face from my css file i defined for google roboto font
doc.autoTable(columns, data);

The pdf still generates with default fonts.  Appreciate your thoughts,

**Comment by simonbengtsson** [comment]
Cross posting http://stackoverflow.com/q/40478179/827047
