### ISSUE TITLE
Striped and grid theme

### ISSUE THREAD

**Issue by sirius210** [simonbengtsson/jsPDF-AutoTable#191]
Hi,

Before the version 2.1.0, I used the theme "DF" so that I could have a table striped with a grid. I used to do like this : 

`
styles : {
            overflow: 'linebreak',
            fontSize: fontSize ,
            fillStyle: 'DF',
        },
`
This method doesn't work anymore. 
But now, with the themes, I just see "striped", "grid" or "plain". Has this theme desappear ? If no, how can I use it again easily ? I don't see anything in the readme ... 

Thanks.

**Comment by sirius210** [comment]
I just have to ask the question to find the answer ... I just need to add in style  : 

`lineWidth: 0.1,`

And it give me a grid table.

**Comment by simonbengtsson** [comment]
Yep `fillStyle` was removed in version 2.1 as it was quite confusing and could be set automatically from `lineWidth` and `fillColor`.
