### ISSUE TITLE
Add Master Page

### ISSUE THREAD

**Issue by acss1881** [simonbengtsson/jsPDF-AutoTable#193]

**Comment by simonbengtsson** [comment]
?

**Comment by acss1881** [comment]
I'm apologize Was modifying the code and wrote directly the unfinished github. And I forgot to delete it.

disculpa. estaba modificando el codigo y escribi directo el github sin terminar. y se me paso borrarlo.

**Comment by simonbengtsson** [comment]
Fair enough!
