### ISSUE TITLE
How to add a title before table

### ISSUE THREAD

**Issue by kamov** [simonbengtsson/jsPDF-AutoTable#194]
I would like to add a title before generated PDF table.
Thanks

**Comment by simonbengtsson** [comment]
Have you checked the content example?

**Comment by kamov** [comment]
Do you mean beforePageContent?
beforePageContent: function(data) {
        doc.text("Header", 40, 30);
    }

**Comment by simonbengtsson** [comment]
Its renamed to addPageContent but yes try that!

**Comment by kamov** [comment]
Work fine beforePageContent, but not addPageContent.
