### ISSUE TITLE
 PDF all  tables in a page

### ISSUE THREAD

**Issue by rezvaneh** [simonbengtsson/jsPDF-AutoTable#196]
I want to PDF multiple tables، **but it's not clear how many tables can be there**. It can be more than 100 tables.
I thinke  the plugin only supports specific number of tables manually. How can I pdf all tables in my html page? I need some thing like ring to set value for every table with a class name

**Comment by simonbengtsson** [comment]
You can call autoTableToJson() multiple times with different table elements so should work.

**Comment by rezvaneh** [comment]
Can you show me an example code?
I want something like this , that not work

```
        var pdf = new jsPDF('l', 'pt', 'a0');
        var res = pdf.autoTableHtmlToJson(document.getElementsByClassName("tbls"));
        pdf.autoTable(res.columns, res.data, {
            theme: 'plain',
            startY: 60,
            styles: {
            },
            columnStyles: {
                1: {columnWidth: 'auto'}
            }
        });
        pdf.save('a.pdf');
```

because of generating  automaticlly of tables,   Number is not clear

**Comment by simonbengtsson** [comment]
getElementsByClassName returns a array with table elements. You would have to loop over it and call autotablehtmltojson and autotable for each element.

**Comment by rezvaneh** [comment]
Thank you @simonbengtsson . It works, but I didn't know can't support UTF-8
It's unbelievable.

**Comment by simonbengtsson** [comment]
Yeah that really is unfortunate.
