### ISSUE TITLE
How to get total number of pages in a pdf file when using autoTableHtmlToJson.

### ISSUE THREAD

**Issue by creedrahul** [simonbengtsson/jsPDF-AutoTable#199]
Hello,
         I am trying to get total count of pages in a pdf file is it possible? The addition of new page happen dynamically while printing table from html. If there is anyway to get the total count of pages it will be really helpful for adding watermark or any desired image.

**Comment by simonbengtsson** [comment]
Take a look at the putTotalPages function in jspdf.

**Comment by creedrahul** [comment]
Thanks SIMON. Your suggestion was really helpful.  Also your answer to [#issues45](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/45) was exactly what i was looking for. thanks a lot buddy
