### ISSUE TITLE
HyperLink support

### ISSUE THREAD

**Issue by khalilTN** [simonbengtsson/jsPDF-AutoTable#200]
Hi,
Is there a way to create hyperlink cells using auto-table ?
Thanks

**Comment by simonbengtsson** [comment]
Check this [question](http://stackoverflow.com/questions/25501024/how-to-create-hyperlink-in-pdf-using-jspdf-js-library) on stackoverflow on how to do it in jspdf. Then combined that with the hooks to add hyperlinks to cells.
