### ISSUE TITLE
text overflow 

### ISSUE THREAD

**Issue by andresgarciac** [simonbengtsson/jsPDF-AutoTable#202]
We are using autotable to generate a pdf, but our texts all over the table gets cut when they are too long. We are using `overflow: 'linebreak'` and it works fine. It is just that the words get cut as you can see in this image:

![2016-12-05](https://cloud.githubusercontent.com/assets/8355877/20890879/9772d79a-bad6-11e6-8bc5-9291164be45c.png)

**Comment by simonbengtsson** [comment]
That looks strange. Could you post the code you are using? And preferably also some example data that I can use to recreate the problem.

**Comment by andresgarciac** [comment]
//this is the object that we're using
gridForIE = [
  {
     "columns":[
        {
           "title":"Nombre\bdel\bvalor",
           "dataKey":"CATEGORY"
        },
        {
           "title":"Moneda",
           "dataKey":"CURRENCY"
        },
        {
           "title":"Cantidad",
           "dataKey":"AMOUNT"
        },
        {
           "title":"Costo\bUnitario",
           "dataKey":"COST_PRICE"
        },
        {
           "title":"Costo\btotal",
           "dataKey":"COST_VALUE"
        },
        {
           "title":"Precio\bde\bmercado",
           "dataKey":"MARKET_PRICE"
        },
        {
           "title":"Ganancia/Pérdida\bno\brealizadas",
           "dataKey":"GAIN_LOSS"
        },
        {
           "title":"Valor\bde\bmercado",
           "dataKey":"MARKET_VALUE"
        },
        {
           "title":"%\bPortafolio",
           "dataKey":"PERCENTAGE"
        }
     ],
     "rows":[
        {
           "CATEGORY":"Nombre\bdel\bValor\b1",
           "CURRENCY":"USD",
           "_MARKET_VALUE":"10.00",
           "_PERCENTAGE":"0.1",
           "AMOUNT":"N/A",
           "COST_PRICE":"10.00",
           "COST_VALUE":"10.00",
           "MARKET_PRICE":"10.00",
           "GAIN_LOSS":"10.00",
           "MARKET_VALUE":"10.00",
           "PERCENTAGE":"0.1",
           "$$hashKey":"uiGrid-008G"
        },
        {
           "CATEGORY":"Nombre\bdel\bValor\b2",
           "CURRENCY":"USD",
           "_MARKET_VALUE":"20.00",
           "_PERCENTAGE":"0.2",
           "AMOUNT":"N/A",
           "COST_PRICE":"20.00",
           "COST_VALUE":"20.00",
           "MARKET_PRICE":"20.00",
           "GAIN_LOSS":"20.00",
           "MARKET_VALUE":"20.00",
           "PERCENTAGE":"0.2",
           "$$hashKey":"uiGrid-008I"
        }
     ]
  }
];

//and this is the code that we're using

var doc = new jsPDF();
doc = new jsPDF('p','pt');

doc.autoTable(gridForIE[0].columns, gridForIE[0].rows,{
      margin: {top: 80},
      startY: doc.autoTableEndPosY() + startY(i),
      tableWidth: 'wrap',
      styles: {

        cellPadding: 4,
        fontSize: 8,
        valign: 'middle',
        halign: 'right',
        overflow:'linebreak',
        //tableWidth: 'wrap',
        //fileColor: [30, 30, 30],
        lineWidth: 0,
        rowHeight: 15,
        //columnWidth: 'auto'
      },
      headerStyles: {
        //overflow:'linebreak',
        //columnWidth: 'auto',
        lineWidth: 0,
        halign: 'center',
        fillColor: [24, 53, 95],
        fontSize: 8,
        rowHeight: 25
      },
      bodyStyles:{
        textColor: [30, 30, 30]
      },
      createdCell: function (cell, data) {
          doc.setFillColor(30, 30, 30);
        console.log(cell);
          console.log(data);

          if (data.column.dataKey === 'CATEGORY') {
             cell.styles.halign = 'center';

           }
           if(data.row.raw.isFooter === "true"){
             cell.styles.fillColor = [128, 130, 132];
             cell.styles.fontStyle = 'bold';
           }

      }
});

doc.save('export.pdf');

//this is the result table.

![2016-12-05 1](https://cloud.githubusercontent.com/assets/8355877/20892921/f61bfd4c-badd-11e6-9242-530b2ea4dffb.png)

**Comment by simonbengtsson** [comment]
Is there a reason that you are using `Costo\bUnitario` instead of `Costo Unitario`? That seems to make jspdf think of it as one big word instead of two and therefore simple force split it in the end.

**Comment by andresgarciac** [comment]
yes, but if we use the write space instead \b in text, the write spaces are showing too long in the table, like this.

![2016-12-05 2](https://cloud.githubusercontent.com/assets/8355877/20894169/62a426d4-bae2-11e6-9543-cd4670b73e14.png)

**Comment by simonbengtsson** [comment]
This might be the real issue. Tried your code, but got this result. If you are running the following fiddle, do your spaces look normal?

https://jsfiddle.net/someatoms/26xm86ku/

Here is a screenshot of my result:

![screen shot 2016-12-05 at 18 32 25](https://cloud.githubusercontent.com/assets/3586691/20895342/5f994e42-bb19-11e6-9781-97c0647e44fb.png)

**Comment by andresgarciac** [comment]
the problem was a jspdf dependency repeated that generate the problem, just removing one the problem is solved.
thanks for your help @simonbengtsson
