### ISSUE TITLE
Hidden Table Columns Causing Col Width Issue

### ISSUE THREAD

**Issue by carlhussey** [simonbengtsson/jsPDF-AutoTable#203]
I have a table with 10 visible columns on it and all the data looks just fine. However, I have 4 columns that are hidden that show up on the PDF fine but it doesn't look like their taken into account when determining the width for the overall columns.

In this screenshot, the **Department Desc** is the last visible column. The remaining ones are all hidden and are not spaced out. 

There is plenty of room in the overall table for those other columns to be included with plenty of room.

![screen shot 2016-12-07 at 5 03 55 pm](https://cloud.githubusercontent.com/assets/6022490/20992119/64caa514-bc9f-11e6-8dae-2fbdec4e3f54.png)

    $('#' + tableID).tableExport({
                fileName: 'EMP Export ('+rowCount+' Results)',
                type: 'pdf',
                jspdf: {
                    orientation: 'l',
                    format: 'bestfit',
                    margins: {
                        left: 5,
                        right: 5,
                        top: 5,
                        bottom: 5
                    },
                    autotable: {
                        styles: {
                            fillColor: 'inherit',
                            textColor: 'inherit',
                            columnWidth: 'auto',
                            overflow: 'ellipsize'
                        },
                        alternateRowStyles: {
                          fillColor: 245
                        },
                        tableWidth: 'auto'
                    }
                }
            });

**Comment by simonbengtsson** [comment]
Could you either post this issue in the tableExport library or recreate the example with only jspdf-autotable?

**Comment by simonbengtsson** [comment]
Closing since no response.
