### ISSUE TITLE
Center a text in a cell with cell.styles.halign

### ISSUE THREAD

**Issue by DGCG** [simonbengtsson/jsPDF-AutoTable#204]
Please,

Im trying to center a text in a cell with this code:

    res = doc.autoTableHtmlToJson(table, {
            left:80,
            right:10,
            top:500,
            bottom: 50,
            width: 60,
            autoSize:false,
            printHeaders:false
        }); 
            
        doc.autoTable(res.columns, res.data, {                
            startY: doc.autoTableEndPosY() + 30,
            pageBreak: 'auto',
            overflow: 'linebreak',            
            drawCell: function (cell, data) {
                if (data.column.index == 1) {                    
                    cell.styles.halign = 'center';
                }            
                if (data.row.index == data.table.rows.length - 1) {
                    doc.setFontStyle('bold');                    
                }
            }            
        });

But cant get the text centered, i try to use renderCell function as inone example but seems it isnt avalaible actually.

Thanks!

**Comment by DGCG** [comment]
I made some search and get the text centered for the second column with this code

drawCell: function (cell, data) {
            
      if (data.column.index === 1) {      
          pdf.autoTableText(cell.text, cell.x + cell.width/2, cell.y + cell.height/2, {
            halign: 'center',
            valign: 'middle'
        });        
      } else {
      		pdf.autoTableText(cell.text, cell.textPos.x, cell.y + cell.height/2, {
            halign: 'left',
            valign: 'middle'
        });      
      }      
      return false;
    }, 


It works nice but the trouble is that the fillColor of the cell is lost, even if I use 

pdf.setFillColor(100,100,100);

inside drawCell the result remains the same, I think this is a bug using pdf.autoTableText  is incompatible with asign fillColor to the cell, am I wrong? My fiddle:

https://jsfiddle.net/dgcg/nugqrpwn/

Thanks for your library!

**Comment by simonbengtsson** [comment]
Have you checked the `textAlign` style?

**Comment by DGCG** [comment]
Thanks for your response,
No I haven't checked it how should I use it? I just need one column be centered.

**Comment by simonbengtsson** [comment]
Use columnStyles to only centre on column. Feel free to create a question on stackoverflow with the tag `jspdf-autotable` if you need exact help how to do this.
