### ISSUE TITLE
Error when including jspdf.plugin.autotable.js

### ISSUE THREAD

**Issue by davideCremona** [simonbengtsson/jsPDF-AutoTable#206]
Hi, I am getting this error:

TypeError: undefined is not a valid argument for 'in' (evaluating '"default"in t')
in:
jspdf.plugin.autotable.js:217
jspdf.plugin.autotable.js:11:157
jspdf.plugin.autotable.js:12

And for this error there are also errors when I define "doc" as "new jsPDF('p', 'pt');"

How can I fix this? Thanks.

**Comment by simonbengtsson** [comment]
Can you show the code you are using? Both html and javascript. Have you tried running the examples in the github repo?

**Comment by simonbengtsson** [comment]
Closing since no response.
