### ISSUE TITLE
Support for rowspan and colspan

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#211]
There is an example of how to make rowspans and colspans with the hooks in `examples/examples.js`. But it is quite cumbersome so it would be nice to have native support.

**Comment by simonbengtsson** [comment]
Rowspans and colspans are now natively supported on master. Will land in the next release.

**Comment by prabusendhil** [comment]
Is rowspan and colspan supports in current release?

**Comment by simonbengtsson** [comment]
The rowspan and colspan feature will land in version 3.0.

**Comment by briandunz** [comment]
@simonbengtsson Hi Simon - our team is eagerly awaiting an update to this functionality.  Any idea of when you might be releasing 3.0?

**Comment by Gavrielo** [comment]
Same here. Any news on the update? :)
