### ISSUE TITLE
Adding New table with header on each page jsPDF

### ISSUE THREAD

**Issue by poohsasne** [simonbengtsson/jsPDF-AutoTable#215]
Hi,
   For generating multiple tables i've set styles:{pagebreak:'auto'} which will add a new page only when the next row doesn't fit, But in myCase it is shifting to another page but header remains on previous page, i want header (doc.text) to be shifted along with table content(doc.autoTable()).
   Can anyone suggest me for the same

**Comment by simonbengtsson** [comment]
You can use the `addPageContent` hook for this. Check the `header-footer` example in `examples/examples.js`.
