### ISSUE TITLE
Could not draw underline under a cell text

### ISSUE THREAD

**Issue by amycuicui** [simonbengtsson/jsPDF-AutoTable#219]
I tried to draw an underline under a cell text, but have not found any style to draw it. And where could i find the styles that cell.styles could support pls?

**Comment by simonbengtsson** [comment]
Unfortunately jspdf does not support underline texts. You might hack something yourselves using the hooks and `doc.line` however. The styles supported are the ones listed in the readme/documentation under the styles header.

**Comment by amycuicui** [comment]
OK, thanks a lot for the reply.
