### ISSUE TITLE
Support row borders

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#222]
Currently the plugin only supports cell borders. It would be cool to also support horizontal borders only for example. The should probably be done by parsing the lineWidth style the same as margin and padding.

**Comment by simonbengtsson** [comment]
Decided not to include this, but can be done fairly easy at the addedRow or addedCell events.

**Comment by spa9999** [comment]
Hi @simonbengtsson ,
Can you please provide an example for this setting the row borders (Not the entire cell).

Thank you

**Comment by spa9999** [comment]
Hu @simonbengtsson ,

I need to add row borders along with stripped row background colors.. like the following..

![image](https://user-images.githubusercontent.com/14339940/76686651-5e31c600-65f3-11ea-9c3b-12c75e1a158d.png)

but, when i try to do both, row color is on top of the row border. Not sure how to fix this..

![image](https://user-images.githubusercontent.com/14339940/76686718-df895880-65f3-11ea-991a-5674d2c1436a.png)

Can you please help with an example.

Thank you
