### ISSUE TITLE
Rowspan and colspan

### ISSUE THREAD

**Issue by charith93** [simonbengtsson/jsPDF-AutoTable#224]
rowspan and colspan set to a cell (as given in example.js) is not working.

**Comment by simonbengtsson** [comment]
Oops, my bad. I got too excited and updated the examples with v3 features. Reverted it now until a release is made. Should be today or sometime this week.

**Comment by anandan4271067** [comment]
rowspan and colspan not fount in min.js file (for the client)

**Comment by simonbengtsson** [comment]
Not sure how you mean? The plugin does not natively support colspans and rowspans in 2.x which is the current version, but there is a work around described in the examples.

**Comment by anandan4271067** [comment]
my data coming as

id    day       time
1      first      12.00
                     14.00
2     secnd    12.00

i need to set the first one be of rowspan of 2 ....how can it be done ???

i am checking for the "id" column name ...and setting there be rowspan of 2 but its not working....

**Comment by simonbengtsson** [comment]
There is no such feature currently. Where did you read that?

**Comment by anandanguru** [comment]
In your example, you have set rowspan and colspan. Can you let me know who your data is and how you have manipulated it as per your pdf in this link

https://simonbengtsson.github.io/jsPDF-AutoTable/#spans

**Comment by simonbengtsson** [comment]
Not anymore, see comment above.
