### ISSUE TITLE
Issue with rowspan on pdf creation

### ISSUE THREAD

**Issue by CJX3M** [simonbengtsson/jsPDF-AutoTable#226]
Sorry to bother you once again, but I'm lost on what my problem is with this one

Hope you can give me a hint on the issue

Thanks!

http://stackoverflow.com/questions/41728107/issue-with-rowspan-on-pdf-creation

**Comment by tomkidumbuyo** [comment]
i have the same issue. how do i do colspan??.

**Comment by simonbengtsson** [comment]
For now I will just point to the rowspan and colspan example in `examples/examples.js`. Version 3 is only a few days away and will include native support for colspan and rowspan among other useful features.

**Comment by simonbengtsson** [comment]
Will take a look at the stackoverflow question asap.
