### ISSUE TITLE
Displaying a header only on the first page

### ISSUE THREAD

**Issue by cguirguis** [simonbengtsson/jsPDF-AutoTable#230]
I have a table spanning many pages, but want to display a header on the first page, before the table starts. This would need to push the table down about 200-300 pixels, but only on the first page (I don't want to waste that margin on the other pages). Does the library currently support this scenario?

**Comment by simonbengtsson** [comment]
Yes! Write the header with the normal jspdf API and use the starty option to push the table down.

**Comment by cguirguis** [comment]
Great!! Thank you.
