### ISSUE TITLE
pagebreak in table row

### ISSUE THREAD

**Issue by RiyasIbnAbdulRahim** [simonbengtsson/jsPDF-AutoTable#231]
i am setting  'overflow-linebreak' to table ,when cell content is a larger text ,and it comes to end of a page the corresponding row is split to two page ,partially on bottom-page and another part on new page,
i want to auto set the row to new page..any solution pls..
and sory for bad english

**Comment by simonbengtsson** [comment]
You basically want to avoid splitting the cell to multiple pages? And instead simply move the entire row to a new page?

**Comment by RiyasIbnAbdulRahim** [comment]
yes absolutly....
and BIG TANkS for ur reply......
waiting for ur solution

**Comment by simonbengtsson** [comment]
Will add an option for this in version 3.0 which will most likely be released today. Stay tuned!

**Comment by RiyasIbnAbdulRahim** [comment]
pls make as soon as posible...i am still waiting....

**Comment by simonbengtsson** [comment]
Can't give you any guarantees, but should be released soon. Shouldnt be too hard to modify the code yourself if you need it right now.

**Comment by simonbengtsson** [comment]
Added a `avoidRowSplit` in master now. Will be released with version 3.0.
