### ISSUE TITLE
Is autoTable usage in addPageContent supported?

### ISSUE THREAD

**Issue by kleinph** [simonbengtsson/jsPDF-AutoTable#232]
The headers for my documents are created with autoTable (because of easier centering).
I also have some real data tables in my document.

So when I want to use the addPageContent callback to draw a header if a table spans over several pages the header is  not drawn and the table is missing some columns.

So is there any support for this?

**Comment by simonbengtsson** [comment]
Sounds like a bug. Could you show me your code?

**Comment by kleinph** [comment]
I made a JSFillde for you: https://jsfiddle.net/20kjL7Lp/2/
The header  and the last 3 columns are missing on the second page.

**Comment by simonbengtsson** [comment]
That is an innovative use of the library. Will make sure that works for version 3. For now you can use the `autoTableText` function:

```js
  doc.autoTable(res.columns, res.data, {
    //startY: height,
    addPageContent: function(data) {
        doc.setFontSize(12);
        let pageWidth = doc.internal.pageSize.width;
        doc.autoTableText("Client", 40, 20, {});
        doc.autoTableText("Title", pageWidth / 2, 20, {halign: 'center'});
        var pc = doc.internal.getNumberOfPages() + ' / ' + 'pc';
        doc.autoTableText(pc, pageWidth - 40, 20, {halign: 'right'});
    }
  });
```

**Comment by kleinph** [comment]
Thanks a lot! This works!
BTW: the `autoTableText()'` method seems to be more suitable for my usecase anyway.

**Comment by simonbengtsson** [comment]
Fixed support for calling autoTable in hooks now in master. The fix will be available in version 3.
