### ISSUE TITLE
RowSpan and Colspan

### ISSUE THREAD

**Issue by prabusendhil** [simonbengtsson/jsPDF-AutoTable#234]
![rowspan and colspan changes](https://cloud.githubusercontent.com/assets/24741576/22780450/d03b14e2-eee4-11e6-9ad5-54e9fcf57436.png)
I saw your example,that have changes for rowspan and colspan. In current version rowspan and colspan is available or not ?

**Comment by prabusendhil** [comment]
When v3 will land. Because I need that rowSpan and colSpan feature urgently Simon.

**Comment by simonbengtsson** [comment]
Check `examples-legacy.js` for how to do rowspans and colspans for now. Thought I would have had time to publish v3 by now, but got some other stuff to take care of first.

**Comment by prabusendhil** [comment]
Example lagacy have rowspan and colspan for whole row and whole columns.
But i need to do row span for 2 cells in two rows.

The same scenario for colspan also bro.
Ex:- It can be done via when i wi set rowspan =2 .does this done by any examples in lagacy .please guide me bro.

**Comment by simonbengtsson** [comment]
v3 means v3.0 so not released yet. To make rowspan=2 you can set the width to the two cells manually.

**Comment by prabusendhil** [comment]
K simon i will try let you know

**Comment by CJX3M** [comment]
Check mi fiddle on how to do rowspan correctly

https://jsfiddle.net/CJLopez/qhc1kdyd/

i'm using version 2.3.0

**Comment by prabusendhil** [comment]
Thanks for sharing this example Simon. I will try. let you know, If i have any query  Simon.

**Comment by prabusendhil** [comment]
Previously i am using 2.1.0 version. Now i want to upgrade jspdf auto table version 2.3.0.
i done this with npm install. But while doing bower install it updates latest 2.3.1. it changes cell.raw type to html format.
![screenshot from 2017-02-18 17-48-42](https://cloud.githubusercontent.com/assets/24741576/23093200/9838b278-f602-11e6-9328-f30dda18ef74.png)

**Comment by simonbengtsson** [comment]
You can get the text from the HTML element like this: cell.raw.textContent

**Comment by prabusendhil** [comment]
Thanks Simons.
While  implementing RowSpan it through error like this.

The code below : 
Object.vals = function(o) {
  return Object.values ? Object.values(o) : Object.keys(o).map(function(k) {
    return o[k];
  });
}

I tool this code from your jsfiddle example.
**Error: Object.vals is not a function**
GetTableJSON@http://localhost:9000/theme/js/tableExport.js:622:30
.tableExport@http://localhost:9000/theme/js/tableExport.js:507:27
leaveReportlistController/$scope.exportPDF@http://localhost:9000/app/report/reportlist/leavereportlist.controller.js:347:13
Parser.prototype.functionCall/<@http://localhost:9000/bower_components/angular/angular.js:10943:15
ngEventHandler/</callback@http://localhost:9000/bower_components/angular/angular.js:19274:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:9000/bower_components/angular/angular.js:12851:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:9000/bower_components/angular/angular.js:12949:18
ngEventHandler/<@http://localhost:9000/bower_components/angular/angular.js:19279:17
jQuery.event.dispatch@http://localhost:9000/bower_components/jquery/dist/jquery.js:4669:15
jQuery.event.add/elemData.handle@http://localhost:9000/bower_components/jquery/dist/jquery.js:4338:6

**Comment by simonbengtsson** [comment]
The error you posted happened in tableExport.js.

**Comment by simonbengtsson** [comment]
Probably not an issue with this plugin. But rather tableExport.js. Let me know if something else comes up.

**Comment by Riyas020691** [comment]
![untitled](https://user-images.githubusercontent.com/7333889/31625965-a13532c2-b2c5-11e7-8f8d-1c03bb683562.png) I try to create pdf using from this html table... but colspan not support. I am using jspdf auto table

**Comment by simonbengtsson** [comment]
Colspan and rowspans are not natively supported in v2 but are coming in v3. There is no planned date for the v3 release right now however.

**Comment by ranapartap** [comment]
@simonbengtsson Thank you for your efforts. Colspan like above example is needed badly. please plan to release v3 sooner.

**Comment by skmohsinmahemud** [comment]
i have facing lots of problem while creating invoice design using jspdf autotable kindly provide sample for invoice design
