### ISSUE TITLE
Table Header of doc.autoTable prints not correct characters

### ISSUE THREAD

**Issue by crascher** [simonbengtsson/jsPDF-AutoTable#235]
Hi, 

do you have an idea why the header of doc.autoTable is not printed with correct character set?  Its normally working fine but I have this special support case where it looks like on the following image.  Source code regarding table creation is also attached.

![yimg-88926612-9002-1840048902](https://cloud.githubusercontent.com/assets/6103950/22854987/ad00bbfe-f078-11e6-9273-8dacf5d09fe8.jpg)

```
var positionColumns = [
                {title: "Menge", dataKey: "quantity"},
                {title: "Bezeichnung", dataKey: "title"},
                {title: "Preis", dataKey: "price"},
                {title: "Summe", dataKey: "total"},
                {title: "Steuersatz", dataKey: "tax"}
            ];

 doc.autoTable(positionColumns.slice(0, 2), [], {
                // Styling
                theme: 'grid', // 'striped', 'grid' or 'plain'
                styles: {
                    font: "helvetica", // helvetica, times, courier
                    overflow: 'linebreak'
                },
                headerStyles: {
                    fillColor: [255, 255, 255],
                    textColor: [40, 40, 40]
                },
                bodyStyles: {},
                alternateRowStyles: {},
                columnStyles: {
                    quantity: {columnWidth: 70},
                    title: {columnWidth: 220}
                },

                // Properties
                startY: 330, // false (indicates margin top value) or a number
                pageBreak: 'auto', // 'auto', 'avoid' or 'always'
                tableWidth: 'auto' // 'auto', 'wrap' or a number
            });
```

Thanks for a hint.
Regards,
Mike

**Comment by simonbengtsson** [comment]
Have not seen anything like that before. Does it look the same without any of the specified options? Does it look okey if you open it in a pdf reader?

**Comment by crascher** [comment]
Thanks for the fast reply, I will try some other configurations within next days and check when I meet the guy with the problem if the pdf is okay or has the same issue.

**Comment by crascher** [comment]
I cannot reproduce this behaviour, is gone after a printer and computer restart. Anyway thanks for your help.
