### ISSUE TITLE
Problem with rowspan and page jump

### ISSUE THREAD

**Issue by CJX3M** [simonbengtsson/jsPDF-AutoTable#236]
Sorry to bother you, but I have a new issue creating pdf, that has cells with a rowspan and are so far down that are set in a page jump

Here'e the Stackoverflow link to the question

http://stackoverflow.com/questions/42255871/rowspan-and-page-jump-issue

Thanks!

**Comment by simonbengtsson** [comment]
Will answer questions on stackoverflow when I got time.

**Comment by CJX3M** [comment]
Sure, no problem, I have a workaround for this issue, but still would love to get your feedback, specailly it is improves the plugin functionality on the next version

Thanks for the support

**Comment by CJX3M** [comment]
Hi there

Sorry to bother you, but, I started to work on a workaround for this issue, and have something that might work in the mean time, but I noticed some odd behavior and I would like to get your feedback.

I updated the question with this info, if you can take a look at it and give some point on how to continue, I would most appreciate!

Thanks

**Comment by CJX3M** [comment]
Sorry to bother you, but had you had any chance to look at my issue?
