### ISSUE TITLE
different startY for pages mayor than 1

### ISSUE THREAD

**Issue by prometeomcclellan** [simonbengtsson/jsPDF-AutoTable#238]
is there a way to make the startY margin of tables different than the startY in the first page ? this is to align tables not at the top of the page itself

**Comment by prometeomcclellan** [comment]
yes ! let me show how I am setting it ...

    doc.autoTable(res.columns, res.data, {
		            theme: 'striped',
		            addPageContent: pageContent,
		            startY: doc.autoTable.previous.finalY + 15,
		            pageBreak: 'avoid',
		            margin: {top: 1}
	      }); 

 this makes the first page to go perfect but in the second page I get the tables at the very top and what I need is them to respect my header that was added in the pageContent

**Comment by simonbengtsson** [comment]
Try a larger margin value such as 100

**Comment by prometeomcclellan** [comment]
ok, I´ll give it a hit and show back the results. thank you

**Comment by prometeomcclellan** [comment]
I did change the margin top to 130 for example, it fixes the second page and it goes perfect but the first page margin top moves as well and leaves a blank space ... is there any way to move the first page tables to the previous position without losing this new change ? I mean, something like if the startY value can be fixed to the original position  ? do I have to change the startY value from doc.autoTable.previous.finalY + 15 to another value that fixes the blank space ?

**Comment by simonbengtsson** [comment]
Not sure that I understand what you mean?

**Comment by prometeomcclellan** [comment]
left is before the change, right is after it...

![first](https://cloud.githubusercontent.com/assets/17907602/23472321/0dbf3b30-fe72-11e6-9c42-5af8736a9112.jpg)

![second](https://cloud.githubusercontent.com/assets/17907602/23472359/2acd07e8-fe72-11e6-9d5d-f9b0c35737d5.jpg)

**Comment by prometeomcclellan** [comment]
here is a detail, I think in the example that you have for the header and footer with table, you are getting you data from one single table, is that correct ? because I am not, I get it from any number of tables, I mean they are many and is all surrounded by a for loop that reads every table

**Comment by simonbengtsson** [comment]
Seems like you have had another table before that ended in the middle of the page? Try removing the doc.autoTable.previous and only use 15.

**Comment by prometeomcclellan** [comment]
ok

**Comment by prometeomcclellan** [comment]
alright, when I remove the doc.autoTable.previous what happens is that the only table that is rendering is the last one of all the tables array ... seems that this is a total new case between issues

**Comment by prometeomcclellan** [comment]
alright, here the code ... the tables are many that we pull from an erp ... so this is the way we do it, as I said not a single table source but many

HTML table code is

    <div id="printdiv" class="test-div" style="margin-top: -40px;margin-left: 1%;">
        <table id="employeeTable" class="table table-bordered table-condensed table-agents" style="">			    
			    <tbody>
			    	<tr>
			        <td id="employeeNumberLabel">Número de Empleado : </td>
			        <td name="employeeNumber" id="employeeNumber">$CODE</td>
			        <td id="employeeHeightLabel">Estatura: </td>
			        <td name="employeeHeight" id="employeeHeight">$HEGHT</td>
			        <td id=""><img id="fotoGuardiaAgents" src="$GUARD" class="image-photo">Fotografía</td>
			      </tr>
			      <tr>
			        <td id="employeeNamesLabel">Nombres y Apellidos : </td>
			        <td name="employeeName" id="employeeName">$NAME</td>
			        <td id="employeeWeigthLabel">Peso (Lbs): </td>
			        <td name="employeeWeigth" id="employeeWeigth">$WEIGTH</td>
			        <td id="employeePhotoLabel" style="color: white;">fotografía</td>
			      </tr>
			      <tr>
			        <td id="employeeChargeLabel">Cargo : </td>
			        <td name="employeeCharge" id="employeeCharge">$CHARGES</td>
			        <td id="employeeEyesLabel">Color de Ojos : </td>
			        <td name="employeeEyes" id="employeeEyes">$EYES</td>
			        <td id="employeePhotoLabel" style="color: white;">fotografía</td>
			      </tr>
			      <tr>
			        <td id="employeeIdLabel">Número de Cédula : </td>
			        <td name="employeeId" id="employeeId">$IDN</td>
			        <td id="employeeSkinLabel">Color de Piel : </td>
			        <td name="employeeSkin" id="employeeSkin">$SKIN</td>
			        <td id="employeePhotoLabel" style="color: white;">fotografía</td>
			      </tr>
			      <tr>
			        <td id="employeeInssLabel">Número de INSSX : </td>
			        <td name="employeeInss" id="employeeInss">$SOCIALSECX</td>
			        <td id="employeeIDateLabel">Fecha de Ingreso : </td>
			        <td name="employeeIDate" id="employeeIDate">$STARTDATEX</td>
			        <td id="employeePhotoLabel" style="color: white;">fotografía</td>
			      </tr>
			    </tbody>
			  </table>
			</div>

and here is the javascript code ...

    var tablesToPrint = document.body.getElementsByTagName('table');
			var countTables = tablesToPrint.length;
			var guardPhotos = document.body.getElementsByClassName('image-photo');
			var countPhotos = guardPhotos.length;
	        var imageElem = document.getElementById('headerLogo');
		    var url = imageElem.src;
		    var photoElem = document.getElementById('fotoGuardiaAgents');
		    var photoUrl = photoElem.src;
		    var todayDate = Date.today().toString("dd-MM-yy");
		  	var dt = new Date();
		  	var time = dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();
		  	var base64Img = null;
		    function getBase64Image(img) {
			    var canvas = document.createElement("canvas");
				    canvas.width = img.width;
				    canvas.height = img.height;
				    var ctx = canvas.getContext("2d");
				    ctx.drawImage(img, 0, 0);
				    var dataURL = canvas.toDataURL("image/jpeg");
				    return dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
				}
				var img = new Image(); var imgPhoto = new Image();
				img.onload = function(){
				    var dataURI = getBase64Image(img);
				    return dataURI;
				}
				imgPhoto.onload = function(){
				    var dataURI = getBase64Image(imgPhoto);
				    return dataURI;
				}
			img.src = url;
			function generate() {
				var doc = new jsPDF('p', 'pt');
				for (var indexTables = 0; indexTables < countTables; indexTables++) {
					for (var indexPrints = 0; indexPrints <= indexTables; indexPrints++) {
						if (indexPrints == indexTables) {
							var tableToPrint = tablesToPrint[indexPrints];
								tableToPrint.style.zIndex = '1';
								tableToPrint.id = 'tabla_'+indexPrints;
							var tableId = tableToPrint.id;
							var res = doc.autoTableHtmlToJson(document.getElementById(tableId));
						  	doc.setPage(1 + doc.internal.getCurrentPageInfo().pageNumber - doc.autoTable.previous.pageCount);
						  	for (var j = 0; j < 1; j++) {

						  		if (countTables <= 4) {
									var nextPagesQuant = 1;
								}
								else{
									var notRoundedCount = (countTables/4);
									var absoluteCount = Math.abs(notRoundedCount);
									var nextPagesQuant = Math.ceil(absoluteCount);
								};
								var totalPagesExp = nextPagesQuant;

								var pageContent = function (data) {
							        // HEADER
							        doc.setFontSize(20);
							        doc.setTextColor(40);
							        doc.setFontStyle('normal');
							        if (base64Img) {
							            doc.addImage(base64Img, 'JPEG', data.settings.margin.left, 15, 10, 10);
							        }
							        doc.text("Report", data.settings.margin.left + 15, 22);

							        // FOOTER
							        var str = "Page " + data.pageCount;
							        // Total page number plugin only available in jspdf v1.0+
							        if (typeof doc.putTotalPages === 'function') {
							            str = str + " of " + totalPagesExp;
							        }
							        doc.setFontSize(10);
							        doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
							    };

							    doc.autoTable(res.columns, res.data, {
							        	theme: 'striped',
							        	addPageContent: pageContent,
							            startY: doc.autoTable.previous.finalY,
							            pageBreak: 'avoid',
							            margin: {
							            	top: 30,
							            }
						        }); 


							    // Total page number plugin only available in jspdf v1.0+
							    if (typeof doc.putTotalPages === 'function') {
							        doc.putTotalPages(totalPagesExp);
							    }
                                                      }
						};
					}; 
				}; doc.save('sueldo_empleado_'+ todayDate + '.pdf');
			}

**Comment by simonbengtsson** [comment]
Do you get get the same error if you try without the images and without the page content hook? Normally I would your code myself but have some other stuff currently so can only give help in debugging it.

**Comment by prometeomcclellan** [comment]
let me give that a try as well, thanks for all support provided by the moment. 

by the way, your plugin is really helpful and an amazing tool.

**Comment by prometeomcclellan** [comment]
now, the answer to that question if I get the same error removing the images and the hook is YES, getting same error even with the tables alone

**Comment by prometeomcclellan** [comment]
ok, I found what I think is nearly to be the root of my problem and as well I found a solution with a little workaround for this issue; here the problem in my case seems to be for I don´t know yet exactly what reason that my first table was losing the style and went to some sort of invisibility (as I said not sure why, by the moment)... what I did is to create an empty table in the begining of the code just before the initial real table and make it invisible, that made my first real table that brings real data to be visible again in my pdf, so all of the tables now render and that empty table is helping me to push it to its position just below my header ... now everything is just perfect and working good so far... not the final solution but a good workaround in my case ... however I´d like to continue debuggingg and learning more from you

**Comment by simonbengtsson** [comment]
Interesting! Can you print the doc.autoTable.previous.finalY variable to the console before you call autotable? Or set a breakpoint in the debugger would of course work as well. Then check what values it has for the table that was not printed.

**Comment by simonbengtsson** [comment]
Just so you know, doc.autoTable.previous will be undefined before the plugin has been called.

**Comment by prometeomcclellan** [comment]
if you mean to do that in the case of the empty table I created, I did not include the doc.autoTable.previous.finalY for that table. but if you mean me to do so for the tables that brings my data from the ERP, then let me give it a hit and I´ll tell you back... anyway the empty table I did like this..

    var columns = [""];var data = ['']; // creating and empty source for this lonely table
    if (tableId == 'tabla_0') { if (j == 0) {doc.autoTable(columns, data, {theme: 'plain', startY: 18}); };	};

    // and creating an empty table that works as a null object to manipulate its position above the ones   with data, this brought back my first table and helps me to push it below header with logo ... etc

**Comment by prometeomcclellan** [comment]
hello Simon, I just want to say thanks for al the support provided, my code is working perfectly and everything in place included images with the addImage fix that you made on december last year... you are a genius... hope to stay in contact in the future ... have a great one

**Comment by prometeomcclellan** [comment]
Hello, Excuse me Simon ! is it posible to manipulate z-index on images with autotable?

**Comment by simonbengtsson** [comment]
Not sure if jspdf supports that. The autotable plugin doesn't do anything with images.

**Comment by prometeomcclellan** [comment]
thanks, nevermind, I just remainded about the drawcell option... that for sure is the answer
