### ISSUE TITLE
JSPDF autotable not working in IE EDGE/11

### ISSUE THREAD

**Issue by Krishanya** [simonbengtsson/jsPDF-AutoTable#242]
Hi,
I'm using JSPDF autotable functionality in my application to download PDF. It works perfectly fine in Chrome & Firefox. But in IE EDGE/10, it throws below error while executing "tableRes = doc.autoTableHtmlToJson($('#'+$('#utilitynameNoSpace').val())[0]);"
SCRIPT5009: 'Symbol' is undefined
File: jspdf.plugin.autotable.js, Line: 10, Column: 11458

I'm using jsPDF AutoTable plugin v2.0.26.

Please help me resolve it, its kind of urgent.

**Comment by Krishanya** [comment]
simonbengtsson, Can you please spare some time answering my query? It's kind of urgent :(

**Comment by Krishanya** [comment]
I managed to fix the above said issue by using latest versions of jspdf.min.js & jspdf.plugin.autotable.js.

Now, when I try opening the PDF in new window it throws "The webpage cannot be displaye" error in IE but works in all other browsers.
This is the code I use to open in new window : doc.output("dataurlnewwindow");

Pls let me know if I miss anything.

**Comment by simonbengtsson** [comment]
have you tried using `doc.save("table.pdf")`? At the top of my head I think IE had problems with the dataurlnewwindow method.

**Comment by Krishanya** [comment]
Yes it works, but I need to open in new window so that it will be consistent across all the browsers.

**Comment by simonbengtsson** [comment]
Take a look in the jspdf repo if there are any workarounds. Unfortunately I don't know of any.

**Comment by Krishanya** [comment]
Thanks for your suggestion.

I would like to provide an option for the user to see the PDF on screen, not necessarily on a new window before deciding on to print or any other activities.
Please let me know if you could quickly think of any such option and guide me.

**Comment by simonbengtsson** [comment]
Unfortunately there is no good way of doing this as far as I know. In the demo for this plugin I use an iframe and post the pdf to that. This works in Chrome, IE and edge but not in Firefox. You might want to take a look at pdf.js.

**Comment by Krishanya** [comment]
Got it.. Thanks!

**Comment by Krishanya** [comment]
One other question, I would like to render the PDF by default in **Landscape** orientation. Irrespective of having the below code, it prints in "portrait".
var doc = new jsPDF('landscape', 'pt');

Am I missing any?

**Comment by Krishanya** [comment]
Simon, Can you please let me know if there is anyway I can change the default font size and style of the contents printed using doc.fromHTML?
Kindly reply at the earliest as I have a deployment by tomorrow.

**Comment by Krishanya** [comment]
I'm using jsPDF.Min.js
