### ISSUE TITLE
Header row issue with JSPDF autotable

### ISSUE THREAD

**Issue by Krishanya** [simonbengtsson/jsPDF-AutoTable#243]
I need to generate a PDF from html table using JSPDF and AutoTable.
In my application I have a table with 2 header rows and lot of row and colspans used in it. Below is the code.
<table>
					<thead>
						<tr>
							<th rowspan=2 align="center" style="padding-top: 10px;">
								Mine Name</th>
							<th colspan="2">Forecast</th>							
							<th colspan="5">Month-to-Date Information</th>
							<th colspan="2">End-of-Month Projection</th>
						</tr>
						<tr>
							<th>Mine Supply</th>
							<th>Plant Demand</th>
							<th>Coal Loaded </th>
							<th>Coal Delivered</th>
							<th>% of Demand Loaded</th>
							<th>Plant Demand Pace</th>
							<th>Plant Demand Variance</th>
							<th>Estimated % of Demand Loaded</th>
							<th>Estimated Coal Loaded</th>
						</tr>
					</thead>
					<tbody>
					<tr>
							<td>ETM - EAST THUNDER</td>
							<td>10</td>
							<td>20</td>
							<td>30</td>
							<td>40</td>
							<td>5.5%</td>
							<td>0.0</td>
							<td>0.9</td>
							<td>0.6%</td>
							<td>0.01</td>
					</tr>
					</tbody>
</table>

I'm using doc.autoTableHtmlToJson to convert the table to PDF. So both the headers looks perfectly fine in 1st page but in the subsequent pages only the 1st header is getting printed. [Note: Wherever there is a colspan I'm simply including a blank <TH> tag to create a placeholder]

I tried using drawHeaderRow & drawHeaderCell, to draw 2nd header. But I couldnt get the proper alignment. The headings are getting overlapped, and doesnt seem to get align with tbody.

 Please help me with this.

**Comment by Krishanya** [comment]
simonbengtsson, Please let me know if the above said implementation is feasible.  I used the below code to achieve double header. But, it doesnt work as expected for the above table design.
 drawHeaderCell: function(cell, data) {
					        doc.rect(cell.x, cell.y, cell.width, cell.height, cell.styles.fillStyle);
					        doc.setFillColor(51, 153, 255);
					        doc.rect(cell.x, cell.y + (cell.height / 2), cell.width, cell.height / 2, cell.styles.fillStyle);
					        doc.autoTableText(cell.text, cell.textPos.x, cell.textPos.y, {
					          halign: cell.styles.halign,
					          valign: cell.styles.valign
					        });
					        doc.setTextColor(255,255,255);
					        //var headerNames = ['','Mine Supply','Plant Demand','Coal Loaded','Coal Delivered','% of Nomination Loaded'] 69
					        
					        var headerNames = [['', cell.textPos.x - 6, cell.textPos.y + (cell.height / 2)],
					                           ['Mine Supply',cell.textPos.x - 15, cell.textPos.y + (cell.height / 2)],
					                           ['Plant Demand', cell.textPos.x - 3, cell.textPos.y + (cell.height / 2)],
					                           ['Coal Loaded', cell.textPos.x + 3, cell.textPos.y + (cell.height / 2)],
					                           ['Coal Delivered', cell.textPos.x - 80, cell.textPos.y + (cell.height / 2)],
					                           ['% of Nomination Loaded', cell.textPos.x - 60, cell.textPos.y + (cell.height / 2)]
					                          ]
					        var text = headerNames[data.column.dataKey];
					      //doc.autoTableText(text, cell.textPos.x, cell.textPos.y + (cell.height / 2), {
					        doc.autoTableText(text[0], text[1], text[2], {
					          halign: cell.styles.halign,
					          valign: cell.styles.valign
					        });
					        return false;
					   },

Please let me know if you want me open this question in stackoverflow.

**Comment by Krishanya** [comment]
Or is there any other way if I can print both the headers in all pages, whenever the content overflows to multiple pages?
FYI.. Now with 2 sets of<th> in the table, I'm able to  get both the headers on 1st page without any issue. but problem occurs when the content overflows, and so I'm looking for a solution.

**Comment by simonbengtsson** [comment]
This table layout is fairly complicated to get to work with jspdf-autotable currently. Version 3 that hopefully will be released soon will have support for multiple header rows and row spans and col spans. Closing for now.
