### ISSUE TITLE
Is it possible to combine jspdf and autotable plugin

### ISSUE THREAD

**Issue by tesmanovicD** [simonbengtsson/jsPDF-AutoTable#244]
Almost like I wrote in title of this post..Is it possible to combine jspdf fromHTML to grab text from html page and jsPDF autotable to grab table and to get that all inside one pdf..I tried but I got some blank space between fromHTML and autotable .I posted on stackoverflow ,but no one answered  yet(2 days ago).Please give me a simple example of combine that two together,without that blank space or I can post stackoverflow link here? Thanks a lot!

**Comment by simonbengtsson** [comment]
I saw your post on stackoverflow. Will write there when I got time to respond.

**Comment by Teshma** [comment]
Can you just said me for now is it possible to get rid of that blank space ? :)

**Comment by simonbengtsson** [comment]
Sure is! Not sure about the details of why it is there though, will take a
look another time. You might want to try manually creating the pdf without
using fromhtml.

**Comment by Teshma** [comment]
If I use doc.text() ,then everything is fine,but the text from that html page is not static :) Thanks for answer man!

**Comment by simonbengtsson** [comment]
You could use jQuery or querySelector to extract the dynamic text?

**Comment by Teshma** [comment]
And to implement that into variable,then variable to doc.text() ? I will try to google something about that? :) If I'm not wrong

**Comment by simonbengtsson** [comment]
Correct!

**Comment by Teshma** [comment]
I solve my problem about blank page :D Can you tell me how StartY work,I want to make my table StartY position to be after doc.fromHTML is that even possible? :) I tried something like this startY: doc.fromHTML +20 and startY: doc.fromHTMLEndPosY() +20 ,but without success :P
