### ISSUE TITLE
Issue with rowspan and pagebreak

### ISSUE THREAD

**Issue by CJX3M** [simonbengtsson/jsPDF-AutoTable#245]
Good day

Sorry to bother, and opening a new issue, but I really need some advice here.

As I mentioned before, I'm having a problem with rowspan cells and pagebreak, where cells are being drawn above the margin

![image](https://cloud.githubusercontent.com/assets/5133204/24168509/0b18ed1c-0e40-11e7-9dab-604792bfa018.png)

So, in order to adjust this, I added the `pageSize` information to the data sent over to the hooks on the `printRow` function

```
var data = hooksData({ column: column, row: row, pageSize: Config.getJspdfInstance().internal.pageSize });
if (hookHandler(cell, data) !== false) {
var fillStyle = getFillStyle(cell.styles);
if (fillStyle) {
```

And, on my `drawCell` hook, I check the span of the cell with the size and position of the cell against the page size and it's in order to prevent the previous from happening

```
if(cell.raw.indexOf("*") > -1) {
   var text = cell.raw.split("*")[0];
   var times = cell.raw.split("*")[1];
   while((cell.height * times + cell.y) > data.pageSize.height - data.settings.margin.bottom) {
      times--;
   }
   doc.rect(cell.x, cell.y, cell.width, cell.height * times, 'FD');
   doc.autoTableText(text, cell.x + cell.width / 2, cell.y + cell.height * times / 2, {
      halign: 'center',
      valign: 'middle'
   });
   return false;
}
```

And I'm getting this

![image](https://cloud.githubusercontent.com/assets/5133204/24168672/9b445f84-0e40-11e7-93a9-b15933e25ee1.png)

So, I'm no longer getting the issue, but now my problem is, how to style those emtpy cell on the next page. Any idea how to achieve this?

Thanks

**Comment by simonbengtsson** [comment]
Sorry for the delay. Not sure of your issue, but will have unofficial rowspan and colspan support in v3.

**Comment by CJX3M** [comment]
No problem.

I had to change the pdf option for an excel one, as the client wanted to import larger than life grids over to pdf, that would only fit on plotter paper, not possible on normal paper without making the font size microscopic.

Will check it out once v3 comes out. Thanks

**Comment by sureeebabu** [comment]
how to print two a5 sheet in one a4 sheet
