### ISSUE TITLE
Linebreak not work

### ISSUE THREAD

**Issue by Minh-Van** [simonbengtsson/jsPDF-AutoTable#246]
I followed the example `Long text` to do my pdf export. Everything worked well until I set another value to  `dataKey: "text"`
It mean that, this is your code in the example,
```
var columnsLong = getColumns().concat([
        {title: "Long text column", dataKey: "text"},
        .......
    ]);
```
I set `package_name` to `dataKey` then I tried to export and `linebreak` didn't work for the column `Long text column`.

I don't understand why `linebreak` only work for `dataKey: "text"`, if it isn't a bug can you explain for me ?

**Comment by simonbengtsson** [comment]
It should work for any dataKey. You have to make sure that the overflow
style is set to linebreak though. In the long text example I think it is
set for the text column only.

**Comment by Minh-Van** [comment]
This is code for `Long text` example
```
examples.long = function () {
    var doc = new jsPDF('l');
    var columnsLong = getColumns().concat([
        {title: "Title with\nlinebreak", dataKey: "text2"},
        {title: "Long text column", dataKey: "text"},
    ]);

   ................

   doc.text("Overflow 'linebreak'", 7, doc.autoTable.previous.finalY  + 10);
    doc.autoTable(columnsLong, getData(3), {
        startY: doc.autoTable.previous.finalY + 15,
        margin: {horizontal: 7},
        bodyStyles: {valign: 'top'},
        styles: {overflow: 'linebreak', columnWidth: 'wrap'},
        columnStyles: {text: {columnWidth: 'auto'}}
    });

    return doc;
```
I think `styles: {overflow: 'linebreak', columnWidth: 'wrap'},` is set as you mentioned above, right ?

**Comment by simonbengtsson** [comment]
You are right, my bad. Code you post your code as well?

**Comment by Minh-Van** [comment]
I have posted an example for my issue at there http://embed.plnkr.co/De58FZf1dHjbWgVy6Xvp/

You can see if I set `{title: "Note", dataKey: "note"},` linebreak doesn't work. But if you use `{title: "Note", dataKey: "text"},` linebreak works well

**Comment by Aakanchha02** [comment]
var columns = [{title: "Question", datakey: "text"}, {title: "Answer", datakey: "text1"}];
var rows=[];
var ansRowCount=0;
for(var i=0;i<5;i++)
{
ansRowCount=i+2;
rows[i]=[dataCategory1[i],ansData["0"][ansRowCount]];
}
pdf.autoTable(columns,rows, {
 		styles: {
	        overflow:'linebreak'
	         },
	       showHeader: 'everyPage',
	  		drawHeaderRow: function(row, data) {
	      //return false; //if you want to hide header
	      return true;
			},
	  		margin : {
	         top : 4,
	         left:0.3,
	         right:0.3
	         },
	  	  theme: 'striped'
	  	  columnStyles: {
		    0: {columnWidth: 2.5},
		    1: {columnWidth: 5.4}
		    }
		 });
![autotable](https://cloud.githubusercontent.com/assets/26770124/24460003/96bf45f2-14ba-11e7-8f99-488615b8edda.PNG)

**Comment by Aakanchha02** [comment]
overflow:'linebreak' is not working.

**Comment by anatha** [comment]
Any update on this issue? Any info we can provide in order to make it easier for you to identify the cause?

**Comment by lpbaiser** [comment]
`overflow:'linebreak'` is not working, I have posted an example for my issue at there: [plnkr.co/edit/45HUtgM4UbpQj9dM5uJd](url)

I tested with another styles to overflow that: visible, hidden, ellipsize. This styles it works. 
See example on image with `overflow:'linebreak'`: 
![pdf](https://cloud.githubusercontent.com/assets/14255595/25090945/afcd4f66-235c-11e7-8e1f-575872d49763.jpeg)

I tested too with `columnWidth: 'wrap'` but the table is cut. See example on image:
![pdf_cut](https://cloud.githubusercontent.com/assets/14255595/25090882/2d73f074-235c-11e7-89bc-451c07067370.jpeg)

**Comment by nankathi** [comment]
I have the same issue, any solution yet?

**Comment by simonbengtsson** [comment]
In the example code posted by @lpbaiser above the columnStyles is specified for the column with the dataKey `text`, but the long text column in his code is `note`. His code should be like this:

        doc.autoTable(columns, data, {
		startY: 20,
		styles: {overflow: 'linebreak', columnWidth: 'wrap'},
		columnStyles: {note: {columnWidth: 'auto'}},
	});

Seems like many people are confused about this which make sense. Will try to make columnStyles more obvious in version 3.0.

**Comment by nankathi** [comment]
@lpbaiser  @Aakanchha02 @anatha Hello guys,
This is how I made it work. Hope it helps
![image](https://user-images.githubusercontent.com/7938113/29323547-1c68cd7a-8196-11e7-8281-fa4342fd8b9b.png)
Here's the updated plunk from @lpbaiser : https://plnkr.co/edit/JNYEeryM7UA6pcoCa24E?p=preview

**Comment by webwakko** [comment]
@rjankathi : how exactly did you make this work? the plunk is not actualy showing the solution to this? or am I missing out on something? 
Please explain what exactly you did to make it work.. much appriciated ;)
