### ISSUE TITLE
jsPDF render div header and auto table from HTML

### ISSUE THREAD

**Issue by SaravananArunagiri** [simonbengtsson/jsPDF-AutoTable#248]
I am using jsPDF to convert HTML to Pdf. Normally when i want only table to pdf is working fine. Here the working code is,

```
var doc = new jsPDF('l');
var elem = document.getElementById("basic-table");
var res = doc.autoTableHtmlToJson(elem);
doc.autoTable(res.columns, res.data, { startY: 20 });
document.getElementById("output").src = doc.output('datauristring');
```
But Now need to append header details in the pdf. I try many code to render div element and table in the same pdf. Here the tried code is ,

```
var doc = new jsPDF('l');
doc.fromHTML($('#printHeader').get(0), 15, 15, {
                'width': 170,
                'elementHandlers': specialElementHandlers
            }); 
var elem = document.getElementById("basic-table");
var res = doc.autoTableHtmlToJson(elem);
doc.autoTable(res.columns, res.data, { startY: 20 });
document.getElementById("output").src = doc.output('datauristring');
```
Cannot Working !.

**Comment by simonbengtsson** [comment]
I think your issue has to do with that the fromHtml function is async. But I'm not that familiar with it. Try asking on stackoverflow with the jspdf tag. Closing now since it doesn't seem related to this plugin.
