### ISSUE TITLE
Building v3 before release?

### ISSUE THREAD

**Issue by desilinguist** [simonbengtsson/jsPDF-AutoTable#251]
I would really, really like to try out the native rowspan/colspan support since I am not able to figure out how to get that to work with manual styling. I know lots of folks have already asked about when v3 is coming out. However, it sounds like the support is already there in `master` and it should be possible to build `master` and use this functionality? When I tried to do that right now using `npm run build`, I get the following errors:

```
ERROR in ./src/main.ts
(66,32): error TS2339: Property 'cells' does not exist on type 'Element'.

ERROR in ./src/main.ts
(67,27): error TS2339: Property 'cells' does not exist on type 'Element'.

ERROR in ./src/main.ts
(80,37): error TS2339: Property 'cells' does not exist on type 'Element'.
```

Is there any way to try out the native rowspan/colspan stuff without waiting for the release?

**Comment by simonbengtsson** [comment]
I ended up doing some other things so the update got delayed quite a bit. But you are right, it is there in master. I'm planning to change the event api a little bit before release though.

Hmm, strange that you get those errors. What version of typescript are you using?

**Comment by desilinguist** [comment]
The log says `ts-loader: Using typescript@2.2.2 ...`

**Comment by simonbengtsson** [comment]
Here are a zip with built v3 files that you can try. You can check the examples on the master branch for information how to use it.

[v3-dist-files.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/916882/v3-dist-files.zip)

**Comment by desilinguist** [comment]
Thanks so much!

**Comment by simonbengtsson** [comment]
I got the same error using the latest typescript so will make sure it works later today probably.

**Comment by simonbengtsson** [comment]
If you end up trying version 3, let me know if you have any questions or feedback.

**Comment by desilinguist** [comment]
Actually, the `examples.js` file has me a little confused. When I look at the code in master and what you sent me, it looks like the library now supports the `rowspan` attribute in the html parser.  I took this to mean that `autoTableHtmlToJson` should now deal with the `rowspan` attribute properly. However, in `examples.js` in the spans example, you don't seem to be using `cell.rowSpan`. 

Am I missing something?

**Comment by simonbengtsson** [comment]
The examples for v2 are actually in `examples-legacy.js` now and the v3 is in `examples.js`. Mistake from my side. Didn't intend to push that yet.

**Comment by desilinguist** [comment]
I didn't see an `examples-legacy.js`  in `master`. I looked around and realized that they are in the `v2` branch instead. I will take a look. Thanks!

**Comment by desilinguist** [comment]
OMG, `rowspan` just works now! This is so awesome! However, I seem to have lost all formatting in my table. I did get some deprecation warnings and made the changes but I guess more things have changed. I will try and figure the rest of the changes out myself by looking at the example! Thanks again!

**Comment by desilinguist** [comment]
Okay, it all works now. I just had to make the following changes: 

`cell.raw.className` → `cell.raw.content.className`
`data.row.raw[i].className` → `data.row.raw[i].content.className`
`data.row.raw[i].textContent` → `data.row.raw[i].content.textContent`

**Comment by simonbengtsson** [comment]
Glad to hear! Hmm, right! Will try to either make that more obvious or write it clearly in the release notes. Cheers!
