### ISSUE TITLE
autoTableHtmlToJson wrong columns count

### ISSUE THREAD

**Issue by JCarlosR** [simonbengtsson/jsPDF-AutoTable#252]
Hi.

I am using the next code:

```
var doc = new jsPDF('l', 'mm', [297, 210]);
doc.text("From HTML", 14, 16);
var elem = document.getElementById("schedule-table");
var res = doc.autoTableHtmlToJson(elem);
console.log(res);
doc.autoTable(res.columns, res.data, {startY: 20});
doc.save('table.pdf');
```

I want to generate a PDF based in the next HTML table:

![snip_20170412104142](https://cloud.githubusercontent.com/assets/3101238/24967237/1390c43e-1f6f-11e7-8c38-fc2b7d5e4156.png)

But the result is:

![snipp](https://cloud.githubusercontent.com/assets/3101238/24967283/312673d6-1f6f-11e7-965c-86d8137f2fc3.png)

The ```console.log``` showed me that the ```res.columns``` had just 2 columns.

I think that the function ```autoTableHtmlToJson``` can be improved to use a number of columns based on the max number of columns (in the rows), or add the colspan value when it appears in the header.

Also, I saw that jsPDF supports images: http://stackoverflow.com/questions/19065562/add-image-in-pdf-using-jspdf

But the ```autoTableHtmlToJson``` doesn't recognize images.

I was looking for that function in the ```src``` folder, but can't find it.

Please give me some ideas and tell me where I can find that function.
I am not a JS expert but probably can do something and make my first pull request :)

Thank you for creating jsPDF. Great work!

**Comment by simonbengtsson** [comment]
This repo is a plugin to jspdf so even if I wished I was cool enough to say I created jspdf, that is not the case ;)

This plugin does currently not support colspans or rowspans natively, but that feature is coming with v3. Images or not natively supported either but can be added with hooks.

**Comment by muzashi36** [comment]
Hi
I am trying to use autoTableHtmlToJson but got an error

Uncaught TypeError: doc.autoTableHtmlToJson is not a function

My code

import jsPDF from 'jsPDF'
import 'jspdf-autotable'


    createPDF () {
      var doc = new jsPDF('p', 'pt');
      var specialElementHandlers = {
          '#editor': function (element, renderer) {
              return true;
          }
      };

      var elem = document.getElementById('content');
  	  var data = doc.autoTableHtmlToJson(elem);
  	  doc.autoTable(data.columns, data.rows, options);

  	  if (typeof doc.putTotalPages === 'function') {
  	    doc.putTotalPages(totalPagesExp);
  	  }

  	  doc.save('tabled.pdf');
    },

**Comment by EliseoAg** [comment]
Try This Library

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.0-alpha.1/jspdf.plugin.autotable.min.js"></script>
