### ISSUE TITLE
Exception and tableExport error

### ISSUE THREAD

**Issue by orunjubd** [simonbengtsson/jsPDF-AutoTable#254]
<script src="../js/FileSaver.min.js" type="text/javascript"></script>
<script src="../js/xlsx.core.min.js" type="text/javascript"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js" type="text/javascript"></script>
<script src="../js/jspdf.plugin.autotable.js" type="text/javascript"></script>
<script src="../js/html2canvas.min.js" type="text/javascript"></script>    
<script src="../js/tableExport.js" type="text/javascript"></script>         
I face a lot of error: some are - [version: 2.3.0]

the afterPageContent, beforePageContent and afterPageAdd hooks are deprecated. Use addPageContent instead
** Use of deprecated style: rowHeight, use vertical cell padding instead
** jspdf.plugin.autotable.js:1163 Deprecation warning: Use dataKey instead of key
I replace all code your exception way.

But rest of 2 error can't understand how can I solve it -

** console.error("Unrecognized overflow type: " + cell.styles.overflow);
** console.log(doc.internal.getFontSize()); ===== ( its output 16)
** tableExport.js:859 Uncaught TypeError: Cannot read property 'fontSize' of undefined

Any help?

**Comment by simonbengtsson** [comment]
The exception seems to happen in tableExport.js. Check that lib.
