### ISSUE TITLE
ReferenceError: jsPDF is not defined

### ISSUE THREAD

**Issue by BRAEIKMiled** [simonbengtsson/jsPDF-AutoTable#259]
Hello, 

I am trying to export some pages in my application into pdf files, I included the jspdf in my code HTML with 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.debug.js"></script>`

and I implemented the code in my controller, and this is my code:

```js
vm.PDFexprt=function(){
    PDFexprt();
};
function PDFexprt(){
    var pdf = new jsPDF('p', 'pt', 'letter');
        source = $('#content')[0];
        specialElementHandlers = {
            // element with id of "bypass" - jQuery style selector
            '#bypassme': function (element, renderer) {
                // true = "handled elsewhere, bypass text extraction"
                return true
            }
        };
        margins = {
            top: 80,
            bottom: 60,
            left: 40,
            width: 522
        };    
        pdf.fromHTML(
            source, // HTML string or DOM elem ref.
            margins.left, // x coord
            margins.top, { // y coord
                'width': margins.width, // max width of content on PDF
                'elementHandlers': specialElementHandlers
            },
            function (dispose) {            
                pdf.save('Test.pdf');
            }, margins
        );
  }
```

and I called this function in my code HTML: 

`<ion-view view-title="{{vm.title}}">
<body>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.debug.js"></script>
   <span class="button" ng-click="vm.PDFexprt()">Export</span>
</body>
</ion-view>`

But it shows

 `ReferenceError: jsPDF is not defined`

Any help please :)

**Comment by simonbengtsson** [comment]
Are you including the jspdf autotable plugin as well? If so what version? Are you using a cdn for the jspdf autotable plugin as well?

**Comment by BRAEIKMiled** [comment]
Thank you for the quick reply,
Yes I am including the jspdf autotable plugin v2.3.2 also using cdn.
Regards,

**Comment by simonbengtsson** [comment]
I made your posted code readable now and realized that you didn't include any usage of this plugin?

**Comment by BRAEIKMiled** [comment]
Yes, But why it shows jspdf undefined despite the fact that I included the plugin in my code? 
In fact I only need to export my app page into a pdf file.

**Comment by simonbengtsson** [comment]
As you do not seem to use the autotable plugin your issue is probably related to your setup of jspdf. If you believe it is an issue with jspdf consider posting an issue in the jspdf repo or post an issue if you think that it is your setup that is the issue.

**Comment by BRAEIKMiled** [comment]
Well that's what I wanted to do but I couldn't post an issue in the jspdf repository.
Thank you for your support :)

**Comment by simonbengtsson** [comment]
Why not? Tried stackoverflow?

**Comment by BRAEIKMiled** [comment]
the "issue" tab is not active in jspdf repository.
No cause my account has been blocked because I didn't write the question as the want it to be writed :/

**Comment by simonbengtsson** [comment]
Are you sure? It is visible for me: https://github.com/MrRio/jsPDF/issues. What is your username on stackoverflow?

**Comment by BRAEIKMiled** [comment]
I though it's in your jspdf repository. For the question that got me blocked I deleted it, they said I will be able to post a question after two days from today :/ 
My username on stackoverflow is "Miled Braik".

**Comment by simonbengtsson** [comment]
Nope, this is a table plugin to jspdf. Fair enough, two days seems reasonable.

**Comment by BRAEIKMiled** [comment]
Well Thank you for your support :) 
I posted the issue in the link you gave me and I hope they will answer me soon 
Have a nice Coding day

**Comment by simonbengtsson** [comment]
If I were you I would read up on why the ReferenceError happens. My guess is that you are not including jspdf correctly on the page. 

Anyhow, good luck!
