### ISSUE TITLE
putTotalPages : 2 tables by page repeat pagination

### ISSUE THREAD

**Issue by leonardotessaroalves** [simonbengtsson/jsPDF-AutoTable#260]
` _.each(self.tables, function(v, k) {

            if (v.options.insertTitle) {
                let tpl = $(`<table><thead><tr><th>${v.options.insertTitle}</th></tr></thead></table>`);

                let templateJson = self.doc.autoTableHtmlToJson(tpl[0]);

                self.doc.setPage(1 + self.doc.internal.getCurrentPageInfo().pageNumber - self.doc.autoTable.previous.pageCount);

                self.doc.autoTable(templateJson.columns, templateJson.rows, {
                    showHeader: 'firstPage',
                    pageBreak: 'avoid',
                    startY: (self.doc.autoTable.previous.finalY + self.options.margin),
                    tableWidth: 'auto',
                    margin: self.options.margin,
                    headerStyles: {
                        fillColor: [20]
                    }
                });

            }

            let res = self.doc.autoTableHtmlToJson(document.querySelectorAll(v.selector)[0]);
            self.doc.autoTable(
                res.columns,
                res.data, {
                    addPageContent: (data) => {
                        return self.insertPagination(data);
                    },
                    startY: Number(self.doc.autoTable.previous.finalY + ((v.options.insertTitle) ? 0 : self.options.margin)),
                    showHeader: 'firstPage',
                    columnStyles: self.processObjects(res.columns, { fillColor: [255] }),
                    headerStyles: {
                        fillColor: [251, 181, 0],
                        fontSize: 8
                    },
                    margin: self.options.margin
                }
            );

        });`

i have a simple forEach. When i add the pagination, the code print twice at same position. someone has the same issue?

**Comment by simonbengtsson** [comment]
Can you check with for example `console.log()` the value you pass to `startY` in each loop?

**Comment by leonardotessaroalves** [comment]
inside each: console.log('finalY:',self.doc.autoTable.previous.finalY);

1 - finalY: 141.75
2 - finalY: 417.45

the simple solution:
`insertPagination(data) {
        let self = this;
        // FOOTER
        /*FIX - check if the page number is diferent*/
        if (data.pageCount !== self.pageCountStart) {
            self.pageNumber = "Página " + data.pageCount;

            if (typeof self.doc.putTotalPages === 'function') {
                self.pageNumber = self.pageNumber + " de " + self.totalPagesExp;
            }
            //footer line
            self.doc.setFillColor(251, 185, 0);
            self.doc.rect(data.settings.margin.left,
                Number(self.doc.internal.pageSize.height - 25),
                Number(self.getPageWidth() - (self.options.margin * 2)), 0.5, 'F');

            //text pagination footer
            self.doc.setFontSize(8);
            self.doc.text(self.pageNumber, data.settings.margin.left, self.doc.internal.pageSize.height - 10);
        }

        /*FIX - set pageCountStart on every call*/
        self.pageCountStart = data.pageCount;
    }`

**Comment by simonbengtsson** [comment]
Not sure what the fix was by glad you solved it.

**Comment by leonardotessaroalves** [comment]
No Problem. On each table i called the method addContent where i put the footer.
so i've just put a "if" to not repeat when the count is equal a current page.
