### ISSUE TITLE
Fit a wider table into PDF

### ISSUE THREAD

**Issue by Krishanya** [simonbengtsson/jsPDF-AutoTable#261]
I have a table with nearly 16 columns, and trying to convert to PDF using JSPDF autotable plugin.

My requirement is I need to break the table header on its space. For Example, if the header name is EOM Projected Mine Variance, I want to break it on space. So that headers with single column like 'Mine' will not get wrapped and look ugly. Please refer my attachment for more details.

Please help me with this.
Thanks,
Krishu
[Reports (93).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/1031697/Reports.93.pdf)

**Comment by Krishanya** [comment]
In the attachement, The 1st and 3rd column header, has a very bad readability.

**Comment by simonbengtsson** [comment]
You can do so with the style: `columnWidth: 'wrap';` on the columns you want to not break. You can check out examples.js to see how to use the columnWidth style.
