### ISSUE TITLE
Table with more 500 rows not show header image

### ISSUE THREAD

**Issue by andynhoo** [simonbengtsson/jsPDF-AutoTable#262]
Does not show the header image on the left when the table has more than 600 records.

My Code:
```js
   var doc = new jsPDF('landscape');
    html2canvas(document.getElementsByClassName('logo'),{
        onrendered: function(canvas) {
            var elem = document.getElementById("tabela-registros-clientes");
            var res = doc.autoTableHtmlToJson(elem);
            var colunas = [];
            colunas.push(res.columns[0],res.columns[1],res.columns[2],res.columns[3],res.columns[4],res.columns[5]);
            var linhas = [];
            for(var item=0;item<=(res.data.length - 1);item++){
                linhas.push([res.data[item][0],res.data[item][1],res.data[item][2],res.data[item][3],res.data[item][4],res.data[item][5]]);
            }
            doc.autoTable(colunas,linhas,{margin: {top: 30},theme: 'grid', showHeader: 'everyPage', headerStyles: { halign:'center' },addPageContent: function(data) {
                doc.text(230, 15, 'Listagem de Clientes');
                doc.addImage(canvas.toDataURL("image/png"),'JPEG',10,5);
                doc.setDrawColor(0);
                doc.setLineWidth(1.5);
                doc.line(0, 1, 300, 1);
                doc.line(0, 209, 300, 209);
            } });
            doc.save("Clientes.pdf");
        }
    });
```

Image header with print more 500 rows
http://i.imgur.com/wTypd7k.png

Image header with print less 500 rows
http://i.imgur.com/mDCgDj4.png

**Comment by simonbengtsson** [comment]
So a table with 499 rows works fine? Sounds strange indeed! What if you make a simplified test without any of your other code. Just the addPageContent with the image. Also test with passing the data returned from autoTableHtmlToJson directly to autotable.

**Comment by andynhoo** [comment]
The same problem happens :( 

My table have a 6 columns and 801 rows.
If you display only 500 records the image appears normal, 
but above that the header image does not show.

**Comment by andynhoo** [comment]
`    var doc = new jsPDF('landscape');
    html2canvas(document.getElementsByClassName('logo'),{
        onrendered: function(canvas) {
            var elem = document.getElementById("tabela-registros-clientes");
            var res = doc.autoTableHtmlToJson(elem);
            doc.autoTable(res.columns,res.data,{
                    margin: {top: 30},
                    theme: 'grid',
                    showHeader: 'everyPage',
                    headerStyles: {
                        halign:'center'
                    },
                    addPageContent: function(data) {
                        doc.text(230, 15, 'Listagem de Clientes');
                        doc.addImage(canvas.toDataURL("image/png"),'JPEG',10,5);
                        doc.setDrawColor(0);
                        doc.setLineWidth(1.5);
                        doc.line(0, 1, 300, 1);
                        doc.line(0, 209, 300, 209);
                    }
            });
            doc.save("Clientes.pdf");
        }
    });`

**Comment by simonbengtsson** [comment]
Does the following simplified example work for you?

```js
html2canvas(document.getElementsByClassName('logo'), {
    onrendered: function (canvas) {
        var image = canvas.toDataURL("image/png");
        var elem = document.getElementById("tabela-registros-clientes");
        var res = doc.autoTableHtmlToJson(elem);
        doc.autoTable(res.columns, res.data, {
            addPageContent: function (data) {
                doc.addImage(image, 'JPEG', 10, 5);
            }
        });
        doc.save("Clientes.pdf");
    }
});
```

**Comment by andynhoo** [comment]
I change the code but the same problem happens :(

With more 600 rows:
http://i.imgur.com/b4p141S.png

With less 600 rows:
http://i.imgur.com/5N4WL9N.png

**Comment by andynhoo** [comment]
`js

ExportarPdf = function(){
    var doc = new jsPDF('landscape');
    html2canvas(document.getElementsByClassName('logo'), {
        onrendered: function (canvas) {
            var image = canvas.toDataURL("image/png");
            var elem = document.getElementById("tabela-registros-clientes");
            var res = doc.autoTableHtmlToJson(elem);
            doc.autoTable(res.columns, res.data, {
                addPageContent: function (data) {
                    doc.addImage(image, 'JPEG', 10, 5);
                }
            });
            doc.save("Clientes.pdf");
        }
    });
}
`

**Comment by andynhoo** [comment]
I post video:
https://vimeo.com/219531035

**Comment by simonbengtsson** [comment]
Hmm interesting. Can you try drawing a thousand or so images outside of the plugin? I.e. in a for loop.
