### ISSUE TITLE
How to display more columns

### ISSUE THREAD

**Issue by MrPallaBall** [simonbengtsson/jsPDF-AutoTable#263]
Hi to all,
I would like to print a pdf with 20 columns.
I have all header titles in an array and all columns values in another array of array like this:
`var header = ['title 1', 'title 2', .... 'title 20']`

`var rows = [['val 1', 'val 2', .... 'val 20'], ['val 1', 'val 2', .... 'val 20'], ['val 1', 'val 2', .... 'val 20']]`

Can you give me an example?
Now I run a code, but I can print only first 12 columns.

Maybe the problem is into jspdf properties?
 ```
var  l = {
          orientation: 'l',
          unit: 'mm',
          format: 'a3',
           compress: true,
           fontSize: 5,
            lineHeight: 1,
          autoSize: true,
         printHeaders: true
 };
                            var doc = new jspdf(l, '', '', '');
```

**Comment by simonbengtsson** [comment]
Not enough info/code to reproduce the issue.

**Comment by MrPallaBall** [comment]
@simonbengtsson : sorry, my mistake. I have 2 table to save in pdf with same header titles but in the second I have a length of header titles more then the first table.

**Comment by prtkkr** [comment]
Hello @simonbengtsson,
I have a requirement to display a table with 20 columns in PDF file. I am thinking of breaking the columns into group of ten. Is it possible to display first 10 columns in first page and the next 10 columns in second page and so on or could you point me in the right direction to proceed with it?
