### ISSUE TITLE
label:question  how set text center on drawRow function?

### ISSUE THREAD

**Issue by leonardotessaroalves** [simonbengtsson/jsPDF-AutoTable#265]
i want to set header text alignment, on draw row function, based on on html class (autoTableHtmlToJson). how do it?

**Comment by simonbengtsson** [comment]
Hi! Stackoverflow is now the preferred forum for questions about how to use this plugin. Please include the `jspdf` and `jspdf-autotable` tags when posting so it is easier to find the question.
