### ISSUE TITLE
Need Jave script code to get the base64 pdf string passing input as HTM code from jsPDF plug-in

### ISSUE THREAD

**Issue by ravipara72** [simonbengtsson/jsPDF-AutoTable#268]
Hi All,

We need to generate the pdf from firefox browse. will pass the HTML content as an input and this HTML code can be tables and plain text. by passing this HTML to code to jsPDF plug-in, we should get the eithere document or pdf base64 string.

Thanks for your help.

Regards,
Ravi Para

**Comment by simonbengtsson** [comment]
With this plugin you can generate a pdf table with the help of the autoTableHtmlToJson function.

**Comment by ravipara72** [comment]
Can anybody provide java script code to generate PDF and to get the generated base64 pdf string by using jsPDF  plug-in.  Below is the html string. this we need to generate in PDF and should get the base64 of generated pdf file. please help me out.

var shtmlstng = "<br><b><u>CONTACT REPORT CONTENT</u></b><br><br>   - Type: <br>   - Date: 11/5/2017<br>   - Location: <br>   - Created: Benoit Navez on 11/5/2017 17:13:34<br>   - Status: Final with SmartScript<br>   - Confidential: N<br>   - Company/Group: MSSSUSDDDIC HALL GROSSSUP<br><br>1. <u>Executive Summary</u><br><br><br><br>2. <u>Contact Persons</u><br><br><br>3. <u>Employees</u><br>   - Benoit <br>   - WimG47987 Segers<br><br><br>4. <u>Associated Opportunities</u><br><br><br>5. <u>Associated Activities</u><br><br><br>6. <u>Detail</u><br>".

**Comment by simonbengtsson** [comment]
I'm not sure but I think jspdf supports exporting base64. If it does you can use it to get a base64 string which will then export base64 for autotable as well. Check the jspdf repo for more information on that.
