### ISSUE TITLE
How to add a footer text just below the table

### ISSUE THREAD

**Issue by hanct** [simonbengtsson/jsPDF-AutoTable#274]
Hi,
How do you add a footer text just below the table? I cannot hardcode the position of the footer text, as the table could be different rows, hence different height

Regards,

**Comment by hanct** [comment]
I got it.
This is the key doc.autoTable.previous.finalY.
doc.text("My footer" ,options.margin.left, doc.autoTable.previous.finalY+30)

**Comment by brahimkra** [comment]
Hi, how can i add text to the previous text using JSPDF?
