### ISSUE TITLE
set a minimum column width before overflow-linebreak

### ISSUE THREAD

**Issue by Basti85i** [simonbengtsson/jsPDF-AutoTable#277]
Hello,

I'm currently using an overflow: linebreak option to produce my pdf-output.
Is there a way to set a minimum column width of e.g. 10 characters before the overflow-linebreak?
In case of the following table my ouput looks like this 
![unbenannt2](https://user-images.githubusercontent.com/31008713/29317085-ba6ca6a2-81ca-11e7-9ba1-1848fa01e02c.PNG)

Code:
`$(document).ready(function() {
  $("#btn_pdf").click(function printpdf() {
      var pdf = new jsPDF('p', 'pt');
      var res = pdf.autoTableHtmlToJson(document.getElementById('variables'));
      pdf.autoTable(res.columns, res.data, {
         startY: 60,
         margin: {horizontal: 20},
         styles: {overflow: 'linebreak', font: 'arial', fontSize: 10, cellPadding: 8, columnwidth: 'auto'}
      }); 
    pdf.save("table.pdf");
});`

Thanks,
Basti

**Comment by nikhilaggarwal** [comment]
Also, facing the same issue

**Comment by simonbengtsson** [comment]
You can set the column width for all columns manually.

**Comment by stark1996** [comment]
apply column width on the tables in your html
`
<th style="width:**px"></th>
`

**Comment by stark1996** [comment]
```
<th style="width">headers</th>
```

**Comment by simonbengtsson** [comment]
`minCellWidth` option added in v3.0.2
