### ISSUE TITLE
Resize columns width after changing the fontSize on a  cell

### ISSUE THREAD

**Issue by Jean-PhilippeD** [simonbengtsson/jsPDF-AutoTable#278]
Hello,

I want to build a table with multiples rows, and some rows need to have a fontSize lower than the others.

I've let the default fontSize to 10 and I want to user a fontSize to 6 for my specific rows.

I used this code which works:

```
drawRow: function (row, data) {
        for(var key in data.row.cells) {
          var text = 'My text to mactch';
          var re = new RegExp(text, 'g');
          if(re.exec(data.row.cells[key].raw)) {
            data.row.cells[key].styles.fontSize = "6";
          }
        };
      }
```

But the problem is the resize is done after the other elements of the table have been built, I think.
Though I have 2 problems.
First, my text has been truncated when it was too large (... added at the end).
Secondly, the columns are not resized, while the purpose was to resize all the columns.

How can I do ?

**Comment by simonbengtsson** [comment]
Try createdCell instead of drawCell

**Comment by Jean-PhilippeD** [comment]
Thanks ! It's working nice !

I just had to replace drawRow per createdCell :)
