### ISSUE TITLE
How to align the image in pdf to the right edge of my table?

### ISSUE THREAD

**Issue by hanct** [simonbengtsson/jsPDF-AutoTable#280]
Using addImage, i manage to add an image to the pdf, on top of the table. But i do not want to hardcode the position of the pdf, so is there any option to align the image to the far right side of pdf, such as the image's right side is align with the table's right side, without hardcoding the position.

**Comment by simonbengtsson** [comment]
Hi! Stackoverflow is now the preferred forum for questions about how to use this plugin. Please include the `jspdf` and `jspdf-autotable` tags when posting so it is easier to find the question.
