### ISSUE TITLE
Print selected rows

### ISSUE THREAD

**Issue by razorrazor** [simonbengtsson/jsPDF-AutoTable#285]
Hi there!
I'm wondering how to print the selected table rows only. Is it possible?

**Comment by simonbengtsson** [comment]
What do you mean by selected rows?

**Comment by razorrazor** [comment]
I'm using jsPDF with DataTables. I would like to export to PDF only the selected rows in a table

**Comment by simonbengtsson** [comment]
The way to go about that would be to extract the selected rows from DataTables using their api and then  use those javascript objects with this plugin.
