### ISSUE TITLE
Checkbox in table header produces error

### ISSUE THREAD

**Issue by Basti85i** [simonbengtsson/jsPDF-AutoTable#286]
When I put a checkbox in the header of my table I'm getting the following error:
TypeError: line[0] is undefined 
in   jspdf.debug.js:9140:6 ("current_word_length = getArraySum(widths_array.slice(word.length - line[0].length));").
Is there any way to work around this?

**Comment by simonbengtsson** [comment]
Checkbox in your html html?

**Comment by simonbengtsson** [comment]
Are you using the `autoTableHtmlToJson` method?

**Comment by Basti85i** [comment]
yes I do.

**Comment by simonbengtsson** [comment]
Hmm, I'll look into it. For now you can look at the source code for autoTableHtmlToJson and try to see what it parses the content to.

**Comment by Basti85i** [comment]
The last column contains checkboxes in each line. 
I'm calling res=pdf.autoTableHtmlToJson(...)
`pdf.autoTable(res.columns, res.data, {
			startY: 50,
			margin: {horizontal: 30},
			columnStyles: {0:{columnWidth: 90},1:{columnWidth: 120},2:{columnWidth: 90},3:{columnWidth: 60},4:{columnWidth: 180}},
			styles: {overflow: 'linebreak', font: 'arial', fontSize: 10, cellPadding: 8},    
			headerStyles: {fillColor: [0,81,150], valign: 'middle'}
		}); `
Ignoring the last column with the checkboxes that doesn't need to be printed. And it works fine How ever when I put a check box in the header ( to check/unchek all the boxes) it produces the error.
Thanks.
Yes I'll try to look in the source code.

**Comment by simonbengtsson** [comment]
Okey! Check the source of autoTableHtmlToJson and see if you can find where things are going wrong :thumbsup:

**Comment by Basti85i** [comment]
Hi, I've tested the jsPDF.autoTableHtmlToJson with a simple table that contains a checkbox in the last header column and I think it works as it's supposed to. The error must occur when loading the return values in the autoTable function, I guess. Maybe you can help with this? It's getting quite difficult here...

**Comment by simonbengtsson** [comment]
Can you post the content of the autoTableHtmlToJson return values?

**Comment by Basti85i** [comment]
I used the following table
![grafik](https://user-images.githubusercontent.com/31008713/30427003-698a6f58-994e-11e7-8b2c-f67dd6722d73.png)
and get:
![grafik](https://user-images.githubusercontent.com/31008713/30427169-119c3bc2-994f-11e7-9bc2-dca8937b0292.png)

For testing I also removed the includeHiddenElements. Could the error be related to that?

`<script>

function autoTableHtmlToJsonTest() {
    var tableElem = document.getElementById("tab");
	var columns = {}, rows = [];
    var header = tableElem.rows[0];
    for (var i = 0; i < header.cells.length; i++) {
        var cell = header.cells[i];
        var style = window.getComputedStyle(cell);
        if (style.display !== 'none') {
            columns[i] = cell;
        }
    }
    var _loop_1 = function (i) {
        var tableRow = tableElem.rows[i];
        var style = window.getComputedStyle(tableRow);
        if (style.display !== 'none') {
            var rowData_1 = [];
            Object.keys(columns).forEach(function (key) {
                var cell = tableRow.cells[key];
                rowData_1.push(cell);
            });
            rows.push(rowData_1);
        }
    };
    for (var i = 1; i < tableElem.rows.length; i++) {
        _loop_1(i);
    }
    var values = Object.keys(columns).map(function (key) { return columns[key]; });
    //return { columns: values, rows: rows, data: rows };
	console.log("values: " + values);
	console.log("rows: " + rows);
};
</script>`

**Comment by Basti85i** [comment]
When I output pdf.autoTableHtmlToJson(document.getElementById('variables')); in my actual table I get:
![grafik](https://user-images.githubusercontent.com/31008713/30427742-3743e670-9951-11e7-98fa-659878f95db7.png)
where the header array contains:
![grafik](https://user-images.githubusercontent.com/31008713/30427792-716a82dc-9951-11e7-8dfa-29b61c3e6034.png)
Checkbox being in the last array element.
Would it be of any help to see the full attribute list in columns[5]?

**Comment by Basti85i** [comment]
It works now after I put a sixth column in the 'autoTable' 'columnStyles' property with a minimum columnWidth of 15. Anything below that will again cause the error.

**Comment by michaeli1** [comment]
Is there any way that I can render checkboxes using autotable?
