### ISSUE TITLE
Wrap / continue table in the same page

### ISSUE THREAD

**Issue by dskc** [simonbengtsson/jsPDF-AutoTable#287]
Will it be possible to continue the table, instead of page breaking, when there is space available on to the right of the table?

**Comment by simonbengtsson** [comment]
Like columns?

**Comment by dskc** [comment]
Yes.. like the below
<img width="354" alt="mul" src="https://user-images.githubusercontent.com/1244769/30537716-77f628ce-9c88-11e7-8298-33f9be613f8b.png">

**Comment by simonbengtsson** [comment]
#307

**Comment by mmghv** [comment]
Check solution [here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/626#issuecomment-609114274).
