### ISSUE TITLE
add border-radius to table 

### ISSUE THREAD

**Issue by marcosguti** [simonbengtsson/jsPDF-AutoTable#288]
it's posible add border radius in table like css?

**Comment by simonbengtsson** [comment]
Unfortunately no. Can't come up with a good way to do it either right now. Let me know if you find one!

**Comment by marcosguti** [comment]
thanks

**Comment by simonbengtsson** [comment]
Unless someone has a good idea how to accomplish this I think this has to be a wontfix.

**Comment by emaalouf** [comment]
Was this ever solved?

**Comment by ddpervez** [comment]
I'm getting the same problem.

**Comment by aryang23titan** [comment]
Getting the same Problem, anyone got this solved?

**Comment by aryang23** [comment]
Getting same problem, Anyone solved this?
