### ISSUE TITLE
Cell height not expanding to fit long text content!

### ISSUE THREAD

**Issue by emiljaeger** [simonbengtsson/jsPDF-AutoTable#289]
This might be an easy fix, perhaps someone can point me in the right direction? This is the code for the autotable. As you can see on the image, its not linebreaking nor fitting the text inside the cell. What could be the issue here? Thanks                           

>   doc.autoTable(columner, uppföljningRows, {
>                                 startY: cursorY,
>                                 margin: { horizontal: this.margin - 15,
>                                 bottom: 30 },
>                                 styles: { overflow: 'linebreak',
>                                  },
> 
>                                 columnStyles: { 
>                                     0: { columnWidth: 77 },
>                                     1: {columnWidth: 25},
>                                     2: {columnWidth: 25},
>                                     3: {columnWidth: 25},
>                                     4: {columnWidth: 45},
>                                 
>                                  },
>                                 theme: 'grid',
>                                 alternateRowStyles: {
>                                     fillColor: [0xe2, 0xe2, 0xe2]
>                                 },
>                             });

![problems](https://user-images.githubusercontent.com/32292393/30849118-9351d5a4-a2a1-11e7-9ecf-f964d0255004.png)

**Comment by simonbengtsson** [comment]
Probably fixed in v3!
