### ISSUE TITLE
How to set cell border createdCell?

### ISSUE THREAD

**Issue by aamirabbas765** [simonbengtsson/jsPDF-AutoTable#290]
createdCell: function (cell, data) {
                debugger;
                if (data.row.cells[0].text[0] === 'Total') {
                    cell.styles.fontStyle = 'bold';
                    $.each(data.row.raw, function (index, row) {
//I want to set cell border here
                        
                    });
                }
            },

**Comment by simonbengtsson** [comment]
Please post questions about how to use the plugin on stackoverflow with the `jspdf` and `jspdf-autotable` tags.
