### ISSUE TITLE
How to set font size or line break for doc.text()???

### ISSUE THREAD

**Issue by aamirabbas765** [simonbengtsson/jsPDF-AutoTable#291]
If you have a question of how to use this plugin, please post on StackOverflow with the tags jspdf and jspdf-autotable.

If you have found a bug, try to describe it in a way that makes it possible to reproduce. Code is always helpful, and live code even more so. Here is a [codepen](http://codepen.io/someatoms/pen/EjwPEb) with `jspdf` and `jspdf-autotable` included that you can fork.

**Comment by simonbengtsson** [comment]
Please post questions about how to use the plugin on stackoverflow with the `jspdf` and `jspdf-autotable` tags.
