### ISSUE TITLE
Can AutoTable Make Table Like This?

### ISSUE THREAD

**Issue by alfradias** [simonbengtsson/jsPDF-AutoTable#292]
I'm new in jspdf and AutoTable. I was search about colspan and rowspan but i can't implement what i want.
I want make table like this is this possible?
 
![image](https://user-images.githubusercontent.com/20962620/31870343-a6441956-b7d7-11e7-907b-1362383d0a75.png)

**Comment by simonbengtsson** [comment]
Since colspans are not supported natively in v2 (coming in v3) I would use pdfkit for such complex tables for now.
