### ISSUE TITLE
how can I make the first row have no columns

### ISSUE THREAD

**Issue by CarlosOrozc** [simonbengtsson/jsPDF-AutoTable#293]
the problem I have is that I can make the first row have no columns and that you can enter a paragraph.

> var column5 = ["","","","","", ""]
   var row5 = [
         ["PERIODO DE LECTURA: 06/02/2017 al 07/03/2017 (29días) - PROXIMA LECTURA:07/04/2017"],
         ["Tipo de Consumo","No. Contador","Lectura Ant.","Lectura Act.","Mult.", "Consumo"]
   ] 

  

> var option5 = {
			theme: 'grid',
       		margin: {
		      top: 172,
		      left:45
		    },
		    bodyStyles: {
            	textColor: 0,
		        cellPadding: 0.5,
		        fontSize: 9,
		        lineColor: [0, 0, 0]
		 	},
        	tableWidth: 125,
		    drawHeaderRow: function(row, data) {
      			return false;
  			}
		}

![captura2](https://user-images.githubusercontent.com/8071575/31971325-893f4162-b8d8-11e7-90fb-253d7ed59b05.PNG)

**Comment by simonbengtsson** [comment]
What you want is column span which is not yet supported but will be in v3.
