### ISSUE TITLE
Unable to use requirejs example in IE 11.1770

### ISSUE THREAD

**Issue by svankamamidi** [simonbengtsson/jsPDF-AutoTable#295]
I was unable to use provided requirejs example in IE 11 (getting below error), it was working fine in chrome. I could use in IE by adding shim entries, but after adding shim entries it stopped consistently working in chrome, but works fine in IE. Can you please suggest one approach to make it work for both IE and Chrome.

Error: 
SCRIPT438: Object doesn't support property or method 'autoTable'

jsPDF object is not detecting autotable methods :(

**Comment by simonbengtsson** [comment]
Thanks for posting! I'll take a look later

**Comment by simonbengtsson** [comment]
Works for me. Can you provide your config and post a new issue?
