### ISSUE TITLE
 Property 'autoTable' does not exist on type jsPDF

### ISSUE THREAD

**Issue by tbiinfotech** [simonbengtsson/jsPDF-AutoTable#297]
I am using angular2 and Node JS. I have installed jspdf and jspdf-autotable both modules using npm.
and in .angular-cli.json file , I have embedded the scripts:
```
"scripts": [ 
        "../node_modules/jspdf/dist/jspdf.min.js",
        "../node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js"
      ],
```

In my component.ts file , I have imported these files as follows:
```
import * as jsPDF from 'jspdf';
import * as autoTable from 'jspdf-autotable';
```

In function of component.ts file I am using sample code as follows:

```
var columns = ["ID", "Country", "Rank", "Capital"];
        var data = [
            [1, "Denmark", 7.526, "Copenhagen"],
            [2, "Switzerland", 	7.509, "Bern"],
            [3, "Iceland", 7.501, "Reykjavík"],
            [4, "Norway", 7.498, "Oslo"],
            [5, "Finland", 7.413, "Helsinki"]
        ];
        var doc = new jsPDF();
        doc.autoTable(columns, data);
        doc.output("dataurlnewwindow");
```

But now when I run the node command to start app then during compilation I am getting error as 
**Property 'autoTable' does not exist on type 'jsPDF'.**

I have console the doc object and found autoTable exists there but don't know why it is creating error?

![image](https://user-images.githubusercontent.com/17080270/32935801-ac0bf722-cb97-11e7-97f4-04a6f891c7a6.png)

Can any one please suggest?

**Comment by simonbengtsson** [comment]
Try replacing `import * as autoTable from 'jspdf-autotable';` with `import 'jspdf-autotable'`

**Comment by tbiinfotech** [comment]
It is working now. actually I was importing both jspdf and jspdf-autotable, that is why it was creating issue.
I am using autoTableHtmlToJson() now, Can we fetch color like addHTML() in this method. actually I wants to show the colors in pdf like 

![image](https://user-images.githubusercontent.com/17080270/32953127-4a09347a-cbd5-11e7-998c-3a7780bcf717.png)

But I am getting only text as 

![image](https://user-images.githubusercontent.com/17080270/32953149-5fc3fad4-cbd5-11e7-8789-d142ed09b1fa.png)

**Comment by grtn316** [comment]
I am having this same problem however, I am using angular 4.3.5 & webpack. 

When using: 

`import * as jsPDF from 'jspdf';
import 'jspdf-autotable'`

I still get the error: Property 'autoTable' does not exist on type jsPDF

Any ideas how to get this functioning?

**Comment by MarcoBatista** [comment]
I have the same issue with Angular 5 & Webpack.

**Comment by bbluszcz** [comment]
same here, any possible update on this issue soon ?

**Comment by alciomarhollanda** [comment]
Same problem here, i'm use 1.1.31

**Comment by pranjal-card** [comment]
Any update on this facing same with angular 5 and webpack and "jspdf": "^1.4.1",
    "jspdf-autotable": "^2.3.5"

**Comment by bessam-haj-salem** [comment]
I have the same issue with Angular 10

**Comment by ashgrey91** [comment]
For angular, you can use,
autoTable(doc, { html: '#html-table-id',startY: 30, });

but I am not sure how to get the lastAutoTable.finalY position.

**Comment by johnEthicalTechnology** [comment]
> instead of doc.autoTable,
> For angular, you can use,
> autoTable(doc, { html: '#html-table-id',startY: 30, });
> 
> "
> You can also use the exported autoTable method. This works better with typescript and alternative jsPDF versions.
> 
> import jsPDF from 'jspdf'
> // import jsPDF = require('jspdf') // // typescript without esModuleInterop flag
> // import jsPDF from 'yworks-pdf' // using yworks fork
> // import jsPDF from 'jspdf/dist/jspdf.node.debug' // for nodejs
> import autoTable from 'jspdf-autotable'
> 
> const doc = new jsPDF()
> autoTable(doc, { html: '#my-table' })
> doc.save('table.pdf')
> "
> The above is from the link
> https://github.com/simonbengtsson/jsPDF-AutoTable#installation
> 
> but I am not sure how to get the lastAutoTable.finalY position in typescript.

@ashgrey91 you can just convert `doc` to an `any` type like so `(doc as any).lastAutoTable`. Not ideal, but it'll get it working.

**Comment by builtbylane** [comment]
assuming you have `@types/jspdf` installed... 

```typescript
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { UserOptions } from 'jspdf-autotable';

interface jsPDFCustom extends jsPDF {
    autoTable: (options: UserOptions) => void;
}

const doc = new jsPDF() as jsPDFCustom;```
