### ISSUE TITLE
jspdf-autotable.: Is it possible tot create colspan(Group header) with json data ? 

### ISSUE THREAD

**Issue by vikasnawal** [simonbengtsson/jsPDF-AutoTable#298]
Hi , 

I wanted to export a PDF using json data with colspan(Group header). 
I am using the below code to generate the PDF. 
MY question is there any option to pass the info of group header like 

![image](https://user-images.githubusercontent.com/1164705/32937301-f092d504-cb9d-11e7-89d9-dfb91f6fccf8.png)

var columns = [
    {title: "ID", dataKey: "id"},
    {title: "Name", dataKey: "name"}, 
    {title: "Country", dataKey: "country"}, 
    ...
];
var rows = [
    {"id": 1, "name": "Shaw", "country": "Tanzania", ...},
    {"id": 2, "name": "Nelson", "country": "Kazakhstan", ...},
    {"id": 3, "name": "Garcia", "country": "Madagascar", ...},
    ...
];

// Only pt supported (not mm or in)
var doc = new jsPDF('p', 'pt');
doc.autoTable(columns, rows, {
    styles: {fillColor: [100, 255, 255]},
    columnStyles: {
    	id: {fillColor: 255}
    },
    margin: {top: 60},
    addPageContent: function(data) {
    	doc.text("Header", 40, 30);
    }
});
doc.save('table.pdf');

**Comment by simonbengtsson** [comment]
You can make that work with a lot of work in version 2 (check the colspan and rowspan example). Will be a lot easier in version 3. No timeline for release though.

**Comment by Oumaimaabiadh** [comment]
same problem
