### ISSUE TITLE
Rendering HTML

### ISSUE THREAD

**Issue by ertz92** [simonbengtsson/jsPDF-AutoTable#300]
there are html tags in my table for formatting - ie: <ul><li>Test</li><li>My</li><li>Name</li></ul>

Currently it displays as < ul>< li> tags on the pdf
Is there a way to display the tags as the bullet points?

Thanks!

**Comment by simonbengtsson** [comment]
Unfortunately no. You could use the hooks and parse the html yourself for each cell however.

**Comment by ertz92** [comment]
ok - thanks!

**Comment by 8ctopotamus** [comment]
Is there anywhere to find an example?
