### ISSUE TITLE
how to make a dynamic loop autotable

### ISSUE THREAD

**Issue by bgomes90** [simonbengtsson/jsPDF-AutoTable#301]
Hello, im trying to do a dynamic loop, to export in pdf.. but it export only the last table... what i am doing wrong?
.alert is the father div of each table

```js
$("#btn-pdf").click(function () {
                    var doc = new jsPDF('landscape', 'pt', 'a4');
                    doc.cellInitialize();
                    var res;
                    $.each($('#resumo_pedido .alert'), function(i, alert){
                        $.each($(alert).find('table'), function (j, table){
                            var elem = table;
                            res = doc.autoTableHtmlToJson(elem);
                            doc.autoTable(res.columns, res.data, {pageBreak: 'always'}, i);
                        });
                    });
                   
                    var header = function(data) {
                        doc.setFontSize(14);
                        doc.setTextColor(40);
                        doc.setFontStyle('normal');
                        doc.text("Testing Report", data.settings.margin.left, 50);
                    };

                    var options = {
                        addPageContent: header,
                        margin: {
                            top: 80
                        },
                        startY: doc.autoTableEndPosY() + 20,
                        pageBreak: 'always'
                    };
                   	doc.autoTable(res.columns, res.data, options);	
                    
                    doc.save("table.pdf");
                });
```

thanks!

**Comment by bgomes90** [comment]
whit this, show only tha last table too
`var tables = $('#resumo_pedido .table');
                    for (i = 0; i < tables.length; i++) { 
                        var res = doc.autoTableHtmlToJson(tables[i]);
                        doc.autoTable(res.columns, res.data, {pageBreak: 'always'});
                    }`

**Comment by bgomes90** [comment]
please close this issue.
i got it.
thanks

**Comment by simonbengtsson** [comment]
Good to hear!

**Comment by brahimkra** [comment]
@simonbengtsson  i have a proble in displaying autotable , i would like this display :
![imp1](https://user-images.githubusercontent.com/14215952/36339649-df41b430-13ca-11e8-8b9f-918cf9bbd471.png)
But i have this display:
![imp2](https://user-images.githubusercontent.com/14215952/36339680-47cfa778-13cb-11e8-913d-ba598d686f7e.png) and this is my code:
 var res5 = doc.autoTableHtmlToJson(document.getElementById("table12"));
  doc.autoTable(res5.columns, res5.data, {
      styles: {
        lineWidth: 1,
        fillColor: [245, 245, 245],
        textColor: [77, 75, 76],
        fontStyle: 'bold',
        headerStyles: {
          cellPadding: 20,
          lineWidth: 0.2,
          valign: 'top',
          fontStyle: 'normal',
          fontSize: 4

        }
      },
      columnStyles: {
        lineWidth: 1,
        // etc
      },
      alternateRowStyles: {
        textColor: [0, 0, 0],
        fillColor: [255, 255, 255],
        fontStyle: 'normal',
        fontSize: 9,
      },

      overflow: 'linebreak',
      startY:finalY + 10,

    });

And this is my HTML code:
         <table *ngFor="let x of currentProject.training.content.CourseSections" id="table12"  align="right" class="table table-bordered size-table">
            <thead>
            <tr>
              <td>{{x.SectionTitle}}</td>
            </tr>
            </thead>
            <tbody>
            <tr  *ngFor="let y of x.Units">
              <td>{{y.UnitTitle}}</td>
            </tr>
            </tbody>
          </table>

**Comment by srallapalli** [comment]
> Good to hear!
Hi,
I want to know how to add dynamic header text for each auto table which is dynamically generated..Please help me on this..Each page in pdf can have multiple tables  

Thanks is advance
