### ISSUE TITLE
Colspan and rowspan update

### ISSUE THREAD

**Issue by Zulfitza** [simonbengtsson/jsPDF-AutoTable#302]
Does the recent release support colspan and rowspan?

**Comment by simonbengtsson** [comment]
Yes, but it's an alpha which is barely tested and the documentation is lacking and not up to date. The examples should all work though.

**Comment by Zulfitza** [comment]
I still don't know why this isn't working. I included the recent js file "jspdf.plugin.autotable.js" into angular-cli.json. The function that generates the table:

 exportActionPDF() {
        var doc = new jsPDF('p', 'pt', 'a2');

        var res = doc.autoTableHtmlToJson(document.getElementById("table_wrapper"));
        // doc.autoTable(res.columns, res.data, {margin: {top: 80}});

        var header = function(data) {
            doc.setFontSize(18);
            doc.setTextColor(40);
            doc.setFontStyle('normal');
            // doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 20, 50, 50);
            doc.text("Management risc", data.settings.margin.left, 50);
        };

        var options = {
            addPageContent: header,
            margin: {
                top: 80
            },
            startY: doc.autoTableEndPosY() + 20
        };

        doc.autoTable(res.columns, res.data);

        doc.save("ManagementRisc.pdf");
    }

The table look like this:
![capture2](https://user-images.githubusercontent.com/28774845/33130753-0ac6793c-cf9d-11e7-8ef6-dac1b9384428.PNG)



And the resultet PDF: 
![capture](https://user-images.githubusercontent.com/28774845/33130765-11058a68-cf9d-11e7-8648-6dfc2c334f48.PNG)

**Comment by simonbengtsson** [comment]
The api of v3 is changed to: 
```js
doc.autoTable({
     html: '#table_wrapper',
     // ...
});
```

Check the colspan and rowspan example or the html example in the v3 branch. Note that the dist files are still v2 at this stage even in the v3 branch. You can either build files yourself or install v3 through npm.

**Comment by Zulfitza** [comment]
I simply tried to use your examples.span function:

exportActionPDF() {

        var doc = new jsPDF('p', 'pt', 'ax');
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.setFontStyle('bold');

        let body = this.bodyRows();
        let head = this.headRows();

        doc.autoTable({
            startY: 60,
            head: head,
            body: body,
            theme: 'grid'
        });

        doc.save("ManagementRisc.pdf");
    }

And i get this error :
![image](https://user-images.githubusercontent.com/28774845/33208793-a5a3a676-d11b-11e7-897e-7f32bcc2f318.png)

**Comment by simonbengtsson** [comment]
The first errors states that the data is undefined. Could you check that?

**Comment by Zulfitza** [comment]
I think i'm using the wrong version of autoTable function. When i use it like this doc.autoTable(head, body) it doesn't crush. But when i use it like you said doc.autoTable({ html: '#table_wrapper'}) i get the error above.

**Comment by simonbengtsson** [comment]
What is the value of your variables body and head?

**Comment by Zulfitza** [comment]
bodyRows() {
    let body = [];
    for (let obj of this.fullList) {
        body.push({
            cui: obj.cui,
            denumire: obj.denumire,
            judet: obj.judet,
            inspectorat: obj.inspectorat,
        });
    }
    return body;
}

    headRows() {
        return [{cui: 'CUI', denumire: 'Denumire', judet: 'Judet', it: 'IT'}];
    }

**Comment by simonbengtsson** [comment]
Try with something simpler, like: 

`let head = [['Hey', 'Hey2', 'Hey3']];
`let body = [['Hey', 'Hey2', 'Hey3'], ['Hey', 'Hey2', 'Hey3']];

**Comment by Zulfitza** [comment]
Now my function looks like this:

 exportActionPDF() {
        let head = [['Hey', 'Hey2', 'Hey3']];
        let body = [['Hey', 'Hey2', 'Hey3'], ['Hey', 'Hey2', 'Hey3']];
        var doc = new jsPDF('p', 'pt', 'a2');
        doc.autoTable({head: head, body: body});
        // doc.autoTable({html: '#table', startY: 100});
        doc.save("ManagementRisc.pdf");
    }
Same error though.

**Comment by simonbengtsson** [comment]
Hmm, strange. I'll take a look this weekend and see if I can sort something out.

**Comment by iamtusharz** [comment]
Hi,
Is this solved.. I am also getting 
The data should be an object or array, is: undefined

when using doc.autoTable({ html: '#table_wrapper'})

**Comment by Genuris** [comment]
Hi,
Wiil you @iamtusharz write more info?
My example code:

`
doc.autoTable({
    	html: '#table_wrapper'
    });
`
![example2](https://user-images.githubusercontent.com/5873648/34358720-e68f1668-ea5a-11e7-979d-29c4ab95677f.jpg)
and I have error

**Comment by a1292717155** [comment]
@Zulfitza  Hello ,  i  clone the code and checkout the version in v3 , but the demo doesn't work.  Did you solve it?
![33208793-a5a3a676-d11b-11e7-897e-7f32bcc2f318](https://user-images.githubusercontent.com/19824463/38726643-0512a37a-3f0b-11e8-80ba-0238f1fdaea5.png)

**Comment by iamtusharz** [comment]
No I was not able to solve it. I used image of the table and embedded it in
the pdf instead.





Best Regards,
Tushar Agarwal

**Comment by arfanHA** [comment]
I have a table view that looks like this
![image](https://user-images.githubusercontent.com/45265088/77149046-58405700-6ac3-11ea-81f0-529a332a634d.png)

but how can I separate my array object with rowspan to look like this

![image](https://user-images.githubusercontent.com/45265088/77148743-bc165000-6ac2-11ea-843c-f029983bc6f1.png)

I was confused in placing 'rowspan, while what I was calling was only the body
` ((f as any).autoTable as AutoTable)({
            head: head,
            body: body,
            theme: "plain",
            startY: currentTextY + 30,
            // @ts-ignore
            margin: {horizontal: 10},
            // tableWidth: 100,
            headStyles: {fontSize: 12, fontStyle: "normal"},
            bodyStyles: {fontStyle: "bold"},
            // @ts-ignore
            styles: {
              lineWidth: 0.01,
              lineColor: 0,
              fillStyle: 'DF',
              // @ts-ignore
              textColor: text,
              fontSize: 12,
              font: 'helvetica',
              // @ts-ignore
              fillColor: background,
              halign: "center",
              overflow: "linebreak",
              cellWidth: "wrap"
            }
          });`

and the body was from this function
`bodyRows(data) {
    let dataLength = 0;
    let jumlah = [];
    let body = [];
    for (let i = 0; i < data.length; i++) {
      for(let j=0;j < data[i].batch.length; j ++){
        // jumlah.push(data[i].batch[j].jumlah);
        jumlah = [...jumlah, data[i].batch[j].jumlah ];
      }
        body.push({
          id: i + 1,
          namaKain: data[i].namaKain,
          jumlah: jumlah
        });
    }
    return body
  }`
