### ISSUE TITLE
Error with customfont plugin

### ISSUE THREAD

**Issue by TianDaGe** [simonbengtsson/jsPDF-AutoTable#303]
https://github.com/sphilee/jsPDF-CustomFonts-support/issues/14

**Comment by TianDaGe** [comment]
Is there any developer who fixed this issue?

**Comment by simonbengtsson** [comment]
Nope, not yet. If you find a fix, I would happily merge it!

**Comment by alkincakiralar1996** [comment]
any solution?

**Comment by simonbengtsson** [comment]
With jspdf 1.4 release this should be fixed. If not please submit a new issue!

**Comment by Shakil1081** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/13831857/56984129-22426d80-6ba7-11e9-847b-8e42ec830a1e.png)

I am using Bangla font  But it's not working with proper word check the image  

`var doc = new jsPDF();

doc.addFileToVFS('kalpurush.ttf','AAEAAAA......');

doc.addFont('kalpurush.ttf', 'custom', 'normal');

doc.setFont('custom');
doc.text(15, 15, 'পুঁজিবাজার নিয়ে শঙ্কিত হওয়ার কিছু নেই: প্রধানমন্ত্`
