### ISSUE TITLE
header text goes beyond the end of the page

### ISSUE THREAD

**Issue by bgomes90** [simonbengtsson/jsPDF-AutoTable#304]
Hello! 
I have an textarea called "Observation", maxlength = 255.
but when it goes from 170, it does not appear on the page ...
What i need to do?
![print](https://user-images.githubusercontent.com/13823899/33279038-5bc453b4-d384-11e7-826e-c77c7abfffc7.png)
Thanks!

**Comment by simonbengtsson** [comment]
Issue does not match the issue template. Feel free to re-submit another issue with more info if you are still having issues.
