### ISSUE TITLE
Unable to get the attribute from table row.

### ISSUE THREAD

**Issue by milacay** [simonbengtsson/jsPDF-AutoTable#309]
I've posted on StackOverFlow for a while and did not receive any responses.  I am kind of new with the jsPDF-AutoTable, but I really like your plug-in -- very useful.   Basically, I tried to identify a specific attribute with some rows and change its background-color (`doc.setFillColor(200, 200, 255)`).  I've done a lot googling/reading and seems drawCell and the way to go, so I was to read the cell.text, but no luck with element attributes.  I also tried cell.raw, but it return as `[object HTMLTableCellElement]`.  If I could at least attract the HTML text like `<td class="Category" colspan="2">Project on PC hardwares</td>`, I can try to figure out how to get specific string in the HTML text.  Please advise. 

Here is the link I posted:
https://stackoverflow.com/questions/47891874/jspdf-autotable-get-the-attribute-of-a-table-row

**Comment by simonbengtsson** [comment]
You should be able to access the html element by doing `cell.text` in the hooks 👍
