### ISSUE TITLE
Dynamic footer to be added to bottom of last page of PDF file being generated

### ISSUE THREAD

**Issue by Chrisjvn** [simonbengtsson/jsPDF-AutoTable#312]
Hello, 

Please assist, it is quite urgent to get this complete.

I am using jspdf and jspdf.plugin.autoTable.js to create pdf files from data being inputted on the html page and i would like to add a sign off section at the bottom of the very last page of the pdf file. 

I have added: 
 let finalY = pdf.autoTable.previous.finalY; // The y position on the page
//  sign off section  
    pdf.text(15, finalY + 300, "Acceptance of quotation by:");
    pdf.text(15, finalY + 335, "Signature");
    pdf.text(207, finalY + 335, "   Name");
    pdf.text(415, finalY + 335, "   Date");
   

The problem with this is that it adds the content 300 and more after the last row of the table. I would like it to be right at the very bottom of the last page. 

What would be the best way to do this? T.I.A

**Comment by Chrisjvn** [comment]
@simonbengtsson please assist

**Comment by zioictus** [comment]
Hi, I had the same problem and I solved this way:
`
let calcHeight = ( heightOfTheHeader + ( heightOfSingleRow * ( numberOfRows % maxNumberOfRowInOnePage ) ) );
 doc.text(x-position, calcHeight , 'Your text here');`

**Comment by simonbengtsson** [comment]
Hi! Stackoverflow is now the preferred forum for questions about how to use this plugin. Please include the `jspdf` and `jspdf-autotable` tags when posting so it is easier to find the question.

**Comment by RajarshiSaha1985** [comment]
Hi how to add a autoTable as footer in each page?? Thanks in advance.

**Comment by kmsharjas** [comment]
@Chrisjvn Did you get the solution?
