### ISSUE TITLE
doc.autoPrint() not working please help

### ISSUE THREAD

**Issue by thilankascentic** [simonbengtsson/jsPDF-AutoTable#313]
Hi Im having an issue with doc.autoPrint(),
could anyone know any way to show the document in print preview ?

**Comment by hahnch** [comment]
I have the same problem.
Did you found a solution?
Thanks in advance.

**Comment by thilankascentic** [comment]
Hi @hahnch,

I used this

 `window.open(doc.output('bloburl'), '_blank');`

**Comment by hahnch** [comment]
ok thx

**Comment by Miguel-At** [comment]
si deseas que al cargar la nueva pestaña aparezcan la herramientas para imprimir 
window.open(pdf.output('bloburl'), '_blank').print();
