### ISSUE TITLE
linebreak not working as expected

### ISSUE THREAD

**Issue by sa1509** [simonbengtsson/jsPDF-AutoTable#316]
I'm having issues with the column headers text and the row text breaking incorrectly in the middle of the word (see attached). In the attachment I would expect the "long text column" to be more squeezed which will increase the width of other columns and also increase the height of the rows. The code I'm using is:
public exportToPDF(reportName: string, cols: any, rows: any) {
        var doc = new jsPDF('landscape');        
        doc.text(15, 40, "Report");
        var options = {            
            margin: { horizontal: 5 },
            bodyStyles: { valign: 'top' },
            styles: { overflow: 'linebreak', overflowColumns: false },
            headerStyles: {
                fillColor: [51, 122, 183],
                textColor: [255],
                halign: 'center',
                text: { minCellWidth: 'wrap' }
            },            
            theme: 'grid'
        };
        doc.autoTable(cols, rows, options);
        doc.save('Report.pdf');
    }
Thanks for your help.
![autotable](https://user-images.githubusercontent.com/31284589/35260679-dbefecd4-0060-11e8-8712-47fbdbebcc2f.PNG)

**Comment by desforets** [comment]
not sure if this might help you but I found this hook helpful. I wasn't having same issue as you but maybe an explicit height to the rows will resize things more sanely.
the drawCell hook might allow you to also do something to the width, maybe set a min width for your earlier columns there

```
drawRow: function (row, data) {
      row.height = 80
    }
```

**Comment by GauntStrelok** [comment]
I have found a reason for this, for strange as it may sound:

```javascript

var data = [{
	"nord": "1",
	"estacionTransformadora": "E.T. Resistencia",
	"equipo": "1DL10",
	"kv": "132",
	"salida": "03/09/2013 08:10",
	"entrada": [""],
	"tipoIndisp": ["P"],
	"autorizCAMMESA": ["S"],
	"horaInfCAMMESA": ["08:10"],
	"text": "Ut sunt nesciunt et labore pariatur minima vel molestias fugit quia quo culpa voluptas sed expedita consequatur dolores aut aut",
        "motivo": "Ut sunt nesciunt et labore pariatur minima vel molestias fugit quia quo culpa voluptas sed expedita consequatur dolores aut aut"
}, {
	"nord": "2",
	"estacionTransformadora": "E.T. Recreo",
	"equipo": "1DL09",
	"kv": "132",
	"salida": "07/03/2017 07:11",
	"entrada": ["07/03/2017 07:18"],
	"tipoIndisp": ["F"],
	"autorizCAMMESA": ["N"],
	"horaInfCAMMESA": ["07:11"],
	"text": "Ut sunt nesciunt et labore pariatur minima vel molestias fugit quia quo culpa voluptas sed expedita consequatur dolores aut aut",
	"motivo": "Ut sunt nesciunt et labore pariatur minima vel molestias fugit quia quo culpa voluptas sed expedita consequatur dolores aut aut"
}];

var colLongs = [{
  "title": "N°\nOrden",
  "dataKey": "nord"
}, {
  "title": "Estacion\nTransformadora",
  "dataKey": "estacionTransformadora"
}, {
  "title": "Equipo",
  "dataKey": "equipo"
}, {
  "title": "K.V.",
  "dataKey": "kv"
}, {
  "title": "Salida",
  "dataKey": "salida"
}, {
  "title": "Entrada",
  "dataKey": "entrada"
}, {
  "title": "Tipo\nIndisp.",
  "dataKey": "tipoIndisp"
}, {
  "title": "Autoriz.\nCAMMESA",
  "dataKey": "autorizCAMMESA"
}, {
  "title": "Hora Inf.\nCAMMESA",
  "dataKey": "horaInfCAMMESA"
}, {
  "title": "Motivo de la Insdisponibilidad",
  "dataKey": "motivo"
}];

doc.autoTable(colLongs, data, {
	startY: 25,
	margin: {
		horizontal: 7
	},
	bodyStyles: {
		valign: 'top'
	},
	styles: {
		overflow: 'linebreak',
		columnWidth: 'wrap',
		tableWidth: 300
	},
	columnStyles: {
		text: {
			columnWidth: 'auto'
		}
	}
});
```

that produces a table that goes off bounds, and have some problems creating the columns, if you change the last column dataKey to "text" it will create the table correctly(yes, i know it sounds crazy)

**Comment by simonbengtsson** [comment]
Should work in v3!

**Comment by pbrandone** [comment]
@simonbengtsson first of all, thanks a lot for the great work, this truly is a great plugin for jspdf.

I'm having a similar problem with the latest release where it's breaking line in the middle of words despite having spaces in other columns to avoid it

<img width="734" alt="Screenshot 2019-06-19 at 09 27 18" src="https://user-images.githubusercontent.com/5202712/59749182-7e0aa800-9274-11e9-8c52-b737f8e3b8ba.png">

Do you have any idea on why this might be happening?

**Comment by mmghv** [comment]
check solution here #568
