### ISSUE TITLE
Add color to table data(td)

### ISSUE THREAD

**Issue by manosymbian1** [simonbengtsson/jsPDF-AutoTable#317]
I`m trying to add color to td, I have tried with inline and external CSS. Is there a way, so that I can add color to particular td alone. Kindly help..

function saveasPdf2()
            {
                var pdfName = "customHTML";
                var doc = new jsPDF('p', 'pt', 'letter');
                var res = doc.autoTableHtmlToJson(document.getElementById("pdfFormTbl"));
                console.log(res);
                var a= [];
                doc.autoTable(res.columns, res.data, {margin: {top: 80}});
                
                var header = function(data) {
                    doc.setFontSize(18);
                    doc.setTextColor(40);
                    doc.setFontStyle('normal');
                    //doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 20, 50, 50);
                    doc.text("Testing Report", data.settings.margin.left, 50);
                  };

                  var options = {
                    beforePageContent: header,
                    margin: {
                      top: 80
                    },
                    startY: doc.autoTableEndPosY() + 20
                  };

                  //doc.autoTable(res.columns, res.data, options);
                
              
                cordovaUtils.createFile(doc.output('blob'), 'hello.pdf',function() {
                    setTimeout(function(){
                        if($NGIsMobilePlatform){
                            spinner.hideSpinner();
                            readPdf.readPdffunc(pdfName+'.pdf',function(){                            
                            },function(){
                            });
                        }
                        else {
                            //pdf.open(pdfName+'.pdf');
                        }
                       
                    },1000);
                   
                });
                
                bootbox.alert("PDF Successfully downloaded");
                $("#pdfForm").addClass("hidden");	
}

This is my code

**Comment by simonbengtsson** [comment]
The plugin does not parse css at this point, but you can style the table manually 👍
