### ISSUE TITLE
table data in column is splitting 

### ISSUE THREAD

**Issue by vijaynagarsoge7** [simonbengtsson/jsPDF-AutoTable#319]
Hello,My name is vijay . I'm using your component and it's great.
Iam having issue while data inside column is large the text in that last line splits.
can you please help me
this is my code.
`function GeneratePDF(){
			var doc = new jsPDF();
            doc.addFont(fontname, fontname, fontstyle);
            doc.setFont(fontname);
            var totalPagesExp = "{total_pages_count_string}";
           
				var pageContent = function (data) {
                doc.setFontSize(fontsize);
                doc.setTextColor(40);
                doc.setFontStyle(fontstyle);
                var headerTitle = "Report For " + projectname;
                doc.text(headerTitle.toUpperCase(), HeaderTitleXAxis, HeaderTitleYAxis);
                doc.setFontSize(HeaderTitleFontSize);                
				 doc.text("Status Report For " + convertDate(new Date()), HeaderDateXAxis, HeaderDateYAxis);
                var rgbCode = hexToRgb(health);
                doc.setFillColor(rgbCode[0], rgbCode[1], rgbCode[2]);
                doc.rect(HeaderRectangleXAxis, HeaderRectangleYAxis, HeaderRectangleWidth, HeaderRectangleHeight, "F");
                
                doc.setLineWidth(lineWidth);
                doc.line(HeaderLineStartXAxis, HeaderLineYAxis, HeaderLineEndXAxis, HeaderLineYAxis);
                var str = "Page " + data.pageCount;
                if (typeof doc.putTotalPages === 'function') {
                    str = str + " of " + totalPagesExp;
                }
                doc.setFontSize(footerFontSize);
                doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
                doc.setLineWidth(lineWidth);
                doc.line(HeaderLineStartXAxis, doc.internal.pageSize.height - 15, HeaderLineEndXAxis, doc.internal.pageSize.height - 15);
                doc.text(FooterText, data.settings.margin.left + 75, doc.internal.pageSize.height - 10);
                doc.text(convertDate(new Date()), data.settings.margin.left + 165, doc.internal.pageSize.height - 10);
            };
           
            var elem = document.getElementById("basic-table");
            var res = doc.autoTableHtmlToJson(elem);
            doc.autoTable(res.columns, res.data, {
                addPageContent: pageContent,
                startY: StartingTableYAxis,
				 margin: { top: 20 },
                theme: 'plain',
                styles: { overflow: 'linebreak' },
                columnStyles: { 0: { columnWidth: FirstColumnWIDTH }, 1: { columnWidth: 'auto', halign: 'left' }, 2: { columnWidth: ThirdColumnWIDTH, halign: 'left' }, 3: { halign: 'left', columnWidth: FourthColumnWIDTH }, 4: { columnWidth: FifthColumnWIDTH } }
            });
            if (typeof doc.putTotalPages === 'function') {
                doc.putTotalPages(totalPagesExp);
            }
            doc.save('Risk Register ' + projectname + ' ' + convertDate(new Date()) + '.pdf');
			
		}
![risk table](https://user-images.githubusercontent.com/31764068/35379022-bf607086-01da-11e8-8c44-b51f1084ff0f.JPG)

**Comment by simonbengtsson** [comment]
Issue does not match the issue template. Feel free to re-submit another issue with more info if you are still having issues.
