### ISSUE TITLE
Can't override theme

### ISSUE THREAD

**Issue by zadraxx** [simonbengtsson/jsPDF-AutoTable#320]
Good afternoon, so far this is working great but running into a major issue:
I'm currently adjusting the grid theme and it won't let me add a border to the header.  I tried setting it in the hooks as well with no luck.

I'm able to adjust the size of the border shown below, but when it comes to adding specifically to the header, it causes a problem.

**Comment by simonbengtsson** [comment]
Hi! Stackoverflow is now the preferred forum for questions about how to use this plugin. Please include the `jspdf` and `jspdf-autotable` tags when posting so it is easier to find the question.
