### ISSUE TITLE
Align columns dinamically

### ISSUE THREAD

**Issue by thefacc92** [simonbengtsson/jsPDF-AutoTable#322]
Hi, 

I want to align my columns dinamically, if it's a number to the right and if it's text to the left.
I've been looking in the examples and documentation, but I cannot find an option that does a similar thing.

I also tried to do the following, but it's not working:

 var columns = ($('#tabla-'+tabla+' thead').find('th')).length;
		

		var text = "";
		var bmpDigits = /[0-9\u0660-\u0669\u06F0-\u06F9\u07C0-\u07C9\u0966-\u096F\u09E6-\u09EF\u0A66-\u0AE6\u0AE6-\u0AEF\u0B66-\u0B6F\u0BE6-\u0BEF\u0C66-\u0C6F\u0CE6-\u0CEF\u0D66-\u0D6F\u0DE6-\u0DEF\u0E50-\u0E59\u0ED0-\u0ED9\u0F20-\u0F29\u1040-\u1049\u1090-\u1099\u17E0-\u17E9\u1810-\u1819\u1946-\u194F\u19D0-\u19D9\u1A80-\u1A89\u1A90-\u1A99\u1B50-\u1B59\u1BB0-\u1BB9\u1C40-\u1C49\u1C50-\u1C59\uA620-\uA629\uA8D0-\uA8D9\uA900-\uA909\uA9D0-\uA9D9\uA9F0-\uA9F9\uAA50-\uAA59\uABF0-\uABF9\uFF10-\uFF19]/;
		var hasNumber = RegExp.prototype.test.bind(bmpDigits);
		var i = 1;
		
		for (i = 1; i <= columns; i++) { 
			text = $('#table tr:nth-child(1) td:nth-child('+i+')').text();
			if (hasNumber(text)){
				
				i=i-1;
				console.log(i+": RIGHT");
				doc.autoTableSetDefaults({
					columnStyles:{
						i: {halign:'right'}
					}
				});
			}else{
				
				i=i-1;
				console.log(i+": LEFT");
				doc.autoTableSetDefaults({
					columnStyles:{
						i: {halign:'left'}
					}
				});
			}
			i++;
		}

**Comment by simonbengtsson** [comment]
Please post questions about how to use the plugin on stackoverflow with the `jspdf` and `jspdf-autotable` tags.
