### ISSUE TITLE
doc.autoTable.previous is undefined

### ISSUE THREAD

**Issue by manosymbian1** [simonbengtsson/jsPDF-AutoTable#326]
doc.autoTable is not having an attribute "previous", so I couldn`t find the previous table and set alignment.

I have two tables it should be displayed one after other, I don`t the height of table since it is dynamic.

doc.autoTable(res.columns, res.data, {margin: {top: 80}});
let first = doc.autoTable.previous;
doc.autoTable(res1.columns, res1.data, {startY: first.finalY + 10});

The above code is working is codepen but this is giving issues in my project "doc.autoTable.previous;"

Kindly help..

**Comment by jwmann** [comment]
I had this problem as well.
This is how I fixed it.

```
doc.autoTable(columns, data, {
  startY: typeof doc.autoTable.previous.finalY === 'undefined' ? 80 : doc.autoTable.previous.finalY + 10,
  margin: {
    top: 80, // This number and the true value of startY above should match
    bottom: 15
  },
  ...
```
Just replace 80 with whatever margin you have on the top.

If you're like me and you want it to start any new table on its own page, this is how I did that:
```
startY: typeof doc.autoTable.previous.finalY === 'undefined' ? 80 : doc.autoTable.previous.finalY + ( doc.internal.pageSize.height - doc.autoTable.previous.finalY ),

```

Lemme know how it goes 👍

**Comment by manosymbian1** [comment]
Still I`m getting issue..
doc.autoTable.previous is a function, I`ve debugged working code from internet, but mine it has nothing like that. kindly help.

**Comment by manosymbian1** [comment]
my project already has jspdf.js and jspdf-autotable, when I`m trying to include jspdf.debug and jspdf-plugin-autotable, which is used in "https://codepen.io/anon/pen/XZjOJO" this page(I have done the modification on that page for multi table and it worked) it didn`t work.

I can`t replace those old files, since it product team code.

doc.autoTable.previous should have a function.
But in my code it has no function like that..
Suggest me other way to find end of previous table and start a new one..

**Comment by jwmann** [comment]
That example works because you're only defining the `let first = doc.autoTable.previous;` before second table but after the first one. Thus guaranteeing it will have a 'previous' table.

My example would work well in a `for` loop.
I'm not sure what else to say.

**Comment by simonbengtsson** [comment]
@manosymbian1 Can you provide the code you are using preferably as a runnable example on codepen?

**Comment by simonbengtsson** [comment]
@jwmann There is a built in option `pageBreak` to specify that each table should be on a new page 👍

**Comment by l3mu31** [comment]
let finalY = doc.autoTable.previous.finalY + 10;
 doc.autoTable(item.columns, item.data, {
            startY: 130,
            showHeader: 'firstPage',
            theme: 'plain',
            pageBreak: 'avoid',
            tableWidth: 'auto',
            styles: {
                font: "helvetica",
                overflow: 'linebreak',
                cellPadding: 0,
                //rowHeight: 80,
                fillStyle: 'S',
                halign: 'left',
                valign: 'middle',
                fontStyle: 'normal',
                tablelineWidth: 0,
                fontSize: 10,
                textColor: 0,
                tableLineColor: 0,
            },
        });
 doc.text(450, finalY + 40, "Total = 15");
in my part..
it seems you need to double click it in first attempt.
am i getting it wrong?

**Comment by tmax-ranjith** [comment]
how to get table height in 
autoTable
