### ISSUE TITLE
customise header text in jspdf autotable. 

### ISSUE THREAD

**Issue by Omkarmhaiskar** [simonbengtsson/jsPDF-AutoTable#327]
I need help in generating pdf using js pdf autotable.

I want to add two header text in the pdf one at left side "Candidate for Hall 1" and one more header at right side with Date:__________.

So my header will look like below.

Left side header Candidate for Hall 1

On the same line header at right side Date:_____________________________

rest of the table data will be.

I have used below code. 

`var r = [
{"id": 1, "name": "Shaw", "country": "Tanzania", ...},
{"id": 2, "name": "Nelson", "country": "Kazakhstan", ...},
{"id": 3, "name": "Garcia", "country": "Madagascar", ...},
...
];

function GenerateReport(r)
{
 var columns = ["ID", "Name", "country", ];
                    var data = r.d;

                    var array = JSON.parse("[" + r.d + "]");
                    var doc = new jsPDF('p', 'pt', 'letter');

doc.setFontSize(12);
                    doc.setFontStyle('bold');

                    doc.text('Candidate for Hall 1', 250, doc.autoTableEndPosY() + 30);
                    doc.autoTable(columns, array, { startY: doc.autoTableEndPosY() + 40, theme: 'grid',
                        createdCell: function (cell, data) {
                            cell.styles.fontSize = 10;
                            cell.styles.textColor = [0 - 0 - 0];
                            cell.styles.lineColor = [0 - 0 - 0];
                            cell.styles.lineWidth = 0.1;
                            cell.styles.halign = 'right';

                        }
                    });
                    doc.save('CandidateData.pdf');
}`

Can any one help me how can i achieve this in the js pdf?

Regards, 
Omkar.

**Comment by simonbengtsson** [comment]
Please post questions about how to use the plugin on stackoverflow with the `jspdf` and `jspdf-stackoverflow` tags.
