### ISSUE TITLE
Text should break in next line instead of ....

### ISSUE THREAD

**Issue by azib1993** [simonbengtsson/jsPDF-AutoTable#329]
When the text size increases than that of cell width it shows '....' instead of breaking into new line. Below is the code I am using.

var doc = new jsPDF('p', 'pt');
        doc.autoTable(columns, rows, {
            theme: 'grid',
            cellPadding: 5,
            margin: { top: 60 },
            addPageContent: function (data) {
                doc.addImage(imgData, 'JPEG', 40, 15, 80, 40);
                doc.setFontSize(18);
                doc.text(270, 35, 'PR-03' + '(' + vm.tl_sourceList.length + ')');
                doc.setFontSize(8);
                doc.text(262, 47, 'From : ' + csdate + ' \n  To : ' + cedate).setFontSize(2);
            }

**Comment by azib1993** [comment]
![2](https://user-images.githubusercontent.com/36398580/36086983-639e8600-0ff1-11e8-9396-04692721450a.png)
 And this is the sample.

**Comment by wBatDeveloppement3** [comment]
styles: { overflow:'linebreak'} on autotable!

**Comment by azib1993** [comment]
Yes I had found it after I posted it here. Anyways thank you!
