### ISSUE TITLE
jpsPDF + AutoTable support for multiple header rows and row spans

### ISSUE THREAD

**Issue by Ssereno** [simonbengtsson/jsPDF-AutoTable#330]
Hi

I have the same problem reported on issue #243 with jsPDF & Autotable when print double hearder table.
My table is more simple (see image). Question:

When the multiple header will be suported?
Any workarround?

![image](https://user-images.githubusercontent.com/32569245/36095572-9fb51da4-0fea-11e8-9478-472bdc1ce173.png)

Regards
Sereno

**Comment by simonbengtsson** [comment]
Support for multiple headers comes in v3. Not sure about workaround for v2.
