### ISSUE TITLE
How to set table with in jsPdf table

### ISSUE THREAD

**Issue by BhuvaneswariVajravel** [simonbengtsson/jsPDF-AutoTable#331]
Hi i am using jsPdf to export report as pdf
my code is here
[
let type;
if(this.type){     
  type = this.type;
}
else{     
  type = "All Products";
}
let columns = ["Product Name", "Product Type", "Brand Name", "Model Name", "Sample Size", "Status", "Version Number"];
let data = [];
for (let i = 0; i < this.data.length; i++) {
  if (type == this.data[i].productName) {        
    let data1 = {};
    data1 = { "Product Name": this.data[i].productName, "Product Type": this.data[i].productType, "Brand Name": this.data[i].brandName, "Model Name": this.data[i].modelName, "Sample Size": this.data[i].sampleSize, "Status": this.data[i].status, "Version Number": this.data[i].versionNo };
    data.push(data1);
  }
  else if (type == "All Products") {        
    let data1 = {};
    data1 = { "Product Name": this.data[i].productName, "Product Type": this.data[i].productType, "Brand Name": this.data[i].brandName, "Model Name": this.data[i].modelName, "Sample Size": this.data[i].sampleSize, "Status": this.data[i].status, "Version Number": this.data[i].versionNo };
    data.push(data1);
  }
}   
var doc = new jsPDF('landscape', 'pt');
doc.setFontSize(18);
doc.setTextColor(0, 0, 255);
doc.text(0, 20, type);
let styles = [{ width: "100%" }];
doc.setFontSize(100);
doc.setTextColor(0, 255, 0);
doc.setLineWidth(0);
doc.table(10, 40, data, columns, {
  autoSize: true,
  printHeaders: true
});
doc.save('table.pdf');
](url)
everything works fine the problem is i want to set width for table and table columns . Please anyone tell how to set width for table and other properties of table
Thanks in advance

**Comment by simonbengtsson** [comment]
Issue not matching the issue template closing for now. Feel free to re-submit another issue with more info if you are still having issues.
