### ISSUE TITLE
Jspdf-Autotable problem in displaying table

### ISSUE THREAD

**Issue by brahimkra** [simonbengtsson/jsPDF-AutoTable#332]
@simonbengtsson  i have a proble in displaying autotable , i would like this display :
![imp1](https://user-images.githubusercontent.com/14215952/36339649-df41b430-13ca-11e8-8b9f-918cf9bbd471.png)
But i have this display:
![imp2](https://user-images.githubusercontent.com/14215952/36339680-47cfa778-13cb-11e8-913d-ba598d686f7e.png) and this is my code:
 var res5 = doc.autoTableHtmlToJson(document.getElementById("table12"));
  doc.autoTable(res5.columns, res5.data, {
      styles: {
        lineWidth: 1,
        fillColor: [245, 245, 245],
        textColor: [77, 75, 76],
        fontStyle: 'bold',
        headerStyles: {
          cellPadding: 20,
          lineWidth: 0.2,
          valign: 'top',
          fontStyle: 'normal',
          fontSize: 4

        }
      },
      columnStyles: {
        lineWidth: 1,
        // etc
      },
      alternateRowStyles: {
        textColor: [0, 0, 0],
        fillColor: [255, 255, 255],
        fontStyle: 'normal',
        fontSize: 9,
      },

      overflow: 'linebreak',
      startY:finalY + 10,

    });

And this is my HTML code:
         <table *ngFor="let x of currentProject.training.content.CourseSections" id="table12"  align="right" class="table table-bordered size-table">
            <thead>
            <tr>
              <td>{{x.SectionTitle}}</td>
            </tr>
            </thead>
            <tbody>
            <tr  *ngFor="let y of x.Units">
              <td>{{y.UnitTitle}}</td>
            </tr>
            </tbody>
          </table>

**Comment by amirensit** [comment]
same problem here

**Comment by simonbengtsson** [comment]
Issue not matching the issue template closing for now. Feel free to re-submit another issue with more info if you are still having issues.
