### ISSUE TITLE
AddPage + row multi line

### ISSUE THREAD

**Issue by Tichju** [simonbengtsson/jsPDF-AutoTable#333]
Hello,

I have a table with rows of several lines.
I would like the content of a line not to be divided into 2 pages, so I added an addPage based on the col and rowspan example.
The addition of page is done well, my page is added except that it appears on this new page that content that could have entered the previous page then the row is cut and the rest of the content is displayed on the next page.

The row seems to cut before adding page and the rest afterwards.
Would you have a solution?

![avec addpage](https://user-images.githubusercontent.com/19664524/36382671-195346b4-158a-11e8-8fe1-24af51f3138b.PNG)
![sans addpage](https://user-images.githubusercontent.com/19664524/36382675-1ea5123c-158a-11e8-820d-2fd95ef8805a.PNG)
```
var posY = row.y + row.height + data.settings.margin.bottom;
var pageHeight = doc.internal.pageSize.height;
if (posY > pageHeight) {
                data.addPage();
 }
```

**Comment by simonbengtsson** [comment]
Interesting! Can you provide a runnable example for example on codepen?

**Comment by simonbengtsson** [comment]
Closing since no response.
