### ISSUE TITLE
doc.autoTableHtmlToJson is not a function

### ISSUE THREAD

**Issue by chitranshkumar14** [simonbengtsson/jsPDF-AutoTable#341]
'doc.autoTableHtmlToJson is not a function' is being displayed whenever i reload the page.
The page i m trying to make is for some geo-referencing work using php where a pdf report is generated dynamically.

I m fetching the data from a database(though that is not the major concern).

The scripts being used are
<script src='https://cdn.rawgit.com/simonbengtsson/jsPDF/requirejs-fix-dist/dist/jspdf.debug.js' </script>
<script src='https://unpkg.com/jspdf-autotable@2.3.2'></script>
`function generate(){
	var doc = new jsPDF('p', 'pt');
	alert("First Check");
	var elem=document.getElementById("tableid1");
  var res = doc.autoTableHtmlToJson(elem);
  alert("Second Check");
  doc.autoTable(res.columns, res.data, {margin: {top: 80}});
	
  var header = function(data) {
    doc.setFontSize(18);
    doc.setTextColor(40);
    doc.setFontStyle('normal');
    //doc.addImage(headerImgData, 'JPEG', data.settings.margin.left, 20, 50, 50);
    doc.text("Testing Report", data.settings.margin.left, 50);
  };

	var options = {
    beforePageContent: header,
    margin: {
      top: 80
    },
    startY: doc.autoTableEndPosY() + 20
  };

  doc.autoTable(res.columns, res.data, options);

    doc.save("table.pdf");`

My url on xampp looks like: http://localhost/tea/rc_bhuvan.php
When i browse around the page and generate the pdf, it does so successfully while the url changes to: http://localhost/tea/rc_bhuvan.php#
and when i remove the # from the Url and hit enter(to reload the page) and try to generate pdf it gives the issues
jspdf.plugin.autotable.js:2267 Uncaught TypeError: Cannot read property 'API' of undefined
and
doc.autoTableHtmlToJson is not a function

Is this due to usage of PHP and AJAX?
@simonbengtsson

**Comment by simonbengtsson** [comment]
Hmm not sure! Feel free posting this question on stackoverflow with the `jspdf` and `jspdf-stackoverflow` tags if you are still having issues.
