### ISSUE TITLE
Use image as page background

### ISSUE THREAD

**Issue by betsonserviceportal** [simonbengtsson/jsPDF-AutoTable#343]
Is it possible to use an image as the background for a page and then overlay the autoTable?  I can overlay images using just jsPDF, but can't figure it out with AutoTable.  What I've tried so far is to addImage the full page size in the pageContent.  The image lays overtop of the table so I can't see the tables.

**Comment by betsonserviceportal** [comment]
I kind of figured this out, so you can delete if you want.  I was able to subscribe to the addPage event.  Not sure how to unsubscribe!  In case this helps.

`		doc.internal.events.subscribe('addPage', function() {
			pageSize = view.doc.internal.pageSize;
			doc.addImage(ServicePortal.Constants.betsonProposalBlankCenter, 'JPG', 0, 0, pageSize.width, pageSize.height);
		});`

**Comment by simonbengtsson** [comment]
Innovative solution! And as soon as the document is finished rendered you automatically unsubscribe in jspdf so you don't need to worry about that 👍

**Comment by soleuil** [comment]
What if you want the solution to work also in the first page? This workaround applies after the doc.addPage is in the code and I was looking to also apply to the initial page. Thanks!

**Comment by muthu920** [comment]
> I kind of figured this out, so you can delete if you want. I was able to subscribe to the addPage event. Not sure how to unsubscribe! In case this helps.
> 
> `doc.internal.events.subscribe('addPage', function() { pageSize = view.doc.internal.pageSize; doc.addImage(myimage, 'JPG', 0, 0, pageSize.width, pageSize.height); });`

Thank you
