### ISSUE TITLE
In Angular 5 , getting issues with autoTable does not exist jsPDF

### ISSUE THREAD

**Issue by raviit36** [simonbengtsson/jsPDF-AutoTable#344]
I have used as shown below 

I have used NPM to install below packages and later i used as below in my component 

import * as jsPDF from 'jspdf';
import 'jspdf-autotable' 

exportPDF() {

 var columns = ["ID", "Name", "Country"];
var rows = [
    [1, "Shaw", "Tanzania"],
    [2, "Nelson", "Kazakhstan"],
    [3, "Garcia", "Madagascar"],
    
];

// Only pt supported (not mm or in)
var doc = new jsPDF('p', 'pt');
doc.autoTable(columns, rows);
doc.save('table.pdf');

  }

error TS2339: Property 'autoTable' does not exist on type 'jsPDF'.

**Comment by DevRonin** [comment]
I have the same problem,
Strangely, sometimes pdf generation is working, despite the error.

**Comment by DevRonin** [comment]
is working now
Forget about 
import * as jsPDF from 'jspdf';
import 'jspdf-autotable'

Just use:
declare let jsPDF;

Before
@Component

also check  package.json
for me, 
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",

was listed twice (also on devDependencies section)

In devDependencies should be only
    "@types/jspdf": "^1.1.31",

I also run 
npm cache verify

but I don;t know if was really need it for this issue.

**Comment by alciomarhollanda** [comment]
Hello, try it.

To work with jspdf-autotable in angular 5, one must install jspdf and jspdf-autotable via npm

npm install jspdf-autotable --save
also add the jspdf and jspdf-autotable files to the scripts array in angular-cli.json

"scripts": [
    "../node_modules/jspdf/dist/jspdf.min.js",
    "../node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js"
],
and in component never import jspdf or jspdf-autotable just

declare var jsPDF: any;
Of course before working with jspdf-autotable one should install jspdf and for development @types/jspdf via npm

npm install jspdf --save
npm install @types/jspdf --save-dev

**Comment by piyush-mantravat** [comment]
I have the same problem,
Strangely, sometimes pdf generation is working, despite the error.

**Comment by simonbengtsson** [comment]
Please post environment questions about how to use the plugin on stackoverflow with the `jspdf` and `jspdf-stackoverflow` tags.
