### ISSUE TITLE
Generated PDF overlap page width

### ISSUE THREAD

**Issue by Sin3W** [simonbengtsson/jsPDF-AutoTable#350]
Hi!
I'm trying to generate a PDF from a big and long HTML table with multiple columns wraping the text of all columns to fit page width. I know that I'm doing something wrong because the final PDF is overlaping page width and not breaking columns texts in new lines.

Can someone help me? 

This is my code [link](https://jsfiddle.net/we4dfhoo/)

Thanks a lot for your help!

**Comment by simonbengtsson** [comment]
This should be fixed in v3
