### ISSUE TITLE
Fails with new jsPdf 1.4.0

### ISSUE THREAD

**Issue by cwolcott** [simonbengtsson/jsPDF-AutoTable#355]
@arif25169 just reported a jsPDF issues MrRio/jsPDF#1767.
The new version of jsPDF 1.4.0 doesn't working for jspdf-autotable. Any workaround to resolve this problem.

**Comment by simonbengtsson** [comment]
Will take a look asap!

**Comment by khom-outsourcify** [comment]
+1

**Comment by simonbengtsson** [comment]
I think everything should work now in 2.3.3! Let me know if it works for you.

**Comment by cwolcott** [comment]
When I include the following everything works just fine
   1.3.5:/jspdf.min.js
   2.3.2/jspdf.plugin.autotable.js

But when I include the following Acrobat Reader throws an error
   1.4.0:/jspdf.min.js
   2.3.3/jspdf.plugin.autotable.js

Do I need to make any changes to my code?
