### ISSUE TITLE
Table width changed with new jsPDF 1.4.0 custom font feature when column align is used.

### ISSUE THREAD

**Issue by Nabuk3** [simonbengtsson/jsPDF-AutoTable#357]
With the new version supporting jsPDF 1.4.0, autotable width has changed with the use of custom fonts. It seems like words are not stripped and table columns are inflated beyond default paper size. It only happens when using halign to columns with imported font being used also.
Without the line "font: 'PTSans'", it works all right.

Code:

    const doc = new jsPDF('p', 'pt');
    const PTSans = "AAEAAAAUAQAAB..."; 
    // according to jspdf, PTSans must be base64 font, full string is on jsPDF/examples/js/basic.js
    doc.addFileToVFS("PTSans.ttf", PTSans);
    
    doc.addFont('PTSans.ttf', 'PTSans', 'normal');
    
    var columns = [
        {title: "ID", dataKey: "id"},
        {title: "Name", dataKey: "name"},
        {title: "Country", dataKey: "country"},
    ];
    var rows = [
        {"id": 1, "name": "Shaw", "country": "Tanzania"},
        {"id": 2, "name": "Nelson", "country": "Kazakhstan"},
        {"id": 3, "name": "Garcia", "country": "Madagascar"}
    ];

    doc.autoTable(columns, rows, {
        theme: 'plain',
        styles: {
            fontSize: 6,
            font: 'PTSans'
        },
        columnStyles: {
            id: {
                halign: "left"
            },
            name: {
                halign: "center"
            },
            country: {
                halign: "right"
            },
        },
        tableWidth: 'wrap',
        showHeader: 'never',
    });
    doc.save('test.pdf');

Default font file: 
[test_default.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2035291/test.1.pdf)

Custom font file: 
[test_custom.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2035295/test.pdf)

Thanks for help.

**Comment by simonbengtsson** [comment]
I have not tried with custom fonts, but can imagine there is going to be some effort getting that to work with the width calculations needed for autotable. Can you post the font your are using (base64 string) and I can take a look at it!

**Comment by Nabuk3** [comment]
Thanks for response, I am using the same font as in their examples. [Here](https://github.com/MrRio/jsPDF/blob/master/examples/js/basic.js) the last function called demoUsingTTFFont. The main reason of their 1.4.0 was to enable utf8 support but still importing external font with needed chars is necessary.

**Comment by simonbengtsson** [comment]
I tried now with the custom font Amiri as examplified in the jspdf docs and everything seems to work fine, could elaborate what doesn't work?

**Comment by Nabuk3** [comment]
Seems like it was problem with the chosen font not in jsPDF or jsPDF-AutoTable. Tested now with Amble font (suitable for Czech chars) - normal, bold and italic working fine. Thanks for sticking with me!
