### ISSUE TITLE
Header/Footer example breaks with jsPdf 1.4.0

### ISSUE THREAD

**Issue by cwolcott** [simonbengtsson/jsPDF-AutoTable#358]
The Header/Footer example breaks with jsPdf 1.4.0 because of the following line:

jsPdf changed the function from width to getWidth and height to getHeight for pageSize.

**Line 174** - doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
Instead of height it should be getHeight()

The following lines should also change:
**Line 95** - var text = doc.splitTextToSize(shuffleSentence(faker.lorem.words(55)) + '.', doc.internal.pageSize.width - 35, {});
Instead of width it should be getWidth()

**Line 276** - if (posY > doc.internal.pageSize.height) {
Instead of height it should be getHeight()

**Comment by simonbengtsson** [comment]
Perfect! Will update those examples asap!

**Comment by simonbengtsson** [comment]
Fixed now, thanks!
