### ISSUE TITLE
columnStyles column-specific alignment doesn't apply to corresponding header

### ISSUE THREAD

**Issue by haysj87** [simonbengtsson/jsPDF-AutoTable#360]
Hello,

I'm attempting to align an entire column (data cells and header), but the following only applies to the data cells:
```
columnStyles: {
  0: {halign: "right"},
  5: {halign: "right"}
}
```
The headers for columns 0 and 5 are not right-aligned.

I also tried the following in conjunction with the above-mentioned columnStyles to no avail:
```
headerStyles: {
  0: {halign: "right"},
  5: {halign: "right"}
}
```

Any help would be greatly appreciated.

**Comment by phildkevin** [comment]
i also getting this problem :(

**Comment by simonbengtsson** [comment]
Can you provide a runnable example where the issue is reproduced?

**Comment by phildkevin** [comment]
i mean using keys or values in columnStyles is working perfectly.
columnStyles: {
  0: {halign: "left"},
}
or
columnStyles: {
  'title': {halign: "left"},
}

but, when it comes to headerStyles, I cannot specifically align a column.
like
headerStyles: {
  0: {halign: "left"},
}
or
headerStyles: {
 'title' : {halign: "left"},
}

by the way, i love your plugin. it is really fast.

**Comment by simonbengtsson** [comment]
Got it! Currently you might have to do that with hooks. Whats your use case? Do you think it is better to include the header in the column styles by default? Currently the column styles are only applied for body section I think.

**Comment by phildkevin** [comment]
Ok thank you! i get it now. Yes I think it is better to include header in the column styles, it will make things more easier.

**Comment by simonbengtsson** [comment]
Will take a second look at it then before releasing v3 👍

**Comment by CyborgMaster** [comment]
Is this resolved? It seems that the column alignment is still not applied to the headers.

**Comment by kyleabens** [comment]
If anyones looking for an easy fix you can always style a specific column header this way

`head: [[{content: 'Services', styles: {halign: 'left'}}, 'Qty', 'Unit Price', 'Subtotal']]`

**Comment by b1naryMan** [comment]
Still not working for me with the latest  v3.5.14. Any alternatives?

**Comment by chinanwu** [comment]
I've got this issue still in v3.5.23 as well
