### ISSUE TITLE
Incorrect headerStyles with custom fonts in jspdf 1.4.0

### ISSUE THREAD

**Issue by alexbazilev** [simonbengtsson/jsPDF-AutoTable#363]
Custom fonts support was added into jspdf 1.4.0. Here is the code from their example:
```
const doc = new jsPDF('p', 'pt');
const PTSans = "AAEAAAAUAQAAB..."; 
// according to jspdf, PTSans must be base64 font, full string is on jsPDF/examples/js/basic.js
doc.addFileToVFS("PTSans.ttf", PTSans);

doc.addFont('PTSans.ttf', 'PTSans', 'normal');
```
Now let's try to apply this custom font to table body and table headers:

```
doc.autoTable(columns, rows, {
...
    styles: {
        fontSize: 6,
        font: 'PTSans'
    },
    headerStyles: {
        fontSize: 6,
        font: 'PTSans'
    }
...
});
```

Custom font from "styles" is correctly applied to table body, but not applied for headers through "headerStyles".

Here is another issue about custom fonts: https://github.com/simonbengtsson/jsPDF-AutoTable/issues/357 , but this is different.

**Comment by alexbazilev** [comment]
My mistake :) 
jspdf-autotable is awesome!

**Comment by Hanafukushi** [comment]
I also face this problem, how can I fix. Please help me :(

**Comment by Hlkz** [comment]
@Hanafukushi  Check if the fontStyle if correct

**Comment by iamkarthikselvaraj** [comment]
> My mistake :)
> jspdf-autotable is awesome!

how did you fix that?

**Comment by FastLogic1** [comment]
i want to change the auto table header color any one plz help me

**Comment by jonasmwansa** [comment]
@FastLogic1 

try this

```
    doc.autoTable({
      head: [columns],
      body: data,
      startY: 190,
      theme: 'plain', // Set the theme to 'plain' to use your own
      headStyles: { FontSize: 8 ,fillColor: [200, 200, 200] }, //then set the color using fillColor
      styles: {
          font: 'normal', // Set the font for the table content
          alternateRowStyles: { fillColor: [245, 245, 245] },
      }
    });
    
```
