### ISSUE TITLE
first page is blank when table data is large

### ISSUE THREAD

**Issue by lzhoucs** [simonbengtsson/jsPDF-AutoTable#365]
When table data is large, 30k rows for example, first page becomes blank. 20k rows works fine.

Here is the plunker to demo the issue: http://next.plnkr.co/edit/pe0vpKpxWIhF6FcN

**Comment by simonbengtsson** [comment]
Interesting! Could you provide a runnable example?

**Comment by uzan16** [comment]
I just noticed that too. I try to print 1k rows works fine, but when I print 10k rows, first page becomes blank and the data that should be inside first page is gone.

**Comment by simonbengtsson** [comment]
Should work in v3

**Comment by simonbengtsson** [comment]
Have you tried latest version?

**Comment by mmghv** [comment]
Debugged [here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/598#issuecomment-610422250).
