### ISSUE TITLE
The afterPageContent, beforePageContent and afterPageAdd hooks are deprecated. 

### ISSUE THREAD

**Issue by 8ctopotamus** [simonbengtsson/jsPDF-AutoTable#366]
First of all, awesome plugin! It seems that is is using depricated jsPDF hooks though. 

I get this error in the console:
`The afterPageContent, beforePageContent and afterPageAdd hooks are deprecated. Use addPageContent instead.`

**Comment by fazefatim** [comment]
did u resove the problem cz i'm getting the same error
