### ISSUE TITLE
v2.3.4 - Page break - empty row on ends of some pages

### ISSUE THREAD

**Issue by SamLeatherdale** [simonbengtsson/jsPDF-AutoTable#370]
I'm having an issue where empty rows are being added at the ends of certain pages. I noticed this is because the printFullRow function does check whether the row can fit on the page, but it still calls printRow even if there is no space left on the page. 

I attached a screenshot of the Chrome devtools showing this problem. I am running this module using Node.js, however I experienced the same issue in browser.

Simply skipping the printRow call if remainingLineCount <= 0 should fix this problem, as far as I can tell.

![printfullrow](https://user-images.githubusercontent.com/2122053/42860021-b3a2e2dc-8a98-11e8-98c3-2897c3722354.png)
![empty row](https://user-images.githubusercontent.com/2122053/42860037-b7c26004-8a98-11e8-8d54-529a18fe5f11.png)

**Comment by simonbengtsson** [comment]
Jsfiddle posted in #362 https://jsfiddle.net/bcnwnucj/ highlighting the issue.

**Comment by isahsantos** [comment]
Existis  a solution to this problem , I need

**Comment by simonbengtsson** [comment]
Try the v3 alpha!

**Comment by isahsantos** [comment]
How I do It ?

**Comment by isahsantos** [comment]
Bom install lastet version jspdf?

**Comment by isahsantos** [comment]
I try this version but happened many problems, some dependencies are necessary how my project is ng2 this problems  not is possible to refresh, because is a project very big and can affect others functionality. Have a suggestion ?

**Comment by simonbengtsson** [comment]
Which dependency was the problem? Angular 2+? What is the error?

**Comment by isahsantos** [comment]
So, this project is very big, the dependencies that occur  problem was  commom , forms, core ,eslint-plugin-jsx-a11y and more

**Comment by simonbengtsson** [comment]
Try and see if this is solved in v3

**Comment by MihirGosai** [comment]
It is not solved yet in v3.

**Comment by MihirGosai** [comment]
It is not solved yet in v3. I think there should be an option to skip incomplete row from previous page and start it from next page.

**Comment by NewbieHere16** [comment]
I also encountered the same issue in version 3.0.13, where I think the issue is when there is an incomplete row from previous page.. the next row will have problem in the computation of cell height.

as seen here in the image below:
![1](https://user-images.githubusercontent.com/48553460/54353438-0afaff80-468f-11e9-9a86-99cec230ca1a.png)

the first row in the second page is being cut because it of the incomplete row previous page. Please let us know..how you go on this..

**Comment by jackiewang5566** [comment]
I have the same issue when the last row on page has very long content and extend it to the next page, on the next page it will cutoff some content, I think maybe cell height calculation in this case might have some issue, is there any workaround for this scenario?

**Comment by amgilroy0894** [comment]
Hi, I am having this issue still
![image](https://user-images.githubusercontent.com/31215138/74530169-59f58880-4f21-11ea-8d04-5d535a6b2c24.png)
My code for creating the PDF looks as follows:
$j( "#export" ).click(function() {
	$j.each(ultraChartData, function(index, value) {
       var doc = new jsPDF();
       var headers = value[0];
       value.shift();

        doc.autoTable({
        head: [headers],
        body: value,
        
        styles: {
        	cellPadding: 10,
        },
        columnStyles: {
    		0: {cellWidth: 30},
    		1: {cellWidth: 80}}
        });
      doc.save('table.pdf');
      });
});

It is supposed to be printing multiple pdfs
