### ISSUE TITLE
table not displaying input checkbox on pdf

### ISSUE THREAD

**Issue by axtho24** [simonbengtsson/jsPDF-AutoTable#372]
My table doesn't render properly on the pdf

Here is my code 
`function startPDF(data) {`
`var dataIs = data;`
`var doc = new jsPDF();`
`var obj_table = $('.partsTable')[0];`
`var res = doc.autoTableHtmlToJson(obj_table)`
`doc.autoTable(res.columns, res.data,  { startY: 80 })`
`window.open(doc.output('bloburl'));`
`}`

Here are the images of my table on my site, and result on pdf

![web_table](https://user-images.githubusercontent.com/22122758/42894315-84aaf6e0-8a84-11e8-8aed-9a2278a7297a.PNG)
![pdf_table](https://user-images.githubusercontent.com/22122758/42894329-8b260e56-8a84-11e8-84e4-c0f6e4ea0eee.PNG)

**Comment by AjayBKere** [comment]
This is not supported in jspdf library to put control on pdf.
you can add rectangle on to the page while creating the pdf.

**Comment by simonbengtsson** [comment]
Issue does not match the issue template (no runnable code example). Feel free to re-submit another issue with more info if you are still having issues.
