### ISSUE TITLE
Auto Table text is printing with extra spaces

### ISSUE THREAD

**Issue by AjayBKere** [simonbengtsson/jsPDF-AutoTable#374]
Auto Table text is printing with extra spaces..
please let me know how can i fix this as Now am in Production.............
Thanks in Advance
![pdf report errors](https://user-images.githubusercontent.com/16608261/43134523-f3a33c76-8f5f-11e8-8588-e33bdb6f1f61.JPG)

**Comment by simonbengtsson** [comment]
Can you provide code with a runnable example so I can reproduce the issue?

**Comment by simonbengtsson** [comment]
Is this still an issue in v3 alpha?

**Comment by cardenasivan** [comment]
I 'm getting the same issue has this been fix
