### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by Hamza141** [simonbengtsson/jsPDF-AutoTable#375]
I haven't been able to get this library to work on Angular 6. Has anyone else had any luck or willing to give any instructions? Other guides mentioned adding a couple of lines in the angular-cli.json file but that file doesn't exist on Angular 6 so I'm not sure where those lines should be added instead.

**Comment by imanshu15** [comment]
You could add those lines on angular.json file,

`"scripts": ["node_modules/jspdf/dist/jspdf.min.js",
                       "node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js"]`

And then follow the instructions on the readme file.

**Comment by simonbengtsson** [comment]
Closing since @imanshu15 solution should work. Will update docs for v3.

**Comment by nicholasfoden** [comment]
Sorry for resurrecting a closed issue, but I am having difficulty getting this to work in angular 6. 

I am following the readme to the letter. 

angular.json:
``` "scripts": [
              "node_modules/jspdf/dist/jspdf.min.js",
              "node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js"
            ]
```
my-component.ts:
```
...
declare var jsPDF: any;

@Component({...
...
myfunction(){
    let doc = new jsPDF('p', 'pt');
    doc.autoTable(columns, data);
    doc.save(my.pdf);
}

```

gives me the error : `ERROR ReferenceError: jsPDF is not defined`
