### ISSUE TITLE
Demo page doesn't work in IE 11

### ISSUE THREAD

**Issue by ves-krd** [simonbengtsson/jsPDF-AutoTable#378]
![capture](https://user-images.githubusercontent.com/11619984/43867818-b18c0518-9b1f-11e8-8908-1508310d7520.PNG)

**Comment by simonbengtsson** [comment]
Will take a look! Do you have any ideas what could be wrong? Any error logs in console?

**Comment by ves-krd** [comment]
Sorry, should have included this:

InvalidStateError on line 419 of examples.js
`xhr.responseType = 'blob'`

**Comment by simonbengtsson** [comment]
Aha! Can you verify it's fixed now?

**Comment by ves-krd** [comment]
Looks like you pushed the code changes to github, but didn't update the hosted page...

https://simonbengtsson.github.io/jsPDF-AutoTable/examples.js

**Comment by simonbengtsson** [comment]
True! Updated now!

**Comment by simonbengtsson** [comment]
Let me know if you are still seeing the issue
