### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by gjuchault** [simonbengtsson/jsPDF-AutoTable#379]
Hello,

As I was using halign for specific columns (columns that contain numbers); I was wondering why column styling could be done with column id, so each column has its styling, but headerStyles was a global object affecting all headers.

I did not manage anyway to get header right-aligned, and even less some headers right-aligned and some left-aligned

```
headerStyles: {
    halign: 'right'
},
```

Seems to be totally avoided on 3.0.0-alpha.3

**Comment by gjuchault** [comment]
A dirty fix using `textEx` from here https://stackoverflow.com/questions/28327510/align-text-right-using-jspdf/28433113

```
const fixedHeaders = [];

doc.autoTable(columns, rows, {
    startY: y(70),
    columnStyles: {
        name: { cellWidth: 80 },
        vat: { halign: 'right', cellWidth: 'wrap' },
        up: { halign: 'right', cellWidth: 'wrap' },
        nb: { halign: 'right', cellWidth: 'wrap' },
        total: { halign: 'right', cellWidth: 'wrap' }
    },
    willDrawCell(data) {
        if (data.row.section === 'head') {
            // you wand the `name` column left-aligned
            if (data.column.dataKey !== 'name') {
                data.cell.text = [];
                fixedHeaders.push(data.cell);
            }
        }
    }
});

doc.setFontSize(10);
doc.setFontStyle('bold');
doc.setTextColor('#fff');
for(let header of fixedHeaders) {
    doc.textEx(header.raw, header.x + header.width - 2, header.y + (header.height / 2), 'right', 'middle');
}
```

**Comment by gjuchault** [comment]
Hm, maybe I had docs with previous version, it seems that `headStyles` is the key now. As of custom styling per header cell, I used `willDrawCell` to set halign to left

**Comment by simonbengtsson** [comment]
Will look over the docs and backwards compatibility before releasing v3. Goal is that there should be no breaking changes, only deprecations such as `headerStyles`. But `didParseCell` seems to be the way to go. I'm considering applying `columnStyles` to head and foot as well. What's your opinion there?

**Comment by gjuchault** [comment]
I'd say that's a good idea :) !

**Comment by brentmclark** [comment]
> I'm considering applying columnStyles to head and foot as well. What's your opinion there?

Did this ever happen?  It doesn't appear to be working as expected.
