### ISSUE TITLE
addPageContent on version 3.0 and data from html

### ISSUE THREAD

**Issue by ruitalia** [simonbengtsson/jsPDF-AutoTable#380]
Hi,

I'm having problems in version 3.0 where using addPageContent and getting data from html.

The header/footer are not firing up.

```
var pdf = new jsPDF("L","pt", "A4", true);
	pdf.autoTable(
		{
			html: "#my_table",
			margin: {"left": 5,"right": 5,"top": 5,"bottom": 15,},
			addPageContent: function(data) {
			       pdf.setFontSize(10);
			       pdf.text(15, 580, "footer");
			}
		}
	);
	
	pdf.save("test.pdf");
```

Anybody has the same problem?

Thanks,

Rui Ponte

**Comment by simonbengtsson** [comment]
Will take a look! For now, can you try changing addPageContent to didDrawPage?

**Comment by ruitalia** [comment]
Hi Simon,

Thanks for your prompt reply.

With the didDrawPage it works like a charm!

Thanks, but why is that?

Rui Ponte

**Comment by simonbengtsson** [comment]
It will be renamed to `didDrawPage` in v3. `addPageContent` should be kept as an alias though, so will look into why it didn't work 👍

**Comment by simonbengtsson** [comment]
Should work now, fixed some hooks issues.
