### ISSUE TITLE
Row text aligned justify

### ISSUE THREAD

**Issue by Gherasimov** [simonbengtsson/jsPDF-AutoTable#381]
Hi,

I have a table with rows that contain very long texts. I cannot align the text 'justify'.
In the image I attached I have a table with two rows and no header.
Is there any way to have the long text justified?

Thank you!

<img width="959" alt="screen shot 2018-08-17 at 4 59 59 pm" src="https://user-images.githubusercontent.com/42471732/44270119-345dc500-a23f-11e8-9176-ffa630d2170e.png">

**Comment by Gherasimov** [comment]
Thank you for the reply!

I already did that, I wrote myself a function to justify text while adding text in pdf and it works.

`   this.document.text(lines, ReportHelper.LEFT_MARGIN, atPosition, { maxWidth: pageMaxWidth, align: "justify" });
`

For autotable I wrote my code in willDrawCell hook, and used the autoTableText function, but it's not working.

` willDrawCell: (data) => {
                const textLines = data.cell.text;
                data.cell.text = [];
                this.document.autoTableText(textLines, data.cell.textPos.x, data.cell.y, { maxWidth: pageMaxWidth, align: "justify" });
}
`
<img width="728" alt="screen shot 2018-08-17 at 5 32 39 pm" src="https://user-images.githubusercontent.com/42471732/44271734-96202e00-a243-11e8-8849-e1bc4aee9bef.png">

**Comment by simonbengtsson** [comment]
Addes support for `halign: justify` now in v3.

**Comment by spp020105** [comment]
May I ask is the `halign: justify` function still supported in the current version?
coz it didn't seems to work in my case.

**Comment by mindtzijib-mx** [comment]
> May I ask is the `halign: justify` function still supported in the current version? coz it didn't seems to work in my case.

I have the same problem.
