### ISSUE TITLE
headerStyles not working?

### ISSUE THREAD

**Issue by jessejanderson** [simonbengtsson/jsPDF-AutoTable#382]
I'm not sure what I could be missing. Everything else seems to work fine but anything I try to set within `headerStyles` just doesn't apply.

Here's a basic version that doesn't work for me:

```
var doc = new jsPDF("p", "pt")

doc.autoTable(COLS, ROWS, {
  headerStyles: { fillColor: [255, 0, 0] },
})

doc.output("datauristring")
```

I've tried several variations and several different style rules (fontSize, textColor, etc) and nothing seems to make any difference in the header row of my table. The only thing I've been able to do that adjusts the header row is to set generic styles with a bodyStyles override:

```
doc.autoTable(COLS, ROWS, {
  styles: { fillColor: [255, 0, 0] },
  bodyStyles: { fillColor: null },
})
```

This _technically_ does work for what I need, but obviously isn't ideal.

**Comment by krith354** [comment]
Same here, is there a change or bug in the latest version?

**Comment by krith354** [comment]
@jessejanderson 
I just fixed it by checking my package.json file. 
`
"jspdf": "^1.4.1",
"jspdf-autotable": "^2.3.4",
`
rolled back to those versions, ran `$ npm install` and everything working perfectly. My previous jspdf-autotable version was "^3.0.0-alpha-3" if I remember correctly, hope this is helpful.
