### ISSUE TITLE
it does not support for Devanagari Fonts (Indian Fonts)..

### ISSUE THREAD

**Issue by balasaheb0888** [simonbengtsson/jsPDF-AutoTable#383]
Feature requests, bug reports etc are very welcome as issues. But questions are directed to stackoverflow with the tags `jspdf` and `jspdf-autotable`.

Note that bug reports should follow these guidelines:

1. A bug should be reported as an [mcve](https://stackoverflow.com/help/mcve)
2. Make sure code is properly indented and [formatted](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) (Use ``` around code blocks)
3. Provide a runnable example. You can use for example this [codepen template](http://codepen.io/someatoms/pen/EjwPEb) as a base with `jspdf` and `jspdf-autotable` already included.
4. Try to make sure and show in your issue that the issue is actually related to this plugin and not your framework of choice, jspdf or your setup.

**Comment by simonbengtsson** [comment]
Does not follow the issue template.
