### ISSUE TITLE
Unable to use it in Angular 2

### ISSUE THREAD

**Issue by chinha0** [simonbengtsson/jsPDF-AutoTable#384]
Hi Sir,

I've followed your tutorial closely and did all these steps:
1. npm install --save jspdf jspdf-autotable

2. Add these scripts into **angular.json** file 
 "../node_modules/jspdf/dist/jspdf.min.js",
 "../node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js"

3. declare var jsPDF: any; in to app.component.ts rather than usual imports

However, I still get the following error
![image](https://user-images.githubusercontent.com/37283112/44617934-ce0c1e80-a89e-11e8-80fb-e8b084a7749d.png)

Here is my snippet of my codes:

![image](https://user-images.githubusercontent.com/37283112/44617940-eb40ed00-a89e-11e8-98eb-3c984bdd48f8.png)

Hope to get some help for you!

Best Regards

**Comment by simonbengtsson** [comment]
Can you try this: https://github.com/simonbengtsson/jsPDF-AutoTable/issues/294

**Comment by chinha0** [comment]
Hi, 

I can't get any solution from the link u provided.. Is there other alternatives to it?

**Comment by JLee21** [comment]
Can you please try this out @chinha0 ?

```
import * as jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import 'jspdf-autotable';
```

This worked for me.

**Comment by jemerald** [comment]
@JLee21 this works well. I think it should replace the current documentation.

by the way, the second line `import { autoTable } from 'jspdf-autotable';` is not necessary.

**Comment by simonbengtsson** [comment]
As mentioned by @jemerald the following should work. Just tested with angular 7.

```
import jsPDF from 'jspdf';
import 'jspdf-autotable';

let doc = new jsPDF()
doc.autoTable({html: '#table'})
```

**Comment by jemerald** [comment]
@simonbengtsson I think doing `import` is better than the current documented method of adding scripts to `angular-cli.json`, would you agree?

If so, consider update the documentation?

**Comment by simonbengtsson** [comment]
Sounds good! Will update it for the v3 release coming in a few days.
