### ISSUE TITLE
NPM version set to 3.0.0-alpha.3

### ISSUE THREAD

**Issue by jessejanderson** [simonbengtsson/jsPDF-AutoTable#385]
I added the package and didn't notice that `yarn add jspdf-autotable` had placed `"jspdf": "^3.0.0-alpha.3"` into my project until hitting multiple issues with the api.

Until the documentation and version information is available on the repo, the npm `@latest` version should probably default to `2.3.4` (with `3.0` having the `@beta` tag)?

**Comment by simonbengtsson** [comment]
Oops! Published 2.3.5 now instead of the alpha.
