### ISSUE TITLE
How to add new page and have autotable be aware

### ISSUE THREAD

**Issue by westwick** [simonbengtsson/jsPDF-AutoTable#386]
Sorry not a great title, but I'm looking for a suggestion on how to accomplish something.

I have a long table which is split into chunks of 5, and basically I don't want to start one of the chunks of 5 at the bottom of the page, so I at the start of the chunk I am checking if the row.y + (5*20, 5 lines times row height) would be too close to the bottom of the page. If it is, I call doc.addPage(), set page, and set cursor at the top. This works as intended and prevents the chunks of 5 from being split across pages, however it causes autotable to not re-draw the header at the top of the new page, as well as the `addPageContent` not being called on this new page, so my header and footer is not drawn.

Any suggestion on how to add a page and have autotable be 'aware' of the new page for the purposes of `addPageContent` and `showHeader: everyPage` ? Or is it possible to trigger these methods manually, or something similar? Any other suggestions? How this makes sense.

**Comment by simonbengtsson** [comment]
I would try using the v3 alpha, better support for these things in there. Not that `addPageContent` is renamed to `didDrawPage`. If you don't want header on the second page you can use `showHeader: 'firstPage'`

**Comment by westwick** [comment]
Hey actually just found you expose `autoTableAddPage()` which handles all the logic of addPageContent and drawing headers, so this fits my needs.

Thanks for your work on this!
