### ISSUE TITLE
Migration to 3.0.0-alpha from 2.3.5 help

### ISSUE THREAD

**Issue by fbmfbm** [simonbengtsson/jsPDF-AutoTable#388]
Hi all,
i would like to migrate some code from jsPdf-Autotable 3.0.0-alpha from 2.3.2 and i can't find any doc or help about the new code.
I'm facing with many error like  : 

"The hook "drawRow" has been removed/renamed in version 3.0 of jspdf-autotable. Make sure you update your project according to the migration guide."

Any on can point me to this migration guide ???

Thank's a lot

fbm

**Comment by simonbengtsson** [comment]
It's not yet complete but it's started and is available in the CHANGELOG.md in the v3 branch. It will be more complete by the time v3's stable release. For your specific case `drawRow` is removed and you can use didDrawCell instead.

**Comment by fbmfbm** [comment]
Thank's Simon,

i'll look at this. I 'm facing with the bug for page break with empty row on 2.3.5 and would try to test with 3.0.0.

**Comment by simonbengtsson** [comment]
Migration guide is now up in the 3.0.0-alpha.4 (RC) release notes. v3 should be released to stable this week.

**Comment by betsonserviceportal** [comment]
I can't seem to find the changelog or release notes.  I found this link, but it's not working.

**Comment by simonbengtsson** [comment]
It's in the releases tab on github! https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.0.0
