### ISSUE TITLE
Alignment is off when table is the child of a hidden div

### ISSUE THREAD

**Issue by freeform700** [simonbengtsson/jsPDF-AutoTable#389]
Hi! I just ran into this:

- Only applies when the table is the child of a hidden element. 

- Applies to table cells that have more than one paragraph OR a line break (\<br />).

- If the cell has multiple paragraphs, subsequent paragraphs are misaligned. 

- If the cell is using line breaks instead, the line break is ignored completely.

- Does not matter if div is hidden through CSS or inline style attribute. Behavior is the same. 

- Same behavior in latest Chrome, Edge, Firefox. 

For a working example, see:: https://codepen.io/caitlinw/pen/mGLLmx

To replicate:

1. Generate a PDF as is. 

2. **Enable the CSS hide rule.** 

3. Generate another PDF. 

Note differences.

**Comment by simonbengtsson** [comment]
In v3 extra whitespace between elements will be replaced by one space which will kind of solve this issue. In your case you might want to keep the line breaks however and then you can parse the html element yourself in the `didParseCell` hook.
