### ISSUE TITLE
jsPDF-AutoTable don't support utf8?

### ISSUE THREAD

**Issue by duykhanh1411** [simonbengtsson/jsPDF-AutoTable#391]
I need add some char (ex: € ... ) on list but it break font like þÿ 
I was try add custom font, it only work on jsPDF (not work on jsPDF-AutoTable)
Do you have any solution for this?

**Comment by mdprw** [comment]
I'm having the same problem and the "þÿ" character appears. This also affects letter spacing and causes the text to get out of the cell. The same code worked with jsPdf v1.3.3 and AutoTable v2.3.2.

**Comment by mdprw** [comment]
in my case the flowwing characters are producing the issue:
`”“`

**Comment by simonbengtsson** [comment]
@duykhanh1411 Can you create a miminal example of the issue?

**Comment by Tronghoang** [comment]
@simonbengtsson, example  [https://plnkr.co/edit/Qaqq2Nw2T98DWB5AzPXn?p=preview]
html:
![image](https://user-images.githubusercontent.com/26815143/50145575-7cbbeb00-02e4-11e9-9846-39cc084966ab.png)
pdf file:
![image](https://user-images.githubusercontent.com/26815143/50145616-95c49c00-02e4-11e9-9030-4e78f9094d70.png)

**Comment by khom-outsourcify** [comment]
Same issue

`       doc.addFileToVFS('Kanit-Regular.ttf', Kanit)
        doc.addFont('Kanit-Regular.ttf', 'custom', 'normal');
        doc.setFont('custom');`

![image](https://user-images.githubusercontent.com/38559820/50328643-7cab2d80-0526-11e9-8c62-003202bc31b7.png)

**Comment by simonbengtsson** [comment]
I tried now with the custom font Amiri as examplified in the jspdf docs and everything seems to work fine, could elaborate what doesn't work?

**Comment by mr-rahimi** [comment]
It seems that AutoTable doesn't support utf8 based on following code example:
[http://jsbin.com/fufafotoji](url)

**Comment by mmghv** [comment]
@mr-rahimi Where did you get this autoTable options from?

Just replace it with this :

```js
  doc.autoTable({
    head: [['سلام']],
    body: [['مرحبا'], ['مرحبا']],
    styles: {
      font: 'Amiri',
      fontStyle: 'normal',
    }
  })
```

**Comment by mr-rahimi** [comment]
@mmghv  Thank you, Mohamed, for your comment.
 honestly, I didn't read the AutoTable options from its official documentation, but I read it from the [PrimeNG](https://primefaces.org/primeng/showcase/#/table/export) report example.

**Comment by SeyyedKhandon** [comment]
> @mr-rahimi Where did you get this autoTable options from?
> 
> Just replace it with this :
> 
> ```js
>   doc.autoTable({
>     head: [['سلام']],
>     body: [['مرحبا'], ['مرحبا']],
>     styles: {
>       font: 'Amiri',
>       fontStyle: 'normal',
>     }
>   })
> ```

Thank you, but it seems, jsPDF doesnt work with table function : 
https://stackoverflow.com/questions/64183071/how-to-generate-utf-8-tables-in-jspdf

**Comment by crazydev901** [comment]
The same issue for me. It is really weird. I don't have any utf-8 character, but it break font like þÿ.
"þÿ" is added in front of the table content. I'm using the latest version of jspdf and jspdf-autotable.
Please help me to solve this issue. Thanks!

**Comment by JalmariO** [comment]
Same thing here. Using latest versions.
I made html - table and added it to doc:
autoTable(doc, { html: '#myTable', startY: 440});

Seems like "-" char breaks that cell.

![image](https://user-images.githubusercontent.com/7537088/99662586-21657b00-2a6e-11eb-86e5-4db400212ad2.png)

**Comment by crazydev901** [comment]
> Same thing here. Using latest versions.
> I made html - table and added it to doc:
> autoTable(doc, { html: '#myTable', startY: 440});
> 
> Seems like "-" char breaks that cell.
> 
> ![image](https://user-images.githubusercontent.com/7537088/99662586-21657b00-2a6e-11eb-86e5-4db400212ad2.png)

I was able to fix it by adding custom font.

**Comment by JalmariO** [comment]
> I was able to fix it by adding a custom font. Please inspect your html and check which font it uses. And then add that font to the jspdf.

I tried to change my table in html to font-family: 'helvetica' and used this same font in jspdf. This did not help.
Maybe I have to try to use custom fonts then.

**Comment by crazydev901** [comment]
> > I was able to fix it by adding a custom font. Please inspect your html and check which font it uses. And then add that font to the jspdf.
> 
> I tried to change my table in html to font-family: 'helvetica' and used this same font in jspdf. This did not help.
> Maybe I have to try to use custom fonts then.
https://stackoverflow.com/questions/26908266/custom-font-faces-in-jspdf#:~:text=To%20add%20the%20font%20to,js%2DFile%20to%20your%20project.
This is how to add a custom font to jspdf.

**Comment by JalmariO** [comment]
> > https://stackoverflow.com/questions/26908266/custom-font-faces-in-jspdf#:~:text=To%20add%20the%20font%20to,js%2DFile%20to%20your%20project.
> > This is how to add a custom font to jspdf.

Thanks for that. I would like to avoid using custom-fonts because I don't really need to.
I tried to change the font for whole app to "Helvetica" and "Arial". Then tried to use those fonts with jspdf also. Still that column sith "-" - sign breaks.
I am using angular material classes thou, could that be an issue on here...

**Comment by JalmariO** [comment]
I don't quite understand the problem, but it seems that angulars PercentPipe formed the number so that minus - sign breaks the autotable... I was able to get it right using .toFixed(2) + %.

**Comment by Shidesin** [comment]
my solution this problem:
1) create custom font ( use this : https://www.devlinpeck.com/tutorials/jspdf-custom-font#:~:text=Adding%20Custom%20Fonts%20to%20jsPDF,of%20your%20desired%20font%20file.&text=Once%20you%20have%20your%20.,to%20this%20jsPDF%20Font%20Converter )
2) add font to project :
![image](https://user-images.githubusercontent.com/66698777/110748161-63e6d980-8250-11eb-9572-c668ff1c079a.png)
3) set font:
![image](https://user-images.githubusercontent.com/66698777/110750325-5c74ff80-8253-11eb-8ffe-a5d8ffc4cb4e.png)
4) use in project )

**Comment by mertcankose** [comment]
Hey guys I applied this article
https://www.devlinpeck.com/content/jspdf-custom-font#:~:text=Adding%20Custom%20Fonts%20to%20jsPDF,of%20your%20desired%20font%20file.&text=Once%20you%20have%20your%20.,to%20this%20jsPDF%20Font%20Converter

and then this code

  doc.autoTable({
    head: ...,
    body: ...
    styles: {
      font: 'Roboto-Regular',
      fontStyle: 'normal',
    }
  })

It works!
