### ISSUE TITLE
jspdf autotable pdf working in browser but while opening in adobe acrobat, it is showing some error popup.

### ISSUE THREAD

**Issue by mrLavish** [simonbengtsson/jsPDF-AutoTable#392]
/**
	 * generate pdf
	 */
	exportContentAsPDFFile(id, fileName, headerName) {
		const doc = new jsPDF('l', 'pt', 'A4');
		const res = doc.autoTableHtmlToJson(document.getElementById(id));
		this.date = new Date().toString();
		const client = this.client_name;
		const date = this.datePipe.transform(this.date, 'MM/dd/yyyy');
		var topMargin = 50;
		if (id == 'cashflow-table-first') {
			topMargin = 40;
		}
		const header = function (data) {
			doc.setFontSize(14);
			doc.setTextColor(40);
			doc.setFontStyle('normal');
			let pageInfo = doc.internal.getCurrentPageInfo();
			if (pageInfo.pageNumber == 1) {
				doc.line(0, 38, 1000, 38);
				doc.text(headerName + client, 10, 30);
				doc.setFontSize(10);
				doc.text('Date- ' + date, 730, 30);
			}
		}
		const rowFontStyle = function (cell, data) {
			const tdElement = cell.raw;
			if (tdElement !== undefined && tdElement.classList !== undefined) {
				if (tdElement.classList.contains('hrow')) {
					cell.styles.fontStyle = 'bold';
					cell.styles.fillColor = [211, 211, 211];
				}
				if (tdElement.classList.contains('frow')) {
					cell.styles.fontStyle = 'bold';
					cell.styles.fillColor = [169, 169, 169];
				}
				if (tdElement.classList.contains('deltasymbol')) {
					cell.styles.fontStyle = 'bold';
				}
			}
		};

		if (this.timeLineList <= 6) {
			doc.autoTable(res.columns, res.data, {
				addPageContent: header,
				pageSplit: true,
				margin: { right: 10, left: 10, top: topMargin, bottom: 50 },
				styles: { fontSize: 8, overflow: 'linebreak', halign: 'right' },
				columnStyles: {
					0: { columnWidth: 300, halign: 'left' },
					text: { columnWidth: 'auto' }
				},
				createdCell: rowFontStyle
			});
		} else {
			if (id == 'balance-table-first') {
				topMargin = 60;
			}
			doc.autoTable(res.columns, res.data, {
				addPageContent: header,
				pageSplit: true,
				margin: { right: 10, left: 10, top: topMargin, bottom: 50 },
				styles: { fontSize: 8, overflow: 'linebreak', halign: 'right' },
				columnStyles: {
					0: { columnWidth: 100, halign: 'left' },
					text: { columnWidth: 'auto' }
				},
				createdCell: rowFontStyle
			});
		}
		doc.save(fileName);
		this._message.showLoader(false);
	}

**Comment by mrLavish** [comment]
here is the generated pdf file [Balance-sheet (2).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2441897/Balance-sheet.2.pdf)

**Comment by mrLavish** [comment]
here is the pdf error in adobe acrobat 
![pdferror](https://user-images.githubusercontent.com/43813189/46409177-2d790c00-c732-11e8-8aac-9c5686f89767.png)

**Comment by simonbengtsson** [comment]
Can you localise the error by removing contents of the pdf until you know exactly what line is causing the error?

**Comment by jemerald** [comment]
The file attached opens fine with Adobe Acrobat Reader under Windows:
![image](https://user-images.githubusercontent.com/9168432/47886114-29f5b380-de9d-11e8-938c-2ce64d2f1de0.png)

**Comment by simonbengtsson** [comment]
Hmm sounds very unlely that margin is causing the problem? Do you have a basic code that I can try?

**Comment by tusharwalzade216** [comment]
In my case, the wrong parameters were passed to function `.text()`. I corrected it & it worked!
Eg. I replaced this - `pdf.text(str, 210 - 14 - 23, pdf.internal.pageSize.height - 7);` with this - `pdf.text(str, 100, 500);`

**Comment by dhirajbasukala-houzz** [comment]
for anyone with similar case: in  my case, I was passing 
```
headerStyles: {
     fillColor: '', // sending empty string caused it, replacing it with valid color such as 'white' worked
     ...
     ...
 }
 ```
