### ISSUE TITLE
Setting linewidth for only one side of the cell and table

### ISSUE THREAD

**Issue by ArakelyanEdgar** [simonbengtsson/jsPDF-AutoTable#398]
I want only the a single side of a cell to have a border/linewidth. Is this possible?

**Comment by simonbengtsson** [comment]
Not possible at the moment, but added it to the backlog now. If you have time, I would gladly accept a pull request.

**Comment by simonbengtsson** [comment]
Closing since I have no immediate plans to implement this as a feature. Should be possible to do with didDrawCell and doc.line function however.
