### ISSUE TITLE
How to add page content with dynamic data

### ISSUE THREAD

**Issue by suryamishra2111** [simonbengtsson/jsPDF-AutoTable#401]
I am generating a PDF with multiple tables. Each table represents a category of data. I am trying to add a footer that contains the PDF Title, Page Number and the category name to which the table belongs. I am able to add the first two part of the footer by setting these values in addPageContent hook. 
The problem comes when I need to show something in footer that depends on the data being displayed by the autotable. I tried passing custom properties to autoTable and reading them off the data argument inside addPageContent but it doesn't work. Is there any way, I can pass custom data objects from the autoTable options to the hooks ?

**Comment by simonbengtsson** [comment]
Should be possible! What type of data do you want to pass? Can you post a simple example?

**Comment by suryamishra2111** [comment]
Hey Simon,

Did you get a chance to look into this ?

**Comment by simonbengtsson** [comment]
Something like this?

```
const dataToPass = { /*...*/}
doc.autoTable({
    // ...
    didDrawPage: (data) => {
         console.log(dataToPass)
    }		
});
```

**Comment by PathanMansoorKhan** [comment]
is there a way addpage dynamically with dynamic data.
