### ISSUE TITLE
columnWidth inside of columnStyles not working

### ISSUE THREAD

**Issue by chadlamson** [simonbengtsson/jsPDF-AutoTable#402]
I have the following code: 

`doc.autoTable(eqColumns, eqRows, {
	styles: {overflow: 'linebreak', fontSize: 10, columnWidth:50},
	columnStyles: {
                  0: { columnWidth: 77 },
                  1: {columnWidth: 25},
                  2: {columnWidth: 25},
               },
});`

No matter how I set the column width, I cannot get it to change. Setting the column width in "styles" works, but I need the first column to be quite a bit longer than the last 2. Am I missing something?

**Comment by chadlamson** [comment]
Just saw in the release notes, that columnWidth was changed to cellWidth. Now my code is: 

`doc.autoTable(eqColumns, eqRows, {
	styles: {overflow: 'linebreak', fontSize: 10,},
	columnStyles: {
                  0: {cellWidth: 100 },
                  1: {cellWidth: 25},
                  2: {cellWidth: 25},
               },
});`

This is working, when the data inside the cell is short, but if the data in the cell is long, it does not overflow, and the set cell width is ignored.

**Comment by marquesgabriel** [comment]
Hi, did you manage to set cell width when data is long?
