### ISSUE TITLE
how to make a dynamic loop autotable

### ISSUE THREAD

**Issue by raje3424** [simonbengtsson/jsPDF-AutoTable#404]
Feature requests, bug reports etc are very welcome as issues. But questions are directed to stackoverflow with the tags `jspdf` and `jspdf-autotable`.

Note that bug reports should follow these guidelines:

1. A bug should be reported as an [mcve](https://stackoverflow.com/help/mcve)
2. Make sure code is properly indented and [formatted](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) (Use ``` around code blocks)
3. Provide a runnable example. You can use for example this [codepen template](http://codepen.io/someatoms/pen/EjwPEb) as a base with `jspdf` and `jspdf-autotable` already included.
4. Try to make sure and show in your issue that the issue is actually related to this plugin and not your framework of choice, jspdf or your setup.

**Comment by raje3424** [comment]
for (let index = 1; index < res.reportData.length; index++) {
          alert(index);
          var doc = new jsPDF('p', 'pt');
          let finalY = doc.autoTable.previous.finalY; // The y position on the page
          console.log(res.reportData[index].dataValues);
          doc.autoTable(columns, res.reportData[index].dataValues, {
              styles: {fillColor: [100, 255, 255]},
              pageBreak: 'always',
              columnStyles: {
                id: {fillColor: 255}
              },
              margin: {top: 60},
              addPageContent: function(data) {
                doc.text(res.reportData[index].sensorName, 40, finalY+30);
              }
          });  
          sensorName = res.reportData[index].sensorName+'_report';
          //doc.text(40, finalY+30, "Hello!");
          doc.save(sensorName+'.pdf');
        }


only displays last table ..... i don't know exactly how much data ..... tested with one table table son data works fine ..... once data is of more table overrides and displays only last table

**Comment by simonbengtsson** [comment]
Closing since it does not follow issue template
