### ISSUE TITLE
Set table's row number based on json index

### ISSUE THREAD

**Issue by haerulmutakin** [simonbengtsson/jsPDF-AutoTable#409]
Hi,, 
Thanks for this great library.

As seen below, there is no single field that can be used as a row number, then how do you display row numbers based on json below? 
I think it's possible to use drawRow or drawCell, but I can't find an example that can explain how it works. Thanks..

```
[
  {
    name: 'name1'
    age: 'age1'
  },
  {
    name: 'name2'
    age: 'age2'
  },
  {
    name: 'name3'
    age: 'age3'
  }
]
```

**Comment by simonbengtsson** [comment]
Should be an example about page numbering that you can look at. Otherwise I would suggest posting on stackoverflow 👌
