### ISSUE TITLE
I need to write bold and normal text in the same cell. Is it possible?

### ISSUE THREAD

**Issue by ultra2** [simonbengtsson/jsPDF-AutoTable#412]
I need to write bold and normal text in the same cell.
My cell value text contains html tags like `<b>`, so it looks like this:
`var text = 'normal <b>bold</b> normal'`
Word wrap also need to work!

How can I do this?

**Comment by simonbengtsson** [comment]
You can use didDrawCell to parse and draw the text yourself.

**Comment by pallamollasai** [comment]
If anyone is still looking for answer the following links might help.

[mix bold & html inside a cell in table SO ](https://stackoverflow.com/questions/57427546/bold-and-normal-textstyle-inside-a-cell-in-jspdf-autotable/57462940#57462940)

[mix bold & html github ](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/364)

**Comment by calldeludo** [comment]
@simonbengtsson can you specify a little bit more? i think there is not any clear solution to this problem, i tried using didDrawCell hook but could not do it work...

**Comment by LuigiSZ** [comment]
@simonbengtsson can you help us to write a cell with mixed font styles ?
thanks

**Comment by LuigiSZ** [comment]
can see : https://github.com/simonbengtsson/jsPDF-AutoTable/issues/744#issuecomment-812129199
