### ISSUE TITLE
Is there a way to create a table with a class or object?

### ISSUE THREAD

**Issue by Hellogark** [simonbengtsson/jsPDF-AutoTable#413]
I want to create a new person from a register form like this for example:

`class Person {
    constructor(Id, Pic, Name, Register_Date) {
      this.Id = Id;
      this.Pic = Pic;
      this.Name = Name;
      this.Register_Date = Register_Date}
}`

And i  want to set the Object Properties names as columns, and properties values as rows iterating over all new persons created. It is possible to do something like this?

**Comment by simonbengtsson** [comment]
You could generate some basic javascript objects from your models before passing them to autotable.
