### ISSUE TITLE
How to attach image on the server side?

### ISSUE THREAD

**Issue by shivkumarganesh** [simonbengtsson/jsPDF-AutoTable#414]
I am trying to generate a pdf document on the Nodejs end as in the server side. I am facing a weird issue. The image which is a base64 URL is not getting generated. I tried every possible way. The PDF gets created with some space in the top and then a popup appears saying that the stream has errors.
 
The code that I have written is as follows:-

```
global.window = {document: {createElementNS: () => {return {}} }};
global.navigator = {};
global.atob = require('atob');
global.btoa = () => {};
var jsPDF = require('jspdf');
var imgData = "Some Base64 URL" // Any JPEG Image

var fs=require('fs');
var doc = new jsPDF()

doc.setFontSize(40)
doc.text(35, 25, 'Paranyan loves jsPDF')
doc.addImage(imgData, 'JPEG', 15, 40, 180, 160)

fs.writeFile('download.pdf', doc.output(), (error) => { /* handle error */ });
```

I have tried all possible stuff but the image does not at all appear. 
NOTE: This is a non Browser implementation and runs on Node Server

**Comment by stark1996** [comment]
Firstly write this the image code
```
var img = new Image;
    img.crossOrigin = "";
    img.src = "../resources/images/.....jpg";
```
```
next 
use img.onload = function () {
//here goes the jspdf code
}
var jPDF = new jspDF();
.....
jPDF.save('...');
```

the onload function is cuz the browser takes time loading and downloading image. so yuh need a onload function so that is waits untill the image is downloaded.

**Comment by danramosd** [comment]
I've run into the same issue, any  luck ??

**Comment by simonbengtsson** [comment]
Closing this this is a question about jspdf.
