### ISSUE TITLE
Cell text colour refuses to change.

### ISSUE THREAD

**Issue by DCZ23** [simonbengtsson/jsPDF-AutoTable#415]
I have followed the steps to some answers on this topic already, but none of them are working. I have the following text which needs to display in a red text:

> <table id="heading1">
> <tr>
> <td class="hrow"><h4>1. DETAILS</h4></td>
> </tr>
> </table>

Here is the code I have written for the PDF:

`
 exportGraph = function () {
 var pdfsize = 'a4';
 var pdf = new jsPDF('l', 'mm', pdfsize);
 var totalPagesExp = "{total_pages_count_string}";

 var res2 = pdf.autoTableHtmlToJson(document.getElementById("heading1"));

 pdf.autoTable(res2.columns, res2.data, {
    createdCell: function(cell, data) {
        var tdElement = cell.raw;
        if (tdElement.classList.contains("hrow")) {
            cell.styles.textColor = "[255,72,72]";
        }
    },
startY: 10,
margin: {left: 5 },
styles: { halign: 'left', fontsize: 12 }
});

pdf.save('Submission-Printout.pdf'); 

}

`

As you can see, what I have done SHOULD in theory work, but the text still appears as not red. Does anyone know why it's not appearing in red text colour?

**Comment by DCZ23** [comment]
Used "textColor" to change it in the table "styles"

**Comment by Dinand-nl** [comment]
Hi DCZ23,
Do you mean like this? 
<td style="color:red; textColor:red">Donna</td>

If I change this in the codepen, it displays red, Perfect, but on the pdf it's still black
https://codepen.io/someatoms/pen/EjwPEb
