### ISSUE TITLE
collapse header with table

### ISSUE THREAD

**Issue by cplaiu** [simonbengtsson/jsPDF-AutoTable#417]
First sorry for my english.

I try to do header and footer for all pages, but when table pass on second page the header collapse with table.

![screenshot from 2018-12-18 13 05 21](https://user-images.githubusercontent.com/32199465/50153083-a87ba880-02c5-11e9-99bd-929bf3b22962.png)

Code of that table:

```
doc.autoTable(columnTableResto, rowTableResto, {
          theme: 'plain',
          showHeader: 'never',
          addPageContent: pageContent,
          styles: {
            halign: 'left',
            overflow: 'linebreak',
            fontSize: 9,
            cellPadding: 0.5
          },
          columnStyles: {
            "titulos": {
              halign: 'center',
              fontStyle: 'bold',
              valign: 'middle',
              columnWidth: 120,
              fillColor: [246, 80, 88],
              textColor: 255
            },
            "contenidoTitulos": {
              columnWidth: 430
            }
          },
          bodyStyles:{
            cellPadding: 10,
            lineWidth: 1,
            lineColor: [0, 0, 0]
          },
          margin: {left:25},
          startY: doc.pageCount > 1? doc.autoTableEndPosY() + 20 : finalTablaGrafico
        });

```
I try to increase '+20' but nothing happen.
Thanks.

**Comment by cplaiu** [comment]
> First sorry for my english.
> 
> I try to do header and footer for all pages, but when table pass on second page the header collapse with table.
> 
> ![screenshot from 2018-12-18 13 05 21](https://user-images.githubusercontent.com/32199465/50153083-a87ba880-02c5-11e9-99bd-929bf3b22962.png)
> 
> Code of that table:
> 
> ```
> doc.autoTable(columnTableResto, rowTableResto, {
>           theme: 'plain',
>           showHeader: 'never',
>           addPageContent: pageContent,
>           styles: {
>             halign: 'left',
>             overflow: 'linebreak',
>             fontSize: 9,
>             cellPadding: 0.5
>           },
>           columnStyles: {
>             "titulos": {
>               halign: 'center',
>               fontStyle: 'bold',
>               valign: 'middle',
>               columnWidth: 120,
>               fillColor: [246, 80, 88],
>               textColor: 255
>             },
>             "contenidoTitulos": {
>               columnWidth: 430
>             }
>           },
>           bodyStyles:{
>             cellPadding: 10,
>             lineWidth: 1,
>             lineColor: [0, 0, 0]
>           },
>           margin: {left:25},
>           startY: doc.pageCount > 1? doc.autoTableEndPosY() + 20 : finalTablaGrafico
>         });
> ```
> I try to increase '+20' but nothing happen.
> Thanks.

**Comment by simonbengtsson** [comment]
Try v3!
