### ISSUE TITLE
Add custom font 

### ISSUE THREAD

**Issue by khom-outsourcify** [simonbengtsson/jsPDF-AutoTable#418]
I already add `jspdf-customfonts` plugin for custom character (TH language)
For  `jspdf` is work 
But `jspdf-autotable` does not work

![image](https://user-images.githubusercontent.com/38559820/50334378-b0904e00-053a-11e9-8a49-b76cd7054428.png)

Do you have any solution for this ?

Custom font: 

`doc.addFileToVFS('Kanit-Regular.ttf', Kanit)`
`doc.addFont('Kanit-Regular.ttf', 'custom', 'normal');`
`doc.setFont('custom');`

**Comment by simonbengtsson** [comment]
I tried now with the custom font Amiri as examplified in the jspdf docs and everything seems to work fine, could elaborate what doesn't work?
