### ISSUE TITLE
 Table Data is consolidated on the right side of the paper whenever trying to print.

### ISSUE THREAD

**Issue by arasabbasi** [simonbengtsson/jsPDF-AutoTable#419]
Hi Simon,

following issue was in the issue-tracker of jspdf. I think it is an issue in autotables. Not sure if this is already fixed by you. 

Link to original issue:
https://github.com/MrRio/jsPDF/issues/1327

> Hello There,
> 
> I'm using the current version of jsPDF and will import jspdf.debug later in parallel to my investigation.
> Actually we only encountered the issue whenever we deploy our code in our production side which is running on linux. When ever we try this locally it actually display the expected behavior. Please see the screenshot below and also my code to generate it.
> ![image](https://user-images.githubusercontent.com/29417483/27268731-2c4e3290-54e4-11e7-8396-7c8a1ce3be82.png)
> 
> This is the function table waiting for the listeners inside the print and export btn.
> 
> function demoFromHTML(btn) {
> var width;
> var heigh;
> var headerc;
> var wc;
> 
> ```
> headerc = $("#table-1-ereceipts-and-issued-deposited tr:visible th").length;
> wc = Math.round(headerc * 115);
> console.log("rounded " + wc);
> 	
> 	
> 	var doc = new jsPDF('l', 'pt', [800,wc]); //
> 	var elem = document.getElementById("table-1-ereceipts-and-issued-deposited");
> 	var res = doc.autoTableHtmlToJson(elem);
> 	console.log("This is res");
> 	console.log(elem);
> 	console.log("This is elem");
> 	console.log(res);
> 	
> 	var identify = isNaN(wc);
> 	
> 	if(identify){
> 	width = doc.internal.pageSize.width;  
> 	height = doc.internal.pageSize.height;  
> 	headerc = $("#table-1-ereceipts-and-issued-deposited tr:visible th").length;
> 	wc = Math.round(headerc * 115);
> 	console.log("is NaN" + wc);
> 	width = wc;
> 	height = 800;
> 	
> 	console.log("New doc witdh" + width + "New doc height" +  height );
> 		
> 	} else {
> 		
> 		console.log("It's not NaN");
> 		console.log("continue");
> 		width = doc.internal.pageSize.widthfunction;  
> 		height = doc.internal.pageSize.heightfunction; 
> 		console.log("This is W: " + width);
> 		console.log("This is H: " + height);
> 	}
> 
> 	
> 	
> 	console.log(doc)
> 	console.log("This is res colums")
> 	console.log(res.columns);
> 	console.log("This is res data");-
> 	console.log(res.data);
> 		
> 
> 	
> 	doc.autoTable(res.columns,res.data, {
> 		headerStyles: {fontColor: 23},
> 	    styles: {fillColor: [255, 255, 255]},
> 	    columnStyles: {
> 	    	id: {fillColor: 0}
> 	    },
> 	    headerStyles: {
> 	    	fillColor: [192, 192, 192],
> 	    	textColor: (0)
> 	    },
> 
> 	    columnWidth: 'auto',
> 	    showHeader: 'everyPage',
> 	    theme: 'grid',
> 	    cellPadding: 5,
> 	    fontSize: 10,
> 	    lineWidth: 2,
> 	    
> 	  
> 	});
> 	
> 	if(btn === 'p'){
> 		console.log("print");
> 		doc.autoPrint();
> 		window.open(doc.output('datauristring'));
> 	} else if(btn === 'pdf') {
> 		console.log("pdf");
> 		
> 		doc.save("pdfInuqery.pdf");
> 		
> 	}
> ```

**Comment by simonbengtsson** [comment]
Hmm, try using v3. It might be fixed there!
