### ISSUE TITLE
Problem with <br> in v3

### ISSUE THREAD

**Issue by spp020105** [simonbengtsson/jsPDF-AutoTable#423]
When I was using v2 with the autoTableHtmlToJson(), I am able to get line break with the `<br>` tag.
However after using v3 with the html option, I am not able to get it anymore.

For example, a text like this:
Morbi lectus felis,  `<br>`
accumsan id hendrerit nec,  `<br>`
scelerisque ut tellus. 

Will become like this:
Morbi lectus felis, accumsan id hendrerit nec, scelerisque ut tellus. 

My options are like this:
```
doc.autoTable({
			html:tbl,
			theme:'grid',
			rowPageBreak: 'avoid',
			styles: { overflow: 'linebreak',lineWidth : 1,lineColor : 200 }, //??
			columnStyles: {0: {cellWidth: 250},1: {cellWidth: 265}},
			});
```
May I ask is this my own problem or v3 does not allow line break with <br> anymore?
Thanks a lot!

**Comment by simonbengtsson** [comment]
The html parsing was rewritten for v3 so it could definitely be a regression with the new `htmlParser.js`. Let me know if you can spot the issue in that there, otherwise I'll look into as soon as I can 👌

**Comment by spp020105** [comment]
I fixed it by deleting line 949 (?)
`cell.text = Array.isArray(cell.text) ? cell.text.join(' ') : cell.text;`
I am not sure will it causes any other problem but it seems to work fine for now.

**Comment by Et3rnal** [comment]
Can we have a word on this? Is that change safe to do? or can we expect a hotfix update?

**Comment by dnlbaldwin** [comment]
Here's a [fiddle](http://jsfiddle.net/Lqpbuzxa/) for it.  You can see issue 365 here too.  Removing the line of code talked about above doesn't seem to fix it for me.

**Comment by webwakko** [comment]
maybe this can help.
Add your break like this in your html.

`Morbi lectus felis, <br />\n`
`accumsan id hendrerit nec, <br />\n`

adding the simple \n part solved the issue for me ;)

**Comment by arunlalkp** [comment]
"The Library always looking for `\n` to render next line / Line break in table cell."

If you working with angular, Then angular always render with a random  directive within the tag ( eg :`<br _ngcontent-lfs-c183>`  ) so the library can not identify and split with `<br>` and add `\n` at the end of each split value

So parse td cell content with InnerHTML Directive

`<td [innerHTML]="parseNextLine(textToRender)"></td>`

and create a function that convert `\n` to `<br>`

`parseNextLine(text) { return text.replace(/(\\r\\n)|([\r\n])/gmi, '<br>');}`

please note : `<br/>` is not accepted by the library at all use only `<br>`
