### ISSUE TITLE
Multiple Tables side-by-side multiple pages don't align

### ISSUE THREAD

**Issue by barretttmf** [simonbengtsson/jsPDF-AutoTable#424]
Looking at the Multiple Tables example, the two side-by-side tables align on the first page that they are displayed, but as they extend to a second page, they are no longer side-by-side. The one on the left prints, then the one on the right prints , but on the following page. They should continue to print on the same page (side-by-side). I believe this was reported in #253, but seems unresolved.

![multipletables](https://user-images.githubusercontent.com/41652324/50833037-99f93d80-1315-11e9-9746-e4c061aaa87f.png)

**Comment by simonbengtsson** [comment]
Oops! Have you debugged anything as to why that is happening? If no one submits a pull request I'll try to fix it as soon as possible.

**Comment by barretttmf** [comment]
It looks like you are using the doc to find the current page number, normally that would be fine, but each table wants to increase the page count once it runs out of room on the current page. It's up to the user to start them on the same page (which is also fine), but you might need to keep a "local" page count in the state to make sure any tables to the left didn't already increase the doc page count. Just a thought, I can't really test it currently.

**Comment by simonbengtsson** [comment]
Can someone verify that the latest commit fixed this?

**Comment by barretttmf** [comment]
The multiple table example lines up now. This fixes the issue.
![multitablefix](https://user-images.githubusercontent.com/41652324/51537615-9e911c00-1e14-11e9-8c21-e8afbb1b6200.png)

**Comment by simonbengtsson** [comment]
Awesome!

**Comment by SukanyaPurushothaman** [comment]
Am facing this issue even if I'm using v3.0.10. Please see my PDF file.
[Sukanya P's Notes.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2869141/Sukanya.P.s.Notes.pdf)

This is my code. I don't know what am doing wrong. 
`const pdf = new jsPDF('l', 'pt',);
    const totalPagesExp = '{total_pages_count_string}';
    let first = null, last = null;

    const footer = function (data) {
        var imgData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGkAAABgCAYAAAAejVzyAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyJpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoV2luZG93cykiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6NTgyQjZCOUY3MDBBMTFFOEExQTBDNzFEQTJGRkQxRUMiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6NTgyQjZCQTA3MDBBMTFFOEExQTBDNzFEQTJGRkQxRUMiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1ODJCNkI5RDcwMEExMUU4QTFBMEM3MURBMkZGRDFFQyIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDo1ODJCNkI5RTcwMEExMUU4QTFBMEM3MURBMkZGRDFFQyIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PjMCxxsAAArtSURBVHja7J0LkBTFGcf/vbe3d7eQBFIIPipHvAA+yEkixAKEongIZXwkWgHOWJC6UDE8oohnoEg8DI9QQUUNoOihQEmJgKZUUIQEeRQUiqgIlA9IIBIsQJEQieEeuzud/mZ2ub3dnZ6Z3Z25ffRX1be7szNzM/3b7/v+/XXvHeN/A9d8PoQ0P8KhEgAMyryzDifODxAPb8v28UETP8IayngLguVNCARawHya6j3vrM5qB9+FZ1z4UIijVAsjWNqE8rJmlPgjqgvdt9tF62EPUhwshIGScATlvmZUlDeiNBASBLnqTneMGNzjDFK8CUfyCe8K8BCCZY0oK2uBT4VCN6xWtE7pQYqZRqEQ8EfCqKBQWNEEvz8cdTtlWbCOok3JDFJiKGwRQsMnhIaAFSgLgTHlXVkwghTIHFJCKGQtJDRCuiosqxBCo0QJjQzsEtFqsgspLhSiRYTCkBAapUJoBBvhLw0roZGe3Z9qoOrL2umJichbvmYeDYWNCJQroeHQqkUb6R6keCNHagZKSWiIUFgebBJjLiU0bNo0byDFh8JmQ2iU+4V3dWjSx1xMhUKZjYx6lEeQEkIhE6EwILR8UOQtEho+JTRSGYvmJo8hJUh4NNGYK4KKMiE0hHcpoZFkNVG11w6QEiQ8hUIfjbkoFAZpzKWKu1ELxA9ufe1+OVEJT6GwVLgZwSoPxoq7Re1dU6KViByAlBgKG6PF3UBzsQsNquXV5hakFKGQKhqBEiE0OgqhUV6UQoOq4z5/Tl9iNBSSMvSL8OeviEDTfAiFimYWmeaZbvfnxaVGJbxe0fALoRFoEZ5VNN5U58u7S45K+CKy/j4oy3lTkPLAXMlJm99heHStw6TOW0dF9Mi58USLey+2fcadHD8emizLX9/FMKeB6ftpdIzYOXYMNY0j+XXseXT7hFuBqy7n+EYQGN6vgCG9/3e4Bojau4cgICWfZu9HyAgQtWWv0nsCtGZs/+NE4Mb+HBd1LuZw5xAQh3khIlNAF47XWn//zCeBPuMZXt5RrJDSAMQlxQeeZUBa3PZJDzHULWL4X1MxQUoTUKzJhlTZBhR7/dwmYMojrEgg5SGg2Lk27AJWbmT5D+nanu4Botf9rpSc20VAseOn/Rn454k8V3ejruN6c2LHvwDmPufD4eNyQA+M57ipv/m5rQDtfkYotRRrRU+fBXYdABasYvj0lDmg2Pb1Qu5PHcMLONwl2Cf/YrhvSeaAOKw9yMxIYt82BHhziRiDDZAD0q9lGTwTEe0OadMehkkLGU5/JQe0eKocEGAvxFlZh3LhTZO5FFBs+4F/FAGkl7YzLFjNLHPQ8hkc/a6w0cM2cpAdI6+6Z7QcELVPjuVxTrKy883AY+sYtrwrB9RF5I4lUzVUdrMtGi1Fgl1SvS/n4nhmCoh87dipAoV05pwIJ6t92PuxXMVdUQnMrrUPKN6TZCrOrvX8DqSA6PHsuQKERAKh/hmGL7+yltnXV3MEHU7sxc4jldkOTAaoYMPd8o32AOmFzg0MDaJRR9WN5RjYm6O7Da+yGgfZtW7flgPycmmMp5D+87U9QG06WLx4eA09Mky8FRg3UnhYmbW6MxuoOvJMC0DcI1Keqrt0AMVvf+IVYMLDhlyX5iRJJSEtSO0IyHsJngGgWCcfPArcvYjhfJP5YFZa6nEKyQSQlyHPU0iV3XhGgGKv9x8BtrwjSfaSWpyzz5QckFfe5GlOqh/P9WY2dtr6PsOh48DzW6yr2Y+9wDDiurYKUN/PRrHUebhLDaggPUlmJAZuHsBRN4Zj4WRuWc3+7LQIfUeS4122AH3+79wAlFOQ4m3oD4BB1da1uFNnknOS1XSDU6EjA3R19yKGRPb9Kuti6bnzzHQAajYfZNdOfmnhQeJJ52/maU56Yw9D0rgx+qJrZ9grlMZ9gmW1uHNfp1Jj8gk7u/bhp3JA9Lz7xXkIiQD96Xkmldn1v4DllAPZ9g+si6WXXcRTepJsws6O0TzRs+vlgMiu+m6ehjurcdDSV43SkMzW7zZktlWxtGNQnpNSzQfZsZlLgUOfyQGR9emRh55E5X0OJh0HnRKqadRvGWbXcvS/GujyrdbjPzoGvPYWw4pN9tYkDKy2Loo6qTi8tA1oeAXY9oE1oCk/BTpU5CGkyq7ADf24vszYaqBav5xltGhkxjgkV8ktANG2qtHMViVBBojsrp/ksQQfMzT9SoKTVT1jh3NpbVA2o5opIPKia3rkMaQrKzl+P567CmjFdPO12W4DGibGcLN+6e1wxJVxEqm3e0dz1wCNuNb8d7sJqNdlwLKZxlAi7yGR1QzjeHIaR9dO2QE0qi+w83E5IO5yiNspVF/Vpd4P7F0tsNLAdeMCYMNbwJKXGU6ecQ7ohn4C+FA5nDa1uywDIjg/H5laSXpljG/2rlZ47HNj/PPfRoZ5q1IDurQLUDfauKSRfWG+ziGYvOkv24Ha+SwjQFQ3nHib8ZIWSbousw/lGKTsls1RGGYDkvrObB6YgqQgKVOQFCRlCpIyBUlBUpZ/kH6zWIyKRyW3O+YBB47a25fa8PtTn3/WCuP9xHPF7MWt4v3ByW343cZ7SSP4webt0RfirnVh6n3umOXdt/zIsla7W/c7YPSQttuefQPoMwk4shKoukS+r5nReoO5a4Be4vgt7wHXVKXej2psS+qS4T3QYKzPm/Ortu/tX2FvTmjdbHGtwxLua4O4r1pxX2u9Kbi6Gu4m3Cg672ZjOjpd27jHALRoCvD0686+TEydu+he+lY78MXZLN7XLcaHYtt7BZKTqi4G9mUQGp4Sn9rpY43FkmS7Djo7flR/43HfoSzfl/CgfYcLBNJe0Tk/THOqmXLQ1oNGZZq+Ff7rm4CVm52fh2ZTz53P8n19LO6rVwFAooS/ZqfRyfE2Zn5q4fBiwl/CohxUM7g1n43oa5zv6MnMr41ySipRYEcQzFomrmObuK++eSYcqOMxv+026uD9S9uKBrvCgXIP5aBFcf9EjUTDsGojx1V9L7PrtSscxjwofjyYcF9DjeO9mqXNmidRx/PNrY06kz75ZmrMymK5Z1DCjOhEkbQfWuud/CV1x3e2NgqdI37k7Woh16bP54pwcv19wC0DgK6dnB9PueewCGsdTda37T5of0p7q/C86Xdm6b7uEvc1WdzXIO8WpLiWkwb2NuT3nFXOj6WcQ7mHQmW8d8ZafQ2w+q82xUc0x/SszNJ9VRvye87yAikLzRoHPPGa+NR/6Ow4yjkULs1C5c+GGF9ythr7bH7b+LNn9eOzmz9o3R39/t0HvYHk6mohCnOUq+pFkn3zEbnIiBl5CuWcebXm59UFhMgNO/a1VgOo06jFG62TozBHg89U6s5u5SLpvjobuaq+QdzXYvch5dVCFI37ENZKEOZ+cFYY/6eiwwnLAdyOnP9fFfRHNiICTkjzQ2Ml0Y8Wisn+4M91rwkJrwF5TXGBueBFom3PKUj03aYI/esdAUZDUXpNkhe5Lhxse40Oxsg1YMVNJdGL2hWS4TUlOhzlNeZe1C6QtKgICAs4ymusvcgzSKTQwno4U17j1Itch0TSmfKM7jWKSlpe5AqkVq8hhaYWI2XqRVmFpLzGHS/KGBL9SeaIgBLSSnW1piz7XpQ2pAioGuA3xjXKXPUiR5CU17SPF9mCpBc3hcdElNe0ixeZQtIQV9xUXtOuXtQGkv61fJTo1YAIL1HdliNepEPSvYZHvYYrr8k1LyL7vwADAHG5t/RI4Vz9AAAAAElFTkSuQmCC'
        // HEADER
        pdf.setFontSize(20);
        pdf.setTextColor(40);
        pdf.setFontStyle('normal');

        if (imgData)
            pdf.addImage(imgData, 'JPEG', 400, 30, 60, 60);

        let str = 'Page ' + pdf.internal.getNumberOfPages();
        if (typeof pdf.putTotalPages === 'function')
            str = str + ' of ' + totalPagesExp;

        pdf.setFontSize(10);
        pdf.setFontStyle("normal");
        pdf.text(str, data.settings.margin.left + 470, pdf.internal.pageSize.height - 30);
        pdf.text('© 2019 3d-reader.com All Rights Reserved.', data.settings.margin.left, pdf.internal.pageSize.height - 30);
    };

    let y = 120;

    $(".note").each(function () {
        const $frnt = $(this).find(".front");
        const $back = $(this).find(".back");
        y = pdf.autoTable.previous ? (first.finalY > last.finalY ? first.finalY + 25 : last.finalY + 25) : y;
        y = y >= 490 ? y + 50 : y;

        pdf.autoTable({
            head: [[$frnt.find(".bk-title").text().trim().toString(), $frnt.find(".pgno").text().trim()]],
            body: [[{
                content: $back.find(".question").text().trim().toString(),
                colSpan: 2,
                styles: {halign: 'justify'}
            }]],
            startY: parseInt(y),
            tableWidth: 200,
            styles: {
                cellWidth: 'wrap',
                valign: 'middle',
                font: 'times',
                fontSize: 12,
                overflow: 'linebreak'
            },
            headStyles: {
                fillColor: [247, 185, 7]
            },
            theme: 'striped',
            margin: {top: 150, right: 350},
            didDrawPage: footer
        });

        first = pdf.autoTable.previous;

        pdf.autoTable({
            head: [[$frnt.find(".bk-title").text().trim().toString(), $frnt.find(".pgno").text().trim()]],
            body: [[{content: $frnt.find(".title").text().trim().toString(), colSpan: 2, styles: {halign: 'justify'}}],
                [{content: $frnt.find(".desc").text().trim().toString(), colSpan: 2, styles: {halign: 'justify'}}]],
            startY: parseInt(y),
            styles: {
                cellWidth: 'wrap',
                valign: 'middle',
                font: 'times',
                fontSize: 12,
                overflow: 'linebreak'
            },
            headStyles: {
                fillColor: [247, 185, 7]
            },
            theme: 'striped',
            margin: {top: 150, left: 340}
        });
        last = pdf.autoTable.previous;
    });
    if (typeof pdf.putTotalPages === 'function')
        pdf.putTotalPages(totalPagesExp);

    pdf.save(`${username}'s Notes.pdf`);`

**Comment by simonbengtsson** [comment]
Can you post a new issue @SukanyaPurushothaman? Don't forget to explain what result you expect and include a runnable minimal example that highlights the issue you are having 👌

**Comment by SukanyaPurushothaman** [comment]
@simonbengtsson I've created a new issue for this. Please have a look at it. [#453](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/453)
