### ISSUE TITLE
Row Content is NOT properly wrapped to corresponding cells in last rows (on few pages) and empty row on few pages

### ISSUE THREAD

**Issue by nikhildesu** [simonbengtsson/jsPDF-AutoTable#426]
Hi I see couple of issues in the latest version too. 
1 - I have large content to display in table and in few pages (last line of page) splits into 2 rows and it is confusing to understand whether it belongs to previous row or next row (next page)  . It should wrap inside corresponding cell .  See the attached. 
2 - Content and page numbers are overlapped in few pages. I tried line overbreak and had set margin bottom but still issue exists.
3 - It also creates empty rows in end of few pages. 

![issue 1](https://user-images.githubusercontent.com/32606893/51044506-4560f700-158f-11e9-8339-c5beb6a2d23e.jpg)

![issue 2 3](https://user-images.githubusercontent.com/32606893/51044507-4560f700-158f-11e9-808a-2d5681876497.jpg)

Here is my code. Please let me know how these can be solved. Immediate response is highly appreciated. 

 doc.autoTable({
          startY: 33,
          margin :{left:10 , right:10 , bottom: 10},
          styles: { fontSize: 8, overflow: 'linebreak',cellWidth: 'wrap'},
          headStyles: { fillColor: [49, 99, 180] },
          columnStyles: {0: {cellWidth: 10},
          1: {cellWidth: 5},
          2: {cellWidth: 25},
          3: {cellWidth: 35},
          4: {cellWidth: 10},
          5: {cellWidth: 10},
          6: {cellWidth: 10},
          7: {cellWidth: 10},
          8: {cellWidth: 35}},
          head: [['Code','Lang','ShortDesc','Description','ParTyp','ParCd','Def','Sys','Long Description']],
          body: rows,
          showHead: 'firstPage',
          theme: 'grid', 
          didParseCell: function(data) {
            rowStyles_Indexes.forEach(id =>{
              if (data.row.index === id) {
                data.cell.styles.fontStyle = 'bold'; 
                data.cell.styles.fontSize = '9'; 
            }
          })},
          didDrawPage: function (data) {    
            var str = "Page " + doc.internal.getNumberOfPages()
            if (typeof doc.putTotalPages === 'function') {
              str = str + " of " + totalPagesExp;
            }    
            var pageSize = doc.internal.pageSize;
            var pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
            doc.text(str, 100, pageHeight - 5);
          },
        })
        if (typeof doc.putTotalPages === 'function') {
          doc.putTotalPages(totalPagesExp);
        }
        this.spinnerService.display(false);
        this.reportName="none";  
        doc.save('tableCodes.pdf');

**Comment by simonbengtsson** [comment]
Could posted is not runnable, can you provide some sample data? Proper formatting would be help as well 🙏

**Comment by simonbengtsson** [comment]
Closing since no response
