### ISSUE TITLE
Polish characters

### ISSUE THREAD

**Issue by FelixNievelstein** [simonbengtsson/jsPDF-AutoTable#433]
I have an issue with some characters. In my Application I have to create a pdf with a table with polish characters like "ł".
Here is a link with more informations to the character : http://www.fileformat.info/info/unicode/char/142/index.htm 
If I add this character to jspdf as text, it is printed correctly, but if I add it as text in my jspdf-autotable row I get the character "B". 
I have compared the html hex values of both characters 
ł =  &#x142;
B = &#x42; 
It seems that jspdf-autotable misinterpret the first hex value. 

Can you help me to fix this?
Thank you for your great plugin!
Kind regards,
Felix

`
this.getPDFRows(renderOption, (rows) => {
                    this.getBase64((base64) => {

                        const pdfDoc = new jsPDF();
                        const col = this.getPDFColumns(renderOption);
                        const yOffset = additionalText ? 10 : 0;
                        const currentDate = moment();

                        pdfDoc.addFileToVFS('FreeSans.ttf', base64);
                        pdfDoc.addFont('FreeSans.ttf', 'custom', 'normal');
                        pdfDoc.setFont('custom');
                        pdfDoc.setFontType('normal');

                        pdfDoc.setFontSize(12);
                        // printed correctly 
                        pdfDoc.text(14, 20 + yOffset, 'ł');

                        if (additionalText) {
                            pdfDoc.text(14, 20, additionalText);
                        }
                        pdfDoc.autoTable({
                            head: [col],
                            body: rows,
                            startY: 30 + yOffset,
                            willDrawCell: function (data) {
                                if (data.row.cells.isRelatedToCompany) {
                                    delete data.row.cells.isRelatedToCompany;
                                }
                                if (data.section === 'body' && data.row.raw && data.row.raw.isRelatedToCompany) {
                                    pdfDoc.setTextColor(42, 127, 186);
                                }
                            }
                        });
                        callback(pdfDoc);
                    });
                });
`

**Comment by simonbengtsson** [comment]
You probably need to include a custom font to get those unicode characters. Look at the jspdf docs or ask on stackoverflow if having troubles 👍

**Comment by FelixNievelstein** [comment]
@simonbengtsson  I already added a custom font which is working fine with jspdf but not with jspdf-autotable.

**Comment by simonbengtsson** [comment]
I modified the `Custom` example with a custom font (japanese characters) the other day. Take a look at that and see if you can spot something.
