### ISSUE TITLE
useCss individual column styles bug

### ISSUE THREAD

**Issue by RileyDavidson-Evans** [simonbengtsson/jsPDF-AutoTable#435]
Hey so loving the package ! One thing I am noticing is that when using the useCss flag, not all columns styles are respected. It seems to add combine all individual column styles and apply to each column of the row ? 

for example if I have a row where the first column's background is explicitly set to blue, and no other columns have the background color. When printing all of the columns now have the background of blue.

**Comment by RileyDavidson-Evans** [comment]
from debugging it seems like this line which combines the styles is causing individual column styling to be over ridden 
`styles: useCss ? polyfills_1.assign(rowStyles, cellStyles) : null,` in -> parseTableSection

**Comment by RileyDavidson-Evans** [comment]
#439

**Comment by RileyDavidson-Evans** [comment]
👍

**Comment by simonbengtsson** [comment]
Fix included in 3.0.5
