### ISSUE TITLE
devanagari(Hindi), jspdf is not generating properly

### ISSUE THREAD

**Issue by harishmarthala** [simonbengtsson/jsPDF-AutoTable#438]
![case](https://user-images.githubusercontent.com/12496063/51906418-1ac5c980-23ea-11e9-8437-34254ecfe6d7.PNG)
I tried in java as well for this problem but no use,please can any one help on this issue

**Comment by simonbengtsson** [comment]
Does not follow issue template (and seems like an issue with jspdf, not jspdf-autotable)
