### ISSUE TITLE
Not supporting for custom fonts. Like arabic, japanse

### ISSUE THREAD

**Issue by prakashsam** [simonbengtsson/jsPDF-AutoTable#440]
I added Japanese custom fonts in jspdf. working fine in jspdf but not working in jspdf-autoable
```
 doc.addFileToVFS("MouhitsuBold.ttf", MouhitsuBold);
      doc.addFont('MouhitsuBold.ttf', 'Mouhitsu', 'bold');
        
      doc.setFont('Mouhitsu', 'bold'); // set font
      doc.setFontSize(20);
    
    // From HTML
    doc.autoTable({html: '.table'});
    
    
    // From Javascript
    let finalY = doc.previousAutoTable.finalY;
    doc.text("おはようございます", 14, finalY + 15);

    doc.autoTable({
        startY: finalY + 20,
        head: [
            ['おはようございます', 'おはようございます', 'Email', 'Country', 'IP-address'],
        ],
        body: [
            ['1', 'Donna', 'なに', 'China', '211.56.242.221'],
            ['2', 'Ruth' , 'jhenry1@theatlantic.com', 'Ukraine', '38.36.7.199'],
            ['3', 'Ruth', 'rwells2@constantcontact.com', 'Trinidad and Tobago', '19.162.133.184'],
            ['4', 'Jason', 'jray3@psu.edu', 'Brazil', '10.68.11.42'],
            ['5', 'Jane', 'jstephens4@go.com', 'United States', '47.32.129.71'],
            ['6', 'Adam', 'anichols5@com.com', 'Canada', '18.186.38.37']
        ],
    });

    finalY = doc.previousAutoTable.finalY;
    doc.text("なに", 14, 10);
    doc.autoTable({
        startY: finalY + 20,
        html: '.table',
        useCss: true,
        styles: {
            font: 'Mouhitsu',
            lineColor: [44, 62, 80],
            lineWidth: 1
        },
    });
    
    return doc;
```

![image](https://user-images.githubusercontent.com/7478698/51979603-8d4eac00-24b3-11e9-9d97-813bb0b670c0.png)

   doc.text("なに", 14, 10); --- working fine for JSPDF

 doc.autoTable .. data not working

**Comment by simonbengtsson** [comment]
Added an example for how to use custom fonts now in the `custom` example. It seems like everything is working? Take a look at your console and make sure you don't have any warnings/errors their.

**Comment by prakashsam** [comment]
Really thanks for implement custom fonts. Its working fine but
I have multiple languages in one PDF export using Anuglar5 ,JSPDF  and Jspdf autotable. . how to do for multiple fonts in Jspdf autotable. Please refer the screenshots

![image](https://user-images.githubusercontent.com/7478698/52692007-ae6dcd00-2f88-11e9-81fc-f647b80ca0bc.png)

**Comment by linigithub** [comment]
I am facing this same issue. Arabic labels are not rendering on pdf table header. I am using jspdf autotable. here is the output 
<img width="1088" alt="Screenshot 2019-03-14 at 2 34 40 PM" src="https://user-images.githubusercontent.com/25053785/54336217-695fb800-4666-11e9-97a1-f23ee7179bfe.png">
```
`  doc.autoTable(columns, row, {
      margin: {horizontal: 7},
      bodyStyles: { valign: 'top' },
      styles: { cellPadding:0.7, fontSize: 7, overflow: 'linebreak',startY: 20 },  
      columnStyles: {
        text: {columnWidth: 5},
        },
      theme: 'grid'
    });
    doc.save("print001.pdf");`
```

**Comment by 1202ajay** [comment]
Hi @prakashsam 
Am facing same issue,
as per your above comments, how did you resolved with custom fonts.

Can you please help me
