### ISSUE TITLE
Autotable doesn't split one row in more than one page

### ISSUE THREAD

**Issue by pirasalbe** [simonbengtsson/jsPDF-AutoTable#444]
Hi, 
I've a row in my table with a very very long text that should be split into more than one page.
You can see the output in the [attachment](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2816317/errore_autotable.pdf) at the row number 12.

Here is my autotable code:
`const columns = [{"header":"#","dataKey":"numero"},{"header":"Tipo prest.","dataKey":"tipoPrestazione"},{"header":"Cod. art.","dataKey":"codiceArticolo"},{"header":"Desc. art.","dataKey":"descrizione"},{"header":"U.M.","dataKey":"unitaMisura"},{"header":"Qta","dataKey":"quantita"},{"header":"Pr. uni","dataKey":"prezzoUnitario"},{"header":"Cod. IVA","dataKey":"aliquota"},{"header":"Totale","dataKey":"prezzoTotale"}];`

`const rows=`[rows](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2816376/rows.txt)

`doc.autoTable({
     columns: columns,
     body: rows,
     startY: startY,
     margin: {
       top: 60,
       right: 5,
       left: 5,
       bottom: 45
     },
     tableWidth: 555,
     showHead: 'everyPage'
})`

I also tried using rowPageBreak and pageBreak (all possible configuration) but the output is nearly the same.

**Comment by simonbengtsson** [comment]
Weird! Have you identified which part of the library that is causing this issue?

**Comment by pirasalbe** [comment]
I found that the problem is in function printFullRow with the calculation of variable maxRowSpanCellHeight because as you can see in the image it is always 0, so when it writes the remaining text of the row in the next call of printFullRow the function canFitOnPage return true.

![autotable](https://user-images.githubusercontent.com/4697821/52049972-6e9df300-254f-11e9-9142-4bfaffcf5e37.png)
Here is the case.

**Comment by marcobarbiero10** [comment]
I have the same problem

**Comment by jackiewang5566** [comment]
I have the same problem. Does the fix has been released? Or is there any workaround instead of changing the source code?

**Comment by marcobarbiero10** [comment]
Hi,

Fix works,

Thanks

Il giorno lun 18 mar 2019 alle 16:40 Di Wang <notifications@github.com> ha
scritto:
