### ISSUE TITLE
AutoTable addPage automatically based on content

### ISSUE THREAD

**Issue by kevinneibarger** [simonbengtsson/jsPDF-AutoTable#447]
I don't believe this is an issue but I'm wondering if we can within the autotable determine when the content is going to automagically force an addPage() to be called. I'd like to know since in my code I need to display a large footer so I typically check to see if the yIndex > 375, if so I add a page and reset the yIndex = 45.  The problem is that my "rows" array is large enough that pages are automatically added somewhere. Is there a hook or something I can override?

		if (yIndex > 375) {
			yIndex = 45;
			pdfHmsPrintDoc.addPage();
		}

Is there a way to do this in the autotable configuration

```
doc.autoTable(columns, rows, {
          drawCell: function(cell, data) {  },
          createdCell: function(cell, data) {   },
          drawHeaderRow: function () {  return false;  },
          drawRow: function(row, data) { },  
          startY: yIndex,
          pageBreak: 'auto',
          showHeader: 'everyPage',
          margin: {left: 20},
          styles: {overflow: 'linebreak'},
          theme: 'grid',
          columnStyles: {title: {columnWidth: 150}, details : 'auto'}
});
```

**Comment by simonbengtsson** [comment]
Sure! With `v3` you should be able to add a page with `doc.addPage()` inside of the willDrawCell or didDrawCell hook.
