### ISSUE TITLE
Header/footer is printed twice if document has more than one table

### ISSUE THREAD

**Issue by nicole-dsouza** [simonbengtsson/jsPDF-AutoTable#448]
In documents that have multiple tables, the header/footer gets printed twice.

Regular header (one table)
![capture](https://user-images.githubusercontent.com/34153968/52257383-17739600-2934-11e9-97dc-7ae47ac76873.PNG)

Header if multiple tables
![capture1](https://user-images.githubusercontent.com/34153968/52257345-eb581500-2933-11e9-80dd-cf145237d3a6.PNG)

I am adding table content like this:

    var pageContent = function (data) {

        doc.setFontSize(11);
        doc.setFontStyle('normal');

        doc.text(address_position, 16, address_text, {
            maxWidth: address_width,
            align: "justify"
        });

    };

    function jspdfTable() {

        var elem = $(".jspdf-table");

        elem.each(function () {

            var res = doc.autoTableHtmlToJson(this);

            doc.autoTable(res.columns, res.data, {
                addPageContent: pageContent,
            });

        });

        doc.save(filename + ".pdf");
    }

Appreciate any help you can provide.

**Comment by cplaiu** [comment]
[Here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/144#issuecomment-232106480)

**Comment by nicole-dsouza** [comment]
> 
> 
> [Here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/144#issuecomment-232106480)

Thanks, this worked for me.
