### ISSUE TITLE
Margin doesn't work correctly.

### ISSUE THREAD

**Issue by gingerbread2016** [simonbengtsson/jsPDF-AutoTable#450]
I created two auto-table for my page. In the old version, these two table could line up Horizontally in the same level.
But for new version, the second table always below the first table. No matter what I put in margin{top}.

Seems like the margin top not work for the second table anymore. But margin,left works well.

Can anyone help to take a look at this issue?

Thanks,

**Comment by cplaiu** [comment]
Put this under first table
  var  firstTable = doc.lastAutoTable.finalY;
and remove margin from second table and put that
  startY: firstTable
