### ISSUE TITLE
Cell Text in drawCell hook has commas

### ISSUE THREAD

**Issue by kevinneibarger** [simonbengtsson/jsPDF-AutoTable#451]
I've created a JSFiddle to show that when I grab the cell text from a specific cell of the autotable it is filled with sporadic commas and all formatting ("\n") are gone. I need to grab and modify this data by using the addPageContent but their are commas in text that should only have one comma. Here is the JSFiddle

https://jsfiddle.net/ptw5n61a/1/

When I do the following

```
   drawCell: function(cell, data) {
		           	 if (data.column.dataKey === "description") {
		           		 var cellVal = cell.text.toString();
		           		 
		           		 if (cellVal != undefined && cellVal != '') {
		           			titleAndDesc.push({
		      	              title: cellVal.substring(0, cellVal.indexOf(':')),
		    	              desc: cellVal.substring(cellVal.indexOf(':')+1)
		    	            });
		    	            i++;
		           		 }
		           	 }
		    	    }
```

And then try to get those values in the addPageContent hook

```
addPageContent: function() {  
		        	for (var i = 0; i < titleAndDesc.length; i++) {
		        		   console.log("TITLE: "+titleAndDesc[i].title);
		        		   console.log("DESC: "+titleAndDesc[i].desc);
		        	   }
		             } 
```

I see the following in the console.

**TITLE: Title
DESC:  This is a string and it's only a string.,Any attempts to make this not a string will,be met with resistance, but with that,resistance you will learn proper use**

Why does this happen? Is it a bug??

**Comment by simonbengtsson** [comment]
Try the latest version 👍

**Comment by kevinneibarger** [comment]
Has the following hook been renamed? I'm not seeing the console.log being printed.

`drawCell: function(cell, data) {
              console.log("In drawCell: "+data.column.dataKey);
              
		           	 if (data.column.dataKey === "description") {
		           		 var cellVal = cell.text.toString();
		           		 
		           		 if (cellVal != undefined && cellVal != '') {
		           			titleAndDesc.push({
		      	              title: cellVal.substring(0, cellVal.indexOf(':')),
		    	              desc: cellVal.substring(cellVal.indexOf(':')+1)
		    	            });
		    	            i++;
		           		 }
		           	 }
		    	    },`

**Comment by simonbengtsson** [comment]
Yes! Checkout the docs or release notes of version 3!

**Comment by kevinneibarger** [comment]
I've upgraded and version 3 and everything looked good until I passed a string into data.cell.text and noticed that my "\n" formatting had been removed and replaced still with ",". I have to format a string longer than the cell width because the requirement is to use "Arial" font instead of the default and for some reason that font doesn't wrap well within the cell. I'm not sure if "Arial" is currently supported. 

So, my issue is that when store the cell text via data.cell.text from **willDrawCell** hook into a json array, it isn't not saved with my necessary formatting. I have a sophisticated method to transform a text string into a text string with "\n" set at the appropriate end of line so appropriate wrapping occurs. This is done before I create the autotable. So the following string

**Title: This is a string and it&#39;s only a string.\\nAny attempts to make this not a string will be met with resistance,\\nbut with that resistance you will learn proper use.**

When printed from data.cell.text, looks like this

**This is a string and it's only a string.,Any attempts to make this not a string will be met with resistance,,but with that resistance you will learn proper use.**

I'm guessing somewhere the "\n" is being replaced with a ",". I would assume it's because it's essentially two lines not one line with "\n" in it. 

All the documentation is excellent and your autotable widget is very useful. It might be cool to have a feature in which we can have mixed formatted text within a cell. Right now it's not an urgent requirement but I thought I could hack my way around it.

**Comment by simonbengtsson** [comment]
Hmm, with the string you provided and the following code I get this result.

```
let doc = new jsPDF('l', 'pt');
doc.autoTable({body: [["This is a string and it's only a string.\nAny attempts to make this not a string will be met with resistance,\nbut with that resistance you will learn proper use."]]});
doc.save("test.pdf");
```

<img width="1068" alt="screenshot 2019-02-13 at 15 47 55" src="https://user-images.githubusercontent.com/3586691/52719883-cfddb180-2fa6-11e9-9032-cc973a32480e.png">

And using the didDrawCell you can manually draw any content you want in a cell using any formatting. A little bit cumbersome, but I think that's the easiest api for it. Let me know if you have a suggestion for a betteer API 👍

**Comment by kevinneibarger** [comment]
Thanks Simon! Shortly after I typed this I figured out a way similar to what you suggested. The "\n" was replaced with "," because the data.cell.text is now a String array with the lines separated by "\n". I simply treated that data as such and parsed the array and re-wrote the content. All of this so I could simply bold the first word of the first line.. 

The API rocks! Thanks!

**Comment by simonbengtsson** [comment]
Aha! That makes sense. In the end a javascript issue I guess... Glad you like it!
