### ISSUE TITLE
Multiple side by tables doesn't align in second page

### ISSUE THREAD

**Issue by SukanyaPurushothaman** [simonbengtsson/jsPDF-AutoTable#453]
Hi,
I'm creating a PDF file with multiple side-by-side tables. The issue am facing is that the tables in the second page won't come as expected. [Please find the runnable code in jsFiddle.](https://jsfiddle.net/765teu2k/)
Am expecting the tables to be side by side in every page (as in the first page of the PDF file generated).

**Comment by simonbengtsson** [comment]
Have you seen the multiple pages example? You need to use `doc.internal.getNumberOfPages();` and `doc.setPage(pageNumber);`

**Comment by SukanyaPurushothaman** [comment]
Hi Simon,
I've seen your example for headers and footers, row span and col span, and multiple tables drawn horizontally :). **_doc.internal.getNumberOfPages();_** is already there in my code (line no:38). I followed your example for headers and footers for that. 
Please look into my working example. I don't know what I've been missing there.

**Comment by tiagomsmagalhaes** [comment]
@simonbengtsson I have found the same issue. My use case is just one table with several records, spanning more than one page. I have text above the table, but on the second page it overlaps.

I tried to use the codepen link you have in the new issue template. But can't get it to download the pdf 
https://codepen.io/anon/pen/aMvMBL?editors=0010

**Comment by SukanyaPurushothaman** [comment]
@tiagomsmagalhaes You didn't include `doc.internal.getNumberOfPages();` in your code. You can see an error in the console. 
![See this error](https://user-images.githubusercontent.com/30044024/53617258-71523d80-3c0c-11e9-83db-ebe94c6c6b85.JPG)

**Comment by tiagomsmagalhaes** [comment]
@SukanyaPurushothaman I'm aware of that error. But I don't get that error locally and I don't call that function locally.

And I also think that use case does not apply for me. I just need a table with variable row number. If it breaks it must go on. The example that @simonbengtsson has on the `examples.js` has a table that breaks and then he sets the page to get a new table. But the trick there is that he changes the positon of this second table.

**Comment by SukanyaPurushothaman** [comment]
Hi @simonbengtsson,
I solved this issue by putting `doc.setPage(pageNumber); ` after the first table as you said. So everything except the footer went well. I thought that setPage() function is not required since am setting the page number in footer function. Thanks for your help.
But am still have an issue with the footer. It's adding multiple footers for each table on a single page. How can I solve this?

**Comment by cplaiu** [comment]
> Hi @simonbengtsson,
> I solved this issue by putting `doc.setPage(pageNumber); ` after the first table as you said. So everything except the footer went well. I thought that setPage() function is not required since am setting the page number in footer function. Thanks for your help.
> [This is my fiddle](https://jsfiddle.net/ocpxzd5m/) with the updated code.
> But am still have an issue with the footer. It's adding multiple footers for each table on a single page. How can I solve this?

Try [https://github.com/simonbengtsson/jsPDF-AutoTable/issues/144#issuecomment-232106480](this)

**Comment by SukanyaPurushothaman** [comment]
@cplaiu Thanks it worked.

**Comment by simonbengtsson** [comment]
👍
