### ISSUE TITLE
column widht is breaking

### ISSUE THREAD

**Issue by Ambi1** [simonbengtsson/jsPDF-AutoTable#457]
If you have a question of how to use this plugin, please post on StackOverflow with the tags jspdf and jspdf-autotable.

If you have found a bug, try to describe it in a way that makes it possible to reproduce. Code is always helpful, and live code even more so. Here is a [codepen](http://codepen.io/someatoms/pen/EjwPEb) with `jspdf` and `jspdf-autotable` included that you can fork.

**Comment by simonbengtsson** [comment]
Not enough info

**Comment by Ambi1** [comment]
hi in my js  pdf im not able to align the table column width properly fro long text. you can see the screen shot.

**Comment by Ambi1** [comment]
![screenshot from 2019-02-25 14 27 56](https://user-images.githubusercontent.com/30460280/53329286-c4c54280-3911-11e9-91b9-55a97fbd0891.png)
