### ISSUE TITLE
column widht is getting broken

### ISSUE THREAD

**Issue by Ambi1** [simonbengtsson/jsPDF-AutoTable#458]
If you have a question of how to use this plugin, please post on StackOverflow with the tags jspdf and jspdf-autotable.

If you have found a bug, try to describe it in a way that makes it possible to reproduce. Code is always helpful, and live code even more so. Here is a [codepen](http://codepen.io/someatoms/pen/EjwPEb) with `jspdf` and `jspdf-autotable` included that you can fork.

**Comment by Ambi1** [comment]
![screenshot from 2019-02-25 14 27 56](https://user-images.githubusercontent.com/30460280/53325559-9b081d80-3909-11e9-9e3c-aeffcd0f1673.png)
hi im geting this issue, column widht is breaking in pdf

**Comment by simonbengtsson** [comment]
Closing since not following the issue template. Please reformat and open a new issue.

**Comment by Ambi1** [comment]
Hi simonbengtsson,
Is nested tables supports for Jspdf generating??
code::

<table name="qrtable" id="qrtable" class="main-para1" width="88%"
cellspacing="0" cellpadding="8" border="0">
<tbody id="trqrtable" name="trqrtable">
<tr>
<td>
<div class="qr_div" div_seq="1" id='tablerow1'>
<table width="100%">
<tr>
<td width="75%">
<input type="text" name="qrid1" id="qrid1" qrid_seq="1" class="qridclass"
value="QR-01">
<textarea id="qrcontent1" name="qrcontent1" qrcon_seq="1" class="qrconclass
qrtext" value="" placeholder="Embed your message here"></textarea>
</td>
<td width="19%">
<div id="container1" class="qrimage"></div>
</td>
<td width="6%"></td>

</tr>
</table>
</div>

<div class="qr_div" div_seq="2" id='tablerow2'>
<table width="100%">
<tr>
<td width="75%">
<input type="text" name="qrid2" id="qrid2" qrid_seq="2" class="qridclass"
value="QR-02">
<textarea id="qrcontent2" name="qrcontent2" qrcon_seq="2" class="qrconclass
qrtext" value="" placeholder="Embed your message here"></textarea>
</td>
<td width="19%" >
<div id="container2" class="qrimage"></div>
</td>
<td width="6%"></td>

</tr>
</table>
</div>

<div class="qr_div" div_seq="3" id='tablerow3'>
<table width="100%">
<tr>
<td width="75%">
<input type="text" name="qrid3" id="qrid3" qrid_seq="3" class="qridclass"
value="QR-03">
<textarea id="qrcontent3" name="qrcontent3" qrcon_seq="3" class="qrconclass
qrtext" value="" placeholder="Embed your message here"></textarea>
</td>
<td width="19%">
<div id="container3" class="qrimage"></div>
</td>
<td width="6%"></td>
</tr>
</table>
</div>
</td>
</tr>


</tbody>
</table>.
