### ISSUE TITLE
custom font does not work (chinese)

### ISSUE THREAD

**Issue by Neilai** [simonbengtsson/jsPDF-AutoTable#459]
var doc = new jsPDF()
    data.styles={font:"yahei",fontStyle:"normal"}
    doc.addFont('yahei.ttf', 'custom', 'normal');
    doc.setFont('custom');
    data.theme="plain"
    doc.text(15, 15, '测试');//the text outside table  display correctly 
    doc.autoTable(data); //the text in the table does not work 
    doc.save('table.pdf');

any body can help me

**Comment by prakashsam** [comment]
@Neilai  see the example custom function in example.js. they clearly mentioned how to add custom fonts. its working fine.

**Comment by Neilai** [comment]
> @Neilai see the example custom function in example.js. they clearly mentioned how to add custom fonts. its working fine.

thank you ! ! ! i  solve it
