### ISSUE TITLE
custom fonts working fine. how to add multiple fonts in one file ?

### ISSUE THREAD

**Issue by prakashsam** [simonbengtsson/jsPDF-AutoTable#460]
Really thanks for implement custom fonts. Its working fine but 
I have multiple languages in one PDF export using Anuglar5 ,JSPDF and Jspdf autotable. . how to do for multiple fonts in Jspdf autotable. Please refer the screenshots.
If i use Japanse or Arabic fonts working fine for particular language.

![52692007-ae6dcd00-2f88-11e9-81fc-f647b80ca0bc](https://user-images.githubusercontent.com/7478698/53415109-5908d580-39f6-11e9-92e8-8f074037e49d.png)

**Comment by simonbengtsson** [comment]
Can you post the code you are using?

**Comment by prakashsam** [comment]
@simonbengtsson   I created two fonts Arabic (Amiri font) and japanse ( mitubachi font ) and added the js files in index.html in your examples.  please the below code.
```
var japanseArra = [
    {
        "questionId": 1,
        "answer": "Arabic : قبعة هو جنسك",
    }, {
        "questionId": 2,
        "answer": "Japanse : お名前は何ですか",
    }
]

// Custom style - shows how custom styles can be applied
examples.custom = function () {
    var doc = new jsPDF();
    doc.autoTable({
        head: headRows(),
        body: bodyRows(),
        foot: headRows(),
        startY: 37,
        columnStyles: {
            name: {
                font: 'mitubachi',
                font: 'Amiri',
            },
        },
        allSectionHooks: true,
    });
    return doc;
};
```

**Comment by simonbengtsson** [comment]
`{font: 'mitubachi',font : 'Amiri' }` will become `{font : 'Amiri' }` when parsed by javascript. You can test by pasting that object in a browser console. You need to make use of the hooks to specify specific row or cell styles. Checkout the `custom styles` example.
