### ISSUE TITLE
First row content missing when using a rowspan that breaks page

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [simonbengtsson/jsPDF-AutoTable#461]
When a rowspan breaks through a page, the first row  is blank
https://glitch.com/edit/#!/prairie-park

**Comment by simonbengtsson** [comment]
Duplicate of #446. But will keep this one open instead since better described.

**Comment by rong4188** [comment]
Hi,
Does anyone get any fix or workaround on this?

Thanks,
Roni

**Comment by simonbengtsson** [comment]
Merged @rong4188 that might have fixed this. It's included in 3.1.1. Let me know if it works for you 👌
