### ISSUE TITLE
Color of header row in jspdf does not change for the first time.It changes in the next iteration. I am using jspdf autoTable.

### ISSUE THREAD

**Issue by khoslamehak** [simonbengtsson/jsPDF-AutoTable#464]
If you have a question of how to use this plugin, please post on StackOverflow with the tags jspdf and jspdf-autotable.

If you have found a bug, try to describe it in a way that makes it possible to reproduce. Code is always helpful, and live code even more so. Here is a [codepen](http://codepen.io/someatoms/pen/EjwPEb) with `jspdf` and `jspdf-autotable` included that you can fork.

**Comment by simonbengtsson** [comment]
Does not follow issue template.

**Comment by khoslamehak** [comment]
I have created table using jspdf and i am using drawheaderCell hook to change the color of header row using a if condition data.column.raw.title.localeCompare("a"||"b"||"c") where a,b,c are title of column array that we pass pdf.autotable(columns,row,{
drawHeaderCell:function(cell,data){
 if(data.column.raw.title.localeCompare("a"||"b"||"c") ){
cell.styles.fillColor=[r,g,b]
}
}.

so this condition does not work in the first case however in the next case when table continues on next page and header is created again the conditon work and changes the color. 
https://stackoverflow.com/questions/33506442/how-to-customize-header-cell-in-pdf-using-jspdf-autotable-plugin
Something pointed by user3571779 on above webpage.

I can't share the code as it is confidential. Hope that give u some hint about the problem
