### ISSUE TITLE
I am not able to get my example to word wrap long text.

### ISSUE THREAD

**Issue by cardenasivan** [simonbengtsson/jsPDF-AutoTable#471]
I'm using the example they provided.

      var ORDERID, ORDERNUMBER, PICKEDDATETIME = "50";
        var LOCATION = "50";
        doc.text("Overflow 'ellipsize' with one column with long content", 14, 20);
        doc.autoTable({
            head: pdfHead,
            body: pdfBody,
            startY: 25,
            // Default for all columns
            styles: { overflow: 'ellipsize', cellWidth: 'wrap' },
            // Override the default above for the text column
            columnStyles: { LOCATION: { cellWidth: 'wrap' } }
        });

        doc.text("Overflow 'linebreak' (default) with one column with long content", 14, doc.autoTable.previous.finalY + 10);
        doc.autoTable({
            head: pdfHead,
            body: pdfBody,
            startY: doc.previousAutoTable.finalY + 15,
            bodyStyles: { valign: 'top' },
            styles: { cellWidth: 'wrap', rowPageBreak: 'auto', halign: 'justify' },
            columnStyles: { LOCATION: { cellWidth: 'auto' } }
        });

        doc.putTotalPages(totalPagesExp);

        doc.save(pdfPrintElement.filename ? pdfPrintElement.filename: 'myPDF.pdf');

it is generating this pdf
[myPDF (1).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/2997300/myPDF.1.pdf)

**Comment by cardenasivan** [comment]
I'm attaching a code pen
https://codepen.io/Cardenasivan/pen/pYqKvP

**Comment by simonbengtsson** [comment]
With the codepen it seems like it is working?
<img width="793" alt="Screenshot 2019-03-23 at 12 36 51" src="https://user-images.githubusercontent.com/3586691/54865617-5a64be00-4d68-11e9-97b8-8f38ed6e0718.png">

**Comment by cardenasivan** [comment]
yeah i figured it out i had to change the body to a json array instead of an array and instead of using head i used cells
