### ISSUE TITLE
jsPDF-AutoTable not working in Firefox 42

### ISSUE THREAD

**Issue by digambarvs** [simonbengtsson/jsPDF-AutoTable#476]
Hi
jspdf-autotable plugin does not print cell values, only prints Layout in FireFox build 42.0 ( Its working in Firefox 65 though )

Is there any Change in miminum browser version supported for jspdf ?

Link Tried : https://simonbengtsson.github.io/jsPDF-AutoTable/#minimal

**Comment by simonbengtsson** [comment]
Weird! Do you get any errors in the console?

**Comment by sagarsalian** [comment]
No, did not get any errors in console .PDF file was generated and it displayed layout ,but no cell values are shown (ie., column and row values are not printed ).
sample export pdf link :   https://codepen.io/vishpatel93/pen/zjOEwj

**Comment by sagarsalian** [comment]
Looks like in function printRow(row) not able to get cell.text Value in firefox version 42.
code -->
 var cell = row.cells[column.dataKey];
 //alert("cell text val="+cell.text)

Note : 
latest version of  jspdf.plugin.autotable.js was used

**Comment by sagarsalian** [comment]
hi,
Found the problem , looks like in older browser Firefox version 42 ,
content.innerText is undefined , so use content.innerHTML if  innerText is undefined.

Solution :
Function name  : function Cell(raw, themeStyles, section){....}

**Code :** 
if (content && fromHtml) {
/// Fix 
        if(content.innerText === undefined) {
                text = (content.innerHTML || '').replace(/' '+/g, ' ').trim();
            }else{
                text = (content.innerText || '').replace(/' '+/g, ' ').trim();//original code 
            }
 //
}

please fix this issue

**Comment by simonbengtsson** [comment]
Great that you find it! Can you send a PR? I'll merge it asap!
