### ISSUE TITLE
AcroForm support

### ISSUE THREAD

**Issue by sirhcybe** [simonbengtsson/jsPDF-AutoTable#477]
I need to create some dynamic PDFs of a form with fillable fields and the layout capabilities of jsPDF are not great. It would be great to use something like AutoTable to layout my form but I need AcroForm fields inside my table and AutoTable doesn't support that. Is this something that can be added to the library?

**Comment by sirhcybe** [comment]
BTW, I started working on this on my own fork. If you want it when I'm done, I can PR it.

**Comment by reinerBa** [comment]
Well it is possible, i found this [example](https://codepen.io/someatoms/pen/vLYXWB?editors=1010) and changed to code to insert an image to insert an acroform 

`    didDrawCell: function(data) {
      if (data.column.index === 5 && data.cell.section === 'body') {
         var td = data.cell.raw;
         var img = td.getElementsByTagName('img')[0];
         var dim = data.cell.height - data.cell.padding('vertical');
         var textPos = data.cell.textPos;
var textField = new TextField()
textField.multiline = true
textField.Rect = [textPos.x,  textPos.y, 30, 10];
doc.addField(textField);
        //doc.addImage(img.src, textPos.x,  textPos.y, dim, dim);0
      }
    }`
