### ISSUE TITLE
Cell border is not printed when a cell has rowspan which breaks page.

### ISSUE THREAD

**Issue by rong4188** [simonbengtsson/jsPDF-AutoTable#480]
![image](https://user-images.githubusercontent.com/10201833/55600585-230afe00-57b9-11e9-8b44-aa9c17199e1a.png)

When a rowspan breaks through a page, the first several rows with rowspan cells in the second page has no border.

**Comment by simonbengtsson** [comment]
Interesting, do you have any minimal sample code to reproduce this with?

**Comment by simonbengtsson** [comment]
Is this the same as can be observed currently in the row and colspan example?

**Comment by rong4188** [comment]
@simonbengtsson yes I think so. When a rowspan cell breaks through page, the method doc.rect is called when rendering the cell. Then after a new page is added, it won't call doc.rect again to print cell border because it doesn't have any information about the cell which has already been rendered in the last page. it seems that some extra information and calculation would be needed when cell height > page remaining space.

**Comment by Fr4gger** [comment]
Hello. Thanks for the great work with this plugin. Is there a solution yet for this issue? I've encountered this when there are columns breaking to a new page with a colspan of a large number. Thanks in advance.

**Comment by rong4188** [comment]
@Fr4gger I am just using the version I modified as above commits at the moment, but it doesn't seem to be merged so far. it is not a complicated fix so probably you can just go through the commits and modify  your local code to see if it works for you.

**Comment by okon3** [comment]
@rong4188 Your pull requests are both closed

**Comment by Fr4gger** [comment]
@rong4188 Thanks for the suggestion. I am trying this right now. I'll let you know the results. One question though, do I need to compile the code again? If so, how can I do that? Currently I am pointing to jspdf.plugin.autotable.js, should I point to /src instead? Thanks in advance.

**Comment by rong4188** [comment]
@okon3 yep the PR is closed by bot. there is nothing I can do at the moment.

**Comment by rong4188** [comment]
@Fr4gger you can simply try to find the nearby code piece in jspdf.plugin.autotable.js then modify it as the PR, just to see if it works for you.

**Comment by Fr4gger** [comment]
@rong4188 thanks for your help. Unfortunately after changing the code with the lines you added the result is the same. It is not working for me. Do you know if there is any kind of solution planned to be released in order to fix this issue in the near future? This is the result I am getting with tables using colspan:

![Screen Shot 2019-05-15 at 2 23 42 PM](https://user-images.githubusercontent.com/15266115/57803140-4b253f80-771d-11e9-8413-b43e43fbd0f1.png)

Any help would be greatly appreciated.

**Comment by rong4188** [comment]
@Fr4gger Hi, I just open another pull request includes the jspdf.plugin.autotable.js. can you just download it and give a shot?

**Comment by Fr4gger** [comment]
@rong4188 Thanks for opening the PR for me to test. Unfortunately I am getting the same error.

![Screen Shot 2019-05-16 at 9 01 13 AM](https://user-images.githubusercontent.com/15266115/57859924-81b09800-77b9-11e9-8504-7177528ed4fd.png)

Thanks anyway. I hope the issue could be solved in the future.

**Comment by rong4188** [comment]
@Fr4gger hmm, do you have a working site that I can have a look at it? or a minimal example with your data?

**Comment by Fr4gger** [comment]
@rong4188 Unfortunately there is no instance available that isn't local yet for our project. But I created a little example in jsfiddle containing the data which I am using to build the table, and the html built table using the data. The js container only has a variable with the data and it is not used to build the table, but the result in the html container is the table which is breaking when trying to export to PDF.

[https://jsfiddle.net/Thunderlight/j389prsy/8/](https://jsfiddle.net/Thunderlight/j389prsy/8/)

**Comment by simonbengtsson** [comment]
Should be fixed in v3.1.3

**Comment by csarellano** [comment]
Hey @simonbengtsson just to let you know that this error shows up again in release v3.2.0. With the latest version v3.2.4 I am getting something like this in the second page.

![image](https://user-images.githubusercontent.com/15254800/63363051-821c7a00-c338-11e9-96ca-a58da9957e80.png)

In version v3.1.3 everything is ok besides that cell without background. The next image is the second page with the same data as the table above.

![image](https://user-images.githubusercontent.com/15254800/63363680-ac226c00-c339-11e9-8531-b7ca9c0ff70b.png)

**Comment by simonbengtsson** [comment]
Interesting! Can you create a new issue with some sample code?

**Comment by Supanutw** [comment]
@rong4188 
how to merge row
<img width="409" alt="Screen Shot 2565-04-04 at 12 27 09" src="https://user-images.githubusercontent.com/15275171/161479438-1a68ab1b-349d-4906-85a9-8a344dab2a76.png">
