### ISSUE TITLE
Rowspan not showing correctly

### ISSUE THREAD

**Issue by bablukpik** [simonbengtsson/jsPDF-AutoTable#481]
I am getting an issue of the jsPDF-AutoTable. It is not showing correctly please see the link below
Here is a [codepen](https://codepen.io/bablukpik/pen/mgrbZG)  or [jsfiddle](https://jsfiddle.net/bablukpik/vh0g789L/7/) with `jspdf` and `jspdf-autotable`

**Comment by bablukpik** [comment]
Please see the following links to find the issue of rowspan
1. https://jsfiddle.net/bablukpik/vh0g789L/7/
2. https://codepen.io/bablukpik/pen/mgrbZG
3. https://stackoverflow.com/questions/55551964/rowspan-issue-in-jspdf-autotable

**Comment by simonbengtsson** [comment]
It seems the linked codepen or jsFiddle doesn't work. Also, can you check if this is related to the other open issue related to this?

**Comment by bablukpik** [comment]
Thanks Sir for responding immediately, but can you give me a link for this related issue?

**Comment by simonbengtsson** [comment]
There are three open issues with the tag bug. Take a look at them and see if any applies.
