### ISSUE TITLE
Issue with extra spaces being added to the PDF

### ISSUE THREAD

**Issue by cardenasivan** [simonbengtsson/jsPDF-AutoTable#483]
this is the link to the code pin i created 
https://codepen.io/Cardenasivan/pen/pYqKvP

**Comment by simonbengtsson** [comment]
Seems like a bug! Can find what is causing the issue? If you create create a minimal example that has one cell without any config does it still happen? If not, what config or content make it appear?

**Comment by cardenasivan** [comment]
it doesn't happen when i have only one cell. Problem happens when i have multiple cells. Maybe because i have multiple cells that has long data. I created a new code pin with with only one cell having the issue. but the text looks correct. https://codepen.io/Cardenasivan/pen/Nmdaxg?editors=1010

**Comment by cardenasivan** [comment]
The issue i think could be is i'm trying to be able to wrap multiple columns. In your example it only shows 1. Is it possible to wrap more than just one column.
