### ISSUE TITLE
CDNJS

### ISSUE THREAD

**Issue by DataTables** [simonbengtsson/jsPDF-AutoTable#49]
Any chance we might see your awesome library on cdnjs.com?

[It looks like they are using npm](https://github.com/cdnjs/cdnjs) for submissions now, so a package.json file would be needed.

**Comment by someatoms** [comment]
That would be great indeed! I'll see what I can do, but I'm not sure it would be accepted. Their policy states that "Libraries must have notable popularity: 100 stars or watchers on GitHub".

**Comment by DataTables** [comment]
I've added one more... :-)

**Comment by someatoms** [comment]
Haha thanks! And I can't thank you enough for DataTables, have been using it in a lot of projects recently.

**Comment by simonbengtsson** [comment]
The plugin is now finally on [cdnjs](https://cdnjs.com/libraries/jspdf-autotable)!
