### ISSUE TITLE
jpsdf mit license

### ISSUE THREAD

**Issue by teodoro1991** [simonbengtsson/jsPDF-AutoTable#492]
Hello,
first of all congratulations for your jspdf software.
I have a question to ask.
I'm going to use jspdf on my web platform. Jspdf is open source.
I'm reading the license here:
https://github.com/MrRio/jsPDF/blob/master/MIT-LICENSE.txt

but I didn't understand this part:
"The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software. "

What does it mean? should I put the copyright notice in the source code? is it also necessary to put it in the final generation of the pdf?

Thank you

**Comment by simonbengtsson** [comment]
You don’t need it in the pdf, but might need to have it some place in your project. Most professional apps and websites have a dedicated section hidden somewhere where they list licenses and project names.

**Comment by teodoro1991** [comment]
I m not have this section. I could put your copyright in the header html
tag code?
Thanks

Il ven 19 apr 2019, 14:06 Simon Bengtsson <notifications@github.com> ha
scritto:

**Comment by simonbengtsson** [comment]
For the `jspdf-autotable` plugin I would personally not care if you didn't include the license at all. If you have requirements from your company etc to follow licence laws etc you probably need to make the licence available somewhere that the user can access it. I'm not really the right person to ask about licenses though.

**Comment by teodoro1991** [comment]
Ok not problem, but i where put the license? In the source code is ok?
Where put it? I m not understand..

Il ven 19 apr 2019, 21:51 Simon Bengtsson <notifications@github.com> ha
scritto:

**Comment by simonbengtsson** [comment]
Sorry, can't help you there. The only thing I know is that many mobile apps puts a link to it in settings.

**Comment by teodoro1991** [comment]
sorry but autotable's software didn't you create yourself? where do you
want me to put your license? I do not understand the issue ..



Il ven 19 apr 2019, 22:03 Simon Bengtsson <notifications@github.com> ha
scritto:

**Comment by simonbengtsson** [comment]
Yes I did and if you ask me, don't bother with autotable's license. Just use the plugin. For my sake you don't need to include the license it anywhere. The only reason it's there is that having no license is more restrictive than an MIT license.

If you have legal requirements from your company to disclose licenses etc thats another story and you might have to read up on how to do it properly to fulfil your companies requirements etc.

**Comment by teodoro1991** [comment]
Ok, but in this link:
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/LICENSE.txt

It is write that autotable is under mit license..you said no now .. I don't
understand

Il sab 20 apr 2019, 08:08 Simon Bengtsson <notifications@github.com> ha
scritto:

**Comment by simonbengtsson** [comment]
I think we are going around in circles here 😄To be safe for legal reasons you can read up on how to handle MIT licenses, but I will never enforce or care about it. Good luck!
