### ISSUE TITLE
Cannot set property 'autoTable' of undefined

### ISSUE THREAD

**Issue by skitscha** [simonbengtsson/jsPDF-AutoTable#494]
I've been running into some issues with the current version of JSPDF. So, I attempted to build the latest version of JSPDF locally and get the following error when I try to launch my website with JSPDF auto table enabled:
![image](https://user-images.githubusercontent.com/25359125/56630075-9021ee80-6615-11e9-8a32-208d9b240ad4.png)
Does anyone have any ideas on what could be causing this?

**Comment by simonbengtsson** [comment]
It seems `jspdf` is not loaded correctly. Can you verify that creating a pdf document without autotable works?
