### ISSUE TITLE
addPage not reset y cursor

### ISSUE THREAD

**Issue by ulumjoe** [simonbengtsson/jsPDF-AutoTable#495]
I'm using didDrawCell hook to add page when table is in some y position, but it seems that after new page, startY is not reseting to 0, but continue the previouse. did I do wrong in my code.
Sorry for my bad english
here's code pen I try to explain

https://codepen.io/anon/pen/QRwPbd

**Comment by ulumjoe** [comment]
No response? perhaps i need to go back to previous version

**Comment by simonbengtsson** [comment]
There was a confusion about tables getting stacked in v2 so in v3 the Y position is not reset. You can reset it manually though.

**Comment by ulumjoe** [comment]
Oke thanks for your reply.

**Comment by patelpratikd** [comment]
Hello @simonbengtsson,

Can you please tell how to reset it manually?
