### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by cedriccharles4** [simonbengtsson/jsPDF-AutoTable#502]
Hi there !

I'm using Autotable and everything is perfectly working, except on IE 11. On IE 11, I have a JS error in the console with "getStringUnitWidth". Is Autotable compatobile with IE11 ?

Thank you in advance!

**Comment by simonbengtsson** [comment]
Should be working with IE11! Can you post the entire error message?

**Comment by cedriccharles4** [comment]
Hi Simon!

Thank you for your answer! Here is the screenshot of the error (it's in french): https://snag.gy/TwAVJt.jpg

`L'objet ne gère pas la propriété ou la méthode "getStringUnitWidth"`

Thank you in advance!

**Comment by cedriccharles4** [comment]
The error line is this one:
 `var width = state_1.default().doc.getStringUnitWidth(line);`

**Comment by simonbengtsson** [comment]
Weird! Let me know if you find a fix!

**Comment by cedriccharles4** [comment]
Hi Simon,

I  unfortunately can't find a fix :(

**Comment by cedriccharles4** [comment]
I have finally found the issue! This was a problem with "Pomise" undefined. I've included this script (only for IE11):
`<script type="text/javascript">
	var ua = window.navigator.userAgent;
	var msie = ua.indexOf("MSIE ");
	if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
		document.write('<script src=https:\/\/cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.5/bluebird.min.js><\/script>');
	}
</script>`
and the download works in IE11!

But I have now another problem, only with IE11. In my table, I have an autocomplete input field. When I type something in that field, it gives me a list of choices. When I've made my choice, the list is hidden with a display:none. But when I download the PDF in IE11 (only with IE11), that list is visible. Not with other browsers. 
PDF generated with IE 11 (not ok): https://snag.gy/zAKwdq.jpg
PDF generated with Chrome (ok): https://snag.gy/9p4lE5.jpg

You can try this there : https://noel-marquet.be/en/glue-consumption/

Thank you in advance,
Cedric

**Comment by simonbengtsson** [comment]
Nice find! Can you verify this is an issue with jspdf and not jspdf-autotable? I don't think this plugin uses any promises.

**Comment by cedriccharles4** [comment]
Ok, I will! Could you please have a look at my other issuer or maybe tell me how I can be sure that a "display:none" element is not displayed in IE11?

Thank you !

**Comment by simonbengtsson** [comment]
Interesting! Can you create a new issue with this with the code you are using? Btw, got the same issue in chrome if I exported the pdf when the menu is still open.
<img width="967" alt="Screenshot 2019-06-12 at 10 50 12" src="https://user-images.githubusercontent.com/3586691/59336967-de8f6780-8cff-11e9-8561-c07d92a6e1be.png">

**Comment by simonbengtsson** [comment]
Seems that it was an issue with using a too recent version of jspdf which dropped support for IE11.
