### ISSUE TITLE
autoTable is undefined using CDN

### ISSUE THREAD

**Issue by madskunker** [simonbengtsson/jsPDF-AutoTable#506]
I have added both CDN's provided in the readme into my html page.  

const doc = new jsPDF();
doc.autoTable({html: '.ReportBody'});
doc.save('table.pdf');

autoTable is undefined

**Comment by simonbengtsson** [comment]
Can you provide which cdn you are using and the code for including it?

**Comment by Bryan988** [comment]
Any update ? 

I have the same issue. I am using jspdf@1.5.3 and jspdf-autoTable@3.5.23. 
Any help would be appreciated. 

Thank you
