### ISSUE TITLE
Blank first page when exporting table

### ISSUE THREAD

**Issue by dnlbaldwin** [simonbengtsson/jsPDF-AutoTable#507]
This appears to be similar to issue 365, however it does not require a large data-set.

Here's the fiddle: https://jsfiddle.net/ny5ck6vr/

Reproduced this issue in Chrome 75.0.3770.90 and Firefox 67.0.2

**Comment by simonbengtsson** [comment]
Probably duplicate of #508 so will close it now and add the helpful jsfiddle in that issue.

**Comment by rong4188** [comment]
@simonbengtsson @dnlbaldwin Hi, actually I don't think this is a bug. You can try make the param startY as a number rather than a string, which can fix this issue in fiddle.
![image](https://user-images.githubusercontent.com/10201833/60632270-db981a80-9e58-11e9-9e13-01b1fcc39fd9.png)
