### ISSUE TITLE
Text gets streched on IE browser

### ISSUE THREAD

**Issue by suryarsp** [simonbengtsson/jsPDF-AutoTable#512]
I use doc.text('longtext',x,y). But it appears like this

![image](https://user-images.githubusercontent.com/21018485/59920768-39843580-9449-11e9-807c-81b5a9ef6317.png)
I have commented the code below

**Comment by suryarsp** [comment]
=` let doc = new jsPDF('l', 'pt', 'a4', true);
          doc.setFontSize(12);
          doc.setFillColor(0, 0, 0);

          // Print Index
          doc.rect(40, 20, 762, 25, 'S');
          doc.setTextColor(0, 0, 0);
          doc.text('Print Index', 73, 35, 'center');

          // Print Info
          doc.rect(40, 45, 762, 59, 'S');
          let data = [
               ['Printed by : ', this.props.WebPartContext.pageContext.user.displayName],
               ['Printed On : ', currentDate]
          ];
          doc.autoTable({
               startY: 50,
               tableWidth: 'auto',
               body: data,
               theme: 'plain',
               willDrawCell: (hook) => {
                    let cell = hook.cell;
                    if(cell.raw.indexOf('Printed') === -1) {
                         cell.textPos.x = cell.textPos.x  - 110;
                    }
               },
               styles: {
                    halign: 'left',
                    fontSize: 12,
                    cellWidth: 'wrap',
                    textColor: [0,0,0]
               },
          });`

**Comment by suryarsp** [comment]
` let doc = new jsPDF('l', 'pt', 'a4', true);
          doc.setFontSize(12);
          doc.setFillColor(0, 0, 0);
         doc.rect(40, 20, 762, 25, 'S');
          doc.setTextColor(0, 0, 0);
          doc.text('Print Index', 73, 35, 'center');
          doc.rect(40, 45, 762, 59, 'S');
          let data = [
               ['Printed by : ', this.props.WebPartContext.pageContext.user.displayName],
               ['Printed On : ', currentDate]
          ];
          doc.autoTable({
               startY: 50,
               tableWidth: 'auto',
               body: data,
               theme: 'plain',
               willDrawCell: (hook) => {
                    let cell = hook.cell;
                    if(cell.raw.indexOf('Printed') === -1) {
                         cell.textPos.x = cell.textPos.x  - 110;
                    }
               },
               styles: {
                    halign: 'left',
                    fontSize: 12,
                    cellWidth: 'wrap',
                    textColor: [0,0,0]
               },
          });`

**Comment by suryarsp** [comment]
` let doc = new jsPDF('l', 'pt', 'a4', true);
          doc.setFontSize(12);
          doc.setFillColor(0, 0, 0);

          // Print Index
          doc.rect(40, 20, 762, 25, 'S');
          doc.setTextColor(0, 0, 0);
          doc.text('Print Index', 73, 35, 'center');

          // Print Info
          doc.rect(40, 45, 762, 59, 'S');
          let data = [
               ['Printed by : ', this.props.WebPartContext.pageContext.user.displayName],
               ['Printed On : ', currentDate]
          ];
          doc.autoTable({
               startY: 50,
               tableWidth: 'auto',
               body: data,
               theme: 'plain',
               willDrawCell: (hook) => {
                    let cell = hook.cell;
                    if(cell.raw.indexOf('Printed') === -1) {
                         cell.textPos.x = cell.textPos.x  - 110;
                    }
               },
               styles: {
                    halign: 'left',
                    fontSize: 12,
                    cellWidth: 'wrap',
                    textColor: [0,0,0]
               },
          });`

**Comment by simonbengtsson** [comment]
If the issues is related to `doc.text()` you can report it in the `jspdf` repo instead.
