### ISSUE TITLE
Text unaligned when column is too narrow

### ISSUE THREAD

**Issue by rong4188** [simonbengtsson/jsPDF-AutoTable#514]
Text is wrapped incorrectly when column is too narrow. It seems like it calculates text lines incorrectly.
![image](https://user-images.githubusercontent.com/10201833/60699117-a0741500-9f46-11e9-97fb-ba0bc25c5854.png)
![image](https://user-images.githubusercontent.com/10201833/60699622-e4681980-9f48-11e9-92af-e36746e42772.png)

https://jsfiddle.net/b69s4cqw/1/

**Comment by simonbengtsson** [comment]
Except for that the row becomes higher than it should, this is actually works as intended. If you add up your specified widths it becomes equal to page width, but wider than table width because of margin. If you set `margin: 0` you can see that the width calculation is correct.
