### ISSUE TITLE
Known issues that can be seen in examples

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#515]
- [x] Sometimes text dimension calculation wrong in long text example (height and width)
- [x] The D in ID not visible in multiple tables example
- [x] Rowspan alignment off when breaking row (rowspan example) (not fixed but tracked in #532)
- [x] Row wrapping weird in from html with css example

**Comment by Marcus-Tecnica-Ltd** [comment]
Hello Simon,

I have been looking at using your jsPDF AutoTable plugin for a reporting application which I am developing for a customer as the conversion from JSON data / HTML table to PDF feature is exactly what I need to implement. I got the plugin with the latest version working, however the data which I am submitting to the PDF can change depending on what the user wishes to report on. This causes problems with the text displayed in each column. The default overflow option is 'linebreak' which is working, however the break occurs in the middle of words, making the data difficult to read.

I was wondering if you could provide any insight as to a configuration for the plugin which would allow for 'linebreak' to occur on spaces as opposed to breaking up words to make the data easier to read.

I will continue to see if I can resolve the problem myself, but if there is any information which you can provide which may help, that would be much appreciated.

Kind Regards,

Marcus

**Comment by simonbengtsson** [comment]
I consider that a bug. It doesn't behave like that in the examples. Can you submit a new issue following the issue template?

**Comment by dnlbaldwin** [comment]
You can also see in the basic example that when there are multiple IP addresses in a table cell, a newline character is not added between them.

e.g. You see 18.186.38.3718.123.22.82, instead of:
18.186.38.37
18.123.22.82

**Comment by simonbengtsson** [comment]
Fixed above issue in latest commit. Thanks for reporting @dnlbaldwin

**Comment by simonbengtsson** [comment]
The issue with wrong text dimensions seems to be an issue with `justify` alignment in jspdf https://github.com/MrRio/jsPDF/issues/2553
