### ISSUE TITLE
Linebreak occurs in middle of words; separating sections of words on different lines

### ISSUE THREAD

**Issue by Marcus-Tecnica-Ltd** [simonbengtsson/jsPDF-AutoTable#516]
jsPDF Version 1.5.3
AutoTable Version 3.1.1

The default behaviour the 'overflow' feature of the AutoTable is 'linebreak' however when pulling data from an HTML table into a PDF using the plugin, the linebreak appears to occur in the middle of words or at any point once it reaches the end the cell.

![image](https://user-images.githubusercontent.com/52526832/61057233-c0935080-a3ec-11e9-8066-ef59079f8ac9.png)

The image should display the issue more clearly. The problem occurs on both the column headers and the row data. My application does vary on the data which will be submitted to the PDF. It works by receiving the data in JSON format, parsing the JSON into an HTML table and then submitting the HTML table to PDF. I did try submitting the JSON data straight to the "AutoTable", however the same result occurred.

Expected result: 'linebreak' should separate strings at spaces as opposed to any character position in a word, otherwise the data is harder to read.

This issue will not occur unless you provide a lengthy amount of data and a good number of columns.

I have managed to replicate the issue (slightly) in a forked code pen.

Result from code pen:

![image](https://user-images.githubusercontent.com/52526832/61057598-870f1500-a3ed-11e9-92c8-a22059ca30f1.png)

Code pen: https://codepen.io/marcus-tecnica-ltd/pen/agMwMd

In terms of the "options" for the AutoTable used in the code pen in relation to the actual project's code, there is no difference. I have not set many strict options. Please note, this is the first of me using the plugin so this may be a result of lack of experience rather than an actual bug.

The data under "city" breaks at the end of "Edinburgh" with a single letter and similarly the serial code runs onto the next line as well. The other columns in this circumstance are fine, however since the data in my application is totally dependent on the what the user submits, this can vary from well presented data to the extreme where multiple columns suffer from this effect.

Is it possible to ensure that line breaking occurs where spaces are present as opposed to breaking up individual words? This is more of a readability issue than anything else. You can make sense of it; however, it would look better if words were not separated on multiple lines.

Please advise...

**Comment by simonbengtsson** [comment]
Currently it will break if there is no. I think it would be fairly easy to prioritize one word columns higher than lengthy text ones so this could be fixed. 

To fix this you can change the cellWidth style for all columns to `wrapped` except for service summary which you can set to `auto`. That way only that column will have line breaks. For an example of this you can check the `long text` example.

**Comment by Marcus-Tecnica-Ltd** [comment]
Since the data is pulled from an html table, do you reference the columns under "columnStyles" using integers or do columns correspond to the titles displayed in the table?

**Comment by simonbengtsson** [comment]
Yes, by integers/indices

**Comment by Marcus-Tecnica-Ltd** [comment]
Okay, I tested this on the same code pen and this is the result which was received: 
![image](https://user-images.githubusercontent.com/52526832/61060709-e02d7780-a3f2-11e9-94be-7b36f215e2aa.png)

https://codepen.io/marcus-tecnica-ltd/pen/agMwMd

I can see the benefit of the "cellWidth" feature and see how this would work where one column has longer text. The problem is these columns can swap order or become different columns depending on what the user decides to generate the report on. Though i think I can use the integer based references for the columns to my advantage and determine what columns should be 'wrapped' and which should be set to 'auto' and work something out from there.

What I'll do is continue to work on this over the course of next week and let you know if I can get the desired result using the "columnWidth" feature to my advantage coupled with code which determines the columns to apply varying widths to. Is there a way in which I can keep in touch with you to discuss this issue as opposed to leaving it open on here? I believe that correct usage of the plugin's styling features will fix it but it might take me some time to work out how to achieve the desired result when the data can change so drastically.

Thank you for the help, much appreciated.

**Comment by simonbengtsson** [comment]
Glad you think it will work out! Writing here is fine 👍

**Comment by simonbengtsson** [comment]
I looked into this now. The reason words are broken up is because the jspdf's text function works. It would probably be possible to prioritize breaking up columns with spaces first but not a feature I will add right now. If anyone else wants to implement it I would happily merge the PR though.
