### ISSUE TITLE
Nested Table in <td>

### ISSUE THREAD

**Issue by Nic-Grunklee** [simonbengtsson/jsPDF-AutoTable#522]
First off, thank you for creating a great library!

I have a nested table in a <td> that only shows up when there is more than one data point in the object used to build the table.  This nested table only shows up in a few rows with in the table. The rest of the table generates as normal, but for those cells with the nested table it creates an array of texts for the <th> and <td> elements in the nested table. So we are left with a text object for each row in the nested table, which is fine.  However, when the PDF builds, it adds white space in front the text object causing it to shift alignment.  When I inspect the data.cell.text there is no additional white space.  

Here are is an example of the text array that gets generated:

![image](https://user-images.githubusercontent.com/16216061/61800900-7dc17780-adf3-11e9-94e6-fb37590a6173.png)

Below is a photo of the webpage(first photo) and generated PDF(second photo).

![HTML](https://user-images.githubusercontent.com/16216061/61800577-e65c2480-adf2-11e9-88f0-ad89e4d4ce3e.png)

![PDF](https://user-images.githubusercontent.com/16216061/61800656-0ab80100-adf3-11e9-9b63-745ccef9b51a.png)

With this I am hoping to either create the subtable in the PDF or have the arrays of text be centered.

**Comment by Nic-Grunklee** [comment]
Can this be reopened? This is still an issue

**Comment by simonbengtsson** [comment]
Can you provide a minimal example highlighting the issue? Preferably as a jsfiddle or codepen.

**Comment by Nic-Grunklee** [comment]
Here is a limited example of the type of table that I am working with.

https://jsfiddle.net/jyohx8ka/1/

The issue is with the alignment on the PDF for the nested table.

**Comment by simonbengtsson** [comment]
Can you add autotable to the jsfiddle as well so I can see the issue?

**Comment by Nic-Grunklee** [comment]
Here is the fiddle with those libs added

https://jsfiddle.net/jyohx8ka/12/

**Comment by simonbengtsson** [comment]
Nice! And I assume those are the alignment issue? Should hopefully not be too hard for something to fix. Will mark it as `bug` and `help wanted`.

<img width="779" alt="Screenshot 2019-08-08 at 15 24 54" src="https://user-images.githubusercontent.com/3586691/62707109-13aef200-b9f1-11e9-9d66-07be6bc9c116.png">

**Comment by Nic-Grunklee** [comment]
Yes, that is correct.  It's also on the first set of percentages as well, just more noticeable on the second set. When I look at the cell data in the console, it has each row in the nested table listed as strings, rather than creating it to a new table.  

I appreciate you taking a look and for creating such a great tool!

**Comment by simonbengtsson** [comment]
Actually, nested tables are not supported when parsing html. The reason you got a table structure above was by chance. The plugin i simply generating a string of the table with `tdNode.innerText` and it happened to look like a table for you.

If you wanted nested tables you can use the `didDrawCell` hook and draw it manually.

**Comment by Nic-Grunklee** [comment]
Would you happen to have a small example of how that would work? I have
used the hooks before.

If not, that's okay.

**Comment by simonbengtsson** [comment]
Sure! Take a look at the `custom` example in `examples/examples.js`. There you see a bunch of customization being applied. For drawing on top of cells go with the `didDrawCell` hook.

**Comment by Nic-Grunklee** [comment]
I am not opposed to that, but would this nested table work if I were to use the actual data rather than html?

**Comment by simonbengtsson** [comment]
Sure the idea is that you draw the table manually in the didDrawCell hook. So any auto table config is possible. No run the below code but something like this:

```
doc.autoTable({
   html: '.table',
   didDrawCell: data => {
       doc.autoTable({
           tableWidth: data.cell.width,
           startY: data.cell.y,
           margin: {left: data.cell.x}
       })
   }
})
```

**Comment by Nic-Grunklee** [comment]
That's what I was thinking you had meant by it. I will have give it some thought as all the tables(nested included) are dynamically generated so that I wouldn't have a set id on the nested table.  

Thanks again!
