### ISSUE TITLE
Option useCss in combination with cell border results in no pdf borders in firefox, ie, edge

### ISSUE THREAD

**Issue by keesbaake** [simonbengtsson/jsPDF-AutoTable#524]
To replicate this bug, try adding a border in the css of the examples page: https://simonbengtsson.github.io/jsPDF-AutoTable/#/ 

In chrome a border will appear, but in the other browsers nothing appears. How to fix it?

**Comment by keesbaake** [comment]
So I did some debugging and found what is the issue:

If you are not using Chrome...  then for window.getComputedStyle() the borderWidth property on the returned CSS2Properties Object is empty. However, if you use HTMLElement.style.borderWidth you do get the correct value. 

I'm a bit reluctant to make the change and do a merge request as I'm not sure if we still want to use the getComputedValues or not. I think Simon Bengsten, the maintainer, has to decide.

**Comment by simonbengtsson** [comment]
Interesting! Maybe we could implement it as `window.getComputedStyle().borderWidth || HTMLElement.style.borderWidth` then? I'll experiment with firefox now.

**Comment by simonbengtsson** [comment]
Seems `borderWidth` is a shorthand only working in chrome. Replaced it with `borderTopWidth` which seems to work in firefox and internet explorer as well. Couldn't use `HTMLElement.style.borderWidth` since it only see the inline styles and not form external style sheets etc.

**Comment by qlum** [comment]
The exact same issue occurs with padding. 
Firefox does not support getComputedStyle().padding only the split variant: paddingTop, paddingRight, paddingBottom, paddingLeft

See: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#notes
