### ISSUE TITLE
First row missing when using autoTableHtmlToJson. Rows with style="display:none" not properly ignored when not using autoTableHtmlToJson.

### ISSUE THREAD

**Issue by ramseymardini** [simonbengtsson/jsPDF-AutoTable#525]
Hi,

When trying to use autoTableHtmlToJson the first row is never rendered. https://codepen.io/ramseymardini/pen/RXjKWz

When I try to not use autoTableHtmlToJson, all rows that should not be rendered (have style="display:none" are still rendered). https://codepen.io/ramseymardini/pen/mNqRWd

Also, the codepen seems to not be working correctly. I had to comment out the line "return this.doc.internal.getCurrentPageInfo().pageNumber;" for it to not throw an error in the console.

**Comment by simonbengtsson** [comment]
Could verify it locally as well. Will look into it asap.

**Comment by simonbengtsson** [comment]
Fixed on master, will be included in next release.

**Comment by ramseymardini** [comment]
Sweet thanks!
