### ISSUE TITLE
Keep columnStyles (cellWidth) with colspan

### ISSUE THREAD

**Issue by cplaiu** [simonbengtsson/jsPDF-AutoTable#526]
I am trying to create a four column table with colspan but with the width of the columns assigned by columnStyles, but if I don't add a row of four columns the colspan ignores the columnStyle.
 
An example:
https://codepen.io/anon/pen/oKodYj

If I remove line 16 of code the width of colspan change.

**Comment by simonbengtsson** [comment]
For reference: 

With the non colspan row (correct):

<img width="795" alt="Screenshot 2019-08-06 at 17 46 02" src="https://user-images.githubusercontent.com/3586691/62554914-4e3e5080-b872-11e9-84a0-88c3a3232104.png">


Without the row (bug):

<img width="800" alt="Screenshot 2019-08-06 at 17 48 22" src="https://user-images.githubusercontent.com/3586691/62554985-6a41f200-b872-11e9-8a8b-87015c148b9b.png">

**Comment by simonbengtsson** [comment]
Fixed in v3.2
