### ISSUE TITLE
How do I get autoTable to modify the contents of a cell prior to rendering in the PDF?

### ISSUE THREAD

**Issue by PaulMcGuinness** [simonbengtsson/jsPDF-AutoTable#527]
I've tried hooking into "didParseCell" and "willDrawCell" but as the data.cell is a reference to the DOM, and changes to it affect the rendered page.

I want to remove certain parts of the text (as it will be too long for the column etc...)

**Comment by simonbengtsson** [comment]
Not actually sure this is possible currently. But I have been wanting to refactor the html parsing code for a while now and will leave this open until done.

**Comment by simonbengtsson** [comment]
My memory was a little foggy. This is actually already possible. `data.cell` is a reference to an internal cell object in which you can modify the value of `data.cell.text` in the `willDrawCell` or `didParseCell` methods to change the text displayed in the table.

**Comment by PaulMcGuinness** [comment]
Excellent :-) Cheers

**Comment by nicolacardi** [comment]
data.cell.raw is a great option, but how do you extract parts of it. If I console.log it it looks like an object having content as a property, but data.cell.raw.content is not working...What kind of object is that?
