### ISSUE TITLE
JSPDF Autotable pdf write hanging IE and taking long time in Chrome

### ISSUE THREAD

**Issue by tharunbcbst** [simonbengtsson/jsPDF-AutoTable#529]
Using the basic below logic  to write the data into PDF in my React Application. During the below step the Chrome is taking almost 30-40 seconds and the IE is simply hanging with out downloading.

doc.autoTable({
        startY: 70,
        head: [['header1','header2'....]],
        body: data,
      });

Agree that, the data is large, (the above time is for 35K records (data Array in the body)).

But Is there any way to avoid the IE hanging issue or writing the data as chunks etc to improve the performance of PDF write.

**Comment by simonbengtsson** [comment]
Sadly not that that I know of.
