### ISSUE TITLE
Extra row getting added automatically for rows automatically

### ISSUE THREAD

**Issue by suryarsp** [simonbengtsson/jsPDF-AutoTable#530]
**Version: ^3.1.4
React Version: 16.7.0**
I am adding a header with column-span  to print items by group

---------------------------------------------------------------
 let doc = new jsPDF('l', 'pt', 'a4', true);
let head = [
    [{
        content: selectedItem.Group,
        colSpan: 6,
        styles: {
            halign: 'center',
            fillColor: [211, 211, 211]
        }
    }],
    {
        id: "No",
        item: "Item",
        responsibleParty: 'Responsible \n Party',
        status: "Status",
        comments: "Comments"
    }
];
doc.autoTable({
    startY: doc.autoTable.previous.finalY,
    tableWidth: 'auto',
    head: head,
    body: [{
        id: selectedItem.ID,
        item: selectedItem.Item,
        responsibleParty: selectedItem.ResponsibleParty,
        status: selectedItem.Status,
        comments: selectedItem.Comments
    }],
    theme: 'grid',
    margin: {
        left: 10,
        right: 10
    },
    didParseCell: (hook) => {
        let cell = hook.cell;
        if (cell.section === 'head') {
            cell.styles.textColor = '#000000';
        }
    },
    willDrawCell: (c) => {
        let cell = c.cell;
        let column = c.column;
        let row = c.row;
    },
    headStyles: {
        fillColor: [255, 255, 255],
        fontSize: 12,
        lineWidth: 0.5,
        lineColor: [0, 0, 0]
    },
    bodyStyles: {
        lineColor: [0, 0, 0],
        textColor: [0, 0, 0]
    },
    styles: {
        overflow: 'linebreak'
    },
    columnStyles: {
        id: {
            cellWidth: 5
        },
        item: {
            cellWidth: 100,
        },
        responsibleParty: {
            cellWidth: 7,
        },
        status: {
            cellWidth: 100,
        },
        comments: {
            cellWidth: 100,
        }
    }
});
doc.save('export.pdf');
---------------------------------------------------------------
I am getting an id row that's been added along with the body rows.
Uploaded the PDF for reference. I need to remove the id that's been adding for all rows
[export (8).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/3478014/export.8.pdf)
Kindly help me to fix this

**Comment by simonbengtsson** [comment]
I'm not sure I understand the issue. Can you format the code you posted? And preferably create a minimal example highlighting the issue?

**Comment by suryarsp** [comment]
It's because of the header that I have addded
`
let head = [
[{
content: selectedItem.Group,
colSpan: 6,
styles: {
halign: 'center',
fillColor: [211, 211, 211]
}
}],
];
`
Due to this an extra column is getting added up so I prevented it makinf the column width to 0.
### Using Hooks
`
willDrawCell: (c) => {
                                   let column = c.column;
                                   if(cell.raw === undefined) {
                                        column.width = 0;
                                   }
                              }
`

Now, this issue has been resolved.

**Comment by suryarsp** [comment]
> I'm not sure I understand the issue. Can you format the code you posted? And preferably create a minimal example highlighting the issue?

[export (25).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/3480326/export.25.pdf)
The first column is blank and it's because of that header
