### ISSUE TITLE
Cannot convert undefined or null to object if array is empty

### ISSUE THREAD

**Issue by cplaiu** [simonbengtsson/jsPDF-AutoTable#531]
I'm using the latest version of autoTable.

In the old version (3.1.4) if an empty array was assigned, the table was not displayed but in this version an error appears.

<img width="353" alt="img_error" src="https://user-images.githubusercontent.com/32199465/62770999-7f9a6480-ba9c-11e9-8deb-ae10ccd8437f.png">

**Comment by simonbengtsson** [comment]
True! Fixed now.
