### ISSUE TITLE
Impossible to set header cell width

### ISSUE THREAD

**Issue by KeystoneJack** [simonbengtsson/jsPDF-AutoTable#534]
Setting the header cell width is seemingly impossible. I have tried with the following and none of them work;

```
doc.autoTable({
    columns: [
        { header: "Description", dataKey: "desc" },
        { header: "Quantity", dataKey: "qty" },
        { header: "Unit price", dataKey: "unit_price" },
        { header: "Ext. price", dataKey: "total" },
    ],
    columnStyles: {
        desc: { columnWidth: 250 },
        qty: { columnWidth: 10 },
        unit_price: { columnWidth: 20 },
        total: { columnWidth: 20 },
    }
});
```
```
doc.autoTable({
    columns: [
        { header: "Description", dataKey: "desc" },
        { header: "Quantity", dataKey: "qty" },
        { header: "Unit price", dataKey: "unit_price" },
        { header: "Total", dataKey: "total" },
    ],
    columnStyles: {
        desc: { cellWidth: 250 },
        qty: { cellWidth: 10 },
        unit_price: { cellWidth: 20 },
        total: { cellWidth: 20 },
    }
});
```
I'm able to set all cells to a specific width but not individually

**Comment by simonbengtsson** [comment]
Weird! Will look into it right away.

**Comment by simonbengtsson** [comment]
The issue should only appear if the table should expand its column instead of shrinking them. It will expand columns passed the cellWidth property now.

**Comment by KeystoneJack** [comment]
@BrickBeard are you using autotable with a framework?

I’m beginning to suspect that it’s an issue with the framework I’m using (Angular). Some issues , not related to this one, disappear after a full refresh of the page.

Seems like hot reload sometimes cache stuff.

**Comment by eBaeza** [comment]
I have the same issue.

It happens if the header is longer than the content in the column. I´m trying to shrink the column but it´s not working.

**Comment by trongdn84** [comment]
columnStyles: {0:{columnWidth: 10}} same as all column as you wish

**Comment by trongdn84** [comment]
you must define index of column not name

**Comment by simonbengtsson** [comment]
Fixed in v3.2.5

**Comment by anuj509** [comment]
what is unit for column width ? and what max and min values ? is then any way to set it in percentage ?

**Comment by molinto** [comment]
Does columnWidth exist?

**Comment by mmghv** [comment]
@molinto 
> Does columnWidth exist?

`cellWidth: 'auto'|'wrap'|number = 'auto'`

https://github.com/simonbengtsson/jsPDF-AutoTable#styling-options
