### ISSUE TITLE
HTML rendering issue

### ISSUE THREAD

**Issue by sshenoy700** [simonbengtsson/jsPDF-AutoTable#538]
The html rendered inside the autotable breaks after upgrading to angular 8. All the li tags are displayed in one single line and if enter key is present then the entire structure breaks and displayed as one single line.

syntax used: 
doc.autotable({html: '#id_of_html_table'})
![Screenshot from 2019-08-27 12-21-53](https://user-images.githubusercontent.com/43390273/63747839-ad1d4580-c8c5-11e9-8b44-47a2cee0fd02.jpg)

**Comment by simonbengtsson** [comment]
This is likely an issue with your configuration. If you believe it is an issue with the plugin, can you try create a minimal example highlighting the issue.

**Comment by sshenoy700** [comment]
The above issue was fixed after i added the thead for the table.. But for the below the table,

html:
<table _ngcontent-nkv-c9="" class="summ_section assment_medication_holder mb-1" id="assmentTable"><thead _ngcontent-nkv-c9=""><tr _ngcontent-nkv-c9=""><td _ngcontent-nkv-c9="">Heading</td></tr></thead><tbody _ngcontent-nkv-c9=""><tr _ngcontent-nkv-c9=""><td _ngcontent-nkv-c9=""><p><strong><u>Assessment and Plan</u></strong>:&nbsp;</p><ol><li><strong>CNS/Psych</strong>:&nbsp;<span>ntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated by</span></li><li><strong>CVS</strong>:&nbsp;<span>ntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated by</span></li><li><strong>Resp</strong>:&nbsp;</li><li><strong>Abd/nutrition</strong>:&nbsp;</li><li><strong>Renal</strong>:&nbsp;<span>ntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated by</span></li><li><strong>ID:</strong>&nbsp;</li><li><strong>Skin:</strong>&nbsp;</li><li><strong>Endo:</strong>&nbsp;</li><li><strong>MSK:</strong>&nbsp;</li><li><strong>Prophylaxis:</strong>&nbsp;<span>ntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated byntegrity-hash generated by</span></li></ol></td></tr></tbody></table>

![Screenshot from 2019-08-27 13-56-42](https://user-images.githubusercontent.com/43390273/63754603-c7115500-c8d2-11e9-84a7-93f307811c20.jpg)


The ul and li elements are not rendering properly. It was working fine with angular 7.
