### ISSUE TITLE
UTF-8 in tables

### ISSUE THREAD

**Issue by kartblanch** [simonbengtsson/jsPDF-AutoTable#542]
Hi, guys!
Does this plugin support UTF-8?
Thanks for answer.

**Comment by simonbengtsson** [comment]
The plugin supports everything that jspdf supports. To support all utf-8 characters in jspdf you might need to add a custom font.

**Comment by kartblanch** [comment]
@simonbengtsson Thanks for your answer! But this problem exists in the table headers. There are no problems in the rows of the tables, only in the headers

**Comment by simonbengtsson** [comment]
Aha you are having an issue. Can you create a new issue where you include a minimal example code of the issue?
