### ISSUE TITLE
UTF-8 Issue in table

### ISSUE THREAD

**Issue by kartblanch** [simonbengtsson/jsPDF-AutoTable#543]
To continue issue [542](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/542).
I have a problem in tables than I'm use UTF-8 characters.

`
doc.setFont('open-sans');
        doc.autoTable({
            startY: dy + 5,
            startX: 20,
            columnStyles: {
                1: {columnWidth: 'auto'}
            },
            head: [
                ['id', 'Заголовок', 'Header']
            ],
            body: [
                [1, 'Строка', 'Raw'],
                [2, 'Строка', 'Raw']
            ]
        });
`

After that  I have a PDF-File which doesn't understand UTF-8:
[bad_sample.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/3610568/bad_sample.pdf)

But, if I add in `jspdf.plugin.autotable.js` file in function `autoTableText` 
`this.setFont('open-sans'); //raw: 1933` then this problem remains only with table headers.
[only_bad_headers.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/3610594/only_bad_headers.pdf)

Is there a solution to this problem? Or am I doing something wrong?
P.S. I imported the font into .js before and use it. The rest of the UTF-8 text is displayed perfectly.

**Comment by kudlav** [comment]
The header is bold. You have to link two files: OpenSans regular and OpenSans bold.

**Comment by kartblanch** [comment]
@kudlav I solved this problem.  Just specify in the parameters function `setFonts` bold style. If second parameters is empty, by default use "normal" style. 
Thanks for your attention! Good luck in developing!
