### ISSUE TITLE
Not able to add border for a single column

### ISSUE THREAD

**Issue by vishalakula19** [simonbengtsson/jsPDF-AutoTable#546]
Hi,

I was Exploring all the available options to add a border to 1 Column like this 

![github](https://user-images.githubusercontent.com/20358277/65247881-d02ac600-db0e-11e9-8eb7-b276b1378275.png)

or adding  border to 2 columns like this
![github](https://user-images.githubusercontent.com/20358277/65247951-fe100a80-db0e-11e9-8cc0-b7798ac5615b.png)

I tried lineWidth in didParseCell Hook but its adding border for each cell.Can anyone help me to achieve the above functionality

Thanks for all your help!!

**Comment by simonbengtsson** [comment]
This feature does not currently exist with the plugin. It would probably be possible to draw the  square on top of the pdf using the `didDrawPage` hook though. Ie first using the information passed to the hook to figure out the position and dimensions of the column and the draw the rectangle using `doc.rect`.
