### ISSUE TITLE
Need help to text too long in jspdf autotable

### ISSUE THREAD

**Issue by trongdn84** [simonbengtsson/jsPDF-AutoTable#547]
when I have text too long in column of autotable I have problem when I use style 
tableLineColor: [187, 187, 187],
tableLineWidth: 1,

It display asbelow
![bug](https://user-images.githubusercontent.com/55567700/65295807-b334d800-db8c-11e9-8f03-e5b7edf72b17.png)

**Comment by trongdn84** [comment]
please help to fix it

**Comment by simonbengtsson** [comment]
It's hard to understand the issue right now. Can you create minimal example and post the code?

**Comment by trongdn84** [comment]
mean when i have a column with too much data it page break is ok but when i was border by tableLineColor if autotable have margin bottom it have tail of border through two page

**Comment by simonbengtsson** [comment]
For me it works. Can you create a minimal example and post the code?

**Comment by trongdn84** [comment]
![image](https://user-images.githubusercontent.com/55567700/65581162-326b4700-dfa5-11e9-8039-eb4f932f0c8b.png)
here my code
 (doc as any).autoTable({
              html: _innerHTML,
              margin:  {right: self.L_PAGE, bottom: self.HEIGHT_HEADER, left: self.L_PAGE},
              startY: _startY,
              headStyles: {
                font: 'OpenSans-Bold',
                halign: 'left',
                textColor: [19, 40, 51],
                fillColor: [223, 226, 230],
                fontSize: 10 * self.ratio,
                cellPadding: 10 * self.ratio
              },
              columnStyles: styleHeader,
              alternateRowStyles: {fillColor: [255, 255, 255]},
              bodyStyles: {fillColor: [255, 255, 255]},
              rowPageBreak: 'avoid',
              theme: themeTbl,
              didDrawPage: pageContent
            });

**Comment by simonbengtsson** [comment]
Can't run that since I don't know what's in `_innerHTML`. Can you try creating a minimal example that I can run without the extra options such as styles etc?

**Comment by trongdn84** [comment]
you can draw html with long data column and use jspdf autotable you can see error in page 2 or 3
