### ISSUE TITLE
Landscape PDF with multiple cols, strange rendering

### ISSUE THREAD

**Issue by t-book** [simonbengtsson/jsPDF-AutoTable#549]
Dear @simonbengtsson,

I'm rendering a landscape pdf with:

```
          pdf.autoTable({
              html: '.csv-table',
              didParseCell: function (table) {
                if (table.section === 'head') {
                  table.cell.styles.fillColor = '#999';
                  table.cell.styles.textColor = '#fff';
                  table.cell.styles.fontSize = 9;
                }

                if (table.section === 'body') {
                  table.cell.styles.fontSize = 9;
                }
              },
          });
```

Which ends in:

![Bildschirmfoto 2019-09-30 um 13 01 07](https://user-images.githubusercontent.com/20478652/65873070-661de680-e382-11e9-88b1-a6372db939d4.png)

Can you say what leads to behavior like this? 

I've recognized that it gets better when only using short names in table header cells. Is it possible to access the content with didParseCell
`if (cell.content == 'Longname'){cell.content = 'LN'}` and just rename long names? or is there maybe already something to truncate long titles?

Thanks!

**Comment by simonbengtsson** [comment]
Can you post the code of a minimal example including data for when this issue?

**Comment by t-book** [comment]
sure. will try to provide a fiddle! thanks!

**Comment by t-book** [comment]
@simonbengtsson voila! https://jsfiddle.net/evgp95jr/2/
so there is something with the length of some cell content header or body. Unfortunately, I do not know what is best practise how to solve. :/ (Great great plugin by the way 👍)

**Comment by simonbengtsson** [comment]
The content of the table cannot fit in the columns and the column width calculation is not smart enough to handle it. There is a bunch of ways to fix it. The easiest is to play around with the `cellWidth` and `overflow` options.

If you add this to the fiddle you can see that the table looks a bit better.

              columnStyles: {
                  10: {
                  	cellWidth: 10,
                  }
              },

**Comment by t-book** [comment]
ah nice @simonbengtsson indeed it does look better. do you think it would help to rename the long header names?if so can I access the cell content and replace it with something at f.e DidcellParse ?

**Comment by simonbengtsson** [comment]
You can try that! I think there was some data that was too long as well though. I think you should play around with the following parameters:

- Alter content (ie changing header names as you suggested)
- Reducing font size
- Increasing paper size
- The `overflow` option
- The `cellWidth` option (some columns you might always want to wrap content for example)

**Comment by t-book** [comment]
Great thanks! I can get /set content content with data.raw, right?

**Comment by simonbengtsson** [comment]
You might be able to do that, but I would probably set `data.cell.tex`.

**Comment by t-book** [comment]
grazie will try!
