### ISSUE TITLE
Any Feature to Manually Add Table Rows from Hook Function?

### ISSUE THREAD

**Issue by KirenJames7** [simonbengtsson/jsPDF-AutoTable#550]
Hi,

Is there Any Feature to Manually Add Table Rows from Hook Function?

For example, I want to add a row with colSpan conditionally between existing rows (not all rows).. Didn't find any methods for this in the API that would allow such a thing..

Would appreciate a prompt response if there is a possibility for this..
Thanks in advance

**Comment by simonbengtsson** [comment]
No real api, but you can experiment with adding rows to the table in the `didParseCell` hook. That hook is executed before width and dimension calculations are done etc.

To get all the data correct however you might instead add all potensial rows and then remove them conditionally in `didParseCell`.

**Comment by KirenJames7** [comment]
@simonbengtsson thanks for your prompt feedback..

But having such a feature would be handy.. don't you think..

**Comment by simonbengtsson** [comment]
Would be nice! I can't think of a straight forward API for it though. Do you have a suggestion?

**Comment by KirenJames7** [comment]
A insert row method to use in the Hook function would be the best way yo go IMO.. I am in the middle of a project ATM.. I will have a deeper look to see ASAP..

I feel another improvement could be done is to allow a table footer..

For the moment I used a empty row with a column span... But having a table footer for this would be better.. for totaling and stuff.. will give a better dynamic

Here is what I am working on.. not the entire finished thing yet

![PO00-2](https://user-images.githubusercontent.com/36771013/66023300-621ecf80-e50e-11e9-9ad3-d1ec0373208d.png)
![PO00-2-1](https://user-images.githubusercontent.com/36771013/66023302-621ecf80-e50e-11e9-91a8-70089874aea7.png)

**Comment by simonbengtsson** [comment]
Looks like an interesting project! I'm hesitant to add those features since it might just increase the API surface without much user benefit. But let me know your findings of best API for both 👍

**Comment by puneet0911** [comment]
Hi @simonbengtsson,

I want to add the Total count row in table if the page is more then one. I have added the row using `didParseCell` hook but in this hook, I am not able to get the page count.
The function `doc.internal.getNumberOfPages()` is always returning count one.

Can you please let me know do you have anything for this?

**Comment by simonbengtsson** [comment]
Have you seen the header footer example?

**Comment by puneet0911** [comment]
Thankyou for the quick reply.
No I did not check the Header footer example.
Can you please share link with me

Thanks
Puneet Sharma

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
