### ISSUE TITLE
If i set the cellWidth for more than 1 columns, the table doesn't fits in all the width of the page.

### ISSUE THREAD

**Issue by eBaeza** [simonbengtsson/jsPDF-AutoTable#552]

**Comment by simonbengtsson** [comment]
Tried this now, but seems to work.

    doc.autoTable({
        columnStyles: {
            0: {cellWidth: 50},
            1: {cellWidth: 50},
        },
        body: [
            ['1', 'Donna', 'dmoore0@furl.net', 'China', '211.56.242.221'],
            ['2', 'Janice', 'jhenry1@theatlantic.com', 'Ukraine', '38.36.7.199'],
            ['3', 'Ruth', 'rwells2@constantcontact.com', 'Trinidad and Tobago', '19.162.133.184'],
            ['4', 'Jason', 'jray3@psu.edu', 'Brazil', '10.68.11.42'],
        ],
    });

Are you doing something special?

**Comment by obark1** [comment]
Hello Simon. I am also experiencing this issue with the newest version 3.2.5 (works in 3.2.4). 

` 
    doc.autoTable({margin: {top: 10, bottom: 30}, startY: 100, styles: {fontSize: number = 9, font: "custom", halign: 'center', overflow: 'linebreak', cellWidth: 15}, 
        headStyles: {
            font: 'custom'
        },
        didParseCell: function (data) {
        var rows = data.table.body;
        if (data.row.index === rows.length - 1) {
            data.cell.styles.fillColor = [239, 235, 200];
        }
    },
        head: head,
        body: body           
    });
`

I have 11 columns in my table.
In 3.2.5 the table does not use the entire width of the page, but only a bit more than half. In 3.2.4 there is no problem. Hope it helps, and thanks for a great tool.

**Comment by eBaeza** [comment]
@simonbengtsson no, i'm just setting up several tables with 5-10 columns.

**Comment by simonbengtsson** [comment]
@obark1 That's by design since you specify that every column should have cellWidth 15. It was a bug in 3.2.4 that made the table not adhere to the cellWidth sometimes.

**Comment by obark1** [comment]
@simonbengtsson I was actually thinking about this, that it was a bug in 3.2.4 that got addressed in 3.2.5. It makes sense, since a fixed cellwidth is specified, but seems to be ignored. Sorry for being a bit too fast to blame the new version, and thanks for the clarification.
