### ISSUE TITLE
Bug? didParseCell returns cell: undefined

### ISSUE THREAD

**Issue by LightningMD** [simonbengtsson/jsPDF-AutoTable#555]
Currently generating from html table, using colspan and data tag to dynamically create subheaders as I need and I need to adjust styling.

Posted as a question here:
https://stackoverflow.com/questions/58332448/didcellparse-does-not-return-cell

Plus codepen here:
https://codepen.io/lightningmd/pen/gOOaezM

cell.halign = 'center'  is updated, but does not render in the pdf using willDrawCell.
When attempting to use didParseCell, cell is undefined.

**Comment by simonbengtsson** [comment]
Answered the stackoverflow question. Will keep this open as a bug for that didParseCell is called with null as data.cell when there are colspan/rowspans. It should not.
