### ISSUE TITLE
IE not working

### ISSUE THREAD

**Issue by oramirezs** [simonbengtsson/jsPDF-AutoTable#556]
In Internet Explorer (Windows 7; I.E 11 with Edge)., when testing the simple.html example, you give the following error:

No se puede obtener la propiedad 'bind' de referencia nula o sin definir
Archivo: jspdf.plugin.autotable.js, Línea: 217, Columna: 5

Thanks you

**Comment by simonbengtsson** [comment]
I'm not sure what's up with the latest version of jspdf. But works for me with jspdf 1.3.5. Can you check that?

**Comment by simonbengtsson** [comment]
I think I found it. Update to the latest version of ispdf-autotable. Then you also need to add this line to avoid an error in jspdf: `<script>if (!window.Promise) window.Promise = {prototype: null}</script>` before you include the jspdf lib.
