### ISSUE TITLE
Table with long columns

### ISSUE THREAD

**Issue by wisnubaldas** [simonbengtsson/jsPDF-AutoTable#557]
I made a table with a long column, but my column did not continue to the next page. can anyone help to keep my table intact when pdf is displayed
code here:
[ create_pdf_from_array.js ](https://gist.github.com/wisnubaldas/23b3ea73b78c794b5d2a1db94a4cc276)

![Screenshot from 2019-10-14 21-45-31](https://user-images.githubusercontent.com/10908214/66760478-64990600-eecc-11e9-9bb6-95c0ebfc7eaf.png)

**Comment by simonbengtsson** [comment]
You have set cellWidth to wrap which means that all cells will wrap their content even if some columns will not fit page.
