### ISSUE TITLE
Node 10: ReferenceError: Blob is not defined or `TypeError: doc.autoTable is not a function`

### ISSUE THREAD

**Issue by tapz** [simonbengtsson/jsPDF-AutoTable#561]
With Node 10 and Mocha:

---

```
const { jsPDF } = require('jspdf');
require('jspdf-autotable');
```

Causes this:

```
ReferenceError: Blob is not defined
      at l.__private__.getBlob (node_modules/jspdf/dist/jspdf.min.js:29:21377)
      at Object.l.save (node_modules/jspdf/dist/jspdf.min.js:29:35467)
```

---

```
const jsPDF = require('jspdf/dist/jspdf.node.debug');
require('jspdf-autotable');

const doc = new jsPDF();
doc.autoTable({...});
```

Causes this:

`TypeError: doc.autoTable is not a function`

**Comment by simonbengtsson** [comment]
Checkout the `examples/nodejs/index.js` for an example of how to use jpsdf and jspdf-autotable in nodejs

**Comment by tapz** [comment]
I checked and jsPDF does not work that way with node.js anymore. You can easily test this yourself. There is now a separate dist-file for node.js in jsPDF. jsPDF-AutoTable adds the autoTable function to the wrong version. The other one does not work with node.js even when you set the window, html2pdf etc. The only way for me to get autotable working is to rename jsPDF.node.debug.js to jsPDF.min.js in node_modules.

**Comment by simonbengtsson** [comment]
Oh! Didn't know they are distributing a nodejs dist file now. Will check it out.

That said, I tried running the nodejs example and it works for me. Does the example fail for you as well?

**Comment by tapz** [comment]
No, I haven't tried the example. I read somewhere that the error occurs only when using Mocha. But obviously, the node dist file should be used with node :-)

**Comment by tapz** [comment]
@simonbengtsson Could you change the question label and reopen this issue, please. Any progress with node?

**Comment by simonbengtsson** [comment]
Can you create a new ticket as a feature request about using jspdf.node.js? Using jspdf.debug.js works when using it as in the examples?

**Comment by tapz** [comment]
The example works. I have no idea what is teiggering the use of Blob in jsPDF. Blob does not exist in node.js, so the only solution is to use the node specific jspdf distribution file. I tried adding the same dependencies and imports to the example, but could not reproduce the issue there.
