### ISSUE TITLE
[Enhancement Suggestion] Proper word-break (don't break in the middle of words)

### ISSUE THREAD

**Issue by mmghv** [simonbengtsson/jsPDF-AutoTable#568]
First, Thank you for such a great plugin which made our life much easier.

I'm facing a big problem when using the plugin with real-life data, when there's even only one cell in a column with long text, the other columns cells will break in the middle of words which makes it unreadable and taking double the vertical space when it should take space from the big column.

![1](https://user-images.githubusercontent.com/5418859/67423537-bd575580-f5d4-11e9-9bbc-2e045004b5d5.jpg)

This makes it unusable without defining `minCellWidth` for columns or preventing it from wrapping altogether, that could work for some cases but that's not the answer, I have user-defined data in these rows which could be one word, or more, I want it to break into lines (correctly) only when needed.

So, as an attempt to solve the problem, I tried to figure out how HTML tables handle this, What I found is that each column will have a minimum width that will not get smaller than the longest word in that column.

So I used the following `hook` code to set `minWidth` for each column to the longest word :

```js
doc.autoTable({
  // ...

  /**
   * Prevent AutoTable from breaking lines in the middle of words
   * by setting the minWidth to the longest word in the column
   * 
   * WARNING: this may cause the table to exceede the allowed width (just like in HTML)
   * and give a "can't fit page" console error, could be improved.
   */
  didParseCell({doc, cell, column}) {
    if (cell === undefined) {
      return;
    }

    const hasCustomWidth = (typeof cell.styles.cellWidth === 'number');

    if (hasCustomWidth || cell.raw == null || cell.colSpan > 1) {
      return
    }

    let text;

    if (cell.raw instanceof Node) {
      text = cell.raw.innerText;
    } else {
      if (typeof cell.raw == 'object') {
        // not implemented yet
        // when a cell contains other cells (colSpan)
        return;
      } else {
        text = '' + cell.raw;
      }
    }

    // split cell string by spaces
    const words = text.split(/\s+/);

    // calculate longest word width
    const maxWordUnitWidth = words.map(s => Math.floor(doc.getStringUnitWidth(s) * 100) / 100).reduce((a, b) => Math.max(a, b), 0);
    const maxWordWidth = maxWordUnitWidth * (cell.styles.fontSize / doc.internal.scaleFactor)

    const minWidth = cell.padding('horizontal') + maxWordWidth;

    // update minWidth for cell & column

    if (minWidth > cell.minWidth) {
      cell.minWidth = minWidth;
    }

    if (cell.minWidth > cell.wrappedWidth) {
      cell.wrappedWidth = cell.minWidth;
    }

    if (cell.minWidth > column.minWidth) {
      column.minWidth = cell.minWidth;
    }

    if (column.minWidth > column.wrappedWidth) {
      column.wrappedWidth = column.minWidth;
    }
  }
});
```

codepen: [https://codepen.io/mmghv/pen/eYYvQqO?editors=1010](https://codepen.io/mmghv/pen/eYYvQqO?editors=1010)

And this was the result :

![2](https://user-images.githubusercontent.com/5418859/67425074-a36b4200-f5d7-11e9-8b19-c1c4d9cc392c.jpg)

As you can see, It fixed the problem, now the spacing makes more sense and the table actually look more like the HTML version.

I believe that this should be the default behavior.

I didn't do a pull request because it still needs improvements and a way to handle `colSpan` but I'm in the middle of a project right now, so I'm leaving this here as a starting point, and as a quick fix for anyone who could be facing the same problem.

`Note` side effect of this, it may cause the table width to get outside of the defined boundaries if the total width of the longest words in each column is greater than the defined `tableWidth`.

This is actually how HTML tables behave, But I fell like it shouldn't be that way with AutoTable, I'm not sure.

**Comment by simonbengtsson** [comment]
Prioritizing not breaking words sounds like a great way to solve many of these issues!

**Comment by fraunos** [comment]
Thanks, your code fixed my issues! I only had slight problems with table width, which shrinked. Fixed it by changing
`    if (cell.minWidth > cell.wrappedWidth) {
      cell.wrappedWidth = cell.minWidth;
    }`
to
`    if (cell.minWidth < cell.wrappedWidth) {
      cell.wrappedWidth = cell.minWidth;
    }`
Now the table uses all available width :)

**Comment by mmghv** [comment]
@fraunos the line of code you mentioned shouldn't shrink the table width, also the fix you proposed might case problems because `wrappedWidth` shouldn't get smaller.

There was [a bug](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/566) that caused the table width to shrink which was fixed in a [recent version](https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.2.9), please check your `jsPDF-AutoTable` version, if it's prior than `v3.2.9` then updating should fix the problem, otherwise please reproduce the problem in a `codepen` so I can investigate it.

**Comment by Subtletree** [comment]
Wow, this code has been a drop in fix for many wrapping issues i've been facing.

Have got by using `overflow` and `cellWidth` but seems to be hit or miss and requires lots of trial and error. Definitely in favour of getting this into the repo if it makes sense for most cases. It does for me!

**Comment by mmghv** [comment]
@Subtletree good to hear that, when it's implemented it should not use `didParseCell` nor `minWidth` but more under-the-hood robust way so you can use hooks normally to change cell content and still be calculated correctly.

**Comment by darshanrampatel** [comment]
@mmghv This is great!

One thing I noticed: the below regex doesn't work in Firefox/Safari/Edge but does in Chrome since those browsers do not support lookbehind in regexes (see [Can I Use...](https://caniuse.com/#feat=js-regexp-lookbehind))
`const words = text.split(/\s+|(?<=-)/);`

For my use-case, I don't want to split on `-` so I am using the below instead:
`const words = text.split( /\s+/ );`

**Comment by mmghv** [comment]
@darshanrampatel Thanks for reporting

I was just trying to mimic html-tables behavior but `jsPDF` doesn't even break on `-` so removing it is the right choice here.

**Comment by simonbengtsson** [comment]
Implemented on master but not yet released. Will be released in 3.4.0.

**Comment by mmghv** [comment]
Awesome!
I'm kinda busy this week but I'll try to do some testing, is it working with `colSpan` ?

**Comment by simonbengtsson** [comment]
No, it only checks for single columns. In fact the plugin currently does not consider colspans when calculating column widths at all.

**Comment by mmghv** [comment]
I found couple of bugs upon testing, I'll send PR in the next couple of days after doing more testing & debugging because there's still a problem.

In the future we should commit this kind of features in a separate branch (as a PR) to achieve the following :
- avoid blocking the `master` branch as the feature could take some time for testing and refactoring.
- grouping all commits related to a feature.
- having a place to discuss the feature (PR comments and code reviews)
- having the ability to discard or postpone the feature without affecting  `master` history

**Comment by simonbengtsson** [comment]
You are right! I thought it was all but done, but also found a few serious issues the other day. Reverted the commit on master now and created a PR https://github.com/simonbengtsson/jsPDF-AutoTable/pull/619
