### ISSUE TITLE
Cannot debug with didDrawCell property

### ISSUE THREAD

**Issue by titosobabas** [simonbengtsson/jsPDF-AutoTable#571]
Also i have this code:

```
doc.autoTable(
	{html: '#my-table-parciales', 
	footStyles : {halign:'center', fillColor:"#fff",textColor:"#000"}, 
	headStyles : {fillColor:"#fff",textColor:"#000"}, 
	styles : {fontSize : 8, minCellWidth : 25},
	didDrawCell: data => {
      console.log(data.section);
   }
});
```

But when i try to see what's happening with my console.log the firefox browser clean all and i can't see anything.

**Comment by simonbengtsson** [comment]
You mean that didDrawCell is not called? Can you try reproducing the issue in a jsfiddle?

**Comment by michaelparkadze** [comment]
Hi, i am using jspdf-autotable on nodejs and i am also trying to console.log inside didDrawCell function and can't see any logs. the function is called as it adds images to the table. Is there a way which I could console.log inside the function?
