### ISSUE TITLE
unable to add padding/margin to cell property

### ISSUE THREAD

**Issue by karthick29** [simonbengtsson/jsPDF-AutoTable#573]
cellpadding aligns the for entire cell. Required left /right padding to align the text in the particular position
![image](https://user-images.githubusercontent.com/22142723/68659121-208f3480-0550-11ea-85ce-8da689101411.png)

**Comment by simonbengtsson** [comment]
Can you post code I can use to reproduce?

**Comment by karthick29** [comment]
Please find the below code, also is possible to have 

 var doc = new jsPDF();
    var head = [
        [
            {content: 'Careem ', }, 
            {content: 'Status', styles: {halign: 'right', fontSize: 9, fontStyle: 'bold', columnWidth:80}},  
        ],
        [
            {content: 'E-Voucher redemption', styles: {halign: 'left',fontSize: 7, fontStyle: 'normal',cellPadding: 1 }}, 
            {content: 'Done',  styles: {halign: 'right',fontSize: 9 ,fontStyle: 'bold'}},     
        ],
    ];

    doc.autoTable({
        head: head, 
        startY: 37,
        tableLineColor: '#c7c7c7',
        tableLineWidth: 0,
        styles: {
            lineColor: '#c7c7c7',
            lineWidth: 0,
            cellPadding: 2 
        },
        headStyles: {
            fillColor: '#ffffff',
            textColor: '#333333'
        },
        didDrawPage: data => {
           doc.roundedRect(14, data.settings.startY, data.table.width, data.table.height, 1, 1, 'S');
          },
        
    });
    return doc;

**Comment by mmghv** [comment]
`cellPadding` can accept an object with specific value for each direction : `cellPadding: {top: number, right: number, bottom: number, left: number}`

**Comment by karthick29** [comment]
Thanks !!! works well :)
