### ISSUE TITLE
Cannot add bold inbetween text using <b> tag

### ISSUE THREAD

**Issue by karthick29** [simonbengtsson/jsPDF-AutoTable#574]
doc.autoTable({
        head:  [ {content: 'E-Voucher <b>redemption</b>', styles: {halign: 'left',fontSize: 7, fontStyle: 'normal',cellPadding: 1 }},  ],   
    });
    return doc;

![image](https://user-images.githubusercontent.com/22142723/68667131-aca85880-055e-11ea-92cf-78cc73ba1871.png)

**Comment by LuigiSZ** [comment]
can see : https://github.com/simonbengtsson/jsPDF-AutoTable/issues/744#issuecomment-812129199
