### ISSUE TITLE
Image not rendering same as html page

### ISSUE THREAD

**Issue by Shankar1430** [simonbengtsson/jsPDF-AutoTable#578]
I need to print html table in print page.

But Image is not rendered properly into print page.

The alignment of image not working properly. I just want to show a table with image in print page from html page without any change.

Please give me a solution. Thank you.

**Comment by simonbengtsson** [comment]
Images are not supported automatically. You can take a look at the examples to see how this is done. If you have found an issue with this please post the code how to reproduce.

**Comment by Shankar1430** [comment]
Yes. I tried that from examples. My image in table is right alignment. But In print, image is just started from cell position x and y. but i need image to place exactly in print like image placed at html page.
