### ISSUE TITLE
The header font style does not change 

### ISSUE THREAD

**Issue by al-ani** [simonbengtsson/jsPDF-AutoTable#580]
My table in the Arabic language thus I used Amiri font. The Amiri font changes the text to the Arabic language for the entire table except of table header. 
I used the following code 

        const unit = "pt";
        const size = "A4"; // Use A1, A2, A3 or A4
        const orientation = "portrait"; // portrait or landscape

        const marginLeft = 40;
        const doc = new jsPDF(orientation, unit, size);

        // doc.setFontSize(15);
        doc.addFileToVFS("Amiri-Regular.ttf", AmiriRegular);
        doc.addFont('Amiri-Regular.ttf', 'Amiri', 'normal');
          
        doc.setFont('Amiri'); // set font
        doc.setFontSize(10);

        const title = "تقرير";
        const headers = [Object.keys(props.data[0])];

        const data = props.data.map(elt => {
            return Object.values(elt)
            // return [elt.name, elt.profession]
        });

        let content = {
            startY: 50,
            head: headers,
            body: data,
            fillColor: [155, 89, 182],
            styles: {
                font: 'Amiri'
            },
            headStyles: {font:'Amiri'},
        };

        doc.text(title, marginLeft, 40);
        doc.autoTable(content);
        doc.save("report.pdf")

![Screenshot from 2019-12-31 06-56-00](https://user-images.githubusercontent.com/22416436/71604145-4671a680-2b9b-11ea-9809-6ad4f222daf6.png)

**Comment by mmghv** [comment]
I can't reproduce it, I'm using an Arabic font and it's working as expected, although I added the font after converting it to a JS file using [jsPDF font-converter](https://github.com/MrRio/jsPDF/blob/master/fontconverter/fontconverter.html).

**Comment by simonbengtsson** [comment]
Have you tried using the headStyles option?

**Comment by simonbengtsson** [comment]
If you run the custom example @al-ani. Can you get that to work? What is the difference if so between yours and that example?

**Comment by al-ani** [comment]
This is an example of my code 
https://jsfiddle.net/alaney/sg7q1mb9/1/#

**Comment by al-ani** [comment]
> If you run the custom example @al-ani. Can you get that to work? What is the difference if so between yours and that example?


This is an example of my code
https://jsfiddle.net/alaney/sg7q1mb9/1/#

**Comment by mmghv** [comment]
This is tricky, the problem is, you added only the `normal` font-face, and the `head` style is bold so it doesn't find the `bold` variant of the font, to fix this, either add the `bold` font-face or just simply use the `normal` font-face for the heading like this :
```js
headStyles: { font: "Amiri", fontStyle: 'normal', halign: "right" },
```

**Comment by al-ani** [comment]
Many thanks @mmghv

**Comment by Krasnopir** [comment]
thank! Add `fontStyle: 'normal',` help for me  too. I am using cyrillic fonts

**Comment by RuslanCherkasArchysoft** [comment]
> thank! Add `fontStyle: 'normal',` help for me too. I am using cyrillic fonts
> ![Снимок экрана от 2020-04-10 07-48-46](https://user-images.githubusercontent.com/22295024/78965379-91d61200-7b05-11ea-8139-7ecfc46324ef.png)
> 
> fixed
> ![Снимок экрана от 2020-04-10 08-28-31](https://user-images.githubusercontent.com/22295024/78965387-94d10280-7b05-11ea-8e9a-a9edc71ee725.png)

Can I find out which font you used?

**Comment by she1da** [comment]
> This is tricky, the problem is, you added only the `normal` font-face, and the `head` style is bold so it doesn't find the `bold` variant of the font, to fix this, either add the `bold` font-face or just simply use the `normal` font-face for the heading like this :
> 
> headStyles: { font: "Amiri", fontStyle: 'normal', halign: "right" },

thank you so much the fontStyle as Normal works!!!
