### ISSUE TITLE
Could we have Prettier conventions?

### ISSUE THREAD

**Issue by rmdias** [simonbengtsson/jsPDF-AutoTable#582]
While working with @ssmiech on the NodeJS support we found ourselves writing with some clashing style conventions. Could we have a Prettier convention to have the IDE watch our backs about it?

Something simple like:
```javascript
{
  "trailingComma": "es5",
  "tabWidth": 4, // or some onther value?
  "semi": true, 
  "singleQuote": false
}
```

let us know :)

**Comment by rmdias** [comment]
@simonbengtsson

**Comment by simonbengtsson** [comment]
Sounds good to me! I prefer to keep it with the `tabWidth: 2` if that's okay for you guys:

```
{
 "trailingComma": "es5"
  "semi": false,
  "singleQuote": false
}
```

**Comment by simonbengtsson** [comment]
@mmghv Do you have any code style preferences?

**Comment by mmghv** [comment]
I'm with you on `tabWidth: 2`, about the quotes I prefer the `singleQuote` but it's not a big deal if you agree on otherwise.

**Comment by simonbengtsson** [comment]
If anything I agree with you on singleQuote as well. Final:

```
{
  "trailingComma": "es5"
  "semi": false,
  "singleQuote": true
}
```

**Comment by rmdias** [comment]
I also prefer `"tabWidth": 2` `  "semi": true` and `  "singleQuote": true`. I just came up with those settings having the current code as base.

So:
```javascript
{
  "trailingComma": "es5"
  "tabWidth": 2, 
  "semi": false,
  "singleQuote": true
}
```

**Comment by mmghv** [comment]
@simonbengtsson you want no [semicolons](https://prettier.io/docs/en/options.html#semicolons) right?, just making sure it's not my mistake because I see it used in the base code.

**Comment by simonbengtsson** [comment]
Yes I think we should remove them.

**Comment by simonbengtsson** [comment]
Merged! 🎉
