### ISSUE TITLE
Problems with Unicode symbols.

### ISSUE THREAD

**Issue by Gustafssonz** [simonbengtsson/jsPDF-AutoTable#585]
Hello! 
I have been working with a website where we try to generate a PDF based on the content. But the website is using ≈ (U+2248) symbol and this is translated into "H in the Autotable. 

≈38.7mm becomes "H38.7mm

I have checked the font I am using and it does indeed support the ApproxEqual symbol.

**Comment by simonbengtsson** [comment]
Weird! Does it work if you use jspdf only?

**Comment by Gustafssonz** [comment]
Hej! 
No, it is printing "H38.7mm like before. So there is something strange going on :(

**Comment by Gustafssonz** [comment]
Solved!
There was a " 'WinAnsiEncoding' " in the addFont method. This was causing the problem.
