### ISSUE TITLE
JSPDF Autotable not adding tfoot

### ISSUE THREAD

**Issue by thomasazdon** [simonbengtsson/jsPDF-AutoTable#589]
I have a html table with a defined thead, tbody, and tfoot. The tfoot contains data dynamially populated through json.  When I get the pdf - the body and headers are rendered but not the footer of the table.  Is there a way for Jspdf autotable to include the defined table footer in the output?  I am speaking of the table footer - not the page footer.

;`
`<script>
    function generate() {
        //Creation of PDF document
        let doc = new jsPDF('l', 'pt');
        const totalPagesExp = '{total_pages_count_string}';
        var elem = document.getElementById('${pm.info.requestId}');
        var data = doc.autoTableHtmlToJson(elem);
        doc.autoTable(data.columns, data.rows, {
        ShowFoot: 'everyPage',
            headStyles: {
                cellWidth: 'wrap',
                fontSize: 10,
                lineWidth: 0.5,
                lineColor: [0, 0, 0],
                textColor: [0, 0, 0],
                fillColor: [211,211,211]
            },
            bodyStyles: {
                cellWidth: 'wrap',
                fontSize: 8,
                lineWidth: 0.5,
                lineColor: [0, 0, 0],
                textColor: [0, 0, 0],
                fillColor: [255,255,255]
            },
            footStyles: {
                
                cellWidth: 'wrap',
                fontSize: 8,
                lineWidth: 0.5,
                lineColor: [0, 0, 0],
                textColor: [0, 0, 0],
                fillColor: [255,255,255]
            },
            //Formatting of pages
            didDrawPage: function (data) {
                //Summa logo on top of the page
                doc.addImage('${pm.variables.get("summa")}', 'PNG', 20, 20, 145, 42.63);
                //Font sizes of report information
                doc.setFontSize(8);
                //Report information: portfolio name, knowledge time and report time
                doc.text(35, 75, '${pm.variables.get("portfolioName")}');
                doc.text(35, 85, '${pm.variables.get("reportTime")}');
                doc.text(35, 95, '${pm.variables.get("knowledgeTime")}');
                //Page numbers
                var str = "Page " + doc.internal.getNumberOfPages()
                if (typeof doc.putTotalPages === 'function') {
                    str = str + " of " + totalPagesExp;
                };
                //Page size
                var pageSize = doc.internal.pageSize;
                var pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
                doc.text(str, data.settings.margin.left, pageHeight - 10);
            },
            
            margin: {
                top: 100
            }
        });
        //Number of pages
        if (typeof doc.putTotalPages === 'function') {
            doc.putTotalPages(totalPagesExp);
        }
        //--------------------------------------------------------------------------------------------------START
        //Change name of report if desired
        doc.save('${pm.info.requestName}${pm.variables.get("reportTime")}.pdf');
        //--------------------------------------------------------------------------------------------------END
    }
</script>`

**Comment by simonbengtsson** [comment]
You are using the old way of initiating the table. Foot and head are parsed with the new html option you can see in the Readme.

**Comment by thomasazdon** [comment]
Thanks for that - however, I have also tried implementing according to the readme - in its most simple form.

`

<script>
    function generate() {
        //Creation of PDF document
        let doc = new jsPDF('l', 'pt');
        doc.autoTable({ html: '${pm.info.requestId}' });
       
        //--------------------------------------------------------------------------------------------------START
        //Change name of report if desired
        doc.save('${pm.info.requestName}${pm.variables.get("reportTime")}.pdf');
        //--------------------------------------------------------------------------------------------------END
}
</script>
`

And I get "jspdf.plugin.autotable.min.js:17 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '43fb3d58-12df-4c0a-b20f-289400673544' is not a valid selector."

` 

> 

> <div id="container" class="container" style="width:80%">

       <table id = "${pm.info.requestId}"  class="display nowrap" style="width:100%"  >
     <tbody>
     {{#each response.portfolios}}
     <thead> 
        <tr>
         <td colspan ="13"></td>
        <td><strong>Period Beginning Balance: {{total.beginningBalance}}</strong></td>
        </tr>
     </thead>
        {{/each}}
        {{#each response.portfolios}}
        {{#each data}}
            <tr>
            <td bgcolor="lightgrey" colspan="13"><strong>Account Key: {{financialAccount}}.{{assetType}}.{{longShort}}.{{custodianAccount}}.{{strategy}}.{{manager}}.{{basket}}.{{symbol}}</strong></td>
            <td bgcolor="lightgrey"><strong>Beginning Balance: {{summary.beginningBalance}} <br> Beginning Bal Type {{summary.beginningType}}</strong></td>
            </tr>
         </tbody>
         </head>
            <th></th>
            <th>Financial<br>Acct</th>
            <th>Financial<br>Account<br>type</td>
             <th>Inventory<br>State</th>
            <th>LotId</td>
            <th>Asset<br>Type</th>
            <th>Symbol</th>
            <th>Long<br>Short</th>
            <th>Custodian<br>Account</th>
            <th>Strategy</th>
            <th>Manager</th>
            <th>Basket</th>
            <th>Quantity</th>
            <th>Book Cost</th>
            </tr>
            </thead>
            <tbody>
               <tr>
            <td></td>
            <td>{{financialAccount}}</td>
            <td>{{financialAccountType}}</td>
            <td>{{inventoryState}}</td>
            <td>{{lotId}}</td>
            <td>{{assetType}}</td>
            <td>{{symbol}}</td>
            <td>{{longShort}}</td>
            <td>{{custodianAccount}}</td>
            <td>{{strategy}}</td>
            <td>{{manager}}</td>
            <td>{{basket}}</td>
            </tr>
            </tbody>
            <tr>
            <td bgcolor="darkgrey" colspan = "13"></td>
            <td bgcolor="darkgrey"><strong>Ending Balance: {{summary.endingBalance}} <br> Debits: {{summary.debits}}  <br> Credits: {{summary.credits}} <br> Ending Bal Type: {{summary.endingType}}</strong></td>
            </tr>
            
         </tbody>
         </head>
        {{/each}}
         <tr>
         <td colspan="13"></td>
        <td><strong>Period Ending Balance: {{total.endingBalance}} <br> Ending Credits: {{total.credits}} <br> Ending Debits {{total.debits}} <br> Ending Balance Type {{total.endingType}}</strong></td>
        </tr>
        <thead> 
         {{/each}}
    </table>
 </div>
</body>`

**Comment by simonbengtsson** [comment]
The error states that it is an issue with the selector passed. Try to log
the id in the console before passing it to auto table to make sure it is
valid.

**Comment by thomasazdon** [comment]
I did - I also changed the name to a nondynamic table identifier - 'trialbalance' - I then get a blank pdf.

**Comment by simonbengtsson** [comment]
You need to pass a valid CSS selector. Maybe you forgot the #?

**Comment by thomasazdon** [comment]
You are 100% correct.  Thank you.

**Comment by thomasazdon** [comment]
It is interesting though that when I switch back to a dynamically generated css table id - Jsautotable cannot find it.   Naming the table id 'trialbalance' works - but naming it using the api call request id dynamically does not.  

DOMException: Failed to execute 'querySelector' on 'Document': '#43fb3d58-12df-4c0a-b20f-289400673544' is not a valid selector.

doc.autoTable({ html: '#${pm.info.requestId}' }); - does not work even when the table is so named and resolves:

> `<table id = "${pm.info.requestId}" `

This consoles to:

    function generate() {
        //Creation of PDF document
        let doc = new jsPDF('l', 'pt');
        doc.autoTable({ html: '#43fb3d58-12df-4c0a-b20f-289400673544' });
       
        //--------------------------------------------------------------------------------------------------START
        //Change name of report if desired
        doc.save('V13 Trial Balance Summary ReportReport time: 2018-01-03T12:00:00Z.pdf');
        //--------------------------------------------------------------------------------------------------END
}
<table id="43fb3d58-12df-4c0a-b20f-289400673544" class="display nowrap dataTable no-footer"
