### ISSUE TITLE
Padding does not work in Firefox when using the useCss option.

### ISSUE THREAD

**Issue by qlum** [simonbengtsson/jsPDF-AutoTable#591]
Similar to https://github.com/simonbengtsson/jsPDF-AutoTable/issues/524

Chrome supports `getComputedStyle().padding` where Firefox and possibly other browsers do not. 

This results in padding being ignored when using the useCss option and applying padding in css.

The solution would be to use the split variant instead:
`getComputedStyle().paddingTop`, `getComputedStyle().paddingRight`, `getComputedStyle().paddingBottom`, `getComputedStyle().paddingLeft`

See for more information: https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#notes

**Comment by simonbengtsson** [comment]
Sounds reasonable! I can merge a PR right away if you send one.

**Comment by qlum** [comment]
I have never used nodejs myself, so I have to figure things out before I can make a proper PR.
For now, here is the quick hacky way of doing things on the compiled js file: [jspdf.plugin.autotable.js.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4159929/jspdf.plugin.autotable.js.zip)

change on line 2134
old: `style.padding,`
new: `style.paddingTop + ' ' + style.paddingRight + ' ' + style.paddingBottom + ' ' + style.paddingLeft,`

I can try to figure out setting everything up properly in the weekend.

**Comment by simonbengtsson** [comment]
You would have to divide the padding sum by four as well right or similar? The file you want to make changes to is most likely `cssParser.ts`.

**Comment by qlum** [comment]
Made the PR,
Basically I just added an array of padding top,right,bottom,left instead of just a combined value.
Since the script would otherwise have to split it anyway. 
It was just a bit of figuring out how node works to compile and prettify it.
I ended up just copy-pasting between a working directory and my git repo.
which should work fine.
