### ISSUE TITLE
How I can remove or show icons in PDF

### ISSUE THREAD

**Issue by DanielObara** [simonbengtsson/jsPDF-AutoTable#593]
When I export PDF using `doc.autoTable({ html: ".MuiTable-root" });` the results is:
![image](https://user-images.githubusercontent.com/42970570/74059867-911ae580-49c7-11ea-81d4-12257b826db3.png)

because my element in html is something like this: 
![image](https://user-images.githubusercontent.com/42970570/74059953-bd366680-49c7-11ea-9b0c-50d8c254e503.png)

How can I remove or show the chev/arrow icons when I export to pdf?

Thanks you!

**Comment by simonbengtsson** [comment]
You can use the didParseCell hook to modify the content of the cell Before it is drawn. It's weird it transformed the icon to a name though.

**Comment by DanielObara** [comment]
Thanks!
