### ISSUE TITLE
custom cell width does not working 

### ISSUE THREAD

**Issue by Tanjeeb** [simonbengtsson/jsPDF-AutoTable#594]
`doc.autoTable({`
                    `html: '#table8', styles: {fillColor: null},`
                    `headStyles: {textColor: [0, 0, 0]},`
                    `alternateRowStyles: {fillColor: null},`
                    `fontSize: 12,`
                    `columnStyles:{ minCellWidth:500}`

               });

**Comment by simonbengtsson** [comment]
Can you post complete example code? Seems to work in the examples?
