### ISSUE TITLE
Potential Error With Users On < Typescript 3.7

### ISSUE THREAD

**Issue by colby2** [simonbengtsson/jsPDF-AutoTable#596]
There is currently an issue when using 3.2.12 with a version less than typescript 3.7.
I am unable to upgrade to typescript 3.7 due to being stuck on Angular 8 for the time being.
The issue was builds failing due to the following error:

> node_modules/jspdf-autotable/dist/index.d.ts:60:6 - error TS1086: An accessor cannot be declared in an ambient context.
60  get pageCount(): number;

Reverting to 3.2.11 fixed the issue for me.

**Comment by simonbengtsson** [comment]
Weird! Released a new version now without the getter in the error message. Let me know if it works for you.

**Comment by colby2** [comment]
> Weird! Released 3.2.13 now without the getter in the error message. Let me know if it works for you.

Didn't expect such a quick fix! So far so good. Looks like it's fixed.
