### ISSUE TITLE
Page break - empty row on ends of some pages

### ISSUE THREAD

**Issue by amgilroy0894** [simonbengtsson/jsPDF-AutoTable#597]
I have read a few closed posts that did not resolve my issue, eg https://github.com/simonbengtsson/jsPDF-AutoTable/issues/370

Hi, I am having this issue still
image
My code for creating the PDF looks as follows:

`$j( "#export" ).click(function() {
$j.each(ultraChartData, function(index, value) {
var doc = new jsPDF();
var headers = value[0];
value.shift();

    doc.autoTable({
    head: [headers],
    body: value,
    
    styles: {
    	cellPadding: 10,
    },
    columnStyles: {
		0: {cellWidth: 30},
		1: {cellWidth: 80}}
    });
  doc.save('table.pdf');
  });
});`

It is supposed to be printing multiple pdfs

**Comment by simonbengtsson** [comment]
I'm not sure I undestand your issue. Can you create a minimal example with formatted code that I can use to reproduce it?

**Comment by amgilroy94** [comment]
fixed with rowPageBreak: 'avoid', when generating autotable
