### ISSUE TITLE
I need use a component as jsPDF-AutoTable in React.

### ISSUE THREAD

**Issue by jochercoles** [simonbengtsson/jsPDF-AutoTable#599]
Hi guys, good morning. Is posible use this component in React? How? As I do any other component?

I'm sorry for molest with my question.

Regards

Javier.

**Comment by mmghv** [comment]
This is a normal javascript plugin, and it doesn't interact with the DOM, so what prevents you from using it in React? I myself use it in VueJS.

You `npm install jspdf jspdf-autotable` and import it:

```js
import jsPDF from 'jspdf'
import 'jspdf-autotable'

// ..

function print() {
  const doc = new jsPDF()
  doc.autoTable({ /* .. */ })
  doc.save('print.pdf')
}
```

**Comment by jochercoles** [comment]
Thank you so much MMGHV for your help. I thought in this possibility, but I didn't want work without security that was possible use.
Regards.
Javier.

**Comment by dscode89** [comment]
For some reason this is isn't working for me when. I am using Vite/TS and I think there is an issue with the type declarations.
