### ISSUE TITLE
How can I adjust the header fields with table data.

### ISSUE THREAD

**Issue by lavarajallu** [simonbengtsson/jsPDF-AutoTable#601]
Hi Team ,  I searched about the auto adjust fields but the text cutting like below this
[holidays_list (14).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4224051/holidays_list.14.pdf)

**Comment by AminBangash** [comment]
I have updated my project from angular 7 to 8. jspdf-auotable isn't working in angular 8. I think it is not supported in new angular version. I got no error but empty page is printed. Any support for angular 8 from jspdf-autotable community.
