### ISSUE TITLE
Table height is always 0

### ISSUE THREAD

**Issue by alexfromgalax87** [simonbengtsson/jsPDF-AutoTable#604]
doc.autoTable({
        startY: 50,
        head: [['Feld', 'Wert']],
        columnStyles: {
          0: { cellWidth: 120 },
          1: { cellWidth: 60 }
        },
        didParseCell: HookData => {
          console.log(HookData); // <- height is set and has value 
          console.log(HookData.table.height);  // <- height is 0 ????
          tableHeight = HookData.table.height;
        },
        body: tableDataArray
      });

In the didParseCell-Hook I get the HookData nad the height is set to the actual height of the table, but if i print out the HookData.table.height the height is 0, why that?

**Comment by jakbar9220** [comment]
Use 'didDrawPage' instead of 'didParseCell'.
