### ISSUE TITLE
Html Property for table reference in Angular 8 not working.

### ISSUE THREAD

**Issue by AminBangash** [simonbengtsson/jsPDF-AutoTable#605]
Jspdf-Autotable not working in angular 8 via html property to reference html table. Is there any solution for it. Have anybody use it in angular 8 while same code was used in angular 7 and it works perfectly. Need suggestion on that.

**Comment by jakbar9220** [comment]
https://github.com/simonbengtsson/jsPDF-AutoTable/issues/508#issuecomment-577171800

**Comment by AminBangash** [comment]
Defining <thead> and <tbody> within table can fix this issue. But this is bug it should be solved. Table can be referred without these tags.

**Comment by simonbengtsson** [comment]
Sounds like a great improvement. Should be noted that I verified now that normal html tables without tbody and thead works. Can you post sample code of what doesn't work?

**Comment by AminBangash** [comment]
> Sounds like a great improvement. Should be noted that I verified now that normal html tables without tbody and thead works. Can you post sample code of what doesn't work?

It works in angular 7 without thead and tbody but not in angular 8.

**Comment by simonbengtsson** [comment]
Fixed in https://github.com/simonbengtsson/jsPDF-AutoTable/commit/307596bd050e1ae0d3079145bdbed5cf0406a3ee. Will be released in >3.3.0.
