### ISSUE TITLE
CellWidth < 10 ?

### ISSUE THREAD

**Issue by hnvseau** [simonbengtsson/jsPDF-AutoTable#609]
Is it possible to have a column width smaller than 10 ?
I want to use it as a column divider (thicker line basically) 

I have tried:
```
div: { minCellWidth: 1, cellWidth: 1, fillColor: 50, overflow: 'hidden' }
```
but it looks like the width is still 10.

Before some update I had:
```
div: { columnWidth: 1, fillColor: 50 }
```
and it was working perfectly:
![Screenshot from 2020-03-03 19-17-39](https://user-images.githubusercontent.com/29463699/75806309-b2cb7a80-5d83-11ea-9f3d-3826e65f06f0.png)

**Comment by simonbengtsson** [comment]
Good point! It might not be possible currently but would be nice!

**Comment by simonbengtsson** [comment]
Since columnStyle only affects only body cells you need to use a hook manually set the cell width of an entire column now.

    didParseCell: data => {
      if (data.column.index === 2) {
        data.cell.styles.cellWidth = 0.5
        data.cell.styles.fillColor = [0, 0, 0 ]
      }
    }

Doing this you can get a column of any width and get around the 10 default value.
