### ISSUE TITLE
Problem with long json

### ISSUE THREAD

**Issue by jeebee2013** [simonbengtsson/jsPDF-AutoTable#61]
Hi
i've a problem with long json text who render strange table

for example:
 example file example.js on Overflow 'linebreak'
in line 315 if you change var sentence = faker.lorem.words(52); -> var sentence = faker.lorem.words(252);
you will have a table with a empty at the beginning
and sometime data in cell are desynchronise.
any ideas?
thanks

**Comment by someatoms** [comment]
I actually ran into the same problem (cell height is higher than what can fit on a page). Unfortunately I don't have a timeline for when it will be fixed.

**Comment by someatoms** [comment]
Since v2.0.2 cells higher than page size now gets ellipsized instead of making empty pages and other formatting issues. This is a first step to solve this issue, but if you want to have longer cells than page size you need to divide it manually for now.

**Comment by jeebee2013** [comment]
thanks simon
i will have a look
thanks for your great work on autotable
jb

**Comment by jeebee2013** [comment]
hi tom
thanks for your help
just try whit 2.0.2
still have the issue with a page break on beginning of pdf when the 1'rst
cell is long text (file : devis N2195.pdf attached)
no issue when 1rst cell is short text  (file : devis N2194.pdf attached)
let me know how i can help
best regards & thanks again

julien

2015-08-29 0:57 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by someatoms** [comment]
It seems like it doesn't work attaching files in emails and posting on github. Could you upload the pdf here? Preferably with the code you are using?

**Comment by simonbengtsson** [comment]
Cells spanning longer than one page height is still an issue and will be truncated now as mentioned above. For now I want do anything more than this, but I'm open for pull requests.

**Comment by santukumar2017** [comment]
This is working fine for me.
Use 'bloburl' instead of 'datauristring'.

Javascript/jquery:

$("#pdf_preview").attr("src", doc.output('bloburl'));

html

<iframe id="pdf_preview" type="application/pdf" style="border:1px solid #666CCC" title="PDF Records" frameborder="1" scrolling="auto" height="520" width="100%"></iframe>
best of luck...
