### ISSUE TITLE
didParseCell: can't target only first row after head

### ISSUE THREAD

**Issue by henrikwirth** [simonbengtsson/jsPDF-AutoTable#613]
Hi, in this example I'm trying to give all the elements in the third column's body an align="right".

The problem is that it seems both the first row in the body and also the head itself has `row.index = 0`. So I can't target all the rows coming after the header.

Instead with this example both the Head and the first row are not aligned right.

Maybe this is a wrong approach, but either way, I feel it shouldn't happen.

```
  pdf.doc.autoTable({
    head: head,
    body: body,
    startY: 97,
    margin: { left: 25, right: 25 },
    bodyStyles: {
      textColor: "#333333",
      fontSize: 8,
      cellPadding: 1,
    },
    headStyles: {
      fillColor: "#2ea701",
      textColor: "#fff",
    },
    didParseCell: function(data) {
      if (data.row.index > 0 && data.column.index === 2) {
        data.cell.styles.halign = "right"
      }
    },
  })
```

**Comment by simonbengtsson** [comment]
You can check that a cell is in body by checking `data.cell.section === 'body'`

**Comment by henrikwirth** [comment]
@simonbengtsson this worked perfectly. Thanks a bunch. Couldn't find this example anywhere.
