### ISSUE TITLE
With Custom fonts Arabic text is breaking

### ISSUE THREAD

**Issue by 1202ajay** [simonbengtsson/jsPDF-AutoTable#614]
`document.autoTable({
      head,
      body,
      startY: XX,
      styles: { lineColor: '#c7c7c7', lineWidth: 0, cellPadding: 2},
      headStyles: { fillColor: '#ffffff', textColor: '#333333', font: '**Helvetica**' },
      bodyStyles: { fillColor: '#f5f5f5', textColor: '#333333', fontSize: 7, lineColor: '#c7c7c7', lineWidth: 0 }
    });`

head am passing as below:
`const head = [{
        content: "طيران الإمارات",
        styles: { valign: 'centre', cellPadding: {top: 3}, fontSize: 9, fontStyle: 'bold', cellWidth: 110.6 },
      },
      {
        content: 'Miles',
        styles: { fontSize: 9, fontStyle: 'normal', valign: 'centre', cellWidth: 35 },
      },
      {
        content: 'Tier Miles',
        styles: { fontSize: 9, fontStyle: 'normal', valign: 'centre', cellWidth: 35 },
      }
      ];
`

with Helvetica Font, Head Text showing as Special characters. 

With Custom font Its showing in Arabic but word is breaking I have passed as header this "**طيران الإمارات**" but in pdf its showing as this **طير لإما**
![ArabicBrakWord](https://user-images.githubusercontent.com/19665785/77246999-50f58680-6c46-11ea-9474-b889119346c9.JPG)
![SpecialChar](https://user-images.githubusercontent.com/19665785/77247000-5226b380-6c46-11ea-955c-05836b055f02.JPG)

** Breaking word

Can you please me help on this

**Comment by mmghv** [comment]
Check if it does the same with `jsPDF` then it's a font problem, otherwise create a codepen replicating the problem

**Comment by 1202ajay** [comment]
with `jsPDF` also same issue..

**Comment by mmghv** [comment]
Then it's not `jsPDF-AutoTable` issue, it might be font issue so try other fonts.

**Comment by 1202ajay** [comment]
@mmghv can you please share sample font which will work for Arabic...
i.e. custom font example

**Comment by mmghv** [comment]
Here you go :

[custom-font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4367588/custom-font.zip)

- I first downloaded the font files (example font : `Amiri` from [google fonts](https://fonts.google.com/?subset=arabic))
- Then, using [jsPDF font-converter](https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html) I converted the font file to `js` file
- then simply imported the font `js` file after importing both `jsPDF` and `jsPDF-AutoTable`

**Comment by 1202ajay** [comment]
@mmghv 
It's working.

Thank you

**Comment by ERROUDANI** [comment]
> Here you go :
> 
> [custom-font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4367622/custom-font.zip)
> 
> * I first downloaded the font files (example font : `Amiri` from [google fonts](https://fonts.google.com/?subset=arabic))
> * Then, using [jsPDF font-converter](https://rawgit.com/MrRio/jsPDF/master/fontconverter/fontconverter.html) I converted the font file to `js` file
> * then simply imported the font `js` file after importing both `jsPDF` and `jsPDF-AutoTable`
> 
> Just one thing, I noticed that some fonts may have small problems with some of the letters (letters compilations or tashkeel) , so you will need to test couple of fonts before deciding on a good font to use.

CAN YOU PLEASE SHOW HOW TO USE IT IN JUST JSPDF
