### ISSUE TITLE
applyPlugin is undefined

### ISSUE THREAD

**Issue by derMart** [simonbengtsson/jsPDF-AutoTable#616]
Hey,

I am trying to use the autoTable Plugin together with the yWorks jsPDF version in a webpack environment.
I installed the autotable repo via `npm install jspdf-autotable`

No errors thrown when
`import { applyPlugin } from 'jspdf-autotable'`
but applyPlugin is undefined. Any ideas?

**Comment by derMart** [comment]
ah i got it, I was using version 3.2.x and version 3.3.0 was just released yesterday ;-)
After updating the npm package to 3.3.0 it is no longer undefined

**Comment by simonbengtsson** [comment]
Glad you found it so soon! Can I ask how you found it? Did you read the nodejs example code?

@mmghv Good decision to export the applyPlugin method considering it seems to be at least one common fork of jspdf out there 👌

**Comment by derMart** [comment]
Well first, thank you so much for this method, very good decision :-) Currently it seems that the standard jsPDF npm version 1.5.3 does not work together with [svg2pdf.js](https://github.com/yWorks/svg2pdf.js), which I need for a project.

Concerning the question, I found out just by looking at the README.md, this was sufficient to get it running in the end. (Wasn't aware that the README changed though between my initial installation of autotable, hence the initial problem)
