### ISSUE TITLE
Trying to get total amount of pages 

### ISSUE THREAD

**Issue by StormNotes** [simonbengtsson/jsPDF-AutoTable#618]
Cheers everyone, I hope you are all staying safe at home!

Now at my issue here around, I am trying to get this information 
![image](https://user-images.githubusercontent.com/21282684/77828033-09fd0a80-70f8-11ea-8144-92b458ba2ded.png)

This is the Header from Google Chrome browser, what i am trying to do, its to display the same "header" but on a top corner of my PDF document, only on the first page.

i been seen around people playing with doc.internals,  but for some reason the data that i am receiving, does not seem to be accurated with my document,  Whenever i check for the pages.length, it always shows "Two ( 2 )" of them, when sometimes my pdf file can come around with only one page, or three, always displaying the same outpit, this been the number two,   is there any way to exactly get those numbers?

**Comment by simonbengtsson** [comment]
Have you seen the header and footer example?

**Comment by StormNotes** [comment]
> Have you seen the header and footer example?

I think not !

**Comment by StormNotes** [comment]
@simonbengtsson , worry not i found a way to develop what i wanted ! 

Il be sharing the Answer !

Scenario: 

Your pdf needs a internal header, why ? cus clients ask for it ! Whatever !

First we declare a variable as an **example il be calling this var as " numOfPages "** , with the value of  " doc.internal.getNumberOfPages() ; "

on my case, i need this to be fully adaptive, for any type of amount of pages of my pdf, sounds repetitive, easy, FOR LOOP!

for ( var i = 1; i <= numOfPages; i++){
doc.setPage(i);
doc.text(20,20 `Page ${i}  of ${numOfPages}`;
}

doc.save ( ' yada yada name.pdf ');


Okay, mind asking why i am setting the var i as a 1 and not 0 ?  i found inside the doc.internal pages array's starts at one, i have no idea why's this, but if the var is set at 0 it will re write on top of your next page.

I hope this can help someone around, i couldt find the right answer before figure this out!

**Comment by mmghv** [comment]
What's wrong with the method used in the [header and footer example](https://simonbengtsson.github.io/jsPDF-AutoTable/#header-footer) ?

https://github.com/simonbengtsson/jsPDF-AutoTable/blob/0866f83ac4731827f8eebb802b3b55cb08105d09/examples/examples.js#L188-L228

**Comment by a-ditucalan** [comment]
any update here?

**Comment by shubhamkaneriv2stech** [comment]
> What's wrong with the method used in the [header and footer example](https://simonbengtsson.github.io/jsPDF-AutoTable/#header-footer) ?
> 
> https://github.com/simonbengtsson/jsPDF-AutoTable/blob/0866f83ac4731827f8eebb802b3b55cb08105d09/examples/examples.js#L190-L225

thanks for this
