### ISSUE TITLE
3.3.1 have not export applyPlugin 

### ISSUE THREAD

**Issue by Krasnopir** [simonbengtsson/jsPDF-AutoTable#622]
in 3.3.0 there was added export applyPlugin, but  after  updating  to 3.3.1 it become  undefined.
now i freezed 3.3.0  version.  fix it  please.
or fix  doc if applyPlugin deprecated

thanks

**Comment by mmghv** [comment]
Just tested it, working fine for me!

**Comment by mmghv** [comment]
And can see it exported in `dist` file

https://github.com/simonbengtsson/jsPDF-AutoTable/blob/0866f83ac4731827f8eebb802b3b55cb08105d09/dist/jspdf.plugin.autotable.js#L938-L940

**Comment by Krasnopir** [comment]
i use 
import { applyPlugin } from 'jspdf-autotable';

and have 
TS2305: Module '"../../../../node_modules/jspdf-autotable/dist"' has no exported member 'applyPlugin'.

it can not  find  export in index.d.ts file

**Comment by mmghv** [comment]
@simonbengtsson Why `applyPlugin` export is not being added to `index.d` ? does it need a special typing?

**Comment by simonbengtsson** [comment]
Seems we needed to revert `export { applyPlugin }` to `export function applyPlugin` again for some reason. Pushed this so it's available on master now @Krasnopir that you can use right now.  We will release a new version on npm  soon as well.

**Comment by mmghv** [comment]
But this way of exporting should be supported
https://www.typescriptlang.org/docs/handbook/modules.html#export-statements

I'm not sure why it's not picking it up, I don't know TS but I believe this is a valid export, maybe it's caused by the plugin that exports the types?

**Comment by mmghv** [comment]
maybe needs an interface or something?
again, I don't know what I'm talking about here :laughing: I'm that families with TS

**Comment by mmghv** [comment]
@simonbengtsson we should release a `patch` version for this fix and not include it with the width improvement release.

**Comment by simonbengtsson** [comment]
Done! Released 3.3.2 now.

**Comment by Krasnopir** [comment]
Thanks gues!
