### ISSUE TITLE
non uniform cellPadding together with halign='center' resp. valign='middle'

### ISSUE THREAD

**Issue by derMart** [simonbengtsson/jsPDF-AutoTable#623]
Hi,

Using version 3.3.1 when having a non uniform `cellPadding`, e.g. left > right in a cell using `halign = 'center'` the text inside is centered across the whole width of: left padding + (text width + extra space available) + right padding
An example is shown here: https://jsfiddle.net/budh6vpm/ (second column)

I am just opening this to discuss if this is desired behaviour or not. To me it felt a little unintuitive.
For a project I needed text centered excluding the paddings, so the text should be centered inside: (text width + extra space available) and then paddings should be applied as specified.
Anybody got an idea how html tables / css are handling such situations? Maybe one could do it exactly the same to avoid confusion...?

For my project I found a general workaround using the willDrawCell hook which i'd like to share:
```
willDrawCell(data) {
  var cell = data.cell;
  if(cell.styles.halign === 'center') {
    var cell = data.cell;
    var pL = cell.styles.cellPadding.left || 0;
    var pR = cell.styles.cellPadding.right || 0;
    var textWidth_2 = (cell.width - pL - pR) * 0.5;
    var textLeftX = cell.textPos.x - textWidth_2;
    var textRightX = cell.textPos.x + textWidth_2;
    if(textLeftX - pL < cell.x) {
      cell.textPos.x = cell.x + pL + textWidth_2;
    }
    if(textRightX + pR > (cell.x + cell.width)) {
      cell.textPos.x = cell.x + cell.width - pR - textWidth_2;
    }
  }
}
```
here is the same example fiddle including the workaround. It also includes the vertical version.
https://jsfiddle.net/e3xLyo6h/2/

kind regards
Martin

**Comment by mmghv** [comment]
Text align should not include padding just like html, so this needs to be fixed.
I'll work on it soon, Thanks for reporting.
