### ISSUE TITLE
Creating Horizontal tables

### ISSUE THREAD

**Issue by nithingit** [simonbengtsson/jsPDF-AutoTable#63]
How can we create Horizontal tables using jspdf-autotable.

For example:

Report Id                                    |      RPT-2375856
Generation Date & Time            |      22-July-2015 | 10:35 AM IST
Requested By                            |      sysadmin

Here each row represents an attribute and its value.I don't want any column headers.
Here reportID ,gen time and requestedby are in one column .

**Comment by someatoms** [comment]
Great question! I suppose you could add a column and style it as a header, something like this:

    var doc = new jsPDF('p', 'pt');
    doc.autoTable(columns, data, {
        drawHeaderRow: function() {
            return false;
        },
        columnStyles: {
            first_name: {fillColor: [41, 128, 185], textColor: 255}
        }
    });
    doc.save('table.pdf');

However it all becomes kind of hard if the table would span multiple pages... I added this as one example in examples.js.

**Comment by nithingit** [comment]
I followed above steps for creating horizontal tables,I am getting the table but fillcolor in columnStyles is not working.

Please find the code below
var doc = new jsPDF(
																		'p',
																		'pt');

																

																

																doc
																		.setFontSize(14);
																doc
																		.setTextColor(
																				46, 116, 181);
																doc
																		.text(
																				"About",
																				40,
																				60);

																var generateUid = function() {

																	var delim = "-";

																	function S4() {
																		return (((1 + Math
																				.random()) * 0x10000) | 0)
																				.toString(
																						16)
																				.substring(
																						1);
																	}

																	return ("RPT"
																			+ delim + (S4() + S4()));
																};

																var repid = generateUid();
																var columns = [
																		{
																			title : "Report Id",
																			key : "rid"
																		},
																		{
																			title : repid,
																			key : "time"
																		} ];

																var d = new Date();
																var curdate = d
																		.toString()
																		.slice(
																				0,
																				-14);

																var data = [ {
																	"rid" : "Report Id",
																	"time" : repid,

																} ,{
																	"rid" : "Generation Date & Time",
																	"time" : curdate,

																}
																];

																doc
																		.autoTable(
																				columns,
																				data,
																				{
																					theme:'grid',
																					startY : 80,
																					tableWidth: 300,
																				
																					
																					styles : {
																						overflow : 'linebreak',
																						cellPadding : 2,
																						rowHeight : 15,
																						fontSize : 10,
																						textcolor:0
																					},
																					
																					 drawHeaderRow: function() {
																				            // Don't draw header row
																				            return false;
																				        },
																				        columnStyles: {
																				           rid:{fillColor: [166, 166, 166]}
																				        }
																			        

																				});

**Comment by nithingit** [comment]
I found out the problem fillColor in columnStyles is not working in theme 'grid'

**Comment by someatoms** [comment]
It should work if you set the style fillStyle to either 'FD' or 'F'. It accepts the same values as the doc.setFillStyle method, but I should clarify that in the documentation or provide an 'auto' option.

**Comment by Dfedericovera** [comment]
I had the same problem this worked for me:
var doc = new jsPDF('landscape');
