### ISSUE TITLE
Custom Font Bug v3.4.1

### ISSUE THREAD

**Issue by bsparacino** [simonbengtsson/jsPDF-AutoTable#632]
In v3.4.1 and v3.4.2 a bug was introduced which breaks custom fonts.
I get the error:
Unable to look up font label for font 'ARIALN', 'bold'. Refer to getFontList() for available fonts.
Unable to look up font label for font 'ARIALNB', 'normal'. Refer to getFontList() for available fonts.

It seems to be inverting either the font or fontStyle between lines of fonts I am printing out.
If I switch back to v3.4.0 then it works.

The issue has to do with this block of code, if I copy the stylesMofifiers block from the previous version then everything is working again.

https://github.com/simonbengtsson/jsPDF-AutoTable/commit/d6e69dab2c194ffd135f42e79b67a0f7c51709b2?diff=split
![image](https://user-images.githubusercontent.com/210408/79073230-44d77480-7c9a-11ea-910c-e8fd825fc81d.png)

**Comment by mmghv** [comment]
Custom fonts works well for me, Could you edit this example to make it not work?
[custom-font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4466663/custom-font.zip)

**Comment by bsparacino** [comment]
Here you go
[custom-font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4466675/custom-font.zip)

**Comment by bsparacino** [comment]
Here you go. If you change the version back to 3.4.0 then the errors go away.

[custom-font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4466683/custom-font.zip)
![image](https://user-images.githubusercontent.com/210408/79074651-75bba780-7ca2-11ea-9acd-7c17b7dbe1fb.png)

**Comment by mmghv** [comment]
Got it, it's a matter of order of lines, `fontStyle` should be applied before `font`, will send PR now.
