### ISSUE TITLE
control margin on pagebreak

### ISSUE THREAD

**Issue by Poorvakute** [simonbengtsson/jsPDF-AutoTable#634]
I want to control margin or change margin for table of page on page break. It is possible to control on new page of pdf, but I am not able to change it while page break.
I Have written this code in didDrawPage():

if (doc.internal.getNumberOfPages() !== data.table.startPageNumber) {
                margin= 30;
            } else {
              margin = 50;
            }

**Comment by mmghv** [comment]
You probably just want to change starting position of first page, if so, set your margin normally and add `startY` option to controls starting position on first page.

From the docs :
> `startY: number = null` Where the table should start to be printed (basically a margin top value only for the first page)

**Comment by Poorvakute** [comment]
No.. see i want to add some introductory text only before start of the table (text is not a part of table). And to adjust that text i have added some margin top to table. Now the table is having large content and it is breaking in 2 pages. Now half of the table is on another page and don't want to add introductory text before this there but as i have set margin to adjust this text , this same margin is coming on second page also.

**Comment by mmghv** [comment]
That's what `startY` is meant for, it sets margin for first page only, which is what you want, because you have content on first page only and you want to offset the table on first page only, so just set `startY` to be what you want, and set margin to be the normal margin for the rest of the pages.

**Comment by Poorvakute** [comment]
I am having multiple table in same pdf. so how can i control for next table?

**Comment by mmghv** [comment]
Again, if you read the [docs](https://github.com/simonbengtsson/jsPDF-AutoTable) you would find out what you want :

> If you want to know something about the last table that was drawn you can use `doc.lastAutoTable`. It has a `doc.lastAutoTable.finalY` property among other things that has the value of the last printed y coordinate on a page. This can be used to draw text, multiple tables or other content after a table.

So you can set `startY` to be `doc.lastAutoTable.finalY` to start printing from last position of previous table.

**Comment by mmghv** [comment]
You could also check the [examples](https://github.com/simonbengtsson/jsPDF-AutoTable/tree/master/examples) to see code of multiple [demo](https://simonbengtsson.github.io/jsPDF-AutoTable/) scenarios.

**Comment by Poorvakute** [comment]
i have gone through it but didn't find any scenarios matching with mine. 
Please find below screenshot: 
![image](https://user-images.githubusercontent.com/48404391/79256418-e66beb00-7e7f-11ea-9397-c4385c77ebec.png)

i have added this text on top of table. you can see the table is breaking in 2 pages and white space before table on second page. second table starting on 3rd page where i want  same introductory page.

**Comment by mmghv** [comment]
What about the [example with content](https://simonbengtsson.github.io/jsPDF-AutoTable/#content)? it has text on first page and table breaks into two pages, exactly your scenario, uses `startY`:

https://github.com/simonbengtsson/jsPDF-AutoTable/blob/799cd737d7491155d0914e7b0dfb093976d16b21/examples/examples.js#L108-L133

About multiple tables, you'll find an example with multiple tables, check it out.

**Comment by Poorvakute** [comment]
working but coming on header like :
![image](https://user-images.githubusercontent.com/48404391/79259481-b3782600-7e84-11ea-8b07-77268cf297d2.png)
