### ISSUE TITLE
specify table border (top, bottom, left, right)

### ISSUE THREAD

**Issue by cplaiu** [simonbengtsson/jsPDF-AutoTable#637]
I have tried to do somthing like that:

<img width="602" alt="9fBzW" src="https://user-images.githubusercontent.com/32199465/79554545-7edfb680-809e-11ea-8c18-313756d7afa5.png">

but I realized that  cannot specify position of border, every time user  specifying `lineWidth` is applied to all edges. It would be nice if user could specify border position like: **top**, **bottom**, **left**, **right**.

I already asked about [stackoverflow ](https://stackoverflow.com/questions/61231635/display-border-only-inside-of-table-autotable-jspdf)but nobody answered, which makes me think that now it is not possible to do this.

**Comment by mmghv** [comment]
Currently you can't set each side of the border because cells share sides so that would be tricky, but if all you need is to have no outside border around the table, you could achieve that with a trick to set table border to white, erasing outside border, like that :

```js
doc.autoTable({
  // ...
  tableLineColor: [255, 255, 255],
  tableLineWidth: 1,
})
```

**Comment by cplaiu** [comment]
@mmghv Thanks youu save my life today.
