### ISSUE TITLE
Is it possible to drop to a new row after every 10 columns?

### ISSUE THREAD

**Issue by Capgop** [simonbengtsson/jsPDF-AutoTable#638]
![image](https://user-images.githubusercontent.com/54747422/80206781-a520cb80-8635-11ea-82a5-cf555149358b.png)

**Comment by mmghv** [comment]
There's no native support for that, You need to manually split your table into multiple tables of 10 columns each, or split columns into rows if that's what you want.

**Comment by Capgop** [comment]
Thank you @mmghv

**Comment by gitKodu** [comment]
Hi @mmghv @simonbengtsson 
I have a table without header, where there are the column 0 and 1 that are "fixed", and the number of other columns is variable. I need to have custom cell widths (equal to each other). 
The problem is that "units width could not fit page", so is there any way to split the table in more of them?



            doc.autoTable(res.columns, res.rows,{
              theme: 'grid',
              showHead: 'never',
              startY: 50,
              columnStyles: {
                    0:{ cellWidth: 200, fillColor: [220,20,60], textColor: 255, fontStyle: 'bold' },
                    1:{ cellWidth: 40, halign: 'center', valign: 'middle', fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' }
              },

              didParseCell: function (data) {
                var rows = data.table.body;
                if (data.column.index >1) {
                  data.cell.styles.halign = 'center';
                  data.cell.styles.valign = 'middle';
                  data.cell.styles.cellWidth = 70;
                }                  
              }

            });
