### ISSUE TITLE
autotable put 'Q' in place of 'Ő' and 'ő'

### ISSUE THREAD

**Issue by Atanii** [simonbengtsson/jsPDF-AutoTable#639]
Whenever I'm trying to export a mat-table containing 'Ő' or small 'ő' characters, in the exported pdf they are replaced by the 'Q' character.

I checked the documentation and I haven't found anything about setting the character encoding.

I'm using the export without additional options, eg.:

```js
const doc = new jsPDF();
doc.autoTable({ html: '#idOfTable' });
doc.save('table.pdf');
```

Everything else seems fine in the export.

**Comment by mmghv** [comment]
Refer to [jsPDF docs](https://github.com/MrRio/jsPDF#use-of-utf-8--ttf) for utf support.

**Comment by Atanii** [comment]
Thanks for the link! I missed that part, but the problem persists.

https://fonts2u.com/free-sans.font?ptext=%C5%91%C5%90

I used this font, converted the ttf to the js file as needed.

```js
import '<<path to js file>>/FreeSans-normal.js';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
```

I tried to import it after, before the jsPDF. I got an error that jsPDF is not defined, so I put this line at the very beginning of the FreeSans-normal.js file:
`import jsPDF from 'jspdf'`

It solved the error, I didn't even get the warning that there is no FreeSans font _(I tried a font without importing and saw it gives a warning in that case)_.

But, even so, after exporting the pdf it has the Q characters...

The interesting thing is that if I used only doc.text for a single line, it printed characters without an error, but without FreeSans I still got: "Q P ." instead of "öŐ."
So the font must be working properly, except for autotable.

```js
const doc = new jsPDF();
doc.setFont('FreeSans');
doc.setFontType('normal');
// doc.text(20, 30, 'őŐ.'); // It's working now.
doc.autoTable({ html: '#chartOfAccountsTable' }); // Still has Q chars...
doc.save('table.pdf');
```

**Comment by mmghv** [comment]
You still need to set font name for `autoTable` :

```js
doc.autoTable({
  html: '#idOfTable',
  styles: { font: "FreeSans" },
});
```

*Note:* table header is using `bold` style, so if you won't import the `bold` variant of the font, make sure to set header style to `normal` :

```js
  //
  headStyles: { fontStyle: 'normal' },
  //
```

**Comment by Atanii** [comment]
Thanks :) Its working now.
