### ISSUE TITLE
Typescript and dependency injection refactor

### ISSUE THREAD

**Issue by simonbengtsson** [simonbengtsson/jsPDF-AutoTable#640]
Have been refactors the entire plugin this weekend to be strict typescript typed and improved the exported types somewhat. Will release new version soon 👌

Also refactored to use parameter dependency injection everywhere instead of the previous `state()` module. Looks a bit messy at times with many parameters, but now all dependencies are clear and testing is much easier. Next step is to write tests for more components, but no timeframe on that.

In terms of feature requests the current most requested features seems to be colspan column width calculations (open issue), splitting wide tables horizontally across multiple tables and performance improvements.

Let me know if you have additional thoughts @mmghv

**Comment by mmghv** [comment]
Great work, just make sure to do some tests before releasing because there seem to be a problem the "Long text" example with `ellipsize`, also "Column styles" example and probably "Custom style".
 
I might be able to help with colspan width calculation in a couple of weeks, pretty swamp right now.

**Comment by simonbengtsson** [comment]
Fixed two for the column styles and custom style example which are probably the ones you saw as well. Have not seen any issues with the long text example though?

**Comment by mmghv** [comment]
I can see it's all fixed now :+1:

**Comment by simonbengtsson** [comment]
Released in 3.4.5 👌
