### ISSUE TITLE
Release 3.4.5 breaks the types

### ISSUE THREAD

**Issue by ranoy** [simonbengtsson/jsPDF-AutoTable#641]
Hello ,
 I have started getting error 'D:/node_modules/jspdf-autotable/dist"' has no exported member 'ColumnDataConfig'. I think there is some regression introduced

**Comment by simonbengtsson** [comment]
Can you show me the code you use? I removed typing for the deprecated initiation type, could that be what you are seeing?

**Comment by ranoy** [comment]
Hello Simon, 
Yes, I am using it as normal type in my angular application.
My import statements : 
import 'jspdf-autotable';
import { Styles, MarginPadding, ColumnDataConfig, ColumnOption } from 'jspdf-autotable';

then I have function with this type . for eg 
 

  public printPdfTables(pdfTables: ColumnDataConfig[], exportParams: ActionBarExportParams) {
    const doc: jsPDF = new jsPDF({ orientation: 'l' });
    const totalPagesExp = '{total_pages_count_string}';
    const filename = exportParams.fileName || 'Export';
    let y = 0;
  .....
  }



  private enrichWithColStyles(gridApi: GridApi, pdfTables: ColumnDataConfig[]): ColumnDataConfig[] {  .. } 



  private iteratorFnToEnrichPDFTable(
    gridApi: GridApi,
    columnApi: ColumnApi,
    exportParams: ActionBarExportParams,
    pdfTables: ColumnDataConfig[]
  )  { ... }

Nothing super fancy, just type information. Am I using it wrong ? It works fine with 3.4.4.

Thanks

**Comment by ranoy** [comment]
I had closed it by mistake, so repopened again

**Comment by simonbengtsson** [comment]
Interesting use case! ColumnDataConfig is now renamed to ColumnInput. Also note that the old initiation type is deprecated and removed from the types.

Out of curiosity, what is your code for calling the actual autoTable method?

**Comment by ranoy** [comment]
Hi ,
 Thanks for the clarification, my code is similar to what you provide in examples : 


  public printPdfTables(pdfTables: ColumnDataConfig[], exportParams: ActionBarExportParams) {
    const doc: jsPDF = new jsPDF({ orientation: 'l' });
    const totalPagesExp = '{total_pages_count_string}';
    const filename = exportParams.fileName || 'Export';
    let y = 0;
    if (exportParams.customHeader) {
      let customHeader = exportParams.customHeader.split('\n');
      customHeader = customHeader.filter(val => val);
      // insert custom header
      doc.setFontSize(this.customheaderFontSize);
      doc.setFontStyle(this.customHeaderFontStyle);
      // we have a manual for-loop insted of calling text fn with array from jspdf as I was facing issue with align center
      customHeader.forEach((val, index) => {
        const xOffSet = doc.internal.pageSize.getWidth() / 2 - (val.length * 1.5) / 2;
        const yOffset =
          index * (this.customheaderFontSize * doc.getLineHeightFactor() * this.ptToMmFactor) +
          (this.defaultMargin as any).top;
        doc.text(val, xOffSet, yOffset);
      });
      // calculate y position
      y =
        customHeader.length *
          (this.customheaderFontSize * doc.getLineHeightFactor() * this.ptToMmFactor) +
        (this.defaultMargin as any).top;
      doc.setFontStyle('normal');
    }
    for (let i = 0; i < pdfTables.length; i++) {
      doc.autoTable({
        ...pdfTables[i],
        ...{
          pageBreak: i === 0 ? 'auto' : 'always',
          startY: y ? y : null,
          didDrawPage: data => {
            // Footer
            let str = 'Page ' + doc.internal.getNumberOfPages();
            // Total page number plugin only available in jspdf v1.0+
            if (typeof doc.putTotalPages === 'function') {
              str = `${str} of ${totalPagesExp}`;
            }
            str = `${filename} ${str}`;
            doc.setFontSize(7);

            const pageSize = doc.internal.pageSize;
            const pageHeight = pageSize.getHeight();
            const pageWidth = pageSize.getWidth();
            doc.text(str, pageWidth / 2, pageHeight - 7);
          }
        }
      });
    }
    if (typeof doc.putTotalPages === 'function') {
      doc.putTotalPages(totalPagesExp);
    }
    doc.save(filename + '.pdf');
  }


If I change my type from `ColumnDataConfig` to `ColumnInput`, it should work? . I am not sure I got your old initiation type deprecation. But I am yer  to read new examples and what has changed. Maybe instead of patch , it should be 3.5.x release.

**Comment by simonbengtsson** [comment]
Aha! Misunderstood what you used ColumnDataConfig for. I would suggest you simply replace ColumnDataConfig[] with UserOptions[].
