### ISSUE TITLE
TypeError: doc.scaleFactor is not a function

### ISSUE THREAD

**Issue by Dinand-nl** [simonbengtsson/jsPDF-AutoTable#643]
I've added jsPDF-Autotables about a month ago in .net core 3.1. And it works.  
No changes made to the js file I use to create a PDF. 
Today I got an error. It points to line 324 of jspdf-autotable with the error in the subject.
It runs out on the first doc.autoTableHtmlToJson() no matter which one comes first.
So I believe Data does not influence the error. And the strange thing it worked perfect all the time I developed it. 
Here is my script

 

>  function generatePdf(luin, ResultType) {
> 
>         var doc = new jsPDF("A4");
> 
>         var elementHandler = {
>             '#ignorePDF': function (element, renderer) {
>                 return true;
>             }
>         };
>         doc.fromHTML(document.getElementById('labs-header-text'), 16, 0,
>             {
>                 'width': 180, 'elementHandlers': elementHandler
>             });  
> 
>         doc.setDrawColor(0, 0, 0);
>         doc.line(16, 30, 190, 30);
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("consultant"));
>         doc.autoTable(res.columns, res.data, { margin: { top: 31, left: 16, right: 16 }, styles: { fillColor: "#ffffff", cellPadding: 0 }, theme: 'plain' });
>         doc.setDrawColor(0, 0, 0);
>         doc.line(16, 58, 190, 58);
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("PData"));
>         doc.autoTable(res.columns, res.data, { margin: { left: 16, right: 16 }, styles: { fillColor: "#ffffff", cellPadding: 0 }, theme: 'plain', startY: doc.autoTable.previous.finalY + 3, });
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("ResultTableHead"));
>         doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff", textColor: "#050000" }, theme: 'plain', fontSize: 12 });
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("ResultTable"));
>         doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff" }, theme: 'plain', startY: doc.autoTable.previous.finalY, });
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("comment"));
>         doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff", textColor: "#050000" }, theme: 'plain' });
> 
>         if (ResultType=== "Assay") {
>             var res = doc.autoTableHtmlToJson(document.getElementById("s_details"));
>             doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff", textColor: "#050000" }, theme: 'plain' });
>         }
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("dates"));
>         doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff", textColor: "#050000" }, theme: 'plain' });
> 
>         var res = doc.autoTableHtmlToJson(document.getElementById("bottomelementtable"));
>         doc.autoTable(res.columns, res.data, { styles: { fillColor: "#ffffff" }, theme: 'plain', fontSize: 8, startY: doc.autoTable.previous.finalY });
> 
>         //autoprint screen lookup if we can skip some steps
>         //doc.autoPrint();
>         doc.save(luin);
>     }

The tags are:

>     <script src="https://unpkg.com/jspdf@latest/dist/jspdf.min.js"></script>
>     <script src="https://unpkg.com/jspdf-autotable"></script>

Jquery 3.5.0.
bootstrap 3.4.1
Datatables 1.10.20

And that is where the autoTableHtmlToJson gets his data from. All tables are build the same as this example and works perfect as you see

> <table id="consultant" >
>     <thead>
>         <tr>
>             <th>xxxxxxxxxx1</th>
>             <th>xxxxxxxxxx2</th>
>         </tr>
>     </thead>
>     <tbody>
>         <tr>
>             <td>@Model.xxxxxxxxxx1.Name</td>
>             <td>@Model.xxxxxxxxxx2.Name</td>
>         </tr>
>         <tr>
>             <td>@Model.xxxxxxxxxx1.Address</td>
>             <td>@Model.xxxxxxxxxx2.Address</td>
>         </tr>
>         <tr>
>             <td>@Model.xxxxxxxxxx1.City</td>
>             <td>@Model.xxxxxxxxxx2.City</td>
>         </tr>
>         <tr>
>             <td>@Model.xxxxxxxxxx1.ZipCode</td>
>             <td>@Model.xxxxxxxxxx2.ZipCode</td>
>         </tr>
>         <tr>
>             <td>@Model.xxxxxxxxxx1.Email</td>
>             <td>@Model.xxxxxxxxxx2.Email</td>
>         </tr>
>     </tbody>
> </table>

Do you have any suggestions why it gives an error?
Thank you. 

(But even now, Thank you for your beautiful product.) 

Dinand

**Comment by simonbengtsson** [comment]
Can you check if you are using latest version?

**Comment by Dinand-nl** [comment]
Hello Simon,
yes, 1.5.3 of jsPDF and 3.5.1 of js-PDF-Autotable

**Comment by simonbengtsson** [comment]
Found it and fixed it in just released 3.5.2. Thanks for reporting!

**Comment by Dinand-nl** [comment]
Oke, amazing that is super fast...Tested it, and it works perfect. 
Thank you for fixing and the fast action.

**Comment by Dinand-nl** [comment]
Hello Simon, 
Sorry again:
After the fix I've seen that all <th> aren't shown in the PDF.  
Is that right.

**Comment by simonbengtsson** [comment]
Nothing in the html parsing should have changed. Can you share your html code or parts of it?

**Comment by Dinand-nl** [comment]
Yes sure, table in the first comment above, is only anonymized with the xxxxxxxx. 

[TableForSimon.txt](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4552341/TableForSimon.txt)

It's the first table in my script (also above).

**Comment by Dinand-nl** [comment]
I wrote a new test application in .net (core 3.1). Don't if you can work with it. 
It is a complete solution. My sample pdf is included.
[JsPDF.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4553934/JsPDF.zip)

**Comment by simonbengtsson** [comment]
Unfortunately I can't run .net since I'm on mac. I think I found the issue however. Can you test the latest 3.5.3 and see if it works for you as well?

**Comment by Dinand-nl** [comment]
I don't know how you did it, but you did it again.
Yes it works, same solution, only with your latest version 3.5.3. PDF as proof below. 
[table300420201105.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4557263/table300420201105.pdf)

Again Amazing. Thank you so much.
