### ISSUE TITLE
 Cannot read property 'getFontSize' of undefined

### ISSUE THREAD

**Issue by zoiii** [simonbengtsson/jsPDF-AutoTable#644]
Hi, I've added jsPDF-AutoTable on my project (Angular 9) yesterday and encountered this issue.

![image](https://user-images.githubusercontent.com/11919790/80661666-81d4a100-8ab9-11ea-8cd2-30856114eb49.png)

> import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

 >const doc = new jsPDF('l', 'pt', 'letter');
 autoTable(doc, {
      body: this.items.getValue(),
      columns: this.columns.map(a => ({ header: a.headerName, dataKey: a.field }))
});

**Comment by simonbengtsson** [comment]
Can you check the version?

**Comment by zoiii** [comment]
Version: 

>  "jspdf": "^1.5.3",
> "jspdf-autotable": "^3.5.2",

**Comment by Capgop** [comment]
I have the same problem 
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.5.2",

![image](https://user-images.githubusercontent.com/54747422/80677810-0da6f700-8ad3-11ea-827b-3c8ba32c8bb2.png)

**Comment by zoiii** [comment]
![image](https://user-images.githubusercontent.com/11919790/80677982-2a97f600-8ae4-11ea-987f-c52c449c3210.png)

> startY: 70 - will cause the error but if I adjust it to 75 and up, it's working

**Comment by simonbengtsson** [comment]
Oh. This is most likely fixed on master. Will release npm version asap.

**Comment by simonbengtsson** [comment]
Released 3.5.3 now that hopefully fixes this issue. Can you see if it works for you?

**Comment by zoiii** [comment]
Confirmed working now for version 3.5.3. Thank you so much.

**Comment by simonbengtsson** [comment]
Btw, how is the new autoTable(doc, {/* options */}) syntax working for you? Is typing working as they should etc?

**Comment by zoiii** [comment]
![image](https://user-images.githubusercontent.com/11919790/80694362-9d15cf80-8afe-11ea-9063-4c31bd5c83b7.png)

![image](https://user-images.githubusercontent.com/11919790/80694422-b28af980-8afe-11ea-82f2-fa25bf26ba77.png)

I haven't encountered any issues yet. It is working fine. :)

**Comment by danielfnz** [comment]
It's working. Thank you so much.

**Comment by Bended** [comment]
Hi, I still have the same error on my Vuejs project.

<img width="618" alt="Screen Shot 2020-05-13 at 11 30 25" src="https://user-images.githubusercontent.com/19405580/81789826-31276400-950d-11ea-852e-2681f1766de2.png">

Version that I use
```
 "jspdf": "version": "1.5.3"
"jspdf-autotable": "version": "3.5.3"
```

Very basic implementation: 

`const doc = new jsPDF();
JsPDFAutotable({
head: [ [ 'Name', 'Email', 'Country' ] ],
 body: [
[ 'David', 'david@example.com', 'Sweden' ],
[ 'Castille', 'castille@example.com', 'Spain' ]
],
});`
