### ISSUE TITLE
I need to duplicate head, table and footer on as many pages as the table size

### ISSUE THREAD

**Issue by zangetsu182** [simonbengtsson/jsPDF-AutoTable#646]
Hello

I am testing the pluggin, I need to make a report that replicates the same head (report title) and footer (page counter) on all pages, I make a query to the bd and the result is not the size, if it exceeds the page it throws the table at me on the other page but it does not replicate the header and the footer, here my code:

    var data= [];
    var pdf = new jsPDF();
    let date = new Date(Date.now());    let day = date.getDate();    let month = date.getMonth() + 1;    let year = date.getFullYear();
    if(month < 10){  d=(`${day}-0${month}-${year}`);}else{  d=(`${day}-${month}-${year}`);  }
    var formatted = date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
toastr.info("Dentro de jsPDF->"+s);   
       var parametros={"op":9 ,"cve": s};                            
/*  make a query to the bd*/
                        $.ajax({
                            data: parametros,
                            type: "POST",        
                            url : "./cliente/managementpayment.php",
                            dataType: 'JSON'                                    
                        }).done(function (respuesta){                             
                             alert("res-"+respuesta); 
                              for(i = 0;i < respuesta.length;i++){            
                                data[i]=([respuesta[i].Importe,
                                    respuesta[i].Folio,
                                    respuesta[i].Fecha,
                                    respuesta[i].Placa,
                                    respuesta[i].RFC,
                                    respuesta[i].Concepto,
                                    respuesta[i].Oficina,
                                    respuesta[i].Usuario,
                                    respuesta[i].Anios]);                                    
                            } 
//                             alert("data-"+data);

                        pdf.setFont("times");
                        pdf.setFontSize(12);
                        pdf.text(68, 14, 'Reporte);
                        pdf.setFontSize(10);
                        pdf.text(67, 18, 'Reporte Principal');
                        pdf.setFontSize(9);
                        pdf.text(80, 22, 'Reporte);
                        pdf.setFontSize(11);
                        pdf.setFontType("bold");
                        pdf.text(91,31,'Historico de Pagos');
                        //pdf.addPage();

                        pdf.text(174, 18, 'Fecha: '+d);
                        pdf.text(174, 22, 'Hora: '+formatted);
                        pdf.setFontType("bold");
                        pdf.setFontType("italic");
                        pdf.setLineWidth(0.8);
                        pdf.line(10, 35, 200, 35);
                        pdf.setFontType("bold");
                        pdf.text(91, 39, 'Datos del Vehiculo'); /*comienza datos del vehiculo*/
                        pdf.setLineWidth(0.6);
                        pdf.line(10, 40, 200, 40);
                        pdf.setFontType("bold"); 
                        pdf.setFontSize(10);
                        pdf.text(20, 44, 'PLACA');
                        pdf.text(55, 44, 'SERIE');
                        pdf.text(130, 108, 'XAX);
                /*here is the problem, if you create the table but when the size exceeds the page in the following pages it only shows the records of the table and not the header*/             
                            var columns = ["Importe", "Folio", "Fecha","Placa","RFC","Concepto", "Oficina", "Usuario","Años"];
                                pdf.autoTable(columns,data,
                                {  styles: {fontSize:8.5 },margin:{ top: 129  }}                                            
                            );
                            pdf.autoTableSetPageContentHook(function(data) {
                                pdf.text("Header 2", 100, 50);
                              });
                        pdf.output('dataurlnewwindow');                            
                        });

**Comment by simonbengtsson** [comment]
Where did you find out about autoTableSetPageContentHook? Seems you are using many deprecated apis. Take a look at the header example for how to draw content on every page.

**Comment by zangetsu182** [comment]
I'm sorry that part of the code is the one I found on the web and I was testing, that part doesn't really work

"pdf.autoTableSetPageContentHook(function(data) {
                            pdf.text("Header 2", 100, 50);
                          });"

removing that, I will read what you tell me, thank you.

**Comment by zangetsu182** [comment]
i resolve this, with this code:

 didDrawPage: () => {

all headers into this, but @simonbengtsson I take this opportunity to ask you about a new message that I get an error, is this:

"Use of deprecated autoTable initiation"

do you know what this error is about?

**Comment by zangetsu182** [comment]
hey @simonbengtsson do you have any idea?
