### ISSUE TITLE
how to loop jspdf array data using javascript directly?

### ISSUE THREAD

**Issue by FixDev** [simonbengtsson/jsPDF-AutoTable#649]
I have an object like this :
`{
              SchoolName: "Eagle",
              No: "0206",
              PrintDateTime: "02-02-2020 10:00:00",
              Operator: [{
                UserId: "0206777",
                TransaksiOperator: [{
                    TrxCode: "101111",
                    Description: "Buy Some Book"
                  },
                  {
                    TrxCode: "101111",
                    Description: "Buy Some Pencil"
                  }
                ]
              }, {
                UserId: "0206778",
                TransaksiOperator: [
{
                    TrxCode: "111111",
                    Description: "Buy Some Shoes"
                  },
                  {
                    TrxCode: "111112",
                    Description: "Buy Some T-shirt"
                  }
                ]
              }]
            }`
I want to convert my table data to pdf, javascript directly, how?

**Comment by FixDev** [comment]
This is an example table, I want the table in the pdf to be the same
![git](https://user-images.githubusercontent.com/54017983/81354893-efef1880-90f6-11ea-9fbe-e4648fe5d5c3.png)

**Comment by FixDev** [comment]
This is the code that already exists now :+1: 
```
const printReport = ({
  IsData
}) => {
  var doc = new jsPDF({
    orientation: "landscape"
  });

  // table
  IsData.forEach(table)

  function table(element, index, array) {
    doc.autoTable({
      head: [
        [{
          content: `User ID: ${element.UserId}`,
          colSpan: 10
        }],
        ["Trx. Code", "Description"]
      ],
    })
    for (const e of element.TransaksiOperator) {
      doc.autoTable({
        body: [
          [e.TrxCode, e.Description]
        ],
        theme: 'grid'
      })
      console.log(e.TrxCode)
    }
  }

  doc.autoPrint();
  doc.output("dataurlnewwindow", "_blank");
};
```
This is the result of PDF :
![pdfgit](https://user-images.githubusercontent.com/54017983/81366116-166f7c80-9114-11ea-9695-5c3141334446.png)

**Comment by santunu23** [comment]
@FixDev Thanks a lot, it saves my day.
