### ISSUE TITLE
How do I remove the bottom border of all rows

### ISSUE THREAD

**Issue by biloo-dev** [simonbengtsson/jsPDF-AutoTable#651]
How do I remove the bottom border without removing the left border from all rows
 
![2020-05-09_055209](https://user-images.githubusercontent.com/37638323/81464454-d8c52f00-91b9-11ea-9db3-e103103351f8.png)

I want to design it this way

![2020-05-09_055035](https://user-images.githubusercontent.com/37638323/81464496-4a9d7880-91ba-11ea-9417-207970b915de.png)

**Comment by biloo-dev** [comment]
Thank you, I think I have found the answer
She is in the "wellDrowCell" event
I took the coordinates of each cell tho I drew a line with this code
doc.line(x1,y1,x2,y2)
x1 -----> data.cell.x;
y1 -----> data.cell.y + data.row.height;
x2 -----> data.cell.x;
y1 -----> data.cell.y 
`willDrawCell: (data) => {

    if (data.section == "body" && data.column.index != 0) {
         doc.setDrawColor(41, 128, 186) 
         doc.setLineWidth(.5);
         doc.line(data.cell.x, data.cell.y + data.row.height, data.cell.x, data.cell.y);
    }
}`

**Comment by Abuabdelah** [comment]
thank you @biloo-dev
