### ISSUE TITLE
Changing the font in the header not working?

### ISSUE THREAD

**Issue by udvaritibor** [simonbengtsson/jsPDF-AutoTable#653]
I've changed the font in my table successfully, and now I want to add a header.
The problem is that the font doesn't apply to it. It's in Times New Roman.
```
autoTable(doc, {
	startY: pageHeight - bottomMargin - footerHeight - tableH,
	margin: { left: margin.left, right: margin.right, bottom: 0 },
	head: head,
	body: body,
	tableWidth: tableWidth,
	theme: "plain",
	columnStyles: columnStyles,
	styles: {
		font: "Lato-Regular"
	}
});
```

I tried using the headStyles property, and also injecting a styles property to the header, but none of them seem to work.

```
...
headStyles: {
	font: "Lato-Regular"
},
...
```

```
const head = [[
	{
		content: "Color Table",
		colSpan: 3,
		styles: { font: "Lato-Regular" }
	}
]];
```

**Comment by simonbengtsson** [comment]
You might need to apply fontStyle: 'normal'. If so you should have a warning in the console mentioning something about bold not found.

**Comment by udvaritibor** [comment]
Oh, thanks, didn't notice the warning.
So headers are bold by default? I think that could cause some misunderstanding to users, like it did to me. But maybe it's just my thing :D

Thanks for the quick response!

**Comment by simonbengtsson** [comment]
True! Added a check for this now.

https://github.com/simonbengtsson/jsPDF-AutoTable/commit/8a8d751e505b3d9ff6498e8e03fb046a640db0d1
