### ISSUE TITLE
Type inaccuracies in Readme.md cause problems with Typescript.

### ISSUE THREAD

**Issue by devin5885** [simonbengtsson/jsPDF-AutoTable#654]
The Readme.md refers to the 'ColumnDef' type (i.e.)

_columns: ColumnDef[] For example [{header: 'ID', dataKey: 'id'}, {header: 'Name', dataKey: 'name'}]. Only use this option if you want more control over the columns. If not specified the columns will be automatically generated based on the content in html or head/body/foot_

However, there is no such type in the index.d.ts file or anywhere else I can find, in fact:

In v3.4.3, the type was ColumnOption
In v3.5.3, the type is now ColumnInput

It seems this was changed without any breaking changes notes in the release notes. (In fact I could not find any release notes at all).

So what is the recommended type to use for this in Typescript and will this change in the future?

**Comment by simonbengtsson** [comment]
I don't think ColumnDef has ever been a type and is only defined in the Readme. Might make sense to keep the type name the same in Readme and typescript though. If you submit a PR I will merge asap 👌

Btw, changelog is located in the github releases page.
