### ISSUE TITLE
Cannot read property 'getFontSize' of undefined

### ISSUE THREAD

**Issue by Bended** [simonbengtsson/jsPDF-AutoTable#655]
Hi, I still have the same error on my Vuejs project is the issue: [https://github.com/simonbengtsson/jsPDF-AutoTable/issues/644#](url)

<img width="618" alt="Screen Shot 2020-05-13 at 11 30 25" src="https://user-images.githubusercontent.com/19405580/81789826-31276400-950d-11ea-852e-2681f1766de2.png">

Version that I use
```
 "jspdf": "version": "1.5.3"
"jspdf-autotable": "version": "3.5.3"
```

```
import jsPDF  from 'jspdf';
import JsPDFAutotable from 'jspdf-autotable';
```

Very basic usage: 

`const doc = new jsPDF();
JsPDFAutotable({
head: [ [ 'Name', 'Email', 'Country' ] ],
 body: [
[ 'David', 'david@example.com', 'Sweden' ],
[ 'Castille', 'castille@example.com', 'Spain' ]
],
});`

**Comment by simonbengtsson** [comment]
Cannot reproduce this. Can you provide a runnable example?
