### ISSUE TITLE
How can I add new row above the first row of body in every single page?

### ISSUE THREAD

**Issue by bellsenawat** [simonbengtsson/jsPDF-AutoTable#657]
I try to find solution in issues but not found. 

Example.

Page 1
------------------------------------------
New row added 
------------------------------------------
row 1
------------------------------------------
row 2
------------------------------------------

Page 2 
------------------------------------------
New row added 
------------------------------------------
row 3
------------------------------------------
row 4
------------------------------------------

Thanks

**Comment by simonbengtsson** [comment]
That's what the table head is for?

**Comment by bellsenawat** [comment]
@simonbengtsson I try multiple header as well but, my condition not fit for this solution. Because I want to add new row if current row match condition and if that row is the first row of page.

**Comment by bellsenawat** [comment]
@simonbengtsson this example what I want to do. As the question I want to add new row "Section" 

![Screen Shot 2563-05-19 at 17 34 35](https://user-images.githubusercontent.com/5281760/82316472-0c445c80-99f7-11ea-8528-ec56fb04abc2.png)

**Comment by bellsenawat** [comment]
@simonbengtsson Do you have any suggestion? or do you need more information?

**Comment by simonbengtsson** [comment]
Aha! You might want to use colspans and style the section rows using the hooks. You can find examples of this in the examples.js file.

**Comment by bellsenawat** [comment]
@simonbengtsson Sorry, I think I explain not clearly. My problems is not about Styling.
### My Problems is : I want to add new row while table is drawing.

Example:  I have array contain this data [1,2,3,4,5,6,7,8,9,10 ... 999]; 

If the table start new page I want to add new data to the 1st row

My header |
------------ | 
1 |
2 | 
2 | 
2 |

**Comment by simonbengtsson** [comment]
Can't you modify the array before passing it to autoTable?

**Comment by bellsenawat** [comment]
@simonbengtsson Ahhh I can modify the array before passing it to autoTable, but I can't add new value to array in any hooks function. 

My workaround right now : 

Hardcode total row each page to display because I can modify data before passing to autoTable.
But If I don't want to hardcode I can't find any solution.

**Comment by simonbengtsson** [comment]
Tell me more about your use case. Why do you need to dynamically add new content? Is it depending on which page it is?

**Comment by IndaSari** [comment]
I have same issue. How do you solve this?
