### ISSUE TITLE
rowspan height larger the page Height not supported

### ISSUE THREAD

**Issue by Alihasanmu** [simonbengtsson/jsPDF-AutoTable#662]
![image](https://user-images.githubusercontent.com/30725063/83130210-97120f00-a0fb-11ea-97a7-8be9073b0199.png)
![image](https://user-images.githubusercontent.com/30725063/83130359-d2144280-a0fb-11ea-94ff-6162feed2c4c.png)
![image](https://user-images.githubusercontent.com/30725063/83130400-dfc9c800-a0fb-11ea-91d7-7e6eb2ee67eb.png)
tried rowPageBreak,pageBreak
Code:
doc.autoTable({
            html: '#section4_table',
            theme: 'grid',
            rowPageBreak: 'avoid',
            margin: { top: 70 },
            headStyles: { fillColor: '#343a40' },
            bodyStyles: {
                halign: 'center',
                valign: 'middle',
            },
            //didDrawCell:function(data){
            //    if(data.row.index>0 && data.row.index % 10 === 0 && data.column.index ===data.table.columns.length-1)
            //    {
            //        doc.addPage("a4","p");
            //    }
            //},
            //willDrawCell:(data)=>{
            //    if(data.cell.rowSpan>10)
            //        {data.cell.rowSpan=6;}
            //},
            didParseCell: enhance ? enhanceWordBreak : null
        });

**Comment by ly678910** [comment]
I have the same problem. May I ask how you solved it? thanks
