### ISSUE TITLE
Group-wise reports

### ISSUE THREAD

**Issue by gopaljangid123** [simonbengtsson/jsPDF-AutoTable#667]
Hi,
Is there any way to create group-wise reports like mentioned in below example.

![image](https://user-images.githubusercontent.com/38186980/83942612-b9e6a680-a812-11ea-872c-a6bf313c1690.png)

Thanks!

**Comment by mmghv** [comment]
You could achieve that with `colspans`, or you can just create multiple tables, a table for each group,

**Comment by gopaljangid123** [comment]
@mmghv I tried that but I was not able to achieve the desired result. If possible, could you please provide a working example that will give the result as per the attached screenshot.

Thanks!!

**Comment by mohamedsayed210** [comment]
@gopaljangid123  how you solve this Issues
