### ISSUE TITLE
Is it possible to achieve flex-wrap like layout?

### ISSUE THREAD

**Issue by Never7Dice** [simonbengtsson/jsPDF-AutoTable#669]
Here's example of what I'd like to achieve:
![image](https://user-images.githubusercontent.com/34353798/84416988-a629ae80-ac1d-11ea-80f4-afe22c6de2fa.png)

So basically:
- all cells are equally important, they all contain generalized content of any type.
- columns proportions are not preserved as cells can be shorter or wider and it doesn't depend on rows above or below.
- the amount of cells per row is not constant.
- the cell can carry over to next row if there is no space left for it on current row .

I know it is kinda against the table layout, but maybe it is possible somehow? Right now I have to make the width of 4 columns fixed and equal. So I waste a lot of space this way, short data get's more space than it needs, long data has to be squished, and the amount of cells in each row is constant.

Example of how currently my layout looks like:
![image](https://user-images.githubusercontent.com/34353798/84418119-577d1400-ac1f-11ea-8ec7-4c4d51cba8a3.png)

Partial solution would be to give cells which are considered having longer data a colspan of 2 or 3 cells

Any suggestions?

**Comment by mmghv** [comment]
As you said it, this is totally against the table layout, the column concept is gone, in HTML this can't be done with tables, it needed a whole new concept (flex layout).

So if you can't do it with HTML tables, you certainly can't do it with AutoTable.

Although I'm wondering why you're giving a fixed & equal width to all columns, it you let it to be auto, it will give most width to the longest content column, but in your example you have some sort of a long hash/path with no spaces that AutoTable will treat as one word and cause it not to wrap, so you may need to set `minCellWidth` for other columns.

**Comment by Never7Dice** [comment]
Understood.

I will try to use `minCellWidth` to improve current behavior, but it would've been great if there was `maxCellWidth`, this way it would be possible to limit the expansion of one cell, but also possible for empty cells to take minimum or 0 width.

**Comment by mmghv** [comment]
> but it would've been great if there was `maxCellWidth`

I agree, maybe we could add it in the future.
