### ISSUE TITLE
CellWidth causing Error: Invalid arguments passed to jsPDF.rect when colspan is present

### ISSUE THREAD

**Issue by Never7Dice** [simonbengtsson/jsPDF-AutoTable#670]
Exception is thrown when using this code:
```
          const paramCell: CellDef = {
            content: `${parameterFillout.parameterName}\n`,
            styles: { cellWidth: visualColumnWidth },
            colSpan: structureColumnsInOneVisual,
          };
```

If I change `cellWidth `to `minCellWidth` it works, it also works if I remove `colSpan `or `cellWidth`
Sounds like something from https://github.com/simonbengtsson/jsPDF-AutoTable/issues/569

Also minCellWidth doesn't seem to work when colSpan is higher than 1. The first column is having colspan: 2 (there is actually 8 columns layout, because I want to insert icon to the left of header while preserving centered text)
![image](https://user-images.githubusercontent.com/34353798/84526261-b1e0a800-ace5-11ea-8396-27f4feb4ff65.png)

**Comment by Never7Dice** [comment]
Update on original issue:

It happens when I have this header structure.
```
      const logHeader: CellDef[] = [
        {
          content: `${log.mask.name}\n${this.dateToLocalePipe.transform(log.createdate)}`,
          colSpan: structureColumnsCount,
          styles: { halign: 'center', fillColor: [22, 160, 133] },
        }];
```

And it doesn't happen when I have additional columns in the header:
```
      const logHeader: CellDef[] = [
        {
          content: ``,
          colSpan: 1,
          styles: { halign: 'center', fillColor: [22, 160, 133], cellWidth: visualColumnWidth / structureColumnsInOneVisual },
        },
        {
          content: `${log.mask.name}\n${this.dateToLocalePipe.transform(log.createdate)}`,
          colSpan: structureColumnsCount - 2,
          styles: { halign: 'center', fillColor: [22, 160, 133] },
        },
        {
          content: ``,
          colSpan: 1,
          styles: { halign: 'center', fillColor: [22, 160, 133], cellWidth: visualColumnWidth / structureColumnsInOneVisual },
        }];
```

**Comment by simonbengtsson** [comment]
Exception? For me it seems to work. Can you provide a runnable example?

**Comment by Never7Dice** [comment]
I didn't have time and possibility to create an isolated example, as the approach with additional columns was not working as I expected it work, so I abandoned it all together.
