### ISSUE TITLE
Why got Row.x, Row.y, and Table.width removed?

### ISSUE THREAD

**Issue by udvaritibor** [simonbengtsson/jsPDF-AutoTable#674]
I used them to do get **specific positions** on the row, like bottom-center position, bottom-right corner, bottom-left corner, etc.

```
const topLeft = new Point2D(innerData.row.x, innerData.row.y);
const bottomLeft = new Point2D(topLeft.x, topLeft.y + innerData.row.height);
const bottomRight = new Point2D(bottomLeft.x + innerData.table.width, bottomLeft.y);
```

Why were they removed? Should I find another way to calculate the mentioned positions, or there is a chance that it will be reverted?

Thanks!

**Comment by simonbengtsson** [comment]
Removed to reduce maintenance. You can use cell.x and cell.y instead together with table.getWidth() function.

**Comment by udvaritibor** [comment]
I see, thanks!
