### ISSUE TITLE
Why aren't Cell, Column, Row, Table, etc classes exported?

### ISSUE THREAD

**Issue by udvaritibor** [simonbengtsson/jsPDF-AutoTable#675]
I'm trying to make methods which calculate some attribute of a row, but I can't define the parameter's type as Row, because it isn't exported.
So I have to use any, which isn't a good thing.

Is there a reason behind it?

**Comment by simonbengtsson** [comment]
There is now reason for it. Feel free to submit a PR exporting them 👌

**Comment by udvaritibor** [comment]
I'm a bit out of time currently, but I will do it when I got some time.
