### ISSUE TITLE
New property: Row.cellCount?

### ISSUE THREAD

**Issue by udvaritibor** [simonbengtsson/jsPDF-AutoTable#676]
Currently I'm using this snippet on Row.cells to count the number of cells in the row:

```
private countCellsInRow(cellsObj: any): number
{
	let count = 0;
	for (let key in cellsObj)
	{
		if (cellsObj.hasOwnProperty(key))
		{
			count++;
		}
	}
	return count;
}
```

Shouldn't there be a built-in property for cellCount?

**Comment by simonbengtsson** [comment]
You can do this `Object.keys(row.cells).length`? Or maybe `data.columns.filter(c => row.cells[c.id]).length`

**Comment by udvaritibor** [comment]
Hmm, that's a good solution, thanks! I'm still a bit newbie in web development :)
