### ISSUE TITLE
doc.autoTable Doesn't work

### ISSUE THREAD

**Issue by donqq** [simonbengtsson/jsPDF-AutoTable#677]
any
Property 'autoTable' does not exist on type 'jsPDF'.
I have seen a couple of solutions to address this, but I want a proper solution not like declare var jsPDF: any; hack. Thanks.!

**Comment by simonbengtsson** [comment]
If you are using typescript you can take a look at the [typescript example](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/examples/typescript/index.ts)
