### ISSUE TITLE
[Question] Is there any way to render rich text?

### ISSUE THREAD

**Issue by Never7Dice** [simonbengtsson/jsPDF-AutoTable#679]
For example I have rich text like this:
![image](https://user-images.githubusercontent.com/34353798/85034423-c3fd9300-b18a-11ea-938a-ff8e4b186a84.png)

Is it possible to achieve something like this anyhow
![image](https://user-images.githubusercontent.com/34353798/85034614-f5765e80-b18a-11ea-9d37-8ed64aa41382.png)

Or at least render part of the text bold and part regular inside the same cell. If it is possible could you please provide a small example. The answers on these issues were not clear enough for me: https://github.com/simonbengtsson/jsPDF-AutoTable/issues/412 and https://github.com/simonbengtsson/jsPDF-AutoTable/issues/422

**Comment by simonbengtsson** [comment]
You can draw it yourself in the didDrawCell hook.

**Comment by Never7Dice** [comment]
Can you provide some example of didDrawCell drawing? At least which properties or objects I am supposed to use.

**Comment by Never7Dice** [comment]
I ended up with some hacky pre and post calculation using 
```
const textLines = doc.setFontStyle('bold')
                .splitTextToSize(parameterFillout.parameterName, data.cell.width - this.cellPadding * 2);
```

It doesn't work well, you have to make rows non-breakable, and somehow decide required height and width of cell beforehand.
I'm rather disappointed, even rendering bold title is full of duct-tape with dynamic table :(
