### ISSUE TITLE
Error: Invalid arguments passed to jsPDF.rect

### ISSUE THREAD

**Issue by manuelamaria** [simonbengtsson/jsPDF-AutoTable#680]
With **version 3.5.4**, we now get an error generating the report:

jspdf.min.js:1286 Uncaught (in promise) Error: Invalid arguments passed to jsPDF.rect
    at Object.l.__private__.rect.l.rect (jspdf.min.js:1286)
    at DocHandler.rect (jspdf.plugin.autotable.js:642)
    at printRow (jspdf.plugin.autotable.js:1415)
    at jspdf.plugin.autotable.js:1221
    at Array.forEach (<anonymous>)
    at Object.drawTable (jspdf.plugin.autotable.js:1220)
    at Object.jsPDF.API.autoTable (jspdf.plugin.autotable.js:2044)
    at _callee$ (assessmentReport.js:318)

I reverted to **version 3.5.3 and it works**.

The code causing this:

```
doc.autoTable({
    startY: textDimension,
    didDrawPage: cell => {
        heightStatus = cell.table.height;
    },
    headStyles: {
        fillColor: [255, 255, 255],
        textColor: [129, 129, 129]
    },
    alternateRowStyles: {
        fillColor: [255, 255, 255]
    },
    head: [['', '']],
    body: [
        [
            {
                content: 'Status:',
                styles: {
                    fontStyle: 'bold',
                    cellWidth: 40
                }
            },
            {
                styles: {
                    fontStyle: 'bold',
                    textColor: status ? [0, 155, 149] : [205, 4, 104]
                },
                content: status ? 'YES' : 'NO'
            }
        ]
    ]
});
```

We can revert to 3.5.3 for the time being, but I'm wondering if we're doing something wrong here.

Thank you!

**Comment by simonbengtsson** [comment]
Weird! When using your code I don't get any error and the pdf looks like this.

<img width="909" alt="Screen Shot 2020-06-19 at 08 41 49" src="https://user-images.githubusercontent.com/3586691/85104423-dc13f780-b208-11ea-8ccf-130833dc87f0.png">

**Comment by manuelamaria** [comment]
Thanks for checking!
I'll play around a bit with the code to see if I can get more info.

**Comment by manuelamaria** [comment]
Sorry for getting back to this so late. The error happens because that code that I pasted above is wrapped inside a Promise. So I have something like this:
```
var doc = new jsPDF();
...
const main = () => {
    return new Promise( r => {
        // some async stuff

        doc.autoTable({ ... });

        // resolve at some point
    })
}

await main();

... 
doc.save('docname.pdf');
```

If I execute the code in the main document flow, it works without error as you said. 

Thanks again for checking this. For the moment I'll stick to version 3.5.3
