### ISSUE TITLE
Custom font does not render properly in pdf

### ISSUE THREAD

**Issue by Shadowsusanoo** [simonbengtsson/jsPDF-AutoTable#681]
I am currently using jsPDF-AutoTable to convert a table containing multiple language texts (Hindi, Tamil, English ,etc. ) to pdf. 
I use the Sakal Bharati font (For Indian languages) , which contains all these languages script in one TTF file and convert it to base64 string to utilise it via custom font method.

The texts are rendered in the pdf, not properly . For example in the first image is how the hindi text should look like.The second image represents how its rendered in the generated pdf .

**How it should look**
![Ideal](https://user-images.githubusercontent.com/47937395/85105874-e0500d00-b228-11ea-998e-a5f891ac1447.jpg)

**Generated content**
![Actual](https://user-images.githubusercontent.com/47937395/85106004-142b3280-b229-11ea-87e1-8e3c763940d4.jpg)

As it can be seen these 2 are very different from each other .
If I convert this to a word/xml file using any online tool , the text gets rendered properly/correctly.
But my query is how to make it happen for the pdf file that is generated ?

Will appreciate a fast response.

**Comment by simonbengtsson** [comment]
It might be a jsPDF issue and not related to this plugin. Can you verify you get the same issue with using only doc.text()?

**Comment by Shadowsusanoo** [comment]
Yes the same issue persists without using the autotable plugin. Sorry for the inconvenience. I shall post this as a issue on jsPDF .

**Comment by simonbengtsson** [comment]
No worries!
