### ISSUE TITLE
footStyle lineWidth overlaps body border

### ISSUE THREAD

**Issue by songssam** [simonbengtsson/jsPDF-AutoTable#683]
Hi,

I tried to show no borders on footer but

it overlaps the bottom border of the body.

Is there a way that bottom border of the body draws?

```footStyles: {lineWidth: 0 or lineColor: '#FFFFFF'}``` hides the bottom of the line

**Comment by nseaSeb** [comment]
Hi, I guess you can hook the line width of the footer.
