### ISSUE TITLE
Change color of a row dynamically

### ISSUE THREAD

**Issue by BadApples11** [simonbengtsson/jsPDF-AutoTable#684]
Hello,
First of all, @simonbengtsson, thanks for this great "jsPDF-AutoTable",  

In a table, I search a text in cell and change cell color using :

`didParseCell: function (HookData) {
	if (HookData.cell == undefined) {return;}
        if (HookData.cell.text[0].indexOf('MY_TEXT_TO_FIND') > -1) {
	HookData.cell.styles.fillColor= [255, 193, 51];	
}`
It works.

Is it possible to change, directly, the entire row color ?

Thanks in advance.

**Comment by BadApples11** [comment]
Hello,
No one has an idea ?

**Comment by nseaSeb** [comment]
Maybe you can make something like this:

```
didParseCell: function (HookData) { if (HookData.cell == undefined) {return;} if (HookData.cell.text[0].indexOf('MY_TEXT_TO_FIND') > -1) { 
for ( const cell of HookData.row.cells) {
cell.styles.fillColor= [255, 193, 51]; }	}
```

**Comment by BadApples11** [comment]
hello, 
thanks for answering
I got this error on firefox :

![image](https://user-images.githubusercontent.com/67412256/86517745-9cb1f180-be2b-11ea-8e05-da1879365946.png)

**Comment by BadApples11** [comment]
Hello, 
I found a solution, 
inspired by this link 

[https://stackoverflow.com/questions/35720805/how-can-i-style-last-row-using-jspdf-autotable-plugin](url)
 
I'm searching row ("myROW ") of cell containing "MY_TEXT_TO_FIND"

 - before "doc.autoTable({"
 - I wrote this
`
		var myROW = 0;
		let drawCell = function(data) {
			doc = data.doc;
			var rows = data.table.body;
			if (rows.length === 1) {
			} else if (data.row.index === myROW) {
				doc.setFontStyle("bold");
				doc.setFontSize("7");
				doc.setFillColor(255, 193, 51);
				}
		};
`
 - then in "didParseCell: "
 - I wrote this :
`if (HookData.cell.text[0].indexOf('MY_TEXT_TO_FIND') > -1) { 
								myROW = HookData.row.index;}`

 - and at the end of  "doc.autoTable({"
 - I wrote this :
`
		willDrawCell: drawCell,`
("drawCell" : defined before "doc.autoTable")

PS : I was surprised that the color of all cells in the row ("myROW") was not changed if a color is not defined in "columnStyles: {"
for example, with the code below
`columnStyles: {
						0: {cellWidth: 9, minCellHeight: 3, valign:'middle', fillColor: 'silver'},
						1: {cellWidth: 9, valign:'middle'},
						2: {cellWidth: 10, valign:'middle', fillColor: 'white'},
                                                .....
`
only the colors of column "0" and "2" are changed, but not the color of cell "1" : it's stay white color
I have to define the color of each column and then the color of the entire row is changed.

Hope this may help others

Thanks for this great "jsPDF-AutoTable"

**Comment by BadApples11** [comment]
hello,

one more comment, the solution is good only if "myROW" value is greater than the number of row in Header and/or Footer.

For example, if "MY_TEXT_TO_FIND" is found in row 2 of your table, and if your Header and Footer have 2 rows, then the color of row 2 in Header and Footer will be also changed.

So, is there a way, to limit the function below, to body of table, and avoid changes in Header and Footer ?

`let drawCell = function(data) { doc = data.doc; var rows = data.table.body; if (rows.length === 1) { } else if (data.row.index === myROW) { doc.setFontStyle("bold"); doc.setFontSize("7"); doc.setFillColor(255, 193, 51); } };`

Thanks in advance.
