### ISSUE TITLE
Multi editable fields in jsPDF documents

### ISSUE THREAD

**Issue by BadApples11** [simonbengtsson/jsPDF-AutoTable#685]
Hello,

I'm using "TextField()" to allow to add comment in PDF.
But only one is available in the PDF file.
Here is a test code : 

`function TEST_FIELD(){
var doc = new jsPDF({orientation: 'l', unit: 'mm', format: 'a4', hotfixes: []} );

//textField1
doc.text(10, 65, 'TextField 1 :');
var textField1 = new TextField();
textField1.Rect = [50, 50, 120, 30];
textField1.multiline = false;
textField1.V = "TextField 1, TextField 1, TextField 1, TextField 1, ";
textField1.T = "TestTextBox";
doc.addField(textField1);

//textField2
doc.text(10, 105, 'TextField 2 :');
var textField2 = new TextField();
textField2.Rect = [50, 100, 120, 30];
textField2.multiline = false;
textField2.V = "TextField 2, TextField 2, TextField 2, TextField 2, ";
textField2.T = "TestTextBox";
doc.addField(textField2);

doc.save('Test.pdf');

}`

With this function, only "textField1" is active in pdf. 
When I delete all "textField1" code, "textField2" is active in pdf.
Is there a way to have both "textField1" and "textField2" (and many others) active in a pdf at the same time ?

Thanks in advance.

**Comment by simonbengtsson** [comment]
It seems this is not related to the autoTable plugin?

**Comment by BadApples11** [comment]
Sorry, no of course, my mistake
can you move it to the right place ?
