### ISSUE TITLE
[Bug?] Text in didDrawPage is not anti-aliased 

### ISSUE THREAD

**Issue by Nervniyak** [simonbengtsson/jsPDF-AutoTable#689]
I'm not entirely sure how to describe it, but the text I add in page footer using `didDrawPage `is drawn without or with different kind of anti-aliasing than all other texts inside or outside table. For comparison it's like if you select diferent type of a-a for font in Photoshop
![image](https://user-images.githubusercontent.com/34353798/86796188-0245ee00-c077-11ea-89c3-94d9b096e25a.png)

The footer font looks more sharp and fat, here's an example of this behavior:
In Chrome with different zoom level (click on images, otherwise it is hard to see)
![image](https://user-images.githubusercontent.com/34353798/86795799-9b283980-c076-11ea-8ad4-2d7eabfa49fb.png)
![image](https://user-images.githubusercontent.com/34353798/86795820-a1b6b100-c076-11ea-8c95-feebc376c3b5.png)
![image](https://user-images.githubusercontent.com/34353798/86795973-c743ba80-c076-11ea-83a9-1abfa64b70cc.png)
In Edge
![image](https://user-images.githubusercontent.com/34353798/86796106-e9d5d380-c076-11ea-9c66-fb33ddd9f049.png)

Both texts were printed using the same font set
```
          doc.setFontSize(10);
          doc.setTextColor(80);
          doc.setFont('helvetica');
          doc.setFontStyle('bold');
          doc.text('A or B single card', x, y);
```
The only text that have this issue is inside `didDrawPage` the text manually added inside `didDrawCell` or outside autotable looks fine.
I couldn't find anything about font anti-aliasing or sharpness in jsPdf, any ideas?

Additional example: the bottom one is from `didDrawPage`, the one above it is outside of autotable, and the one in the cell is inside `didDrawCell`

![image](https://user-images.githubusercontent.com/34353798/86797606-88aeff80-c078-11ea-8745-90607ad3e0db.png)

**Comment by Never7Dice** [comment]
I decided not to use `didDrawPage` and instead use basic approach for JsPdf
```
    const totalPages = doc.internal.getNumberOfPages();
    for (let j = 1; j < totalPages + 1; j++) {
      doc.setPage(j);

      doc.setFontSize(10);
      doc.setTextColor(80);
      doc.setFont('helvetica');
      doc.setFontStyle('bold');
      if (logoBase64) {
        const ratio = logoImage.width / logoImage.height;
        const height = 10;
        const width = height * ratio;
        doc.addImage(logoBase64, 'JPEG',
          this.sideTableMargin, this.pageHeight - this.sideTableMargin * 1.5,
          width, height);
      }

      const str = j + ' of ' + totalPages;
      const horizontalPos = this.pageWidth / 2;
      doc.text(str, horizontalPos, this.pageHeight - 5, { align: 'center' });
    }


    doc.save(`${reportInformation.title}.pdf`);
```

And this way there is no issue with anti-aliasing
![image](https://user-images.githubusercontent.com/34353798/86941635-d4cb7400-c14c-11ea-9179-88bfd348ef61.png)
