### ISSUE TITLE
Split column across pages if not enough space

### ISSUE THREAD

**Issue by VKB2612** [simonbengtsson/jsPDF-AutoTable#690]
I want to print remaining columns on a new page if it is not enough horizontal space to show it on one page.

**Comment by simonbengtsson** [comment]
If you remove tableWidth: wrap it will shrink the table width to fit the page. I assume you would like to have something like this though? 

![frame](https://user-images.githubusercontent.com/3586691/87555250-7dca1f80-c6b5-11ea-929a-637e7bc373d5.png)


I thought we already had a feature request for this since it is one of the most requested features. Couldn't find it now though so maybe you can edit this ticket to be a feature request instead?

**Comment by VKB2612** [comment]
Hi @simonbengtsson 

This is exactly what is needed. I edit the ticket now.
Thanks.

**Comment by simonbengtsson** [comment]
Great 👌 Simplified the issue a bit now.

**Comment by DDorrance90** [comment]
Watching this issue, I have the same preferences.

**Comment by VKB2612** [comment]
Hi @simonbengtsson ,  
Is there any update on this?

Thanks and regards

**Comment by simonbengtsson** [comment]
As far as I know no one is working on it.

**Comment by VKB2612** [comment]
Hi @simonbengtsson 

This requirement/feature is quite important for release as wrapping cell content is not a feasible option (lengthy numeric values are not easily readable when wrapped). It would be really helpful if this task can be prioritized.
Thanks in advance.

Regards

**Comment by simonbengtsson** [comment]
Agreed, seems like many people are looking for this feature. I have no bandwidth to look into it in the foreseeable future. I'll be happy to review a merge request asap if you make one however.

**Comment by VKB2612** [comment]
Hi @simonbengtsson ,

if I have understood you correctly, you want me to make the proposed/requested changes and make a merge request?
Regards

**Comment by simonbengtsson** [comment]
That would be great!

**Comment by VKB2612** [comment]
Hi @simonbengtsson 

Unfortunately this would not be possible from my end in the moment. 
Can you please suggest any other alternate solution?

Thanks and Regards

**Comment by simonbengtsson** [comment]
Except for increasing page size or making font size smaller I don't know of a alternative solution.

**Comment by Sindhuja1295** [comment]
Hi i have 139 columns using jspdf-autotable, how to adjust or split column or is there any alternate solution?

**Comment by simonbengtsson** [comment]
I thought some about it now and I guess you could select a huge page such as A0 in landscape. Then split it with a tool such as this https://deftpdf.com/split-pdf-down-the-middle. Maybe you can even find a way to split a page with jspdf.

**Comment by prpateldev** [comment]
I can help, I will start working on it

**Comment by simonbengtsson** [comment]
Sounds great!

**Comment by Sindhuja1295** [comment]
Hi, 
My requirement is to support 100 columns in jspdf-autotable plugin? is it possible?

**Comment by simonbengtsson** [comment]
If you specify a large document or small text sure 👌

**Comment by prpateldev** [comment]
> Hi,
> My requirement is to support 100 columns in jspdf-autotable plugin? is it possible?

yes but need to modify the plugin code

**Comment by simonbengtsson** [comment]
You can set small font size with the plugin api and set large page size with jspdf

**Comment by Sindhuja1295** [comment]
Can i have the sample please? Where i have to change the font sze in plugin and page size?

**Comment by Sindhuja1295** [comment]
Hi,

I have set small font size and large page size in jspdf,
my version jspdf-plugin-autotable- v3.5.6

 I have 139 columns,

but i am facing the below error, kindly assist to overcome from this issue.

![image](https://user-images.githubusercontent.com/54404515/93345025-fd0fd700-f84f-11ea-939c-725d5365273e.png)

**Comment by VKB2612** [comment]
> I can help, I will start working on it

Hi @prpateldev 
Thanks. Appreciate the help.

**Comment by Sindhuja1295** [comment]
Hi, 

I have 139 columns in the pdf report, as u have guided i have adjusted the font size and page size.
Kindly find the below image,
![image](https://user-images.githubusercontent.com/54404515/93845119-4aab9a00-fcbd-11ea-9fd9-3d558732f6ba.png)

**Comment by prpateldev** [comment]
Hello @simonbengtsson hope you are doing well. 

I have implemented initial logic to split columns across pages, please create a new branch for it so I will make a pull request as it's in still development and may need more cases to handle, I don't want to make pull request for master.

Thanks

**Comment by jcla490** [comment]
Pls @simonbengtsson merge this

**Comment by nasim-alizai-pgl** [comment]
@prpateldev  how we should use it ? please

**Comment by nsdotorg** [comment]
Do we have an example on how to use the split columns?

**Comment by mmghv** [comment]
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/4c04f6a089b9dea919e84fee5fff649552cd49b8/examples/examples.js#L654-L662
