### ISSUE TITLE
Use of deprecated autoTable initiation-JSPDF AutoTable plugin

### ISSUE THREAD

**Issue by Sindhuja1295** [simonbengtsson/jsPDF-AutoTable#696]
While i am initiating the jspdf v3.5.6, below error occurs,

Use of deprecated autoTable initiation

**Comment by anvictorsantos** [comment]
The same is occurring with me:

![image](https://user-images.githubusercontent.com/19178547/88987988-fd5b0f80-d2ad-11ea-9783-d5a9e017cfaa.png)

**Comment by bnupy** [comment]
Where is the Documentation and solution for this issue ? I haven't located a  stackoverflow solution for this

**Comment by vzakharov-rxnt** [comment]
Try this:
```
import autoTable from 'jspdf-autotable'
autoTable(doc,{
                head: [columns],
                body: rows,
```
Also rename other props if suggested by similar console errors.
