### ISSUE TITLE
The jsPDF-AutoTable plugin is incompatible with the latest jsPDF 2.0.0

### ISSUE THREAD

**Issue by KuznetsovVN** [simonbengtsson/jsPDF-AutoTable#702]
Hello,

The [jsPDF 2.0.0](https://github.com/MrRio/jsPDF/releases/tag/v2.0.0) is released and i test it together with the autoTable plugin. I found an exception in the autoTable plugin code.
[Sample](https://codepen.io/kuznetsovvn/project/editor/DQzONx)

**Comment by Timebutt** [comment]
Feels like there are more issues than just this when I'm using `jsPDF-AutoTable` with the newly release `jsPDF` version `2.0.0`. Maybe we should rephrase this issue into something more general to make `jsPDF-AutoTable` compatible with the latest version?

**Comment by simonbengtsson** [comment]
v3.5.9 now supports jspdf 2.0
