### ISSUE TITLE
not compatible with jsPDF 2.0

### ISSUE THREAD

**Issue by wilson3q** [simonbengtsson/jsPDF-AutoTable#703]
Jspdf-Autotable breaks after upgrading to latest jsPDF 2.0 update, errors like:

no such function:
setFontStyle()
autoTable()

Please help to upgrade the API to make it compatible with jsPDF 2.0. Thanks.

**Comment by simonbengtsson** [comment]
v3.5.9 now supports jspdf 2.0

**Comment by wilson3q** [comment]
great! thanks
