### ISSUE TITLE
Your Codepen does not work due to security exceptions in Firefox

### ISSUE THREAD

**Issue by AntonTrapp** [simonbengtsson/jsPDF-AutoTable#71]
Would be great as other browsers like Google Chrome don't support PDFs and it takes ages to download/view/delete the PDF after every change.

Message is:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf blob:http://s.codepen.io/c0998d36-85ff-e24d-8784-bf5d76017475 blockiert ("frame-src http://codepen.io http://* https://* safari-extension://*").

**Comment by simonbengtsson** [comment]
Hmm, you are right. The examples doesn't work in firefox. Will take a look at it now.

**Comment by simonbengtsson** [comment]
The examples actually did work in firefox. I was confused since the pdf's were downloaded and not embedded on the page as before. It doesn't seem to be a way to embed pdf's on page from now on with firefox?

**Comment by AntonTrapp** [comment]
No idea what Mozilla changed the last months (except that the ignore the URL for new tabs which made it necessary to install another plugin), sorry. Can't help you here :(

**Comment by simonbengtsson** [comment]
Will close this for now. Improving the examples page to work better in browsers that doesn't embed pdfs are on the todo list, but there is no timeplan for it now.
