### ISSUE TITLE
Not compatible with jspdf 2 in node.js

### ISSUE THREAD

**Issue by tapz** [simonbengtsson/jsPDF-AutoTable#714]
After updating fomr jspdf 1.5.3 to 2.0.0, I had to change this 
`const jsPDF = require('jspdf/dist/jspdf.node.debug');`
to this
`const jsPDF = require('jspdf/dist/jspdf.node');`

After that I'm doing what used to work...

```
const { applyPlugin } = require('./node_modules/jspdf-autotable/dist/jspdf.plugin.autotable');

applyPlugin(jsPDF);

```
But now I'm getting the following error:
```
/node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js:1516
    jsPDF.API.autoTable = function () {
                        ^

TypeError: Cannot set property 'autoTable' of undefined
    at Object.default_1 [as default] (/node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js:1516:25)
    at applyPlugin (/node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js:1466:26)
```

Versions:
```
"jspdf": "2.1.0",
"jspdf-autotable": "3.5.9",
```

Works fine with jspdf 1.5.3.

**Comment by simonbengtsson** [comment]
Can you check what you are doing different to the nodejs example?

**Comment by tapz** [comment]
@simonbengtsson I don't see anything different between my code and the nodejs example.
