### ISSUE TITLE
Remove the usage of setFontStyle for compatibility with jspdf v2

### ISSUE THREAD

**Issue by Lightras** [simonbengtsson/jsPDF-AutoTable#715]
Now after upgrading to jspdf v2 I get the error "this.jsPDFDocument.setFontStyle is not a function". This is because the function was removed in jspdf v2.0.0 according to their release notes:

> Removed APIs that were previously marked as deprecated. Namely: addHTML, fromHTML, html2pdf, addSvg, addButton, addTextField, addChoiceField, cellInitialize, **setFontStyle, setFontType**, clip_fixed

**Comment by simonbengtsson** [comment]
There should be no usage of setFontStyle in the latest version of the plugin. Can you verify you are not using it in the hooks? If you are not, can you post example code of when it fails?

**Comment by simonbengtsson** [comment]
Fixed in 3.5.12
