### ISSUE TITLE
How to set font size and position in specific text

### ISSUE THREAD

**Issue by kmsharjas** [simonbengtsson/jsPDF-AutoTable#717]
I want to set  font size and position in a specific text.how can i do that?

`doc.text(
      40,
      30,
      "jspdf"
              );`

**Comment by JoakFlores** [comment]
To set font size
doc.setFontSize(2);

**Comment by kmsharjas** [comment]
@JoakFlores Thanks for your suggestion ,But this is not what I want.Below is the sample I need

![image](https://user-images.githubusercontent.com/15127210/92582295-66bb3e80-f2ae-11ea-81ef-11261066d606.png)
