### ISSUE TITLE
To print into ZEBRA iMZ320

### ISSUE THREAD

**Issue by JoakFlores** [simonbengtsson/jsPDF-AutoTable#718]
Hi

I have to print on mobile printer a PDF file, I have only 3-inch width to print, how can I change the autotable dimensions?

![error1](https://user-images.githubusercontent.com/6606922/92534006-572dee00-f1f9-11ea-8d58-6deea8175d8b.jpg)

**Comment by simonbengtsson** [comment]
Have you looked at font size on the docs?

**Comment by JoakFlores** [comment]
Hi Simon.

First, I show to the "user" one view with the table on normal "size", then, if the "user" wants to print, click on button and send the data to print.

I get it the same "view" to build the PDF file.

Have I to build another table to the PDF file?


![error2](https://user-images.githubusercontent.com/6606922/92606444-8cc5ec00-f278-11ea-8a55-6160c6daa871.jpg)


`  <table>
        <thead class="col-encabezados-tabla">
          <tr>
            <th class="label-cell col-titulo-tabla">Nombre Jugador</th>
            <th class="numeric-cell">Gol</th>
            <th class="numeric-cell">Tarjeta Amarilla</th>
            <th class="numeric-cell">Tarjeta Roja</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td class="label-cell">Joaquín Flores</td>
            <td class="numeric-cell">1</td>
            <td class="numeric-cell">&nbsp</td>
            <td class="numeric-cell">&nbsp</td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <td class="label-cell">Adán García</td>
            <td class="numeric-cell">&nbsp</td>
            <td class="numeric-cell">1</td>
            <td class="numeric-cell">&nbsp</td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <td class="label-cell">TOTALES</td>
            <td class="numeric-cell">1</td>
            <td class="numeric-cell">0</td>
            <td class="numeric-cell">0</td>
          </tr>
        </tbody>
      </table>`

**Comment by JoakFlores** [comment]
Hi Simon .... I can! 

But now, how can I calculate the height document? each PDF won't have always the same number rows on the table

![error3](https://user-images.githubusercontent.com/6606922/92637238-3075c300-f29e-11ea-8171-4584c8c672ba.jpg)
