### ISSUE TITLE
Add header footer with multiple pages with image 

### ISSUE THREAD

**Issue by BhavikThakkar** [simonbengtsson/jsPDF-AutoTable#719]
we are using JSPdf for export to pdf 

- First i am using html to canvas to take data and convert it into image 

- now image is long which can not fit in single pdf page

- I need to place header , footer and page number on each page of pdf .

below logic generates pdf but 2 issues are there

1)  Header is not showing in each page 
2)  Footer overwrite with data 

    const pdf = new jspdf(); // A4 size page of PDF
    const pName = JSON.parse(window.localStorage.getItem('programName'));
    const projectName = JSON.parse(window.localStorage.getItem('projectName'));
    const pNo = JSON.parse(window.localStorage.getItem('programNumber'));
    const projectNo = JSON.parse(window.localStorage.getItem('projectNumber'));
    const currentdate = new Date();
    const datetime = (currentdate.getMonth() + 1) + '/' + currentdate.getDate() + '/' + currentdate.getFullYear()
    const runDate = 'Run Date: ' + moment(datetime).format('MM/DD/YYYY');
    const data = document.getElementById('docreview');
    const margin = 3;

    html2canvas(data).then(canvas => {
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(8);
      if (pNo || pName || projectNo || projectName) {
        pdf.text(10, 6, 'Program :' + pNo + ' / ' + pName);
        pdf.text(10, 10, 'Project :' + projectNo + ' / ' + projectName);
      }
      pdf.text(10, 14, 'CR-CO Log Info');
      pdf.setFontSize(7);
      pdf.text(175, 6, runDate);
      // pdf.text(175, 10, 'Page : ' + (i + 1));
      // Few necessary setting options
      const imgWidth = 208 - 2 * margin;
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth / canvas.width);
      let heightLeft = imgHeight;
      const contentDataURL = canvas.toDataURL('image/png');
      let position = 18;
      pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
      pdf.setFontSize(8);
      pdf.text(85, 295, 'IFM360 Program Management Module');
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
        pdf.setTextColor(0, 0, 0);
        pdf.setFontSize(8);
        pdf.text(80, 295, 'IFM360 Program Management Module');
        pdf.addPage();
      }
      pdf.save('Cr_CoLog.pdf');
    });

please assist how i can fix this ?

**Comment by BhavikThakkar** [comment]
> we are using JSPdf for export to pdf
> 
> * First i am using html to canvas to take data and convert it into image
> * now image is long which can not fit in single pdf page
> * I need to place header , footer and page number on each page of pdf .
> 
> below logic generates pdf but 2 issues are there
> 
> 1. Header is not showing in each page
> 2. Footer overwrite with data
>    const pdf = new jspdf(); // A4 size page of PDF
>    const pName = JSON.parse(window.localStorage.getItem('programName'));
>    const projectName = JSON.parse(window.localStorage.getItem('projectName'));
>    const pNo = JSON.parse(window.localStorage.getItem('programNumber'));
>    const projectNo = JSON.parse(window.localStorage.getItem('projectNumber'));
>    const currentdate = new Date();
>    const datetime = (currentdate.getMonth() + 1) + '/' + currentdate.getDate() + '/' + currentdate.getFullYear()
>    const runDate = 'Run Date: ' + moment(datetime).format('MM/DD/YYYY');
>    const data = document.getElementById('docreview');
>    const margin = 3;
>    html2canvas(data).then(canvas => {
>    pdf.setTextColor(0, 0, 0);
>    pdf.setFontSize(8);
>    if (pNo || pName || projectNo || projectName) {
>    pdf.text(10, 6, 'Program :' + pNo + ' / ' + pName);
>    pdf.text(10, 10, 'Project :' + projectNo + ' / ' + projectName);
>    }
>    pdf.text(10, 14, 'CR-CO Log Info');
>    pdf.setFontSize(7);
>    pdf.text(175, 6, runDate);
>    // pdf.text(175, 10, 'Page : ' + (i + 1));
>    // Few necessary setting options
>    const imgWidth = 208 - 2 * margin;
>    const pageHeight = 295;
>    const imgHeight = (canvas.height * imgWidth / canvas.width);
>    let heightLeft = imgHeight;
>    const contentDataURL = canvas.toDataURL('image/png');
>    let position = 18;
>    pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
>    heightLeft -= pageHeight;
>    pdf.setFontSize(8);
>    pdf.text(85, 295, 'IFM360 Program Management Module');
>    while (heightLeft >= 0) {
>    position = heightLeft - imgHeight;
>    pdf.addPage();
>    pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
>    heightLeft -= pageHeight;
>    pdf.setTextColor(0, 0, 0);
>    pdf.setFontSize(8);
>    pdf.text(80, 295, 'IFM360 Program Management Module');
>    pdf.addPage();
>    }
>    pdf.save('Cr_CoLog.pdf');
>    });
> 
> please assist how i can fix this ?


![doc review rpt page break (2)](https://user-images.githubusercontent.com/9841783/92918140-c7807d80-f44c-11ea-85b0-3ba67227e243.JPG)

**Comment by sandeepseagu** [comment]
Hello Bhavik Thakkar,

Were you able to find the solution for this problem?. I am having the same issue of adding header to each page. JsPdf and html2canvas.

Thank you,
Sandeep

**Comment by sandeepseagu** [comment]
> > we are using JSPdf for export to pdf
> > 
> > * First i am using html to canvas to take data and convert it into image
> > * now image is long which can not fit in single pdf page
> > * I need to place header , footer and page number on each page of pdf .
> > 
> > below logic generates pdf but 2 issues are there
> > 
> > 1. Header is not showing in each page
> > 2. Footer overwrite with data
> >    const pdf = new jspdf(); // A4 size page of PDF
> >    const pName = JSON.parse(window.localStorage.getItem('programName'));
> >    const projectName = JSON.parse(window.localStorage.getItem('projectName'));
> >    const pNo = JSON.parse(window.localStorage.getItem('programNumber'));
> >    const projectNo = JSON.parse(window.localStorage.getItem('projectNumber'));
> >    const currentdate = new Date();
> >    const datetime = (currentdate.getMonth() + 1) + '/' + currentdate.getDate() + '/' + currentdate.getFullYear()
> >    const runDate = 'Run Date: ' + moment(datetime).format('MM/DD/YYYY');
> >    const data = document.getElementById('docreview');
> >    const margin = 3;
> >    html2canvas(data).then(canvas => {
> >    pdf.setTextColor(0, 0, 0);
> >    pdf.setFontSize(8);
> >    if (pNo || pName || projectNo || projectName) {
> >    pdf.text(10, 6, 'Program :' + pNo + ' / ' + pName);
> >    pdf.text(10, 10, 'Project :' + projectNo + ' / ' + projectName);
> >    }
> >    pdf.text(10, 14, 'CR-CO Log Info');
> >    pdf.setFontSize(7);
> >    pdf.text(175, 6, runDate);
> >    // pdf.text(175, 10, 'Page : ' + (i + 1));
> >    // Few necessary setting options
> >    const imgWidth = 208 - 2 * margin;
> >    const pageHeight = 295;
> >    const imgHeight = (canvas.height * imgWidth / canvas.width);
> >    let heightLeft = imgHeight;
> >    const contentDataURL = canvas.toDataURL('image/png');
> >    let position = 18;
> >    pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
> >    heightLeft -= pageHeight;
> >    pdf.setFontSize(8);
> >    pdf.text(85, 295, 'IFM360 Program Management Module');
> >    while (heightLeft >= 0) {
> >    position = heightLeft - imgHeight;
> >    pdf.addPage();
> >    pdf.addImage(contentDataURL, 'PNG', margin, position, imgWidth, imgHeight);
> >    heightLeft -= pageHeight;
> >    pdf.setTextColor(0, 0, 0);
> >    pdf.setFontSize(8);
> >    pdf.text(80, 295, 'IFM360 Program Management Module');
> >    pdf.addPage();
> >    }
> >    pdf.save('Cr_CoLog.pdf');
> >    });
> > 
> > please assist how i can fix this ?
> 
> ![doc review rpt page break (2)](https://user-images.githubusercontent.com/9841783/92918140-c7807d80-f44c-11ea-85b0-3ba67227e243.JPG)
Hello Bhavik Thakkar,

Were you able to find the solution for this problem?. I am having the same issue of adding header to each page. JsPdf and html2canvas.

Thank you,
Sandeep
