### ISSUE TITLE
Calculated table cell is only about 1/3 of the size of the cell

### ISSUE THREAD

**Issue by AntonTrapp** [simonbengtsson/jsPDF-AutoTable#72]
Would be a really great tool, if the cell size would be calculated correct. At about 1/3 of the space available I get "..." instead of the text (that would easily fit in the cell).

http://plnkr.co/edit/xJE8zpU47lBcPqwOF4Ei?p=preview

When I could live with 2/3 space wasted and try to enable overflow: "linebreak" it is getting worse, it get's just an error.

The actual source is at the end of the script.js - just converted them from CoffeeScript. Just a small document, some columns and 1 table with 1 row with some text in one column.

Apart from that it's very easy to use, processing fast, ... - would love it!

**Comment by simonbengtsson** [comment]
Unfortunaletly the plugin doesn't support `mm` yet, only `pt`. If you change that it should work!

**Comment by AntonTrapp** [comment]
Correct file: http://plnkr.co/edit/zIpyU2?p=preview - changed from "mm" to "pt" -> Working!

Maybe a big line in the readme would be a great idea?

Thank you very much!

**Comment by AntonTrapp** [comment]
Btw.: would offer you a paypal beer for the help, saved me a lot of hours, I'm sure :)

**Comment by simonbengtsson** [comment]
Clarified that in the readme now! And thanks! I needed this for a project as well however so I got properly paid for it already.
