### ISSUE TITLE
HookData and CellHookData types are not exported

### ISSUE THREAD

**Issue by Nervniyak** [simonbengtsson/jsPDF-AutoTable#720]
I wanted to type my data input in function as `CellHookData`, but could not import the type, because it is not exported unlike for example `MarginPadding` and `ContentInput`

```
declare class HookData {
	table: Table;
	pageNumber: number;
	pageCount: number;
	settings: Settings;
	doc: jsPDFDocument;
	cursor: Pos | null;
	constructor(doc: DocHandler, table: Table, cursor: Pos | null);
}
declare class CellHookData extends HookData {
	cell: Cell;
	row: Row;
	column: Column;
	section: "head" | "body" | "foot";
	constructor(doc: DocHandler, table: Table, cell: Cell, row: Row, column: Column, cursor: Pos | null);
}
export declare type MarginPadding = {
	top: number;
	right: number;
	bottom: number;
	left: number;
};
export interface ContentInput {
	body: RowInput[];
	head: RowInput[];
	foot: RowInput[];
	columns: ColumnInput[];
}
```

![image](https://user-images.githubusercontent.com/34353798/93271637-70680900-f7bc-11ea-8d7e-f5c5b704f26e.png)

Is there any reason for it to be not exported? I have to use `any` not sure if there's workaround.

**Comment by simonbengtsson** [comment]
Nope, it should probably be experted. Ill accept a PR right away if publisher 👌

**Comment by Never7Dice** [comment]
https://github.com/simonbengtsson/jsPDF-AutoTable/pull/721

**Comment by maxfriedmann** [comment]
Hey @Nervniyak, did this ever get merged and released?

@vbinithyanandamv your PR is missing `HookData`, is that intended?
