### ISSUE TITLE
set halign right is not working properly ! Help Needed Urgently

### ISSUE THREAD

**Issue by akashcs88** [simonbengtsson/jsPDF-AutoTable#722]
Hi, i am working on a project in Codeigniter . There is need to export pdf report of data generated dynamically by Ajax Json . 
I used jsPDF Autotable plugin. When i use halign right to shift cell columns right, it hides / overflow contents. I tried much but couldn't not resolve. 
I am attaching screenshot for your review . Please help !
![Screenshot (297)](https://user-images.githubusercontent.com/71430523/93439139-ce473e80-f8eb-11ea-8385-d02962af3188.png)
![Screenshot (301)](https://user-images.githubusercontent.com/71430523/93439156-d56e4c80-f8eb-11ea-88e9-7bf69bb97022.png)
![Screenshot (300)](https://user-images.githubusercontent.com/71430523/93439187-e0c17800-f8eb-11ea-8973-886ee1f33484.png)

**Comment by simonbengtsson** [comment]
I checked the examples now and the halign works their. If I were you I would try to find the difference to your usage and the examples.
