### ISSUE TITLE
Override addPage

### ISSUE THREAD

**Issue by yenshin** [simonbengtsson/jsPDF-AutoTable#724]
I wan't autotable to use a specific orientation for it's generation.

For example I'm working on pdf in portrait, and for some table I would like autotable to add page and table using landscape orientation.

Is it possible? Maybe if i can override "addPage(format, orientation)"

Thanks for any suggestion or hack :)

**Comment by khocef** [comment]
```javascript
        const doc = new jsPDF('p'); // Portrait

        doc.setFontSize(18);
        doc.text('My PDF Table', 11, 8);
        doc.setFontSize(11);
        doc.setTextColor(100);

        doc.addPage('', "l"); // switch to landscape

        (doc as any).autoTable({
          head,
          body: data,
          theme: 'striped',
        });

        doc.addPage('', "p"); // And back to Portrait 
        doc.text("Do you like that?", 20, 20);
```

**Comment by yenshin** [comment]
Just tested, it works, for multiple page tab.
Thanks a lot for this answer !
