### ISSUE TITLE
lastAutoTable property in TypeScript

### ISSUE THREAD

**Issue by tomimelo** [simonbengtsson/jsPDF-AutoTable#728]
I cant manage to get working the lastAutoTable property in typescript. I'm using the autotable exported method as it says in the docs (` import autoTable from 'jspdf-autotable';` ) and creating my table with `autoTable(doc, options);`
I need to get the final Y of the last autotable for multiple tables.
With `doc.lastAutoTable.finalY` it says that lastAutoTable property does not exist on type jsPDF.

**Comment by simonbengtsson** [comment]
You'd have to mark doc as any to use lastAutoTable in typescript `(doc as any).lastAutoTable`. Let me know if you get any ideas of how this can be improved in the plugin 👌

**Comment by tomimelo** [comment]
I already tried that but I get an error.

```
ERROR Error: Invalid arguments passed to jsPDF.rect
    at Object.L.__private__.rect.L.rect (jspdf.es.min.js:67)
    at DocHandler.rect (jspdf.plugin.autotable.js:394)
    at printRow (jspdf.plugin.autotable.js:1022)
    at jspdf.plugin.autotable.js:870
    at Array.forEach (<anonymous>)
    at Object.drawTable (jspdf.plugin.autotable.js:870)
    at autoTable (jspdf.plugin.autotable.js:1476)
    at CommandComponent.generatePDF (command.component.ts:48)
    at SafeSubscriber._next (command.component.ts:36)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
```

I'm trying to generate the pdf with multi tables like the following:

```
generatePDF() {
    let doc = new jsPDF();

    for (let i = 0; i < this.tables.length; i++) {
      autoTable(doc, {
        head: [this.tables[i].head],
        body: this.tables[i].body,
        foot: [this.tables[i].foot],
        startY: (doc as any).lastAutoTable.finalY + 10,
        pageBreak: 'avoid',
      });
    }

    window.open(URL.createObjectURL(doc.output("blob")));
  }
```

If I hardcoded the startY with a value I get no errors and the pdf get generated correctly.

**Comment by Charlie91** [comment]
up to this issue.
have this problem too.

**Comment by LucBrungard** [comment]
@Charlie91 Can you describe your problem or show code please ? I managed to use it in with TypeScript thanks to this post and this one : https://stackoverflow.com/questions/63565808/how-to-get-the-finaly-of-lastautotable-in-jspdf-autotable

**Comment by JacobAguilar** [comment]
It worked

`let posY = (doc as any).lastAutoTable.finalY;`

**Comment by PTJohn0122** [comment]
Same issue here. I tried 
```
let PDF = new jsPDF("p", "pt", "a4");
autoTable(PDF, {<some userOptions>}); 
let posY = (PDF as any).lastAutoTable.finalY;
```
and got error message 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading finalY)
```

**Comment by titoadeoye** [comment]
> I already tried that but I get an error.
> 
> ```
> ERROR Error: Invalid arguments passed to jsPDF.rect
>     at Object.L.__private__.rect.L.rect (jspdf.es.min.js:67)
>     at DocHandler.rect (jspdf.plugin.autotable.js:394)
>     at printRow (jspdf.plugin.autotable.js:1022)
>     at jspdf.plugin.autotable.js:870
>     at Array.forEach (<anonymous>)
>     at Object.drawTable (jspdf.plugin.autotable.js:870)
>     at autoTable (jspdf.plugin.autotable.js:1476)
>     at CommandComponent.generatePDF (command.component.ts:48)
>     at SafeSubscriber._next (command.component.ts:36)
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
> ```
> 
> I'm trying to generate the pdf with multi tables like the following:
> 
> ```
> generatePDF() {
>     let doc = new jsPDF();
> 
>     for (let i = 0; i < this.tables.length; i++) {
>       autoTable(doc, {
>         head: [this.tables[i].head],
>         body: this.tables[i].body,
>         foot: [this.tables[i].foot],
>         startY: (doc as any).lastAutoTable.finalY + 10,
>         pageBreak: 'avoid',
>       });
>     }
> 
>     window.open(URL.createObjectURL(doc.output("blob")));
>   }
> ```
> 
> If I hardcoded the startY with a value I get no errors and the pdf get generated correctly.

4 years later but were you able to find a solution?😅 I have the exact same issue now where i am using typescript and also iterating over objects to create tables but startY returns undefined. My dataset is very large and i might cry if i have to manually create them.  Could there may be be an id or a key one can add to every autotable created to be used as a reference point to find the finalY on the document?
