### ISSUE TITLE
ellipses calculation

### ISSUE THREAD

**Issue by AntonTrapp** [simonbengtsson/jsPDF-AutoTable#73]
I think it is not a very good idea to "cut" a text like "10" to "1..." which makes the text longer ;)

**Comment by simonbengtsson** [comment]
Haha no, that is a bug. Could you reproduce it in a codepen är similar?

**Comment by AntonTrapp** [comment]
Correct file: http://plnkr.co/edit/zIpyU2?p=preview - changed from "mm" to "pt" -> Working!

Thank you very much!
