### ISSUE TITLE
Linebreak not working correctly for rows with different fontsize

### ISSUE THREAD

**Issue by AntoniosFesenmeier** [simonbengtsson/jsPDF-AutoTable#733]
Hi, 

i'am currently using version 3.4.3 of autotable for my project and facing a problem regarding the linebreak functionallity.
As you can see in the screenshot the style defines a fontsize of 10 for the table. In the willDrawCell hook i set the fontsize for the first row to 10 which breaks the linebreak functionallity. if fontsize is the same for all the rows, everything is working as expected.

![comparison_bug](https://user-images.githubusercontent.com/22680585/95547790-07af2d80-0a04-11eb-88ff-014dc5f280af.PNG)

**Comment by simonbengtsson** [comment]
willDrawCell is called after all calculations are done. Try didParseCell instead.

**Comment by AntoniosFesenmeier** [comment]
I have also tried the other hooks, but nothing worked for me. So what is the correct way to do stuff like that?

**Comment by simonbengtsson** [comment]
Take a look at the custom styles example for how to customize styles for specific cells or rows etc
