### ISSUE TITLE
Getting Error "Of the table content, ... could not fit page"

### ISSUE THREAD

**Issue by weilies** [simonbengtsson/jsPDF-AutoTable#734]
I couldn't figure out what's went wrong. I am able to print out the PDF report without error. 
But i got error in console 
"Of the table content, 92 units width could not fit page"
every time i output using autotable.

Here is my code in Stackblitz, method "**autoTable2()**"
https://stackblitz.com/edit/jspdf-faker-adn4?file=src/app/app.component.ts

**Comment by simonbengtsson** [comment]
The error is about that the entire table could not fit into the available page width. If the table looks good to you anyway it can be ignored but if you want the error to go away you would have to reduce the width of the the columns to fit the page width.

**Comment by tapz** [comment]
I have tried to reduce the column widths and that does not help. Older version did not give this warning, but at some point all columns started to give this. Would like to at least have an option to silence the warnings. Now getting hundrets of warnings to the console when the tables looks just fine.

**Comment by tapz** [comment]
I'm still seeing this every time with tons one rows. I have asked this several times before: would it be possible to add a flag to hide the warning? It would make my life a whole lot easier.

**Comment by tapz** [comment]
I now silenced the error in my code. Not a very elegant solution, but the best I could do.

`console.error = () => {};`

**Comment by hjrobinson** [comment]
Yeah, this irks me too. Thanks for the suggestion. To clarify for people who've never used console.error before (like me) put it before doc.autoTable() in your code.

**Comment by hjrobinson** [comment]
I did want to note here that if you don't need actual cell widths you can just set the width of the table with tableWidth and the errors won't show in the console.

**Comment by CynthiaBlue** [comment]
I am getting the same error message... 
"Of the table content, 200 units width could not fit page"

I am using Quasar/Electron for my development environment.  I'm following the simple example.  

```

      var doc = new jsPDF()
      // From Javascript
      var finalY = doc.lastAutoTable.finalY || 10

      doc.text('From javascript arrays', 14, finalY + 15)

      doc.autoTable({
        startY: finalY + 20,
        head: [['ID', 'Name', 'Email', 'Country', 'IP-address']],
        body: [
          ['1', 'Donna', 'dmoore0@furl.net', 'China', '211.56.242.221'],
          ['2', 'Janice', 'jhenry1@theatlantic.com', 'Ukraine', '38.36.7.199'],
          [
            '3',
            'Ruth',
            'rwells2@constantcontact.com',
            'Trinidad and Tobago',
            '19.162.133.184',
          ],
          ['4', 'Jason', 'jray3@psu.edu', 'Brazil', '10.68.11.42'],
          ['5', 'Jane', 'jstephens4@go.com', 'United States', '47.32.129.71'],
          ['6', 'Adam', 'anichols5@com.com', 'Canada', '18.186.38.37'],
        ],
      })

      finalY = doc.lastAutoTable.finalY

      doc.text('From HTML with CSS', 14, finalY + 15)
      
      doc.autoTable({
        startY: finalY + 20,
        useCss: true,
        margin: {horizontal: 5},
        styles: {overflow: 'linebreak', cellWidth:'wrap', minCellWidth: 20},
      })

      doc.save("test.pdf")
      return doc
```

The PDF saves okay. I'm still learning how to use this, so trying some things to get rid of the error. I may just use @tapz solution to suppress it, but I don't like doing that.

**Comment by os-tohe** [comment]
I was able to fix this by setting autotable option tableWidth: 'wrap' (credits: [Brent](https://stackoverflow.com/a/57421880/12099062))

**Comment by michael-sumner** [comment]
For anyone wishing to use the "suppress error" solution;

The type error appears:
```
Error: Unexpected empty arrow function.  @typescript-eslint/no-empty-function
```

Therefore, you will want to do the following:

```jsx
// Save the original console.warn function
const originalWarn = console.warn;

// Override console.warn - suppress jspdf autotable warnings
console.warn = () => {
  return null;
};

// ... your autoTable() code here
// ... another autoTable() code here (if you have any)

// Restore the original console.warn function
console.warn = originalWarn;
```

Hope this helps!

**Comment by mdmahendri** [comment]
this warning helps me detect insertion of empty row (zero length list) because of faulty logic in my code.
if you try to insert empty row `doc.autoTable({body: [] ...)`, the warning will be triggered
