### ISSUE TITLE
Uncaught TypeError: Cannot set property "autoTableText" of undefined

### ISSUE THREAD

**Issue by Jelx** [simonbengtsson/jsPDF-AutoTable#739]
Hi.

jsPdf version: 2.1.1
jsPdf-autotable version: 3.5.13

The title is the error I get when I deployed Angular app on the server (with production build). If I'm building and serving the app locally then it works without a problem and exports to .pdf work as well.

When searching through the code the only thing that I think could be a problem was line 
`jsPDF.API.autoTableText = ...`
in jspdf.plugin.autotable.js file.

I added 
`if(!jsPDF.API) {
    jsPDF.API = {};
}`
at the beggining of the `function default_1(jsPDF) {`.

So far, the build with --prod works normally and all .pdfs are generated correctly.

Can you tell me if this is a bug or am I doing something wrong?

**Comment by simonbengtsson** [comment]
It seems to be an issue with your setup. Most likely related to the way you import jspdf and jspdf-autotable.

**Comment by Jelx** [comment]
I figured that would be the case. 

I've managed to get it to work by cleaning up the cache and fresh package install.

Thanks for confirming.
