### ISSUE TITLE
Overflow linebreak not working with autoTable 

### ISSUE THREAD

**Issue by jdat82** [simonbengtsson/jsPDF-AutoTable#74]
Hi,

I'm using jspdf 1.0.272 and autoTable 1.3.4.

In one image, here is an illustration of the issue I face :
![jspdf_autotable_wrong_cell_height](https://cloud.githubusercontent.com/assets/2780462/10479220/485bbb98-7263-11e5-94b7-ca2a4ea014bb.png)

I have a table with 3 columns. Overflow is enabled for the third one. When there is overflow, the cell height is incorrect. Generally, the last line is not shown.

Here is how I invoke autoTable :
```
                columns = [
                    {title: $translate.instant('test__label'), key: 'label'},
                    {title: $translate.instant('test__status'), key: 'ok'},
                    {title: $translate.instant('test__comment'), key: 'comment'}
                ];
                doc.autoTable(columns, atp.checklist, {
                    startY: checklistOffset + 20,
                    overflow: 'linebreak',
                    overflowColumns: ['comment'],
                    renderCell: function (x, y, width, height, key, value, row, settings) {
                        if (key === 'ok') {
                            var v = value;
                            value = [];
                            if (v === true || v === 'true') {
                                doc.setTextColor(70, 136, 71);
                                value.push('OK');
                            }
                            else if(v === false || v === 'false') {
                                doc.setTextColor(185, 74, 72);
                                value.push('KO');
                            }
                            else{
                                value.push('');
                            }
                            doc.setFontStyle('bold');
                        }
                        else {
                            doc.setTextColor(50);
                            doc.setFontStyle('normal');
                        }
                        doc.setFillColor(row % 2 === 0 ? 245 : 255);
                        doc.rect(x, y, width, height, 'F');
                        x += settings.padding;
                        y += settings.lineHeight / 2 + doc.autoTableTextHeight() / 2 - 2.5;
                        doc.text(value, x, y);
                    }
                });
```

I took this line from examples but I'm not sure to understand it. Notably the soustraction of 2.5 :
```
y += settings.lineHeight / 2 + doc.autoTableTextHeight() / 2 - 2.5;
```

Also, just so you know (may have been corrected since), in this release, `examples.html` is wrong :
```
<script src="jspdf.plugin.autotable.js"></script>
```

Should be replaced by :
```
<script src="../jspdf.plugin.autotable.js"></script>
```

Thanks a lot for any advice or workaroud.

**Comment by jdat82** [comment]
Found a workaround. Doesn't understand it but it works. Probably a bug.

Removing the bold in the second column get the right cell height in the third column. 

So I removed this line :
```
doc.setFontStyle('bold');
```

**Comment by simonbengtsson** [comment]
You are right. There were an issue with the height and width of bold text. I would revomend you to use the 2.x release since it has a lot of edge case fixed.

**Comment by jdat82** [comment]
Thanks. Is there a detailed migration guide notably for hooks ?

**Comment by simonbengtsson** [comment]
Its not that detailed but there is a section in the readme about difference between version 1.x and 2.x. I changed the names of some hooks and created a few new ones for version 2.0. You can read more about them in the readme as well.
