### ISSUE TITLE
Aligning text at the most right of the table

### ISSUE THREAD

**Issue by pedrohenriiz** [simonbengtsson/jsPDF-AutoTable#740]
I'm making a pagination and currently I'm suffering trying to position the text aligned to the right of the table. I'm using 40 margin on both sides of the table, but if I use the page size - this margin, the pagination text appears like this.

![98583230-ce880880-22a2-11eb-984e-ff8cba32f442](https://user-images.githubusercontent.com/56472003/98588256-270ed400-22aa-11eb-9384-3d663b67e25e.png)

Removing 80 instead of 40 also doesn't work because sometimes the page will have more pages, breaking the layout, as shown below. The blue line shows that the text is offside of the table.

![98583402-1149e080-22a3-11eb-9362-8673322425e8](https://user-images.githubusercontent.com/56472003/98588292-3726b380-22aa-11eb-97df-b37c67e68f84.png)

I'm using the didDrawPage hook with this code:

```jsx
function drawPage(doc, configs) {
  let paginationTitle = doc.internal.getNumberOfPages() || '';

  const footerOfText = configs?.footer?.ofText || '';

  if (typeof doc.putTotalPages === 'function' && paginationTitle) {
    paginationTitle = `${paginationTitle} ${footerOfText} ${configs.totalPages}`;
  }

  const { pageSize } = doc.internal;

  const pageHeight = pageSize.height;

  const pageWidth = pageSize.width;

  const footerConfig = {
    fontSize: 9,
    textColor: 100,
    textPosition: {
      xAngle: pageWidth - 80,
      yAngle: pageHeight - 25,
    },
    ...configs.footerStyle,
  };

  doc.setFontSize(footerConfig.fontSize);
  doc.setTextColor(footerConfig.textColor);

  doc.text(
    paginationTitle,
    footerConfig.textPosition.xAngle,
    footerConfig.textPosition.yAngle
  );
}
```

I tried to search if there is something, like a prop, that I can pass and align it to the right but didn't find anything. So, how it's possible to align the text at right dynamically?

Thanks!

**Comment by simonbengtsson** [comment]
The issue is most likely related to that you have to move the text to the left by the same amount as the text width?

**Comment by pedrohenriiz** [comment]
Yes. I was questioning if there is some way to position the text at the right side of the table instead of the page. Some texts will be wider than others, as shown on image 1 and 2.

**Comment by simonbengtsson** [comment]
Maybe I'm misunderstanding but I think you need to subtract the text width instead of using 80?

**Comment by pedrohenriiz** [comment]
I've tried doing this but the text appears way too far from the edge. 
![image](https://user-images.githubusercontent.com/56472003/98593568-16625c00-22b2-11eb-8047-4b96ba83e226.png)

Maybe I'm doing something wrong? I added a new variable called textWidth and subtract from the pageWidth

```jsx
function drawPage(data, doc, configs) {
  let paginationTitle = doc.internal.getNumberOfPages() || '';

  const footerOfText = configs?.footer?.ofText || '';

  if (typeof doc.putTotalPages === 'function' && paginationTitle) {
    paginationTitle = `${paginationTitle} ${footerOfText} ${configs.totalPages}`;
  }

  const { pageSize } = doc.internal;

  const pageHeight = pageSize.height;

  const pageWidth = pageSize.width;

  const textWidth = doc.getTextWidth(paginationTitle);

  const footerConfig = {
    fontSize: 9,
    textColor: 100,
    textPosition: {
      xAngle: pageWidth - textWidth,
      yAngle: pageHeight - 25,
    },
    ...configs.footerStyle,
  };

  doc.setFontSize(footerConfig.fontSize);
  doc.setTextColor(footerConfig.textColor);

  doc.text(
    paginationTitle,
    footerConfig.textPosition.xAngle,
    footerConfig.textPosition.yAngle
  );
}

```
