### ISSUE TITLE
jspdf@2 Support?

### ISSUE THREAD

**Issue by briananderson1222** [simonbengtsson/jsPDF-AutoTable#741]
Are there plans to support jspdf@2+? Since the jspdf constructor is no longer exported as `default` this causes a fair amount of problems. I attempted to go down the `applyPlugin` route, but I must not understand something there as that seemed to just set all the methods up on the jsPdf instance under a non-existent property called `API`. Which then causes issues in other various methods that attempt to get a reference to the jsPdf instance which now get the instance of `API` instead of the doc itself.

**Comment by simonbengtsson** [comment]
Jspdf should be supported. Check the examples which use v2 by default.

**Comment by themacboy** [comment]
Sorry. Im very, very noob and not sure if my problem is related to this issue.

I has a static web page where I load jsPDF library and autoTable using Tags in the index.html.

But when I try to use the autoTable module it respond not found:

"TypeError: jsPDF.autoTable is not a function"

I have checked in the console for jsPDF.API and autoTable is no listed:

![image](https://user-images.githubusercontent.com/8063711/99855113-61b81c80-2b86-11eb-8ffa-bffd4b93a867.png)

What Im doing wrong? thx in advance
