### ISSUE TITLE
Table line doesn't show correctly on tables with  page breaks

### ISSUE THREAD

**Issue by pkrstic-tq** [simonbengtsson/jsPDF-AutoTable#742]
When you set tableLineColor and tableLineWidth, on long table that needs to break across multiple pages, rectangle that should go around table is not calculated correctly (top position)
![image](https://user-images.githubusercontent.com/69855174/99666606-7bb10c80-2a6b-11eb-8252-f4b68f94a470.png)

**Comment by simonbengtsson** [comment]
Interesting! Can you attach some example code that highlights the issue?
