### ISSUE TITLE
Formatting within cells using HTML <b> and <i> elements to bold and italicize

### ISSUE THREAD

**Issue by Chen2x** [simonbengtsson/jsPDF-AutoTable#744]
Hi @simonbengtsson and autotable contributors, 

I am looking for a way to bold and italicize specific strings within an autotable cell using HTML elements. Currently I am using jquery to get an HTML table and adding in HTML elements ```<br/>``` and ```<b>``` at specific lines before entering the data into autotable to be displayed.

```$(this).html($(this).text().replace('Part #:','<br/><b>Part #:</b>').replace('SKU:','<br/><b>SKU:</b>').trim()```

An example of the current output is this:
![image](https://user-images.githubusercontent.com/17359706/99831598-5389e200-2b2d-11eb-8e03-655bf99f11e7.png)

When autotable takes the input, the ```<br/>``` element is respected and a newline can be seen but the the ```<b>``` tags are removed and the styling is not applied. Are there any built in methods that would currently allow different in cell styling? If not I would like to request this as a new feature since there doesn't seem a way to style strings differently in a cell currently, only global within the cell.

**Comment by simonbengtsson** [comment]
You can draw the text yourself in the didDrawCell hook for example. The plugin does not parse the text in anyway for styling purposes however and by default all text in a cell has the same styling.

**Comment by Chen2x** [comment]
By drawing do you mean html2canvas? For this specific task I need the contents of the table to be copyable which from my understanding is not possible with html2canvas since it creates an image. Are there any other solutions that can allow the text to be copied?

**Comment by LuigiSZ** [comment]
I add in willDrawCell some code to support mixed style in cell for tag < b >, < i >, < u >, < del >
is not perfect but work.

[script-willDrawCell.txt](https://github.com/simonbengtsson/jsPDF-AutoTable/files/6246086/script-willDrawCell.txt)

**Comment by martinharyanto** [comment]
Sorry for commenting here after so long. I was looking for this exact problem and try to use @LuigiSZ script, but it turns out it doesn't work so well with newest version of `autoTable`.

For those who come to this place and still find it hard to render multiple font style on one sentence, I just found the solution (it was chatGPT that gave me this enlightment). I hope this can help someone out there. For other styles you just need to add more tags, or copy and paste this code then ask chatGPT to improve it with whatever you want. 🙏 

```
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const doc = new jsPDF();

const data = [
  { content: 'Dokumen ini <b>merupakan</b> Pesanan Pembelian Resmi (PO)' }
];

const processText = (text: string) => {
  const parts = text.split(/(<\/?b>)/).filter(part => part.trim() !== '');
  return parts;
};

const renderText = (doc: jsPDF, cell, text: string) => {
  const parts = processText(text);
  const { x, y, width } = cell;
  let cursorX = x;
  doc.setFont('helvetica', 'normal');
  parts.forEach(part => {
    if (part === '<b>') {
      doc.setFont('helvetica', 'bold');
    } else if (part === '</b>') {
      doc.setFont('helvetica', 'normal');
    } else {
      const textWidth = doc.getTextWidth(part);
      doc.text(part, cursorX, y);
      cursorX += textWidth;
    }
  });
};

doc.autoTable({
  head: [['Column']],
  body: data.map(row => [row.content]),
  willDrawCell: function (data) {
    if (data.section === 'body') {
      const cell = data.cell;
      const text = cell.raw;
      cell.text = [];
      renderText(doc, cell, text);
    }
  }
});

doc.save('table.pdf');
```

**Comment by nrgbistro** [comment]
Hey @martinharyanto, I tried using your code to generate my table but some of the text appears very off. Do you know how to fix that? (I also used chatGPT to no avail and I'm very new to jsPDF)

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/79836d33-3b2b-40fa-9e9a-753e1dbb203c">

**Comment by Hassan1ahmad** [comment]
**Example: Using jsPDF + jsPDF-AutoTable to render mixed text styles in a cell**
* This example shows how to render **bold** and normal text together 
* inside the same cell by parsing <b>...</b> tags manually.
*


`import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const doc = new jsPDF();

// Sample data with mixed bold/normal text
const data = [
  { content: "This document <b>is part of</b> real Purchase Order (PO)" },
];

// Split string into text parts (<b> and normal)
const processText = (text) =>
  text.split(/(<\/?b>)/).filter((part) => part.trim() !== "");

// Custom renderer for mixed text
const renderText = (doc, cell, text) => {
  const parts = processText(text);
  const { x, y } = cell;
  let cursorX = x + 2;
  doc.setFont("helvetica", "normal");

  parts.forEach((part) => {
    if (part === "<b>") {
      doc.setFont("helvetica", "bold");
    } else if (part === "</b>") {
      doc.setFont("helvetica", "normal");
    } else {
      const textWidth = doc.getTextWidth(part);
      doc.text(part, cursorX, y + 3.5);
      cursorX += textWidth;
    }
  });
};

// ✅ AutoTable with bold & normal mixed text
autoTable(doc, {
  head: [["Description"]],
  body: data.map((row) => [row.content]),

  styles: { fontSize: 10, cellPadding: 3, valign: "middle" },
  theme: "grid",

  // Step 1: prevent autoTable from drawing text first
  willDrawCell(data) {
    if (
      data.section === "body" &&
      typeof data.cell.raw === "string" &&
      data.cell.raw.includes("<b>")
    ) {
      data.cell.text = [];
    }
  },

  // Step 2: manually render text after background
  didDrawCell(data) {
    if (
      data.section === "body" &&
      typeof data.cell.raw === "string" &&
      data.cell.raw.includes("<b>")
    ) {
      renderText(doc, data.cell, data.cell.raw);
    }
  },
});

doc.save("mixed-text-table.pdf");`
