### ISSUE TITLE
Row page break at specific y coordinate when drawing row and same startY for all page breaks.

### ISSUE THREAD

**Issue by edgarecko7** [simonbengtsson/jsPDF-AutoTable#746]
Hello, i am facing an issue with page breaks when the tables does not fit in one page.

Is it possible to set a page break while drawing rows (hooks or with autotable option) at specific Y coordinate? Say i have a table with header, body and footer (drawn only at last doc page), if a row is at 70 % of the page height (specific Y coordinate/cursor.y property), break and start another page and draw the header again and keep drawing the body.

The automatic page break does not work for my case because of the specific styling i have to deal with, the rows of my body (are dynamic in qty), the data comes from an rest api and the last row of the data, has to take all the height space available up to 70% of the page height if its y position is greater i have to page break.

And with the default behavior, takes all the height space available from the given startY coordinate, and if the page break occurs, the header of the table is drawn at the very beginning of the page height, and i want the header be drawn at the same Y coordinate as the header of the first page.

Can i do that with the "jspdf-autotable": "^3.5.13" version, or do i have to change the code?
I am using "jspdf": "^2.1.1" and jspdf-autotable in a nodeJS Rest API and i stream the pdf whenever the user wants to download it. And the data i fetch has no styles or table (pdf), it is a json.

Any help, advice is welcome.

Thanks in advance.

**Comment by simonbengtsson** [comment]
In not fully understanding the question but you might want to look into vertical margin.

**Comment by edgarecko7** [comment]
I completely forgot that in the docs specifies that startY property is applied only in the first page. My mistake.

My question is, if i can specify a page break at specificY coordinate or even better, max table height, so it draws in another page.
Say if a Row or beforeDrawCell Y position is in (eg. 200) page position, i would write the following code:
```javascript
doc.autoTable({
styles: { ... },
breakAtY: 200, /* start drawing you (table) in a new page when a body row reaches this y page position */
rowBreakAtY: 200, /* start drawing you (table) in a new page when a body row reaches this y page position */
maxTableHeight: 200 /* you (table) have no other choice but to start a new page and be drawn in it */
doc.autoTable({
  head: [...],
  body: [...],
  foot:[...],
...
})
```

For your vertical margin suggestion, do you mean the margin object
```javascript
doc.autotable({
...,
margin: { top : topMargin /* where i want all the tables be drawn */, ... },
...
})
```
or
```javascript
doc.autotable({
...,
verticalMargin: topMargin /* where i want all the tables be drawn */,
...
})
```
cause this last one, i dont find any verticalMargin property in the exports.

**Comment by simonbengtsson** [comment]
Yes by vertical margin I meant the top and bottom property. It seems you should be able to accomplish what you want with those.

**Comment by edgarecko7** [comment]
Ok, with the table top and bottom margin properties set, seems to work and the table splits almost fine, because now the final row of the first page, is split half of its content in the first page, and the remaining content in the other page, and as i said, the table style i need, this procedure does not meet the needs.

That's why i would like to set the page break when the row is about to be drawn.
I tried with the didDrawCell and WillDrawCell hook, to see if the Y position is (eg. 200), if that happens, i added a new page and set that one, reset the Y position to (eg. 60) to starting drawing over.
Because one column of the rows i get is a 'description' field and its content is variable (can increase row height a lot)
But since the hook occurs for all the row columns, i ended with a document with many many pages, hehehe.

That what this question is about.

Can i do that with the current version of jspdf autotable or this specific use case i am facing has to be implemented to the code?

**Comment by simonbengtsson** [comment]
Maybe the rowPageBreak option is useful in this case?

**Comment by edgarecko7** [comment]
Perfect!

rowPageBreak and margin were the solution. (I am not that good at styling yet, since i do more of back end side)

Thank you very much for your quick replies.

Just one more question. I can't set the minimum table height, can I?

**Comment by calldeludo** [comment]
i am not sure that you can set it... but you can try

`bodyStyles: { minCellHeight: 30 }` 

hope it helps you

**Comment by nileshjadhav8897** [comment]
didParseCell:({table, pageNumber,cursor,row,pageCount,section,settings,doc,cell,column,})=>
    {
      if(pageBreakcount.includes(row.index))
      {
     
        row.height=doc.internal.pageSize.height;

    },


[year wise pagebreak.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/10041473/year.wise.pagebreak.pdf)

@simonbengtsson  it work for specific row after page break
