### ISSUE TITLE
how can I define a max-cell-width?

### ISSUE THREAD

**Issue by fralfarom** [simonbengtsson/jsPDF-AutoTable#749]
Hi! I'm needing define a max-cell-width to all cells(I'm getting data from a API) I know about cellWidth: number but this set alls cells width to cellWidth value...I need all cells to have free width but not exceed a maximum width.
![imagen](https://user-images.githubusercontent.com/61016763/101061072-dcae0980-356e-11eb-8b02-b4fe8e46ebaf.png)

for example in the photo the cellWidth is set in 25 and idError, idInstance has more than it needs...is there any way to do it?
Thank You!!

**Comment by vbinithyanandamv** [comment]
did you tried  `styles: { maxCellWidth : number } ` ?? that should work.

**Comment by bonbonsiregar** [comment]
> did you tried `styles: { maxCellWidth : number } ` ?? that should work.
 
Is there a way for autotable to automatically resize the cell based on the text length?

https://stackoverflow.com/a/54306551/15471776

Here I found properties like `styles: { cellWidth: 'auto', cellWidth: 'wrap' }
` are these valid?
