### ISSUE TITLE
Option to add page numbers

### ISSUE THREAD

**Issue by sjurba** [simonbengtsson/jsPDF-AutoTable#75]
It would be great with an option to add page numbers for when the document spans multiple pages.

**Comment by simonbengtsson** [comment]
How would you want that feature to work? The `header and footer` example uses page numbers, but it is using the default way of doing that in jspdf.

**Comment by sjurba** [comment]
Ah, I see. I guess I could just copy that, but it would be a nice feature for you library to make it a bit easier to use. For example something like this:
````
{
 pageNumbers: {
  position: [left | center | right],
  template: "Page {count} of {total}",
  generator: function(count, total) {
     return "Page " + count + " of " + total;
  }
  style: {...}
}
````

**Comment by simonbengtsson** [comment]
I agree and will consider it for a future update. Right now this plugin only draws things within the boundaries of the table itself and leaves everything else to jspdf. This simplifies the code so Im a little bit hesitant to change it.

**Comment by simonbengtsson** [comment]
I added this request to the future work section in the readme.
