### ISSUE TITLE
Page counter if page size > 1

### ISSUE THREAD

**Issue by PortStone** [simonbengtsson/jsPDF-AutoTable#751]
In the example is already shown how you can do a page counter but what if I don't want to show it if it is only one page?

**Comment by simonbengtsson** [comment]
Interesting question! I'd look at writing all of the page numbers after the table is drawn instead of in the didDrawPage hook. That way you can check if it is more than one page or not.

**Comment by PortStone** [comment]
Yea that did the work. An example is listed here: https://github.com/MrRio/jsPDF/issues/1340#issuecomment-319313368
