### ISSUE TITLE
Use `doc.getLineHeightFactor()` instead of `FONT_ROW_RATIO` constant in `autoTableText()`

### ISSUE THREAD

**Issue by gpbmike** [simonbengtsson/jsPDF-AutoTable#753]
When using `autoTableText` with an array of text strings, it would be nice for a previously set `lineHeightFactor` to be used. 

Documentation for `getLineHeightFactor`: http://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html#getLineHeightFactor
Fix would go here: https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/src/autoTableText.ts#L15

Use case:

```js
doc.setLineHeightFactor(2);
doc.autoTableText(['First Line', 'Second Line'], 0, 0);
```

I would expect more space between the first and second line, but a value of 1.15 is hardcoded.

**Comment by simonbengtsson** [comment]
Looks great! Let's continue discussion in the pull request.
