### ISSUE TITLE
New line issue when using in Angular

### ISSUE THREAD

**Issue by arunlalkp** [simonbengtsson/jsPDF-AutoTable#757]
When I use AutoTable along-with Angular, there is an issue in cell content new line rendering. I saw the library checks the `\n`  and `<br>` for rendering a new line in `parseCellContent()` function.
 When we use the `<br>` tag, Angular randomly adds attributes to it like `<br _ngcontent-mjv-c183="">` In this case, the `<br>` check fails, and nothing happens to cell contents.
Using the `innerHTML` Directive can be a fix, but there has any other solution right here?

**Comment by simonbengtsson** [comment]
Oh! Good catch. A PR would be much appreciated!

**Comment by arunlalkp** [comment]
Sure 👍🏼
