### ISSUE TITLE
Line height

### ISSUE THREAD

**Issue by XinYiMan** [simonbengtsson/jsPDF-AutoTable#76]
Hello, my name is Francis and I'm using your component. I was wondering how I can set the row height, because the default height is not enough. How can I do?

This is my code

			function generatefromtable(intestazione) {
				try{
					var $ret=true;
					var totalPagesExp = "{total_pages_count_string}";
				    //var doc = new jsPDF('p', 'pt');
					var doc = new jsPDF('l', 'pt', 'a4', true); 
				    var header = function (doc, pageCount, options) {
					doc.setFontSize(20);
					doc.text(intestazione, options.margins.horizontal, 60);
					doc.setFontSize(options.fontSize);
				    };

				var renderCell = function (x, y, width, height, key, value, row, settings) {				    
				    doc.rect(x, y, width, height, 'S');				    

				    y += settings.lineHeight / 2 +
				    doc.internal.getLineHeight() / 2 - 2.5;
				    doc.text('' + value, x + settings.padding, y);

				};

				    var footer = function (doc, lastCellPos, pageCount, options) {
					var str = " " + pageCount + "/" + totalPagesExp;
					doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
				    };
				    var options = {renderHeader: header, renderFooter: footer, renderCell: renderCell, margins: {horizontal: 40, top: 80, bottom: 50}};    

				    // Be sure to set the second parameter (indexBased option) to true
				    // It will be the default behavior in v2.0, but are now behind an option for compatibility
				    var res = doc.autoTableHtmlToJson(document.getElementById("tbl_pdf"), true);
				    doc.autoTable(res.columns, res.data, options);

   				    doc.putTotalPages(totalPagesExp);

				    doc.output("dataurlnewwindow");

				}catch(err) {
			    		//err.message per avere il testo del messaggio
					ret=false;
				}

				return ret;
			}

**Comment by simonbengtsson** [comment]
Hi! Checkout the different styling options. I think `rowHeight` is what you are looking for.

**Comment by XinYiMan** [comment]
I'll explain at the end of my problem I have too many columns and pdf that is the result of no avail. So I decided to split a single line on two lines. The problem is that jsPDF is only the first line as a header. How can I do?

**Comment by simonbengtsson** [comment]
If you don't have enough space for your columns the only thing I can think of is to make the text smaller, put the page in landscape or print on a bigger paper. The plugin unfortunately doesn't support to have the columns divided on the same row if that is what you meant.

**Comment by XinYiMan** [comment]
How set font dimensions?


            function generatefromtable(intestazione) {
                try{
                    var $ret=true;
                    var totalPagesExp = "{total_pages_count_string}";
                    //var doc = new jsPDF('p', 'pt');
                    var doc = new jsPDF('l', 'pt', 'a4', true);
                    var header = function (doc, pageCount, options) {
                    doc.setFontSize(20);
                    doc.text(intestazione, options.margins.horizontal, 60);
                    doc.setFontSize(options.fontSize);
                    };

                var renderCell = function (x, y, width, height, key, value,
row, settings) {
                    doc.rect(x, y, width, height, 'S');

                    if ((key === 2)||(key === 3)||(key === 4)||(key === 5))
{
                    var strWidth = doc.getStringUnitWidth('' + value) *
                        doc.internal.getFontSize();
                    x += width;
                    x -= 2 * settings.padding;
                    x -= strWidth;
                    }

                    y += settings.lineHeight / 2 +
                    doc.internal.getLineHeight() / 2 - 2.5;
                    doc.text('' + value, x + settings.padding, y);

                };


                    var footer = function (doc, lastCellPos, pageCount,
options) {
                    var str = " " + pageCount + "/" + totalPagesExp;
                    doc.text(str, options.margins.horizontal,
doc.internal.pageSize.height - 30);
                    };
                    var options = {renderHeader: header, renderFooter:
footer, renderCell: renderCell, margins: {horizontal: 40, top: 80, bottom:
50}};

                    // Be sure to set the second parameter (indexBased
option) to true
                    // It will be the default behavior in v2.0, but are now
behind an option for compatibility
                    var res =
doc.autoTableHtmlToJson(document.getElementById("tbl"), true);
                    doc.autoTable(res.columns, res.data, options);

                       doc.putTotalPages(totalPagesExp);

                    doc.output("dataurlnewwindow");

                }catch(err) {
                        //err.message per avere il testo del messaggio
                    ret=false;
                }

                return ret;
            }


2015-10-19 17:54 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by simonbengtsson** [comment]
To change font size or other font related styling, checkout the different styling options described in the readme.

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to post other issues if you have other questions or issues.
