### ISSUE TITLE
How to add a link in a cell properly?

### ISSUE THREAD

**Issue by amiram** [simonbengtsson/jsPDF-AutoTable#762]
I have a column with url's. The url's are long. I tried several options but each one is not working well.

1. Just render the cell as the others - the cell is combined from multiple lines since the text is long. Only the first line is a link because only it starts with https and the others don't, but the link is wrong since it includes only the first line (only "https" and a little more.
2. Use style.overflow = 'ellipsize' - here we see only the first row with just the start of the url followed by `...` but the link target also being cut.
3. Use a hook like that:
```
willDrawCell: data => {
                if (data.cell.section === 'body' && data.column.index === 3) {
                    doc.textWithLink('Click here', data.cell.x, data.cell.y, {url: data.cell.text.join('')});
                    data.cell.text = [' ']; // just to avoid printing the url
                }
            }
```
The problem here is that the cell looks black just as the color of the text, instead of light gray. 
![Screenshot from 2021-01-10 21-02-29](https://user-images.githubusercontent.com/1693597/104132627-4a77fd00-5387-11eb-9b26-4c4273b9e9e3.png)

**Comment by risalfajar** [comment]
Is this possible to implement?

**Comment by ir-fuel** [comment]
Better late than never:
in the `willDrawCell` hook you have to do the complete custom rendering of the cell. If you return `false` it will skip its own rendering of the cell. You will need to provide up front the text for the hyperlink when it calculates cell sizes, and not the hyperlink itself, to be sure the cell is the correct size.

**Comment by zbetulaltundal** [comment]
It didnt work out for me @ir-fuel

**Comment by ir-fuel** [comment]
No idea if it's any use to you, as this won't be copy paste, but here you go:

```
const autoTableLinkText = (
  text,
  url,
  x,
  y,
  styles,
  doc
) => {
  styles = styles || {}
  const PHYSICAL_LINE_HEIGHT = 1.15

  const k = doc.internal.scaleFactor
  const fontSize = doc.internal.getFontSize() / k
  const lineHeightFactor = doc.getLineHeightFactor
    ? doc.getLineHeightFactor()
    : PHYSICAL_LINE_HEIGHT
  const lineHeight = fontSize * lineHeightFactor

  const splitRegex = /\r\n|\r|\n/g
  let splitText = ''
  let lineCount = 1
  if (
    styles.valign === 'middle'
    || styles.valign === 'bottom'
    || styles.halign === 'center'
    || styles.halign === 'right'
  ) {
    splitText = typeof text === 'string' ? text.split(splitRegex) : text
    lineCount = splitText.length || 1
  }

  // Align the top
  y += fontSize * (2 - PHYSICAL_LINE_HEIGHT)

  if (styles.valign === 'middle') y -= (lineCount / 2) * lineHeight
  else if (styles.valign === 'bottom') y -= lineCount * lineHeight

  if (styles.halign === 'center' || styles.halign === 'right') {
    let alignSize = fontSize
    if (styles.halign === 'center') alignSize *= 0.5

    if (splitText && lineCount >= 1) {
      for (let iLine = 0; iLine < splitText.length; iLine += 1) {
        const xPos = x - doc.getStringUnitWidth(splitText[iLine]) * alignSize
        const textWidth = doc.getTextWidth(splitText[iLine])
        const textColor = doc.getTextColor()
        const drawColor = doc.getDrawColor()

        if (url) {
          doc.setTextColor(0, 0, 238)
          doc.setDrawColor(0, 0, 238)
          doc.line(xPos, y + 1, xPos + textWidth, y + 1)
        }

        doc.textWithLink(
          splitText[iLine],
          xPos,
          y, {
            url
          }
        )

        doc.setTextColor(textColor)
        doc.setDrawColor(drawColor)
        y += lineHeight
      }
      return doc
    }
    x -= doc.getStringUnitWidth(text) * alignSize
  }

  if (styles.halign === 'justify') {
    doc.textWithLink(text, x, y, {
      maxWidth: styles.maxWidth || 100,
      align: 'justify',
      url
    })
  } else {
    doc.textWithLink(text, x, y, {
      url
    })
  }

  return doc
}
```

called from:
```
const willDrawCell = (hookData, language) => {
  const { doc } = hookData

  if (hookData.section === 'body' && (hookData.column.index === 3 || hookData.column.index === 4)) {
    const { cell } = hookData
    const textPos = cell.getTextPos()
    console.log(textPos)
    console.log(cell.x, cell.y)
    doc.rect(cell.x, cell.y, cell.width, cell.height, 'F')

    const url = `https://www.google.com`

    autoTableLinkText(
      cell.text[0],
      url,
      textPos.x,
      textPos.y,
      {
        halign: cell.styles.halign,
        valign: cell.styles.valign,
        maxWidth: Math.ceil(
          cell.width - cell.padding('left') - cell.padding('right'),
        ),
      },
      doc
    )

    return false
  }

  return true
}
```

called from
```
  doc.autoTable({
    styles: {
      halign: 'right'
    },
    headStyles: {
      fillColor: [128, 128, 128]
    },
    head: [
      [
...
      ],
    ],
    body: data.map((d) => [...]),
    margin: {
      top: 70, right: 10
    },
    willDrawCell: (hookData) => willDrawCell(hookData, language),
    didDrawPage: (d) => {
      height = d.cursor.y
    },
  })
```

**Comment by zbetulaltundal** [comment]
> No idea if it's any use to you, as this won't be copy paste, but here you go:
> 
> ```
> const autoTableLinkText = (
>   text,
>   url,
>   x,
>   y,
>   styles,
>   doc
> ) => {
>   styles = styles || {}
>   const PHYSICAL_LINE_HEIGHT = 1.15
> 
>   const k = doc.internal.scaleFactor
>   const fontSize = doc.internal.getFontSize() / k
>   const lineHeightFactor = doc.getLineHeightFactor
>     ? doc.getLineHeightFactor()
>     : PHYSICAL_LINE_HEIGHT
>   const lineHeight = fontSize * lineHeightFactor
> 
>   const splitRegex = /\r\n|\r|\n/g
>   let splitText = ''
>   let lineCount = 1
>   if (
>     styles.valign === 'middle'
>     || styles.valign === 'bottom'
>     || styles.halign === 'center'
>     || styles.halign === 'right'
>   ) {
>     splitText = typeof text === 'string' ? text.split(splitRegex) : text
>     lineCount = splitText.length || 1
>   }
> 
>   // Align the top
>   y += fontSize * (2 - PHYSICAL_LINE_HEIGHT)
> 
>   if (styles.valign === 'middle') y -= (lineCount / 2) * lineHeight
>   else if (styles.valign === 'bottom') y -= lineCount * lineHeight
> 
>   if (styles.halign === 'center' || styles.halign === 'right') {
>     let alignSize = fontSize
>     if (styles.halign === 'center') alignSize *= 0.5
> 
>     if (splitText && lineCount >= 1) {
>       for (let iLine = 0; iLine < splitText.length; iLine += 1) {
>         const xPos = x - doc.getStringUnitWidth(splitText[iLine]) * alignSize
>         const textWidth = doc.getTextWidth(splitText[iLine])
>         const textColor = doc.getTextColor()
>         const drawColor = doc.getDrawColor()
> 
>         if (url) {
>           doc.setTextColor(0, 0, 238)
>           doc.setDrawColor(0, 0, 238)
>           doc.line(xPos, y + 1, xPos + textWidth, y + 1)
>         }
> 
>         doc.textWithLink(
>           splitText[iLine],
>           xPos,
>           y, {
>             url
>           }
>         )
> 
>         doc.setTextColor(textColor)
>         doc.setDrawColor(drawColor)
>         y += lineHeight
>       }
>       return doc
>     }
>     x -= doc.getStringUnitWidth(text) * alignSize
>   }
> 
>   if (styles.halign === 'justify') {
>     doc.textWithLink(text, x, y, {
>       maxWidth: styles.maxWidth || 100,
>       align: 'justify',
>       url
>     })
>   } else {
>     doc.textWithLink(text, x, y, {
>       url
>     })
>   }
> 
>   return doc
> }
> ```
> 
> called from:
> 
> ```
> const willDrawCell = (hookData, language) => {
>   const { doc } = hookData
> 
>   if (hookData.section === 'body' && (hookData.column.index === 3 || hookData.column.index === 4)) {
>     const { cell } = hookData
>     const textPos = cell.getTextPos()
>     console.log(textPos)
>     console.log(cell.x, cell.y)
>     doc.rect(cell.x, cell.y, cell.width, cell.height, 'F')
> 
>     const url = `https://www.google.com`
> 
>     autoTableLinkText(
>       cell.text[0],
>       url,
>       textPos.x,
>       textPos.y,
>       {
>         halign: cell.styles.halign,
>         valign: cell.styles.valign,
>         maxWidth: Math.ceil(
>           cell.width - cell.padding('left') - cell.padding('right'),
>         ),
>       },
>       doc
>     )
> 
>     return false
>   }
> 
>   return true
> }
> ```
> 
> called from
> 
> ```
>   doc.autoTable({
>     styles: {
>       halign: 'right'
>     },
>     headStyles: {
>       fillColor: [128, 128, 128]
>     },
>     head: [
>       [
> ...
>       ],
>     ],
>     body: data.map((d) => [...]),
>     margin: {
>       top: 70, right: 10
>     },
>     willDrawCell: (hookData) => willDrawCell(hookData, language),
>     didDrawPage: (d) => {
>       height = d.cursor.y
>     },
>   })
> ```

this has worked for me! thank you!
