### ISSUE TITLE
Align text in the specific cells of autotable grid right (right align)

### ISSUE THREAD

**Issue by kmsharjas** [simonbengtsson/jsPDF-AutoTable#765]
Hi,

Is there a way to right-align the text in the specific cells of the auto-table grid? 
![image](https://user-images.githubusercontent.com/15127210/106570288-b0593e00-655b-11eb-87ce-d481007bb272.png)
Above there is a screenshot of the auto-table grid I have till now and I want to align the text right. How can I do that? Here is the function I wrote for it :

`doc.autoTable({
      startY: 130,
      margin: { top: 80, bottom: 20 },
      didDrawPage: function (data) {
        data.settings.margin.top = 40;
      },
      body: this.PDFArray,
      columns: Object.keys(this.PDFArray[0]).map((column) => ({
        header: column,
        dataKey: column,
      })),
      theme: "plain",
      tableWidth: "auto",
    });`

**Comment by kmsharjas** [comment]
@simonbengtsson need action

**Comment by vlourme** [comment]
I had the same issue, but this feature is already built-in, you can use it like that:
```ts
autoTable(doc, {
  head: [['Column 1', 'Column 2']],
  columns: [
    { dataKey: 'mycolumn', header: 'Column 2' }
  ],
  columnStyles: {
    mycolumn: {
      halign: 'right'
    }
  }
})
```

**Comment by Mashiane** [comment]
This only works for the data in the rows, how does one set the alignment of the header?
