### ISSUE TITLE
Certain Columns Has Extra Wide Width

### ISSUE THREAD

**Issue by BarishSarac** [simonbengtsson/jsPDF-AutoTable#766]
Hi,

I have certain columns in my dataset, when I add those, width of them gets extremely wide taking mostly whole width of the table, I am not sure why. Any ideas?

![exData](https://user-images.githubusercontent.com/2792881/106801287-3098a580-6627-11eb-8500-ff7e3ea8cbc2.PNG)
![exPrint](https://user-images.githubusercontent.com/2792881/106801289-31313c00-6627-11eb-8704-e61a0f99f50a.PNG)

**Comment by BarishSarac** [comment]
I can't set column widths hardcode like with numbers, so I had to wrap them. 
```
 content = {
        margin,
        startY: startY,
        head: headers,
        body: data,
        styles:  {
          cellWidth: "wrap",
        };
```
the only issue with this, there is quite bit of space empty to the right of the document now that their width is not automatically distributed. Otherwise, I can enable/test then activate wrap  only to those that create too wide width issue but since I have literally 32 columns users can activate/deactivate I'd rather not test each one to see which ones are causing this too wide problem. If there's a solution better than what I did please let me know.

**Comment by simonbengtsson** [comment]
Hmm can you try to create a minimal reproducible example and post here?
