### ISSUE TITLE
Ignore element with Tag name, ID or Class

### ISSUE THREAD

**Issue by bes1002t** [simonbengtsson/jsPDF-AutoTable#769]
Sometimes you don't wanna add specific elements in the generated PDF. For instance in my HTML table header I have an image which indicates the order (caret). When generating a PDF out of this table, I don't wanna add the image to the PDF.

It would be greate if there would be an option like
```
doc.autoTable({
    html: '#licenses_details table',
    ignore: [ '#foo', '.bar', 'element' ],
    useCss: true
});
```

**Comment by simonbengtsson** [comment]
You can use `doc(autoTableHtmlToJson(elementId)` for this and then filter the data yourself. It is not documented right now, but will be at some point.

**Comment by bes1002t** [comment]
@simonbengtsson thanks for your quick response. Your proposal works regarding the element removal, but how could you use the returned JSON to generate the PDF?

The following code produces a messed up PDF which is using one row for each cell.
```
const table = doc.autoTableHtmlToJson('#my_id table')
doc.autoTable({
    head: table.columns,
    body: table.data,
    useCss: true,
});
```
