### ISSUE TITLE
Cell text missing

### ISSUE THREAD

**Issue by marccollin** [simonbengtsson/jsPDF-AutoTable#77]
I have many html table then i try to print

with this code

```
var doc = new jsPDF('p', 'pt');
var res = doc.autoTableHtmlToJson(tableId, true);
doc.autoTable(res.columns, res.data);
doc.output('dataurlnewwindow');
```

result

![result]
(http://img.ctrlv.in/img/15/10/18/562397028018a.jpg)

It's like the text is wrapping.

**Comment by simonbengtsson** [comment]
Can you post the html for your table and the value of the tableId variabler?

**Comment by marccollin** [comment]
it's a bootstrap table


table content

```
<table id="freeRoomTableResult" style="margin-top: -41px;" data-show-header="true" class="table table-striped table-hover" data-toggle="table" data-height="330">
   <thead>
      <tr>
         <th style="">
            <div class="th-inner ">Immeuble</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Appartement</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Nb de lit disponible</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Chambre semaine</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Chambre mois</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Pension semaine</div>
            <div class="fht-cell"></div>
         </th>
         <th style="">
            <div class="th-inner ">Pension mois</div>
            <div class="fht-cell"></div>
         </th>
      </tr>
   </thead>
   <tbody>
      <tr data-index="0">
         <td style="" data-room-id="1">460 Ch. Chambly</td>
         <td style="">1</td>
         <td style="">A</td>
         <td style=""></td>
         <td style=""></td>
         <td style=""></td>
         <td style=""></td>
      </tr>
</tbody>
</table>
```

tableId is $("#freeRoomTableResult")[0]

**Comment by simonbengtsson** [comment]
With the html you posted the image you posted seem to be expected behavior? Or what do you mean with wrapping? You can try the style `overflow: linebreak;` if you don't want the cells to clip the content with `...` when there is no room for the whole text.

**Comment by marccollin** [comment]
i not used the correct word. 

i'm mean the text is not all displayed

**Comment by simonbengtsson** [comment]
Do you mean for example `460 Ch. Cham...` instead of `460 Ch. Chambly`? If so, try the `overflow: linebreak;` style.

**Comment by marccollin** [comment]
ya, will try.

**Comment by simonbengtsson** [comment]
Closing this for now. Let me know if you have other issues!

**Comment by marccollin** [comment]
seem ligne overflow: linebreak don't exist...

on the table table-layout:fixed;
on the th, td word-wrap:break-word;

tried without success, i use bootstrap-table plugin, maybe it's the problem.

**Comment by simonbengtsson** [comment]
Do you get any errors? Or is it the same problem as before? Can you in that case post the result of the `doc.autoTableHtmlToJson(tableId, true);`? And perhaps also the make sure that tableId is of the type html table element. The variable name `tableId` sounds like it might be a string. Bootstrap should not be an issue.

**Comment by marccollin** [comment]
```
tableId =  $("#freeRoomTableResult")[0];
```

res is a object who contain

columns: Array[7]
data: Array[296]
rows: Array[296]
