### ISSUE TITLE
Instead of using the DOM internally, use a DOM copy

### ISSUE THREAD

**Issue by bes1002t** [simonbengtsson/jsPDF-AutoTable#770]
It's a cool feature that you can manipulate the DOM using autoTable hooks. Unfortunately by using this feature you will manipulate the real DOM, not just the DOM which is used for the PDF.

I'm trying to find a solution for this issue: https://github.com/simonbengtsson/jsPDF-AutoTable/issues/769
So I simply removed all images (in header) with the "didParseCell" hook. The strange thing is, this just removed the image from my actual table, but kept the text "image/svg+xml" in the PDF...
```
        doc.autoTable({
            html: '#my_id table',
            useCss: true,
            didParseCell: function(data) {
                if (data.cell.section === 'head') {
                    var imgs = data.cell.raw.querySelectorAll("my-svg");
                    for (let img of imgs) {
                        img.parentNode.removeChild(img)
                    }
                }
            }
        });
```

I don't know whether this is a bug or the expected behavior, but I think it's strange.

**Comment by simonbengtsson** [comment]
You could use `doc.autoTableHtmlToJson(elementId)` and the filter out the data before passing it to autotable. It is not documented right now but will be at some point.

**Comment by bes1002t** [comment]
@simonbengtsson perhaps this would solve my issue, but does not change a thing about the fact that the real DOM is manipulated if you use the hooks. I could imagine that most users want to manipulate the DOM which is used for the PDF, not the real DOM.

**Comment by simonbengtsson** [comment]
In the didParseCell the data has already been parsed so the only reason you'd want to manipulate the DOM here I think would be to change the real DOM.

If you want to change the content of a cell you would have to do something like this `cell.text = data.cell.raw.textContent + 'Extra'`

**Comment by bes1002t** [comment]
right, after parsing the DOM it is available within the plugin. Why would someone want to manipulate the website DOM using the plugin? Wouldn't it make more sense to manipulate the PDF appearance inside of a hook?

**Comment by simonbengtsson** [comment]
Agreed! However, since the html is already parsed before the `didParseCell` hook is called, do you still have a use case for modifying the DOM in the `didParseCell` hook?

**Comment by bes1002t** [comment]
Depends on what "parsed" means in the context of the plugin. For me "parsed" just means the plugins is holding a DOM which is later used to create the PDF. But if "parsed" means the PDF is already created, then it would not make sense to change the DOM anymore.

Anyways, I don't think it's important which hook we're talking about, I would simply create a deepcopy of the DOM as soon as autotable could access it. 

If I understand the code correctly, I would simply add this code
``` let newArgs = Object.assign({}, args)````
at this location:
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/182c4005bc87db53f4773ba743eab8e72b9e50c2/src/applyPlugin.ts#L13

**Comment by simonbengtsson** [comment]
Parsing in the context of this plugin means iterating over the html table and extracting the texts that should be displayed in the pdf. This means that when the didParseCell method is called the plugin will never access the dom element again.

**Comment by bes1002t** [comment]
Ah I see, then maybe an additional hook "didLoadCell" would be cool. In this hook it should be possible to access the DOM / JSON which is used to extract the text that should be displayed.

Thanks for your clarification. :)

**Comment by simonbengtsson** [comment]
That would work! The library can take a table element however as well so maybe you can try something like this as well?

```
const cloned = document.querySelector('#table').cloneNode(true)
element.rows[0].cells[0].textContent = 'modified'
doc.autoTable(cloned)
```

**Comment by bes1002t** [comment]
@simonbengtsson mh unfortunately autoTable can not handle the cloned node. I tried it without a modification to verify that it works, but the PDF contains only white pages.

```
const cloned = document.querySelector('#my_id table')
doc.autoTable(cloned)
```

**Comment by simonbengtsson** [comment]
I looked at the docs now and it should have been:

        const cloned = document.querySelector('#table').cloneNode(true)
        doc.autoTable({ html: cloned })

**Comment by bes1002t** [comment]
Ah, my bad!
I already tried this version and it did not work. But I also passed "useCss: true", so it produced an error message and I thougt that it does not work. 

Thanks this should fix it (but without the css applied) :P

**Comment by simonbengtsson** [comment]
Fixed the crash now I think 👌 Unfortunately you still won't be getting the styles since `window.getComputedStyle` is used to parse the css which does not work on cloned elements. I guess you could temporarily add the cloned element to the dom off screen somewhere and then remove it once the autoTable method has been called.

**Comment by bes1002t** [comment]
@simonbengtsson  thanks for fixing this that fast :)
the css is not that important to me, I was able to center the cells by using halign. So some kind of workaround but it fits my needs.

I guess we could close this now.
