### ISSUE TITLE
Bug cells with index 0 style can't be customized in willDrawCell

### ISSUE THREAD

**Issue by castrix** [simonbengtsson/jsPDF-AutoTable#777]
so I'm trying to style the cell to give top border based on some condition, I set the border/line color default to white, and when the cell data passed the condition, it will chang ethe border color

```
willDrawCell: (data: any) => { .....

if (data.row.cells[6].text[0].slice(0, 2) === "1/") {
        for (let i = 0; i < 11; i++) {
          data.row.cells[i].styles = {
            ...data.row.cells[i].styles,
            lineColor: "#e0e0e0",
            lineWidth: { top: 0.2, right: 0, bottom: 0, left: 0 },
          };
        }
      }
...}
```
I'm expecting the border start from cell 0 to the end cell, but this is the result I got 
![1](https://user-images.githubusercontent.com/17196308/110425356-cddb7380-80d6-11eb-9342-9695f6456b9e.jpg)

The border in cell with index 0 is missing, I tried other styling as well (such as textColor) and it didn't work

**Comment by simonbengtsson** [comment]
In the willDrawCell styles have already been parsed. Use didParseCell instead
