### ISSUE TITLE
You recently removed the `width` property from table, but did it as a patch level change

### ISSUE THREAD

**Issue by krainboltgreene** [simonbengtsson/jsPDF-AutoTable#779]
This broke my code because I expected to not encounter any public api changes in a patch level release.

**Comment by simonbengtsson** [comment]
I don't think any documented public api changes have been done. If so please point me to that code change and I'll revert it.

**Comment by krainboltgreene** [comment]
https://github.com/simonbengtsson/jsPDF-AutoTable/commit/1a4dea16f5a1bdaf4ca9467533d751924c90c176#diff-41b76dc43070308a3e3f270eb861b65259fd377aef32fe30e32ef61b07d086f6L77

**Comment by simonbengtsson** [comment]
Got it. This is a non-documented API and does not come with a guarantee of not changing. I don't expect many changes going forward however.
