### ISSUE TITLE
Prevent repeated header row on multiple pages

### ISSUE THREAD

**Issue by emiller12** [simonbengtsson/jsPDF-AutoTable#78]
Hi Simon,

Thanks for the great plugin.

I am working on a project where I need to display multiple tables (as many as 10), one after the other in a single PDF. Some of the tables get quite long, so a single table may span multiple pages.

I have noticed that when a table spans multiple pages, the default behavior is to repeat the table header at the start of each new page, as long as the same table is continuing into it.

Is there a way to turn this feature "off", or prevent the repeated header row from being drawn?

When a table spans into a new page, I would like my table rows to just continue on from where they left off, without a repeat of the table header being drawn.

I hope this makes sense. Please let me know if there is a way I can configure this.

Regards,
Elliott

**Comment by simonbengtsson** [comment]
Hi! This use case was the reason I created the plugin in the first place. However, each table could span several pages so I needed a header on each. Having a header only on the first table makes a lot of sense to, but it is not directly supported right now. Will make it a top priority to add in the next release.

For now, you can use the `drawHeaderRow` hook like below. See it used in this [codepen](http://codepen.io/someatoms/pen/epebqj)

    doc.autoTable(data.columns, data.rows, {
      drawHeaderRow: function(row, data) {
        if (data.pageCount > 1) {
          return false;
        }
      }
    });

I would also be interested in improving the design to differentiate between a new table and a continuation of a table while displaying headers on all pages. Let me know if you have any ideas.

**Comment by emiller12** [comment]
Thanks Simon. The drawHeaderRow hook is a good solution. It worked a treat.

I guess it would be handy to be able to differentiate between the two, as then you would be able to style them slightly differently so it is obvious that it isn't a new table starting at the top of the page.

**Comment by simonbengtsson** [comment]
Great! I close this issue for now, but will keep it in mind for the future!

**Comment by leefsmp** [comment]
`drawHeaderRow` has been removed in v 3.0 but it's not obvious to me how to migrate the following code with the new hook API: 

    doc.autoTable(data.columns, data.rows, {
        drawHeaderRow: function(row, data) {
          if (data.pageCount > 1) {
            return false;
         }
      }
   });

Some light on that would be greatly appreciated. Thanks!

**Comment by jovylouverzano** [comment]
> Hi! This use case was the reason I created the plugin in the first place. However, each table could span several pages so I needed a header on each. Having a header only on the first page makes a lot of sense too, but it is not directly supported right now. Will make it a top priority to add in the next release.
> 
> For now, you can use the `drawHeaderRow` hook like below. See it used in this [codepen](http://codepen.io/someatoms/pen/epebqj)
> 
> ```
> doc.autoTable(data.columns, data.rows, {
>   drawHeaderRow: function(row, data) {
>     if (data.pageCount > 1) {
>       return false;
>     }
>   }
> });
> ```
> 
> I would also be interested in improving the design to differentiate between a new table and a continuation of a table while displaying headers on all pages. Let me know if you have any ideas.

hu 

> Hi! This use case was the reason I created the plugin in the first place. However, each table could span several pages so I needed a header on each. Having a header only on the first page makes a lot of sense too, but it is not directly supported right now. Will make it a top priority to add in the next release.
> 
> For now, you can use the `drawHeaderRow` hook like below. See it used in this [codepen](http://codepen.io/someatoms/pen/epebqj)
> 
> ```
> doc.autoTable(data.columns, data.rows, {
>   drawHeaderRow: function(row, data) {
>     if (data.pageCount > 1) {
>       return false;
>     }
>   }
> });
> ```
> 
> I would also be interested in improving the design to differentiate between a new table and a continuation of a table while displaying headers on all pages. Let me know if you have any ideas.

hi simon, the pen is not working anymore.. will you please update it? thank you sir

**Comment by bymi15** [comment]
Hi,
Try using the `showHead` prop like this:
```
doc.autoTable(data.columns, data.rows, {
  showHead: "firstPage"
});
```

**Comment by AnnaVidal** [comment]
> Hi, Try using the `showHead` prop like this:
> 
> ```
> doc.autoTable(data.columns, data.rows, {
>   showHead: "firstPage"
> });
> ```

it works, thanks a lot!!!
