### ISSUE TITLE
Question: How to right align individual column headers?

### ISSUE THREAD

**Issue by Mashiane** [simonbengtsson/jsPDF-AutoTable#785]
Hi there.

I am able to apply a column style so that the columns of choice are right aligned. Below is my result.

How do I ensure that the headers are also right aligned, only for the columns I need?

1. My columns are added by using the {dataKey:"", "header":""} objects for each column.

Can one just add a "style" object for each header when using that type of object?

<img width="539" alt="RightAlignHeader" src="https://user-images.githubusercontent.com/5799306/112720212-b0dfd680-8f05-11eb-9f2a-dd466fa0cab5.png">

Thanks.

**Comment by thebestlucc** [comment]
i'm having the same problem.
