### ISSUE TITLE
How to add table header on manually added page

### ISSUE THREAD

**Issue by darshanrampatel** [simonbengtsson/jsPDF-AutoTable#797]
Hi there,

I am trying to manually add a new page based on certain conditions in my code, but I am not able to add the table header on subsequent pages.

Am I missing a function that I should be using?

Here is a sample of a PDF - I would like to show the table header on every page.

I have tried setting `showHead` but it doesn't seem to have any impact.

Is there a way I could explicitly call the autotable `addPage()` function from [here](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/7779385c85255f61d02f4a5ad9fccb1e8f3664c0/src/tableDrawer.ts#L440)?

```html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <title>Simple example</title>
  </head>

  <body>
    <button onclick="generate()">Generate pdf</button>

    <script src="jspdf.umd.min.js"></script>
    <script src="https://unpkg.com/jspdf-autotable"></script>

    <script>
      function generate() {
        var doc = new jspdf.jsPDF()
        const margin = 6;
        const pageHeight = 215.9;

        doc.autoTable( {
          startY: 10,
          margin: { horizontal: margin },
          theme: 'grid',
          columnStyles: { 4: { cellWidth: 80 } },
          head: [ [ '1', '2', '3', '4', '5', '6', '7', '8' ] ],
          showHead: 'everyPage',
          body: [
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ],
            [ 'Sample', 'Row', 'to', 'highlight', '', 'the', 'cell', 'bug' ]
          ],
          willDrawCell: function ( data ) {
            if ( data.column.dataKey === 0 && data.cell.section === 'body' ) {
              // Manually calculate if the new row height will be too long to fit on the current page
              const height = 40;
              if ( height + data.cursor.y > ( pageHeight - ( margin * 3 ) ) ) {
                // Add page and reset cursor
                data.doc.addPage();
                data.cursor.y = margin * 2;
                data.cell.y = margin * 2;
                data.cell.styles.fillColor = '#FFFFFF'; // No effect
                data.cell.styles.textColor = 255 // No effect
              }
              data.row.height = height
              Object.values( data.row.cells ).forEach( e => e.height = height ); // Update all cells to predicted nested table height
            }
          }

        } )

        doc.save( 'test.pdf' );
      }
    </script>
  </body>

</html>
```
[test.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/6404717/test.pdf)

Note: I am also running into issue #774, but that's not the issue here.

**Comment by darshanrampatel** [comment]
Looks like this maybe was possible [in the past](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/386#issuecomment-416998726_), by using `autoTableAddPage()` but this just calls `doc.addPage()` under the hood now so doesn't work.

**Comment by darshanrampatel** [comment]
I have worked around this by instead of manually adding a new page, just adjusting the `cursor.y` within the `didDrawCell` hook so that the next row would force a new page. This also resolves the issue with #774 I was seeing.

**Comment by hraftery** [comment]
> I have worked around this by instead of manually adding a new page, just adjusting the `cursor.y` within the `didDrawCell` hook so that the next row would force a new page. This also resolves the issue with [#774](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/774) I was seeing.

Oh my, this looks to still be the way in 2026. If you want to insert a page break, I found the following effective:

```
didDrawCell: (data) => {
  if(data.row.index == maxRowsPerPage) data.cursor!.y = pdf.internal.pageSize.getHeight();
}
```

where `maxRowsPerPage` is the, possibly dynamic, number of rows before inserting a page break. Setting the cursor to the page height seems a crude but effective way to get a new page to start.

**Comment by simonbengtsson** [comment]
I believe that if a page is added in a autotable hook using the default jspdf addPage it should automatically add a header etc?

**Comment by hraftery** [comment]
> I believe that if a page is added in a autotable hook using the default jspdf addPage it should automatically add a header etc?

Not in my case, which I think is pretty standard:

- jsPDF 4.2.1, autotable 5.0.7.
- `head` and `body` pre-calculated. 17 columns, 17 rows (coincidentally).
- Renders nicely by default, with rows split over pages with the header row repeated on each page.

My `autoTable` call looks like this:

```
const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
const pageHeight = pdf.internal.pageSize.getHeight();

autoTable(pdf, {
  head,
  body,
  startY: margin,
  margin: margin,
  styles: { fontSize: 8, cellPadding: 2 },
  headStyles: { fillColor: [83, 74, 183] },
  didDrawCell: (data) =>
  {
    //Check if it's time to start a new page
    if(data.column.index === data.table.columns.length - 1)
    {
      if(myLogicForBreakingThePageEarly())
      {
        data.cursor!.y = pageHeight;
        //pdf.addPage();
      }
    }
  }
});
```

Which works nicely - if the logic fires, the current page is ended, and the table starts again at the top of the next page with a new header.

If I use `pdf.addPage()` instead, not only is the header not repeated, the table starts part way down the next page.

**Comment by simonbengtsson** [comment]
Weird! If you create a new issue with an example how to reproduce I'll take a look.
