### ISSUE TITLE
Exclude a column

### ISSUE THREAD

**Issue by veeruborra** [simonbengtsson/jsPDF-AutoTable#80]
is there any option to exclude a column in a table.columns like wdit,delete..

**Comment by simonbengtsson** [comment]
One way would simply loop over the dataand remove the column before calling the plugin. Another way would be to use the hooks to avoid drawing that column. Checkout the row and colspan example for hints how this could be done.  If you want help with a specific problem, feel free posting more information.

**Comment by veeruborra** [comment]
Thank you.My problem cleared..

**Comment by simonbengtsson** [comment]
Good to hear!

**Comment by AbiraamInnive** [comment]
How to omit columns which has no data,below is my code  

var columns =[
                    "category","name","Financialyear","FinancialYear","MonthNo",'Open SO Value','value',
            //     "Current Level","percentage","trendValue","metric_prefix","metric_suffix","Inventory","InventoryQuantity",
            // "Age 30","Age 60","Age 90","Age 120","Age 150","Age 180",">Age 180","suffix","trendValue","Not Due","OverDue"
             ]
                console.log(columns,"dsgfuhsd")

                var rows = [];
                for (var i = 0; i < data.length; i++) {
                    rows.push([ data[i].category, data[i].Financialyear,data[i].Financialyear,data[i].MonthNo,
                        data[i]['Open SO Value'],data[i].value]);
                }
                 var doc = new jsPDF();
                doc.autoTable(columns, rows, {
                    margin: {top: 20},
                    
                });
<img width="612" alt="img_20221221(2)" src="https://user-images.githubusercontent.com/109072164/208824092-8d16b1af-0a8f-4da0-81c6-b69e2b5ef2fe.png">

                doc.save('Report.pdf');
