### ISSUE TITLE
Id column to be added on each subsequent page as well when using horizontalPageBreak

### ISSUE THREAD

**Issue by singhinderpal** [simonbengtsson/jsPDF-AutoTable#800]
Hello team,

We have been using DevExtreme's Angular DataGrid which a huge data set (min 17 columns).
The datagrid allows to add custom jsPDF-AutoTable Options like below... 

`
      autoTableOptions: {
        headStyles: {
          fillColor: '#EDEFF0',
          textColor: '#3D4551',
        },
        theme: 'grid', // striped | grid | plain
        tableLineWidth: 0,
        horizontalPageBreak: true,
        styles: {
          cellWidth: 'wrap',
        }
      }
`

I used `horizontalPageBreak: true` here so that table can break and extend to multiple pages. It all works good but makes it real hard for a user to match pages with a lack of a common factor between them.

It would be much much better if we can add some column, say Id, to all subsequent pages created using `horizontalPageBreak: true`.

Current Behaviour for 15 Columns:
Page 1: Col 1 (id), 2-9
Page 2: Col 10 - 15

Required Behaviour for 15 Columns:
Page 1: Col 1 (id), Col 2-9
Page 2: Col 1 (id), Col 10 - 15

Please help in achieving this.

**Comment by simonbengtsson** [comment]
Sounds like a great suggestion! I would be happy to review a merge request attempting this,

**Comment by singhinderpal** [comment]
Hi @simonbengtsson , I had submitted a PR #801 and I am waiting for you to review it. We need to use it in our project so It would be much help if you can review and see if it is worthy to merge.

**Comment by singhinderpal** [comment]
HI @simonbengtsson ,

I see the PR #801 is now merged. Is it released and ready to reference in our own projects?

I currently have 3.5.14 referenced in my project.

**Comment by simonbengtsson** [comment]
Not merged yet but you can point to the specific commit with npm in the meantime.

**Comment by singhinderpal** [comment]
I referenced `"jspdf-autotable": "git://github.com/simonbengtsson/jsPDF-AutoTable.git#599ab9d",`.
I tried the first 7 chars, and complete hash in the above reference.
I then navigated to `node_modules/jspdf-autotable` and following is observed:

- README.md is updated to the latest.
-`dist/jspdf.plugin.autotable.js` doesn't contain the latest code.

![image](https://user-images.githubusercontent.com/62807061/118397634-a2df4400-b672-11eb-94e6-cb200122a4a5.png)

**Comment by singhinderpal** [comment]
Hi @simonbengtsson 

I updated the dist in my forked repo and started integrating in my project.
Upon few rounds of usage and testing, I found a small bug which cause `horizontalPageBreakRepeat: 0` to get ignored in the `if` condition. The fixed has been pushed and PR is raised alongside to fix it in the main repo of the project.
