### ISSUE TITLE
listing all options within select (instead of just what's selected)

### ISSUE THREAD

**Issue by jacobSpitzer** [simonbengtsson/jsPDF-AutoTable#806]
Hi,
After a great appreciation and thanks for the wonderful plugin i'm using ...
I just found a small bug,
if the table contains a select tag with dropdown options, then the plugin will show all options on the generated PDF, instead of showing just the selected option.
I'm trying to find a workaround.

**Comment by jacobSpitzer** [comment]
i just added one line of code inside the plugin as followed: 
in the function "parseContentCell" i added:
`    if (cell.getElementsByTagName('select').length > 0) { return cell.getElementsByTagName('select')[0].options[cell.getElementsByTagName('select')[0].selectedIndex].text}`

**Comment by simonbengtsson** [comment]
You can use the `didParseCell` hook to parse the html in a custom way as as well if you want to avoid changing the library code.
