### ISSUE TITLE
Multiple rows on the header

### ISSUE THREAD

**Issue by tonytomov** [simonbengtsson/jsPDF-AutoTable#81]
Hello,

Unfortunately I can not find away to add  more than one row in the header of the table.
If the feature is not present it will be great to have this again with rowspan and colspan support.

I apologize if this feature is available.

Kind Regards

**Comment by simonbengtsson** [comment]
Linebreak can be done with the style overflow:linebreak; and multiple headers can be manually added with the help of hooks. 

There is an example showing how you can accomplish rowspan and colspan.

If you need more assistance, can you post an image showing a little bit more of  what you want to do?

All good, Simon

**Comment by tonytomov** [comment]
Hello,

Thank you very much for the suggestion. 
While try to do what you suggest I came across a small problem.
Actually I use the drawHeaderRow to create additional row in the header.
To this event are passed two parameters row and data.
The problem is that in the row parameter the x, y and width properties of certain cell are not set yet. They are set after printRow function.

These properties are important to what I try to do.
I suggest you to either replace the table.headerRow with table.columns in the first parameter or add addional parameter something like this:
```...
        if (settings.drawHeaderRow(table.headerRow, hooksData({row: table.headerRow}), table.columns ) !== false) {
            printRow(table.headerRow, settings.drawHeaderCell);
        }
...
```

**Comment by simonbengtsson** [comment]
The data option actually contains the whole table object so you can access the columns by doing something like this `data.table.columns`. Or did I misunderstand your suggestion?

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to reopen if you have further questions or issues.
