### ISSUE TITLE
Is this a bug? ModifyRowToFit 

### ISSUE THREAD

**Issue by Never7Dice** [simonbengtsson/jsPDF-AutoTable#810]
I think this line should be outside of `if`, otherwise when the condition is false we get 2 cells with minHeight resulting in twice the space used.
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/507e13f7a59711e69ac1d765bff1bc607d37189f/src/tableDrawer.ts#L202

When I was modifying library fork for my custom logic this line was the reason for some unexpected behavior and I think it's a bug.

If it's intended could you please explain why is it inside `if`?

**Comment by simonbengtsson** [comment]
I think it should be inside of the if. The remainder cell is what is left of a cell after it is split if it didn't fit on the first page. Not entirely sure what you mean with twice the space used. If the cell does not fit on the current page it will get the height of the remaining space and the remainderCell that will be drawn on the next page will get the original cell height with the drawn cell height subsctracted.

**Comment by Never7Dice** [comment]
So, by twice the space used I meant that if you set minCellHeight to 50 for example, in the worst case scenario you'll have height of 99.99 because of this code.

>  will get the original cell height with the drawn cell height subsctracted
No it would not. Imagine if you have 2 columns in the row and only 50 remainingPageSpace. The 1st column cell has a text that requires height of 60. 2nd column has text that requires only height of 10, but has minCellHeight set to 40.

Because the 2nd cell didn't meet the `if` condition this minCellHeight will be used again on next page, so you'll get the total height on 2 pages of 50+40, with 30 of them not having any content at all, just white space.
