### ISSUE TITLE
last column is missing when horizontalPageBreakRepeat is set 

### ISSUE THREAD

**Issue by AlanHilal** [simonbengtsson/jsPDF-AutoTable#811]
Hi,
I have table, with both `horizontalPageBreak` and `horizontalPageBreakRepeat` set to `true`
I also gave a width to one of my columns but that makes the last column to not be in the pdf.
It works when I remove column width.

```
doc.autoTable({
    body: rows,
    columns: columns,
    horizontalPageBreak: true,
    horizontalPageBreakRepeat: 'id',
    columnStyles: {
        name: {
            cellWidth: 100,
        },
    },
});
```

**Comment by simonbengtsson** [comment]
Sounds like a bug. Can you provide a minimal runnable example that highlights the issue?

**Comment by AlanHilal** [comment]
I was able to reproduce it without `cellWidth` too
https://jsfiddle.net/AlanDzday/nwxt5gyv/33/

**Comment by NitishaSrivastav** [comment]
@simonbengtsson  and @AlanHilal in the example that you have mentioned is not printing the third column "Country". The id column is taking place of third column in page 2. Please provide the solution ASAP.

**Comment by e-medeiros** [comment]
@simonbengtsson
I tried something similar , may its belongs here. In my auto-table I can't even see my ID collumn.
https://jsfiddle.net/manelvm/4o53gsj9/20/
