### ISSUE TITLE
Question: How to render raw nested Json data into a table correctly

### ISSUE THREAD

**Issue by RipleWare** [simonbengtsson/jsPDF-AutoTable#815]
I'm trying to render a table using raw Json data because I need to split the data into multiple PDFs per Site.

My data looks something like below. Basically, each Site can contain multiple Services, each Service can contain multiple Clients and each Client can contain multiple Appointments. The table can also contain multiple Sites.
```
Site: [
    Name: SiteA,
    Services: [
        [
            Name: ServiceA
            Clients: [
                [
                    Name: ClientA
                    Appointments: [
                        [
                            Name: Appt1
                        ],
                        [
                            Name: Appt2
                        ]
                    ]
                ],
                [
                    Name: ClientB
                    Appointments: [
                        [
                            Name: Appt3
                        ],
                        [
                            Name: Appt4
                        ]
                    ]
                ]  
            ]
        ],
        [
            Name: ServiceB
            Clients: [
                Appointments: [...]
            ]
        ]
    ]
]
```
I can table the data in HTML fine, but my problem is that I need to create a separate PDF for each Site within the table, so I have gone down the path of building the table manually using raw Json data.

I have built the table and defined all columns, however, I am unsure how to build the body rows correctly so they become nested. I am finding that if I build the rows with just the specific column details, I am getting blank cells everywhere.

```
let bodyRows = [];
bodyRows.push( {site: { content: site.Name, rowSpan: site.TotalAppointments} } );

site.Services.forEach( ( service ) => {

	bodyRows.push( {service: { content: service.Name, rowSpan: service.TotalAppointments } } );

	service.Clients.forEach( ( client ) => {

		bodyRows.push( {client: { content: client.Name, rowSpan: client.TotalAppointments } } );

		client.Appointments.forEach( ( appt ) => {

			bodyRows.push( { name: appt.Name } );

		})

	})
})
```

Can you tell me how to nest the row data correctly, or build the table manually.

Thanks

**Comment by RipleWare** [comment]
This can be closed. I got around it by adding a `v-for` on the `<body>` so I could add an `id` element. That way I could split out all `id`s to a separate PDF.

**Comment by roushanara2019** [comment]
Hi Ripleware,
Could you please share the code because i'm also having the same issue and unable to resolve it.

Thanks...

**Comment by roushanara2019** [comment]
> This can be closed. I got around it by adding a `v-for` on the `<body>` so I could add an `id` element. That way I could split out all `id`s to a separate PDF.

Hi Ripleware,
could you please share me the code because i'm also having the same problem.

Thanks...
