### ISSUE TITLE
Last column is removed if horizontalPageBreakRepeat  is set

### ISSUE THREAD

**Issue by NitishaSrivastav** [simonbengtsson/jsPDF-AutoTable#816]
My table contains 38 columns and  few of the columns are hidden in the pdf format

**Comment by simonbengtsson** [comment]
You mean that they did not fit on the page?

**Comment by NitishaSrivastav** [comment]
I want my first column to be first column of every page if my data contains more column and it does not fit on one page so i am using  horizontalPageBreak: true,horizontalPageBreakRepeat: 1, these two properties and The problem that I am facing is when the page break is placing rest of the columns onto another page the first column of the page break is replaced by my column present at 1st index. this is happening  from page 2.

**Comment by simonbengtsson** [comment]
Sounds like a bug indeed. Could you share a screenshot and some minimal code of how it can be reproduced?

**Comment by NitishaSrivastav** [comment]
In my case head array length is 37 so that page break is applied.
autoTable(doc, {
      head: ["1","2" ],
      body:[[ "abc","def"], ["abc","def" ] , ["abc","def" ],["abc","def" ]],
      useCss: true,
      margin: { top: 35, right: 20, bottom: 30, left: 10 },
      horizontalPageBreak: true,
      horizontalPageBreakRepeat: 1,
      headStyles: {
        fillColor: '#dbdbdb',
        textColor: '#0a0a0a',
        fontStyle: 'bold',
        lineWidth: 0,
      },
      didParseCell: function (data) {
        var dataInCell = data.cell.text[0];
        var rowEligibleForStyle = data.row.cells[0].raw
        if (dataInCell == '×Parent' || dataInCell == '×Child' || dataInCell == '') {
          data.cell.text[0] = ''
        }
        if (data.section == 'body') {
          if (rowEligibleForStyle === ForeCastingAppConstants.Total || rowEligibleForStyle === ForeCastingAppConstants.TotalRevenue || rowEligibleForStyle === ForeCastingAppConstants.TotalParentCOGS || rowEligibleForStyle === ForeCastingAppConstants.TotalParentExpense || rowEligibleForStyle === ForeCastingAppConstants.TotalExpense || rowEligibleForStyle === ForeCastingAppConstants.CasflowParentTitle || rowEligibleForStyle === ForeCastingAppConstants.CasflowTitle || rowEligibleForStyle === ForeCastingAppConstants.EBITDA || rowEligibleForStyle === ForeCastingAppConstants.ComparisonPeriod) {
            data.cell.styles.fillColor = [219, 219, 219];
            data.cell.styles.textColor = [0, 0, 0];
            data.cell.styles.fontStyle = 'bold';


          }
          else {
            data.cell.styles.cellPadding = 10;

          }
          if (/\d/.test(data.cell.text[0])) {
            data.cell.styles.halign = 'right';
            data.cell.styles.cellPadding = { top: 10, right: 10, bottom: 10, left: 0 };
          }
        }
      },
      didDrawCell: function (data) {
        if (data.section == 'body') {
          data.row.cells[0].text[0] = '';
        }
      }
    });

**Comment by prpateldev** [comment]
Hi @NitishaSrivastav I think it takes index of col so if you want to print very first col on each page set horizontalPageBreakRepeat=[0]. it should help if not send me config to regenerate the issue I will try to fix it.

**Comment by NitishaSrivastav** [comment]
Hi @prpateldev @simonbengtsson there was an issue with setting horizontalPageBreakRepeat=0. The 0th index column was not getting printed on every page so I have inserted one blank column at 0th index and shifted all my array elemnts by 1 .So I am using horizontalPageBreakRepeat=1 for every page break.Also I don't think that horizontalPageBreakRepeat=0 this property is going to make any difference because we can set any column to repeat on every page break.
