### ISSUE TITLE
Overflow Linebreak inst working on this part of my code

### ISSUE THREAD

**Issue by ElberSousa** [simonbengtsson/jsPDF-AutoTable#817]
I have other text bigger than this one and the text is working normaly, but this one isnt working.

![image](https://user-images.githubusercontent.com/77744003/129358787-57761f98-9af6-4104-8919-89f0e994d28b.png)

![image](https://user-images.githubusercontent.com/77744003/129358849-db82f18e-3056-4a3b-bcd2-039a111979a0.png)

![image](https://user-images.githubusercontent.com/77744003/129359086-166e5ec9-3f1b-4483-ba87-88c9e54f934b.png)

![image](https://user-images.githubusercontent.com/77744003/129358934-79d9c930-f8ab-427b-9bd4-d4315b4df8fd.png)

**Comment by simonbengtsson** [comment]
Interesting! Could include minimal example code highlighting the issue?
