### ISSUE TITLE
Bug: horizontalPageBreakRepeat: 0 not working (fix included)

### ISSUE THREAD

**Issue by knodlagc** [simonbengtsson/jsPDF-AutoTable#818]
When I use `horizontalPageBreakRepeat: 0` this is not working, because `0 == false`, so the condition in dist/jspdf.plugin.autotable.js fails:
![Bildschirmfoto von 2021-08-18 18-12-39](https://user-images.githubusercontent.com/30718587/129933817-6a1f78ee-e5aa-49f6-91a3-3bead39b0a6a.png)

This bug can be fixed for example like so:
![Bildschirmfoto von 2021-08-18 18-18-26](https://user-images.githubusercontent.com/30718587/129934548-a994d6d2-1f61-4093-9a39-17ec38cb42dc.png)

As I am working on a urgent project, I'd highly appreciate a very quick fix :)

**Comment by simonbengtsson** [comment]
Looks reasonable! If you send a merge request I'll merge right away. I suggest using `!= null` to cover both undefined and null.

**Comment by simonbengtsson** [comment]
Fix released
