### ISSUE TITLE
HorizontalPageBreak  sheets are added to the end of the document

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [simonbengtsson/jsPDF-AutoTable#820]
Hi, when I use horizontalPageBreak the table continues to another page, but these sheets are added to the end of the document. Why?
this is how it looks schematically, the continuation of page 1 went to page 3
How to make the continuation of page 1 immediately after the first page?

sheet1
column1,column2,column3...column15

sheet2
column1,column2,column3...column15

sheet3 -> **continuation** sheet1  ????
column15,column16,column17

sheet4 -> **continuation** sheet2  ????
column15,column16,column17

jsPDF Version 2.3.1 Built on 2021-03-08T15:44:11.672Z
jsPDF AutoTable plugin v3.5.15

**Comment by simonbengtsson** [comment]
Could you add som minimal sample code that highlights the issue?

**Comment by aleksandrmozgovoi** [comment]
` var doc = new jsPDF('p', 'mm', 'a4');
            
            doc.addFont("js/PTSans.ttf", "PTSans", "normal");
            doc.setFont("PTSans"); // set font

            doc.autoTable({
                didDrawPage: function (data) {
                    doc.addImage(imgLogo, 'JPEG', data.settings.margin.left, 5, 20, 18);
                    doc.setFontSize(10);

                    doc.text($('#textAreaCenter').val(), data.settings.margin.left + 50, 8);
                    doc.text($('#textAreaRight').val(), data.settings.margin.left + 120, 8);
                },
                
                head: columns,
                headStyles: { fillColor: null, textColor: 20, lineColor: 20, lineWidth: 0.1, halign: 'center', valign: 'middle' },

                horizontalPageBreak: true,
                body: rows,
                theme: 'grid',
                tableWidth: 'wrap ',
                
                styles: { font: 'PTSans-Regular', fontStyle: 'normal' },
                margin: { top: 24, bottom: 10 },

            });`

**Comment by aleksandrmozgovoi** [comment]
[download.pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/7082297/download.pdf)
result

**Comment by simonbengtsson** [comment]
Great! Could you minimize the the example further by removing irrelevant options etc? Would also be great if you included the data used in the example. This would increase the chances of someone will look into this.

**Comment by zhao-weiqi** [comment]
same issue for me
