### ISSUE TITLE
setting rawRow Data

### ISSUE THREAD

**Issue by antoniochaul** [simonbengtsson/jsPDF-AutoTable#83]
Sir, at line 345:
`var row = new Row(rawRow);`

the rawRow is passed as parameter on the constructor, however at the Row constructor:
```javascript
class Row {
    constructor() {
        this.raw = {};
```

it's not set.
I noticed beacuse I needed the data on a hook, it's simple fix:
```javascript
class Row {
    constructor(raw) {
        this.raw = raw || {};
```

**Comment by simonbengtsson** [comment]
Fixed it now in version 2.0.14. Thanks!
