### ISSUE TITLE
How to get dynamically generated table's last row's x,y position?

### ISSUE THREAD

**Issue by z41dth3c0d3r** [simonbengtsson/jsPDF-AutoTable#831]
![2021_10_14_0ol_Kleki](https://user-images.githubusercontent.com/80527688/137288134-40958110-fad0-4d2c-8e99-8499ff598606.png)

**Comment by SkullMasher** [comment]
Hi, isn't it suppose to be the goal of "lastAutoTable.finalY" ?

eg: doc.text('GROSS TOTAL', 42, doc.lastAutoTable.finalY + 20)

Cheers.

**Comment by navinrangar** [comment]
> Hi, isn't it suppose to be the goal of "lastAutoTable.finalY" ?
> 
> eg: doc.text('GROSS TOTAL', 42, doc.lastAutoTable.finalY + 20)
> 
> Cheers.

thanks. it helped
