### ISSUE TITLE
Infinite loop when using horizontalPageBreakRepeat

### ISSUE THREAD

**Issue by rarysson** [simonbengtsson/jsPDF-AutoTable#839]
Currently if you use try to use horizontalPageBreakRepeat option with a very long column, it will cause an infinite loop and will break the user browser.

The MCVE: https://jsfiddle.net/scorpion147/oenmqjy7/5/

I don't know exactly what is causing the issue, but I know it's something on the loop inside the function `calculateAllColumnsCanFitInPage` located on `tablePrinter.ts`

**Comment by iiminov** [comment]
I managed to get around this issue by setting column style by limiting the width.

For example:
``
clumnStyles: { super_long_string_of_text: { cellWidth: 100 } }
``

**Comment by mmghv** [comment]
Released in [v3.7.0](https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.7.0)
