### ISSUE TITLE
inputData.forEach is not a function error when using AutoTable jsPDF plugin

### ISSUE THREAD

**Issue by DelRes** [simonbengtsson/jsPDF-AutoTable#84]
Hi, 
I am very new to jsPDF. I want to print a table using jsPDF and am using the AutoTable jsPDF plugin.
But I am getting the error "inputData.forEach is not a function" 
Can you please help and direct as to what can be the reason for this ?

I have declared the following files in my html file:

               <script src="utils/html2canvas.js"></script>
		<script src="utils/jspdf.debug.js"></script>
		<script src="utils/forEach.js"></script>
		<script src="utils/jspdf.min.js"></script>
		<script src="utils/jspdf.plugin.autotable.js"></script>

The "forEach.js" file that I have used here is the code that I had referred from a post you had mentioned in this link:
https://github.com/simonbengtsson/jsPDF-AutoTable/issues/18

and in the main file behing the download PDF button, I have written the following code

                var aResultData = oResultTableModel.getData();
		var aResultColumns = [{title: "Job Code", key: "jobCode"},
		                      {title: "Job Title", key: "jobTitle"}, 
		                      {title: "Job Family", key: "jobFamily"}, 
		                      {title: "Career Track", key: "careerTrack"},
		                      {title: "Level", key: "jobLevel"},
		                      {title: "Location", key: "location"}, 
		                      {title: "Job Type", key: "jobType"}];
				
		var pdfDoc = new jsPDF('p','pt');
		pdfDoc.autoTable(aResultColumns, aResultData, {});
		pdfDoc.save('Results.pdf');

Can you please help with this issue

**Comment by simonbengtsson** [comment]
I added some input validation now in the latest version of the plugin `2.0.15`. First, try to update and see if you get any other useful error messages. 

Looking at the code you posted the most likely error is probably that `aResultData` is not an array or object. Can you check it's value before sending it to autoTable?

You should also be able to remove most of your scripts. `html2canvas.js` is included in `jspdf.debug.js` and `jspdf.min.js` is the same as `jspdf.debug.js`, but minified. As long as you don't have to support IE8, you should be fine without `forEach.js` as well. 

    <script src="utils/jspdf.min.js"></script>
    <script src="utils/jspdf.plugin.autotable.js"></script>

**Comment by DelRes** [comment]
Thanks a lot!!! You were right. The reason was aResultData was not an array.
