### ISSUE TITLE
Khmer Unicode Issue in PDF Generation

### ISSUE THREAD

**Issue by chhinsras** [simonbengtsson/jsPDF-AutoTable#841]
This may related with issue #391. 

I try exporting from the table or javascript data.

![image](https://user-images.githubusercontent.com/31751665/139818773-e7898458-7dd0-45a7-b6d7-187c061a196b.png)

This is the original data
![image](https://user-images.githubusercontent.com/31751665/139819284-76ec9fe1-c683-4d6c-9c1f-6cf6b34c4565.png)

I also try something like font coversion like this https://jsbin.com/fufafotoji/edit?html,js,output

It does show Khmer text (but not properly character) and lose all English text as shown here
![image](https://user-images.githubusercontent.com/31751665/139819670-305b1fba-ee17-4798-8e69-2216573dea0d.png)

Note: If I use jsPDF generating pdf from html. it works. 

```

` openPDF():void {
    let DATA = document.getElementById('htmlData');
    html2canvas(DATA).then(canvas => {

        let fileWidth = 208;
        let fileHeight = canvas.height * fileWidth / canvas.width;

        const FILEURI = canvas.toDataURL('image/png')
        let PDF = new jsPDF('p', 'mm', 'a4');
        let position = 0;
        PDF.addImage(FILEURI, 'PNG', 0, position, fileWidth, fileHeight)

        PDF.save(`${this.title}.pdf`);

    });
  }`
```

![image](https://user-images.githubusercontent.com/31751665/139820221-f26aba73-cf35-46dd-8409-81d9364b8cd4.png)

**Comment by simonbengtsson** [comment]
Weird! Does it work when you are using the jspdf text method? I assume there is an issue with how you are adding the custom font needed for those characters (see the custom font example)

**Comment by chhinsras** [comment]
@simonbengtsson it shows as below.
![image](https://user-images.githubusercontent.com/31751665/140023687-6b6ba093-d80f-4866-8838-34b6d72021bc.png)

this is original text.

![image](https://user-images.githubusercontent.com/31751665/140023637-6770f608-59e5-4923-bcf9-67cb8024e522.png)

**Comment by simonbengtsson** [comment]
This plugin use the jsPDF text method to write text so you need to get that working first. The issue is likely that you need a custom font for utf-8 characters. There is an example of this in the custom fonts example in this repo.

**Comment by chhinsras** [comment]
could you show me how to

**Comment by SivKay** [comment]
@chhinsras Hello brother, have you found a solution yet?

**Comment by chhinsras** [comment]
> SivKay

I used ngx-export-as for exporting from angular project. Or pupeeteer by nodejs or asp.net

**Comment by SivKay** [comment]
> 

how about react brother? Have you got one?

**Comment by chhinsras** [comment]
> > 
> 
> how about react brother? Have you got one?

https://react-pdf.org/components#document, try this. or you can use broswer print.

**Comment by SivKay** [comment]
Thanks a lot
