### ISSUE TITLE
Dynamic Page Margin Setup 

### ISSUE THREAD

**Issue by chyasif** [simonbengtsson/jsPDF-AutoTable#846]
In addition to Header and Footer , I have custom content to show in first page. But the  second page starts according to margin setup which is making a blank line at the start of second and subsequent page. Is there any way to set the margin for each page? Thanks.

![image](https://user-images.githubusercontent.com/33647101/141647270-25deb0d0-4747-4171-bec6-dd38221add02.png)

**Comment by chyasif** [comment]
Got the solution by setting startY value.

**Comment by JarvisChao** [comment]
@chyasif 
I have the same problem about this issue, setting startY can solve the problem, but when I change tableLineWidth, it is wrong after the first page.

## Page1
![page1](https://user-images.githubusercontent.com/38325453/142181659-3d1a0cad-2e1f-46eb-8a7f-89a81c1f9a30.png)

## Page2
![page2](https://user-images.githubusercontent.com/38325453/142181676-4f445d9a-8732-4e18-a1cc-b963516fe4fe.png)

Is there any solution?
