### ISSUE TITLE
When the table of last page is filled, the footer content will be cut.

### ISSUE THREAD

**Issue by JarvisChao** [simonbengtsson/jsPDF-AutoTable#847]
As the image, footer content is cut. Is there any solution?

![content-cut](https://user-images.githubusercontent.com/38325453/142224748-4d404b30-fe9b-4f77-ae93-08cbf76e6f0e.png)

### My code
<img width="386" alt="code" src="https://user-images.githubusercontent.com/38325453/142225167-85f28ed0-9340-44e0-b5c8-1b308d08017b.png">

**Comment by simonbengtsson** [comment]
Can you post sample code?

**Comment by JarvisChao** [comment]
> 

Hello~
I finally set margin bottom at the table to make sure it has enough space to add my foot content

**Comment by JarvisChao** [comment]
> Can you post sample code?

Hello~
I finally set margin bottom at the table to make sure it has enough space to add my foot content
