### ISSUE TITLE
rowspan/colspan from HTML table

### ISSUE THREAD

**Issue by riwanab** [simonbengtsson/jsPDF-AutoTable#85]
I have an HTML table with rowspan="2" and when the pdf is generated with this table, there is no rowspan="2" anymore :(

**Comment by simonbengtsson** [comment]
When using the autoTableHtmlToJson method only data is converted. All styling has to be done manually.

**Comment by riwanab** [comment]
Ok perfect, I will check this.

Thanks

**Comment by riwanab** [comment]
Ok I have added "rowSpan" attribute for each cell :

var autoTableHtmlToJson = function(table){

        var data = [],
            headers = [],
            header = table.rows[0],
            tableRow,
            rowData,
            i,
            j;

        for( i = 0 ; i < header.cells.length;i++){
            headers.push( (typeof header.cells[i] !== "undefined") ? header.cells[i].textContent : "" );
        }

        for( i = 1 ; i < table.rows.length; i++ ){
            tableRow = table.rows[i];
            rowData = [];

            for( j = 0; j < header.cells.length; j++ ){
                if( typeof tableRow.cells[j] !== "undefined" ){
                    rowData.push({
                        value   : tableRow.cells[j].textContent,
                        rowSpan : tableRow.cells[j].rowSpan
                    });
                }
                else{
                    rowData.push({
                        value   : "",
                        rowSpan : 1
                    });
                }
            }
            data.push( rowData );
        }
        return { columns:headers, data:data, rows:data }
    };

and in drawCell I have :

drawCell: function (cell, data) {

                doc.rect(cell.x, cell.y, data.table.width, cell.height * cell.raw.rowSpan, 'S');
                doc.autoTableText(cell.raw.value, cell.x + cell.width / 2, cell.y + cell.height * cell.raw.rowSpan, {
                    halign: 'center',
                    valign: 'middle'
                });
                return false;
}

I don't understand why its not working and how I will be able to activate the "linebreak" for each cell.

Have you any idea ?

**Comment by prabusendhil** [comment]
Above code was working or not?

**Comment by riwanab** [comment]
No, code was not working.
My solution was to create a table with duplicate cell.
So transform a cell with rowspan = 2 to two cells with no rowspan.

**BEFORE :**
I had a table like :
___________  ______________
| Sentence | rowspan = 2 |
___________                      |
| Sentence |                      |
___________________________    

**NOW:**
I had a table like :
___________  ______________
| Sentence | rowspan = 1 |
___________  _____________ |
| Sentence | rowspan = 1 |
___________________________

**Comment by prabusendhil** [comment]
So you didn't got solution till like u mentioned
