### ISSUE TITLE
How to remove color of the header while using grid theme?

### ISSUE THREAD

**Issue by Parasbuda** [simonbengtsson/jsPDF-AutoTable#851]
Hello i want to get rid of the green color from the header while using grid theme of the library.

**Comment by Marlintt** [comment]
You can change the color by adding headStyles: fillColor see example (darkred in this particular case).

pdf.autoTable({
    html: '#dataAutoTable',
    margin: { left: 10, right: 10, top: 20, bottom: 30 },
    startY: 79,
    theme: 'grid',
    headStyles: {
      fillColor: [139, 0, 0]
    },
    bodyStyles: {
      fontSize: 8
    }
  });

**Comment by Parasbuda** [comment]
im trying to make background of header white by putting fillColor:[255,255,255] but the header is disappearing.
![Capture1](https://user-images.githubusercontent.com/60026182/148010424-74bf8404-0aaf-4a7f-8ec1-be8c10076299.PNG)

**Comment by Parasbuda** [comment]
Basically i dont want any color in header.

**Comment by Marlintt** [comment]
Hi Parasbuda,
When going totally white with background, you'll have to add 
textColor: [0, 0, 0], 
Because the theme color still also is white for the header.
