### ISSUE TITLE
How to Format second Page

### ISSUE THREAD

**Issue by matze1708** [simonbengtsson/jsPDF-AutoTable#854]
Hello Guys,

I am trying to convert a table from Vue to PDF using the following code,
But from the 2nd page I have, my page header in the table, or the table is too high from the 2nd page. What can I use to adjust this?

```
makeShootingBookPDF() {
      var source = this.$refs["myShootingbook"];
      let rows = [];
      let columnHeader = ['Verein', 'Aktivität', 'Stand', 'Standaufsicht', 'Waffe', 'Disziplin', 'Begin', 'Ende', 'bestätigt Verein'];
      let pdfName = 'Schiessbuch von ' + this.$store.state.UserAuth.user.vorname + ' ' + this.$store.state.UserAuth.user.name;
      source.items.forEach(element => {

        var temp = [
          element.name,
          element.aktivitaet,
          element.KurzBez,
          element.Aufsicht,
          element.KurzT,
          element.LangBez,
          new Date(element.beginn.replace(" ", "T")).toLocaleString([], {dateStyle: 'short', timeStyle: 'short'}),
          new Date(element.ende.replace(" ", "T")).toLocaleString([], {dateStyle: 'short', timeStyle: 'short'}),
        ];
        if (element.bestaetigung_holen === 1) {
          temp.push(new Date(element.bestaetigung_holen_datum).toLocaleString([], {
            dateStyle: 'short',
            timeStyle: 'short'
          }))
        } else {
          temp.push('')
        }
        rows.push(temp);
      });

      var doc = new jsPDF();
      doc.autoTable(columnHeader, rows, {

        startY: 40,
        margin: {horizontal: 10},
        styles: {overflow: "linebreak"},
        bodyStyles: {valign: "top"},
        columnStyles: {email: {cellWidth: "wrap"}},
        theme: "striped",
        didDrawPage: function (data) {

          // Header
          doc.setFontSize(20);
          doc.setTextColor(40);
          doc.text(pdfName, data.settings.margin.left, 22);
          doc.setFontSize(12);
          doc.text("Erstellt am " + new Date().toLocaleString() + " von schuetzenbuch.de", data.settings.margin.left, 30);

          // Footer
          var str = "Seite " + doc.internal.getNumberOfPages();

          doc.setFontSize(10);

          var pageSize = doc.internal.pageSize;
          var pageHeight = pageSize.height
              ? pageSize.height
              : pageSize.getHeight();
          doc.text(str, data.settings.margin.left, pageHeight - 10);
        }
      });
      doc.save(pdfName + '.pdf');

    },
```
Thank you

**Comment by Jendorski** [comment]
Any solution to this please?

**Comment by Jendorski** [comment]
`    
    const hderRows = headerRows(excludedFields as Record<string, any>);
  
    doc.setFontSize(18);
    doc.text('Inc.', 5, 10);
    var base64Img: string = base64Image();
    doc.addImage(base64Img, 'png',100, 21, 100, 100, );
  
    doc.setFontSize(12);
    doc.text([`Start Date: ${startTime}`, `End Date: ${endTime}`], 155, 20, {
      align: 'left',
    });
  
    doc.setFontSize(17);
    doc.text('Statement', 170, 10,);
    
    doc.text([
      `Full Name: ${userInfo?.fullName}`,
      `Email: ${userInfo?.email}`, 
      `Opening Balance: $${openBalance}`, 
      `Closing Balance: $${closeBalance}` 
    ], 5, 20);
    doc.setFontSize(11);
    doc.setTextColor(100);
  
    autoTable(doc, {
      pageBreak: 'auto',
      head: hderRows,
      headStyles: {
        font: 'times',
        fontSize: 10,
        cellWidth: 'wrap',
        fillColor: [0,128,0],
        fontStyle: 'bold',
        overflow: 'ellipsize',
      },
      startY: 50,
      margin: {
        left: 2,
        right: 2,
        top: 10,
        bottom: 40
      },
      theme: 'striped',
      tableWidth: 'auto',
      showHead: 'firstPage',
      body: bdyRows,
      tableLineColor: '#c7c7c7',
      tableLineWidth: 0,
      bodyStyles: {
        font: 'times',
        fontSize: 10,
        overflow: 'ellipsize',
      },
      didDrawPage: function (data) {
        try{
  
          // Footer
          var str = "Page " + (doc.internal.pages.length - 1);
  
          doc.setFontSize(10);
  
          var pageSize = doc.internal.pageSize;
          var pageHeight = pageSize.height
              ? pageSize.height
              : pageSize.getHeight();
          doc.text(str, data.settings.margin.left + 182, pageHeight - 8);
  
          var pageSize = doc.internal.pageSize;
          var pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth();
  
          var text = doc.splitTextToSize("Inc. All rights reserved. All deposits are insured by the Deposit Insurance Corporation (DIC). Inc. is licensed by the Bank. Inc trademarks of  LTD. ", pageWidth - 20,);
  
          doc.text(text, data.settings.margin.left + 3, pageHeight - 25);
  
      }catch(err){}
      }
    }); 
`

This is how I got it to work, check for the `didDrawPage`

Good luck.
