### ISSUE TITLE
propose slight change in the documentation

### ISSUE THREAD

**Issue by micksp** [simonbengtsson/jsPDF-AutoTable#857]
I use this in a vite project. it works great locally, but once build the code responds with "autoTable is not a function"
I solved this eventually by using the alternative import and code syntax: 
```
import jsPDF from "jspdf";
import autoTable from 'jspdf-autotable';
autoTable(doc, {...});
```
I suspect Vite optimizes this import out of the build
```
import 'jspdf-autotable';
```
because it doesn't recognize it is being used. 
I would propose to set the `import...from` as the default syntax in the documentation. I feel it is the more usual way.

**Comment by fran1987** [comment]
I had the same problem, I solved it with this bit from official documentation:
https://github.com/simonbengtsson/jsPDF-AutoTable/tree/v3.5.23#api

> In addition to the exported autoTable(doc, options) method you can also use applyPlugin to add the autoTable api to any jsPDF instance.
> 
> import jsPDF from 'jspdf/dist/jspdf.node.debug'
> import { applyPlugin } from 'jspdf-autotable'
> applyPlugin(jsPDF)
>

**Comment by micksp** [comment]
@fran1987 Yeah, I saw that too. Didn't try it but it'll likely solve the problem as well. The solution I used is also in the docs. My suggestion is that one of these methods is better mentioned as the default way to install and use, rather then the `import 'jspdf-autotable';` which is now the first thing people see and it may give them trouble when building for production.

**Comment by FPG-Alan** [comment]
solved the problem here:
https://github.com/simonbengtsson/jsPDF-AutoTable/issues/860#issuecomment-1034453871

**Comment by simonbengtsson** [comment]
Sounds great to me. I would accept a merge request that changed the default import style in the documentation to `import autoTable from 'jspdf-autotable'`.

**Comment by simonbengtsson** [comment]
Merged
