### ISSUE TITLE
autoTableHtmlToJson does not work for table without thead tag

### ISSUE THREAD

**Issue by wlad73** [simonbengtsson/jsPDF-AutoTable#859]
I have a table: 
`<table id="basic-table">
  <tbody>
    <tr>
      <td>value_1_1</td>
      <td>value_1_2</td>
      <td>value_1_3</td>
      <td>value_1_4</td>
    </tr>
    <tr>
      <td>value_2_1</td>
      <td>value_2_2</td>
      <td>value_2_3</td>
      <td>value_2_4</td>
    </tr>
   </tbody>
</table>`
and with the function try to create a pdf file with table header:
`function generate_pdf() {

  var doc = new jsPDF('p', 'pt');

  var res = doc.autoTableHtmlToJson(document.getElementById("basic-table"));
  var head = ['ID', 'First Name', 'Last Name', 'Email'];
  doc.autoTable(head, res.data);

  doc.save("table_without_header.pdf");
}`
I could not find any parameter to ignore missing header in the table

**Comment by ihorbond** [comment]
This is still an issue
