### ISSUE TITLE
Create a relationship between tables

### ISSUE THREAD

**Issue by jdnichollsc** [simonbengtsson/jsPDF-AutoTable#86]
Hi man, thanks for this plugin!

One question, Is possible to create a relationship between tables?
See please: http://screencast.com/t/JU1CohJogJFt

For example, if a table has a page break, the other also go to next page

Thanks in advance! :dancers:

**Comment by simonbengtsson** [comment]
Do you mean something like changing default options? I have been thinking about that but not added yet.

The picture you linked to seems to be bug. I will look into a fix for it.

**Comment by simonbengtsson** [comment]
Couldn't reproduce the issue. If you are still having issues feel free to reopen with some code. In terms of default options, that feature is put on hold and will probably not show up until the next major version.
