### ISSUE TITLE
prevent wrap

### ISSUE THREAD

**Issue by zhao-weiqi** [simonbengtsson/jsPDF-AutoTable#862]
Hi, I want to prevent the wrap for the first column.
```
columnStyles: {
    0: {cellWidth: 'auto'}
},
```
I can only see options like 'auto', 'wrap' for cellWidth property.
My purpose is to display the text in one line for only first column in table.

**Comment by simonbengtsson** [comment]
Look at the overflow style insteas

**Comment by Llorx** [comment]
And how to prevent word break, just the same as CSS `white-space: nowrap;`?

I mean, to allow line breaks, but to keep complete words when possible, to avoid this:
![image](https://user-images.githubusercontent.com/702490/155127580-ccace157-6747-426e-903f-515ca7562107.png)

but instead to have this:
![image](https://user-images.githubusercontent.com/702490/155127926-6c6986c0-3f76-464c-8b89-09b80fa33f59.png)
