### ISSUE TITLE
Consider to support IE 11 by setting webpack target to 'es5'

### ISSUE THREAD

**Issue by janmas** [simonbengtsson/jsPDF-AutoTable#865]
By default webpack 5 does not support IE 11 (please see https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11). As a consequence the referenced NPM package does not work in IE 11 anymore. Please consider to keep supporting IE 11 by configuring webpack to target 'es5' (please see https://stackoverflow.com/questions/64339314/webpack-babel-transpile-object-arrow-functions-doesnt-work/64395200#64395200).

**Comment by simonbengtsson** [comment]
Sounds great. I would be happy to review a merge request for this.

**Comment by janmas** [comment]
OK, thanks, https://github.com/simonbengtsson/jsPDF-AutoTable/pull/868 has been created.

**Comment by simonbengtsson** [comment]
Merged
