### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by fr3sh** [simonbengtsson/jsPDF-AutoTable#87]
Hi
Export to pdf does not support special characters like ą ś ć ż ł ó ę.
Is there a chance to fix it?

**Comment by simonbengtsson** [comment]
As @hhurz mentioned it is a known issue with jspdf, you would have to try another library.

**Comment by fuzunspm** [comment]
still having the same issue? any workaround..?

**Comment by junaidmirza199** [comment]
still having the same issue? any workaround..?
