### ISSUE TITLE
npm do not has non-minified version

### ISSUE THREAD

**Issue by Llorx** [simonbengtsson/jsPDF-AutoTable#870]
Both files are the minified version:
![image](https://user-images.githubusercontent.com/702490/157413012-9a1bfc89-6e2f-412c-be27-869d249bf335.png)

**Comment by blackdrago** [comment]
+1

I ran a diff between the two files, and there was none. Unminified files are critical for debugging, so I'd really appreciate an unminified option.

**Comment by simonbengtsson** [comment]
Thanks for reporting! Build script fixed and non minified version will be available in next version.
