### ISSUE TITLE
In nodejs Worker Threads it crashes

### ISSUE THREAD

**Issue by Llorx** [simonbengtsson/jsPDF-AutoTable#871]
In nodejs Worker Threads there's no `this`, but `globalThis`:
![image](https://user-images.githubusercontent.com/702490/157413401-965062eb-a6f4-44a5-9e3f-528664537bea.png)

So this line fails, as there's neither `window`:
```javascript
void 0!==this?this:window
```
Is the minified version in the npm.

**Comment by simonbengtsson** [comment]
Would be a great improvement! Would likely be some minor changes to the build script.
