### ISSUE TITLE
Jspdf autotable header text alignment issue

### ISSUE THREAD

**Issue by SathishRavichandran** [simonbengtsson/jsPDF-AutoTable#876]
Iam using jspdf autotable in my project ,if the table has more data header cells text are not aligned properly.
text are not coming correctly in proper text-wrap is there any property to fix the text alignment

![image](https://user-images.githubusercontent.com/17080107/165752208-23d16512-93ae-4cf7-95c6-974608cdc87e.png)

**Comment by simonbengtsson** [comment]
How do you mean not aligned correctly?

**Comment by SathishRavichandran** [comment]
Lets say if you have table with more column headers eg: if you have 15 column headers the text for each column is not aligned properly
 text: Driver Num
Expected: **Driver 
                 Num**
Original result: Drive
                          r   
                        Num 

Please check my screenshot which i attached how headers are coming if we table with more column headers
