### ISSUE TITLE
Language translation issue.

### ISSUE THREAD

**Issue by Ariful4593** [simonbengtsson/jsPDF-AutoTable#877]
Hi, I already made a website for my client. Here are two language support on this website English and Hungarian. English and Hungarian also work fine on websites but when I want to try to pdf it that's time some word is broken or may not be supported. For example (tálaló hűtő) It's a Hungarian word but when I try to pdf it and that's time the word is separated by a single space. I notice that there is the main problem when I used (ű and ő) this word.

![talalo](https://user-images.githubusercontent.com/65606159/166122728-4b53668d-9c3c-4607-998c-07e7d03c9e8b.png)
![talalo2](https://user-images.githubusercontent.com/65606159/166122730-c05dce61-6146-49fc-9f84-56a69f858e17.png)

**Comment by simonbengtsson** [comment]
To support additional characters you would need to include an external font.

**Comment by simonbengtsson** [comment]
You can check the custom style example

**Comment by Ariful4593** [comment]
I think it's jsPdf library issue.
