### ISSUE TITLE
How not to Render the hidden table rows in autoTableHtmlToJson()?

### ISSUE THREAD

**Issue by sebint** [simonbengtsson/jsPDF-AutoTable#88]
Hai ,
 I have a table, and at the execution time i hide certain rows and those rows need not to render in the PDF,is that possible with jsPDF-AutoTable?

**Comment by simonbengtsson** [comment]
The current `autoTableToJson()` function does not support that, but it would be pretty easy to add. Will mark it as a feature request and add it in the next version.

**Comment by simonbengtsson** [comment]
In the latest version `2.0.16` the default behavior is now to not include hidden html rows. If hidden html rows are wanted however you can set the second parameter `includeHiddenRows` to true like this.

`var res doc.autoTableHtmlToJson(tableElem, true);`

Let me know if this is what you had in mind.
Cheers!

**Comment by sebint** [comment]
Ohhh....Thanks man...
