### ISSUE TITLE
How to create rows within rows

### ISSUE THREAD

**Issue by skaidigitalnorge** [simonbengtsson/jsPDF-AutoTable#880]
Awesome package, btw!

I'd like to make each "variant" and price" have its own line or row, if that makes sense. How do I do that?
![2022 05 10](https://user-images.githubusercontent.com/92500207/167565738-2848fea1-3335-409e-ad5d-4ae63916594c.png)

Best regards,
Ragnsan

**Comment by simonbengtsson** [comment]
Hi! You can try adding a linebreak character ofter each price/variant ie `\n`

**Comment by skaidigitalnorge** [comment]
Hey, thanks for the help! That definitely worked. But now I have an issue, where the rows are not spacing out correctly. 
![2022 05 10](https://user-images.githubusercontent.com/92500207/167602527-76ae5fe2-7392-4fb5-a5a1-6bc54dd9d694.png)
Now how do I make the rows space out correctly, for a given product? Basically I want the same behavior as a regular html table, where the columns in the same row are the same height, like this:
![2022 05 10](https://user-images.githubusercontent.com/92500207/167603095-33288594-d5fe-4537-b817-a9b415d23f22.png)
Appreciate the help!
