### ISSUE TITLE
Desktop/mobile inconsistency, addImage make image stretched

### ISSUE THREAD

**Issue by MatthieuAvrgs** [simonbengtsson/jsPDF-AutoTable#881]
Hi,

I am trying to add an image to a cell in my pdf table.
For this I use autoTable (filled with a body containing table of data - rows and cells)
And I use didDrawCell to draw my Image from base64 string.

- When I save and export the pdf on my computer (running my app locally) images are well shaped, no pixel issue. 
![Capture d’écran 2022-05-14 à 15 16 45](https://user-images.githubusercontent.com/37926109/168427381-13d2e53a-6f4d-4b15-b8ba-26c67990d4c1.png)

- When I save and export the pdf on my mobile (running my app on Android) images are stretched like if a kid was drawing it.. lots of lines drawing everywhere..
![Screenshot_20220514-151548_Office](https://user-images.githubusercontent.com/37926109/168427418-e25f9626-e18e-4471-858e-27bd87bca94e.jpg)

I am wondering why the behavior is not the same between desktop and mobile, did someone already encountered this problem?
I don't share my code as I think it is not related to it as it is working well on my desktop.. ionic/cordova plugin missing? I searched for hours to not say days and week and I finally decided to open this topic because the struggle is real..

Any advice would be great

**Comment by simonbengtsson** [comment]
Could you try creating a minimal example that highlights the Issue? Sounds like it is related to jspdf and not this plug-in.
