### ISSUE TITLE
Specify an custom cell ID

### ISSUE THREAD

**Issue by jesben** [simonbengtsson/jsPDF-AutoTable#885]
It could be handy with an option to specify an custom cell ID, which later can be used to insert images from or other stuff.

See this example
```
const imgGroups = {
   imgGroup1: [imgObj1,imgObj2],
   imgGroup2: [imgObj3,imgObj4]
};

autoTable(doc, {
  body: [
    [{ 
         content: 'Text1',
         customId: 'imgGroup1'      
    }],
    [{ 
         content: 'Text2',
         customId: 'imgGroup2'      
    }],
   didDrawCell: (data) => {
         // Insert images
         const imgGroupId = data.row.raw[data.column.index].customId;

        if (Object.prototype.hasOwnProperty.call(imgGroups, imgGroupId)) {
            // Do doc.addImage() with data from imgGroups[imgGroupId] 
        }
   });
});
```

BTW. thanks for a awesome lib!

**Comment by simonbengtsson** [comment]
Sounds like a great idea! You can actually do this already although in a somewhat roundabout way

didDrawCell: (data) => {
    console.log(data.table.body[data.row.index].cells[data.column.index].raw?.customId)
});

**Comment by jesben** [comment]
You're a hero, thank you!

`console.log(cell.raw?.['customId']);`
