### ISSUE TITLE
what is the table unit that autoTable accept

### ISSUE THREAD

**Issue by nauman223** [simonbengtsson/jsPDF-AutoTable#886]
![image](https://user-images.githubusercontent.com/30920605/171610130-b838a8be-d0be-494f-a6e0-17e752b8b401.png)

My pdf width is 608.93pt when I gave jsPDF-AutoTable a specific width then that width is greater then its pdf size. 
Like in the screenshot I have gave 478 width size to the table when I generate pdf of it then its size is equal to 608pt of pdf (second screenshot)

![image](https://user-images.githubusercontent.com/30920605/171610666-46926e61-4e6e-44a2-9b70-ca96ad89ba73.png)

**Comment by simonbengtsson** [comment]
Can you provide  minimal example reproducing this?
