### ISSUE TITLE
Table Multi Header How can I do this

### ISSUE THREAD

**Issue by bluesleech** [simonbengtsson/jsPDF-AutoTable#89]
Hi I using your Library to Create Table to PDF,
I have a question , If I want to do Multi Table Header,
but I do this is fail,the view always show me single Header,
And What can I do this? Thanks   !!!!

**Comment by simonbengtsson** [comment]
To create multiple headers you would have to use hooks and insert them manually. Let me know if you have troubles with this. You can check for example the horizontal headers example for how to use hooks.

**Comment by bluesleech** [comment]
Let my try it  again,have any question I will ask for you , Thank you very much !!! : )

**Comment by simonbengtsson** [comment]
If you have further issues, feel free to reopen!

**Comment by Grendizr** [comment]
Hi. I am reopening this one, cause I am not sure the hooks will help in this case.  

I have a table with header made of two rows. I want both rows to be exported as part of the header, with same style.

I have updated you basic table from the sample. Note that the display here is not correct as both row headers should be displayed the same way.

``
<table id="basic-table" style="display: none;">
    <thead>
    <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Country</th>
        <th>IP-address</th>
    </tr>
     <tr>
        <th>&nbsp</th>
        <th colspan="2">Name</th>
        <th>Email</th>
        <th colspan="2">Location</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1</td>
        <td>Donna</td>
        <td>Moore</td>
        <td>dmoore0@furl.net</td>
        <td>China</td>
        <td>211.56.242.221</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Janice</td>
        <td>Henry</td>
        <td>jhenry1@theatlantic.com</td>
        <td>Ukraine</td>
        <td>38.36.7.199</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Ruth</td>
        <td>Wells</td>
        <td>rwells2@constantcontact.com</td>
        <td>Trinidad and Tobago</td>
        <td>19.162.133.184</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Jason</td>
        <td>Ray</td>
        <td>jray3@psu.edu</td>
        <td>Brazil</td>
        <td>10.68.11.42</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Jane</td>
        <td>Stephens</td>
        <td>jstephens4@go.com</td>
        <td>United States</td>
        <td>47.32.129.71</td>
    </tr>
    <tr>
        <td>6</td>
        <td>Adam</td>
        <td>Nichols</td>
        <td>anichols5@com.com</td>
        <td>Canada</td>
        <td>18.186.38.37</td>
    </tr>
    </tbody>
</table>
``

Thanks in advance for your quick feedback.
