### ISSUE TITLE
Multiple rows appearing in single row

### ISSUE THREAD

**Issue by rashmi712** [simonbengtsson/jsPDF-AutoTable#892]
I am using MUI to dynamically create table which has collapsible table within it.(screenshot attached for reference)
![Collapsible Table](https://user-images.githubusercontent.com/25747607/173553647-4c8d9806-1fa8-4c12-81c5-8453453e9d9a.PNG)
Post Downloading the table all the inner rows are appearing in single row instead of separate rows although the table has separate <tr> for each rows.
@simonbengtsson Could you please suggest.
![Result](https://user-images.githubusercontent.com/25747607/173554205-b65a3627-c919-4b62-9986-f278e1f89961.PNG)

**Comment by rashmi71** [comment]
@simonbengtsson Could you please take a look here and guide how can we achieve this. Any help here ?
