### ISSUE TITLE
fillColor turn's black when specifing an object to lineWidth

### ISSUE THREAD

**Issue by ferflores507** [simonbengtsson/jsPDF-AutoTable#897]
This happens when you assign the object with some or all properties (top, right, bottom, left).

The workaround is to assign fillColor a value that is not false or null (another issue), in my case I had to assign white.

**Comment by JavorovNetIt** [comment]
I have the same issue!

**Comment by MikeDabrowski** [comment]
Me too! 

@simonbengtsson 

https://github.com/simonbengtsson/jsPDF-AutoTable/blob/896a73dc57bc99b922d9fd76e547b065424217b9/src/tableDrawer.ts#L402-L409

Here is the place where the fillColor is replaced by 'S' which is the default for line stroke/fill. Imo, lines use jsPDF.setDrawColor, don't they?

I can create PR with the change.

**Comment by simonbengtsson** [comment]
Would be great! If all the examples works and the tests pass I'll merge right away 👌

**Comment by MikeDabrowski** [comment]
So the changes would be: 
Remove fallback here: 
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/896a73dc57bc99b922d9fd76e547b065424217b9/src/tableDrawer.ts#L407
And replace `'F'` with `cellStyles.fillColor` here:
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/896a73dc57bc99b922d9fd76e547b065424217b9/src/tableDrawer.ts#L395

I actually doubt this 395 line is needed. I'm testing using my project's table where I use 'plain' theme, no borders here.

**Comment by MikeDabrowski** [comment]
@simonbengtsson PR ready, I'd appreciate if you take a look
