### ISSUE TITLE
PDF getting corrupted in a ExtJS based application

### ISSUE THREAD

**Issue by sijohn** [simonbengtsson/jsPDF-AutoTable#90]
HI,

We are using jsPDF-autoTable plugin in our ExtJS based application. Is there any known limitation of this jsPDF library or for this plugin in a ExtJS environment ?
Below is the sample HTML string which we are trying to render to PDF,

'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html ><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><link href="table.css" rel="stylesheet" type="text/css" /><body><table cellspacing="0"> <thead><tr><th>Task Details</th><th>Progress</th><th>Vital Task</th></tr>             </thead><tbody>           <tr><td>Create pretty table design</td>       <td>100%</td><td>Yes</td><tr class="even"><td>Take the dog for a walk</td><td>100%</td><td>Yes</td><tr><td>Waste half the day on Twitter</td><td>20%</td><td>No</td>     </tr><tr class="even"><td>Feel inferior after viewing Dribble</td><td>80%</td><td>No</td></tr><tr><td>Wince at "to do" list</td><td>100%</td><td>Yes</td></tr><tr class="even"><td>Vow to complete personal project</td><td>23%</td><td>yes</td></tr>             <tr><td>Procrastinate</td><td>80%</td><td>No</td></tr><tr class="even"><td><a href="#yep-iit-doesnt-exist">Hyperlink                Example</a></td><td>80%</td><td><a href="#inexistent-id">Another</a></td></tr></tbody></table></body></head></html>'

and below is the JS code we are using to generate the PDF

parser=new DOMParser();
htmlDoc=parser.parseFromString(source, "text/html");
console.log(htmlDoc.getElementsByTagName('table'));

  var pdfsize = 'a0';
  var pdf = new jsPDF('l', 'pt', pdfsize);

  var res = pdf.autoTableHtmlToJson($(htmlDoc.getElementsByTagName('table')).get(0));
  pdf.autoTable(res.columns, res.data, {
    startY: 60,
    tableWidth: 'auto',
    columnWidth: 'auto',
    styles: {
      overflow: 'linebreak'
    }
  });

  pdf.save(pdfsize + ".pdf");
  
 The PDF is getting generated but corrupted, In Chrome browser's PDF viewer the content is appearing overlapping(refer Chrome_PDF_view.jpeg in attachments).

When we try to open the PDF in adobe reader it says its corrupted.

We have also attached PDF debug data for reference.

Any help or suggestion on this will be very much helpful.

Regards,
Sijohn
![chrome_pdf_view](https://cloud.githubusercontent.com/assets/14990764/11306661/4021d104-8fd9-11e5-9ac5-cd40ed99b4c4.JPG)
[first (2).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/40350/first.2.pdf)
[pdf_validation_error.txt](https://github.com/simonbengtsson/jsPDF-AutoTable/files/40351/pdf_validation_error.txt)

**Comment by simonbengtsson** [comment]
I have not tried the plugin with ExtJS, but I think it should work. To test if there is an issue with ExtJS,  can you try to create a normal pdf with only jspdf (not this plugin) in ExtJS? And can you also try to generate your table pdf in a browser environment without ExtJS?

**Comment by simonbengtsson** [comment]
Will close this for now. Feel free to reopen if it is not resolved.

**Comment by CaCtus491** [comment]
We are seeing the exact same behaviour in ExtJS 5.1.2 - the theming is missing and columns are pushed to the left, mostly on top of each other.

This only happens if we compile our project using Sencha cmd. When uncompiled, or using a the testing environment (rather than production) for the build, it appears to work OK, although I'm yet to try the resulting PDF outside of Chrome. 

This behaviour is consistent even if we include jsPDF + AutoTable JavaScript files separately in our index.html and test it using a very basic test in ExtJS (single column with header and two rows of data).

We have found that if we set the individual column widths when creating the table with AutoTable, then we get the correct result when viewing the PDF in Chrome (theming returns and columns are displayed next to each other), however the resulting PDF when viewed in NitroPDF only shows two of the expected 40 or so rows.

**Comment by simonbengtsson** [comment]
Spontaneously that sounds like an encoding issue. I will download extjs and try for myself.

**Comment by CaCtus491** [comment]
I am away for the next week. I will attempt to put together a concrete example once I return if you haven't made progress in the meantime.

**Comment by simonbengtsson** [comment]
Do you still see issues with extjs? Since I don't have extjs I havn't been able to test further.

**Comment by CaCtus491** [comment]
Sorry, I haven't had a chance to create a demo application and for other reasons in the meantime, we've switched to a server side solution. If I get the chance to create an example I will come back to post it, however things are rather busy at the moment.

**Comment by CaCtus491** [comment]
I've been looking into this again, and the issue persists...

I've created a basic example. The table works just fine when using the unminified ExtJS sources, but after going through the Sencha build process (so we end up with a single app.js file) we get a broken PDF. See below for example output PDF files.

To test this out, grab the demo project from the Google Drive link: https://drive.google.com/file/d/0Bwxm_v-oy1oLbG95OWtDWTJQdjQ/view?usp=sharing
and install Sencha Cmd: https://www.sencha.com/products/sencha-cmd/

You can view the working uncompiled version by hitting index.html in the top level folder contained in the zip file - /PDFTest/index.html.

To view the broken compiled version, hit /PDFTest/build/production/PDFTest/index.html

To make changes, you can edit /PDFTest/app/view/MyPanelViewController.js directly, or alternatively download Sencha Architect 4 (early access version) and open /PDFTest/PDFTest.xds although for this issue I expect editing the file directly would be easiest.

To compile again after making changes, run 'sencha app build' from the directory containing app.json (/PDFTest).

Note that this is a simplified version of our use case , hence the weird drawRow hook (we need to add a horizontal line when 'z' in the data is true).

If the columnStyle code is uncommented, the PDF generated by the compiled version works better, in that the styling looks OK when opened in Chrome, but other PDF readers claim the PDF file is corrupted. Also, even in Chrome, the horizontal line between the second and third data rows is missing (yet works OK in the uncompiled version).

[test (uncopmiled).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/413276/test.uncopmiled.pdf)
[test (compiled).pdf](https://github.com/simonbengtsson/jsPDF-AutoTable/files/413277/test.compiled.pdf)

**Comment by CaCtus491** [comment]
I'm really flying blind here, but I compared the two PDFs in my previous comment in a hex viewer - seems that in the compiled version, a bunch of NaN values are appearing in the output as opposed to what I assume are the correct numeric values in the other PDF. See the following image for a few examples.
![pdfnan](https://cloud.githubusercontent.com/assets/17428191/18378421/4d6a2a1e-76b0-11e6-8f62-6d2dc5baa643.png)

**Comment by CaCtus491** [comment]
PDFs work OK if I use the compiled ExtJS output, jspdf.plugin.autotable.js, and jspdf.debug.js.
If I change to jspdf.min.js instead then the corrupted PDFs appear.

I presume that compiled versions of ExtJS and jsPDF are conflicting somehow, so technically this probably isn't a jsPDF AutoTable issue.

**Comment by simonbengtsson** [comment]
Forgot about this issue, but remember quickly troubleshooting it without much luck. Glad it works with the debug version of jspdf and that it don't seem to be an issue with this plugin (A). Will close for now. If someone thinks it is an issue with this plugin after all, feel free to reopen.
