### ISSUE TITLE
The cell botton padding incorrect for longer content text?

### ISSUE THREAD

**Issue by ntruongvux** [simonbengtsson/jsPDF-AutoTable#906]
I have a longer the text and use the default styles, it auto wrap the text
but the bottom padding incorrect for the cell content.

Where can I find the same issue?

![image](https://user-images.githubusercontent.com/55976935/182328709-379eb45c-d43e-4fc1-8f56-68e3791600af.png)

**Comment by ntruongvux** [comment]
Because I change `lineHeight` to 1.5, but I don't know next do?

**Comment by simonbengtsson** [comment]
You would have to set the cell height manually. Setting line height does not automatically change cell height for now.

**Comment by ntruongvux** [comment]
if I don't set `lineHeight` for jsPDF, can I custom line height between multiple lines in the same content body?


![image](https://user-images.githubusercontent.com/55976935/182345816-c49cba97-6b7e-46f2-892b-2b55287adee5.png)

**Comment by ntruongvux** [comment]
yeah, I created multiple body[][] contents inside the body.

**Comment by mmghv** [comment]
Released in [v3.7.0](https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.7.0)
