### ISSUE TITLE
Add text rotation in cells

### ISSUE THREAD

**Issue by sikelio** [simonbengtsson/jsPDF-AutoTable#909]
Hi,

I was looking for text rotation in cells, I checked a little bit and didn't found something about this.
So I'm asking if there is a way to do it , because I know that jsPDF can do it.

**Comment by nicolacardi** [comment]
This is a partial answer, but maybe it's a good basis to create a complete one.
I check if the text starts with R90, and if so it rotates the text.

```
willDrawCell: (data) => {

         if (data.section === 'body' && data.cell.text[0].substring(0,3)== "R90" ) {

          docPDF.text(data.cell.text[0].substring(3), data.cell.x + data.cell.width /2 , data.cell.y + data.cell.height /2, {angle:90});

         }
      }
```

The problem is that data.cell.text[0] is ONLY giving the first row. I/we should work with cell.data.raw BUT I cannot access to "content" property of it.

**Comment by sikelio** [comment]
Oh thank you very much
I'll try it :D

**Comment by simonbengtsson** [comment]
There is a feature request about it here https://github.com/simonbengtsson/jsPDF-AutoTable/issues/510

**Comment by nicolacardi** [comment]
Not being able to access row.cell.raw (content property seems to be not available...) I better specified what I proposed earlier, as follows:

      willDrawCell: (data) => {

        let cellContent = '';
        for (let i = 0; i < data.cell.text.length; i++) {
          cellContent = cellContent + data.cell.text[i];
        } //this "parks" raw content into cellContent variable

         //if (data.section === 'body' && data.cell.text[0].substring(0,3)== "R90" ) {
        if (data.section === 'body' && cellContent.substring(0,3)== "R90" ) { //it checks whether text starts with 'R90' and if so that gets rotated
          docPDF.setFontSize(16);
          docPDF.text(cellContent.substring(3), data.cell.x + data.cell.width /2 + 2 , data.cell.y + data.cell.height - 5, {angle:90});
          //the following cycle prevents autotable from writing BOTH the rotated and the non rotated text
          for (let k = 0; k < data.cell.text.length; k++) {
            data.cell.text[k] = '';
          }
         }
      },

**Comment by nicolacardi** [comment]
Hello Simon, I would be happy enough if I could manage data.cell.raw…
If I console.log it it shows an object with a few properties among which also “content”.
But data.cell.raw.content is not accessible, doesn’t even get compiled…
Can you give me a hint?
Thanks
Nicola

**Comment by netorody** [comment]
Hey @nicolacardi, you have any success on this?

**Comment by marcosRandulfe** [comment]
Is that feature working in autotable headers
