### ISSUE TITLE
Does the plugin support Chinese?

### ISSUE THREAD

**Issue by AlexHodovas** [simonbengtsson/jsPDF-AutoTable#910]
Does the plugin support Chinese?
thanks

**Comment by simonbengtsson** [comment]
Yes! To get Chinese working with jsPDF however you might need to add a custom font that supports Chinese characters. See the [jsPDF documentation](https://github.com/parallax/jsPDF#use-of-unicode-characters--utf-8) on adding an utf-8 font for more information. You can also check the custom style example for an example of how to use the plugin with a custom font.

**Comment by AlexHodovas** [comment]
@simonbengtsson 
thank you 

unfortunately, something went wrong ((

![image](https://user-images.githubusercontent.com/55617181/184940385-068b25f5-21dc-4175-a1e3-30a16dc445fc.png)

<img width="979" alt="image" src="https://user-images.githubusercontent.com/55617181/184940504-438b9d4f-467f-412d-8395-a2f647909ff5.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/55617181/184940599-b2143f59-fec0-4f09-b57f-3645704308cf.png">
