### ISSUE TITLE
Repeating Mutiple Columns using horizontalPageBreakRepeat.

### ISSUE THREAD

**Issue by gitsakil09** [simonbengtsson/jsPDF-AutoTable#911]
Is it possible to repeat more than one header columns in every page when the table width exceeds the page width? I haven't found any solution yet. Is there any way to add this feature in future? Something like by providing an array of keys or some other ways.

`horizontalPageBreakRepeat: [0,1,2,3]` for example.

**Comment by simonbengtsson** [comment]
I think you will be able to accomplish what you want with the horizontalPageBreak option.

**Comment by gitsakil09** [comment]
> I think you will be able to accomplish what you want with the horizontalPageBreak option.

Thank you for your reply. I have set the `horizontalPageBreak: true`. I can see the table is breaking and thats ok. What I want is the repetition of multiple header columns. By setting `horizontalPageBreakRepeat: 0`, I can see the first column is repeating but I want columns first, second and third repeated. I hope you have understood me. If there is any snippets I would be grateful. Thanks.

**Comment by gitsakil09** [comment]
Any update yet?

**Comment by simonbengtsson** [comment]
Got it. Marked it as a feature request now. Let me know if you start work on it. It could be somewhat complex so feel free to send an implementation plan for review beforehand.

**Comment by gitsakil09** [comment]
@simonbengtsson thank you so much for spending time on it. Is it possible to make `horizontalPageBreakRepeat` an array of column datakey. Something like `horizontalPageBreakRepeat: [0,1,2]` or `horizontalPageBreakRepeat: ['id','name','email']`. This is just an idea you know. Sorry for bothering.

**Comment by simonbengtsson** [comment]
Make sense to me!

**Comment by ecosse3** [comment]
Any updates on this?
