### ISSUE TITLE
Option useCss in combination Bootstrap v5 results in no pdf borders between rows

### ISSUE THREAD

**Issue by colgibson** [simonbengtsson/jsPDF-AutoTable#915]
When using `useCss`, the AutoTable plugin seems to rely on checking `border-top-width` for setting the `lineWidth`.

This works in Bootstrap v4.6 which used border-top for row separators but Bootstrap v5 now seems to use border-bottom which causes the PDF to be output with no row borders.

The area of the [v3.5.25] plugin that seems to be responsible is https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/src/cssParser.ts#L36-L38

Given that lineWidth/border can be an object and not constrained to just being a number, maybe this:

```
// style.borderWidth only works in chrome (borderTopWidth etc works in firefox and ie as well)
let bw = parseInt(style.borderTopWidth || '')
bw = bw / pxScaleFactor / scaleFactor
```
should/could be changed to the following to allow for this:
```
// style.borderWidth only works in chrome (borderTopWidth etc works in firefox and ie as well)
let bw = {
  top: parseInt(style.borderTopWidth || ''),
  right: parseInt(style.borderRightWidth || ''),
  bottom: parseInt(style.borderBottomWidth || ''),
  left: parseInt(style.borderLeftWidth || '')
}
bw = Object.fromEntries(Object.entries(bw).map(([k, v]) => [k, v / pxScaleFactor / scaleFactor]))

```
I'm unable to offer any help with a PR but hopefully the above is of use

**Comment by mmghv** [comment]
Released in [v3.7.0](https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.7.0)
