### ISSUE TITLE
Align header by cell

### ISSUE THREAD

**Issue by xasor** [simonbengtsson/jsPDF-AutoTable#92]
Hello!

I want to align header cells by cell, first column align to the left and second column align to the right. I can do this easily for the rest of the cells (using createdCell hook method) but not for header cells ( using createdHeaderCell hook).

![image](https://cloud.githubusercontent.com/assets/16100023/11500337/5e9a2b60-9824-11e5-8553-4a2fe7cf85c5.png)

Thanks!

**Comment by simonbengtsson** [comment]
Seems to be a bug, will look into it

**Comment by wingy3181** [comment]
Attempted to fix it...https://github.com/simonbengtsson/jsPDF-AutoTable/pull/94/files..this worked for me..

**Comment by simonbengtsson** [comment]
Perfect!

**Comment by xasor** [comment]
Hello!

I also confirm, it is working for me!

Thanks a lot!

**Comment by wingy3181** [comment]
Any chance you could release a new minor version?

**Comment by simonbengtsson** [comment]
Done! Sorry for the delay.
