### ISSUE TITLE
Using jsPDF with Wordpress

### ISSUE THREAD

**Issue by mjordansc** [simonbengtsson/jsPDF-AutoTable#922]
Hi, I'm trying to use jsPDF-Autotable with Wordpress.
I included both files source locally and added "module" to the script tag where I'm including the following code from the tutorial:

`import jsPDF from 'jspdf';`
`import autoTable from 'jspdf-autotable';`
`const doc = new jsPDF()`
`autoTable(doc, { html: '#reportsTable' });`
`doc.save('table.pdf')`

But I keep getting the error "Failed to resolve module specifier jspdf". All three files are in the same folder. Can anyone point me in the right direction?

Thank you!

**Comment by rafaelmardojai** [comment]
Use the `umd` version of `jsPDF` and import it like this:

```html
<script src="jspdf.umd.min.js"></script>
<script src="jspdf.plugin.autotable.min.js"></script>
<script>
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    doc.autoTable({});
</script>
```
