### ISSUE TITLE
Bengoli/bangla associated characters not showing properly

### ISSUE THREAD

**Issue by muhib-dev** [simonbengtsson/jsPDF-AutoTable#925]
i have added custom bangla font but all bangla custom fonts not showing properly
![Screenshot 2022-10-25 192003](https://user-images.githubusercontent.com/58384619/197784210-06160a24-948c-4088-894c-2978aa88e62f.png)

**Comment by muhib-dev** [comment]
image added

**Comment by simonbengtsson** [comment]
Seems to be a jspdf issue rather than a jspdf-autotable issue?

**Comment by muhib-dev** [comment]
> Seems to be a jspdf issue rather than a jspdf-autotable issue?

oh yes!
