### ISSUE TITLE
FontType no longer allows string (custom fonts)

### ISSUE THREAD

**Issue by apancutt** [simonbengtsson/jsPDF-AutoTable#935]
The changes introduced by [6ae084](https://github.com/simonbengtsson/jsPDF-AutoTable/commit/6ae084b4d2418e6b2ec3f66490cf30d087a81ee9) cause TS errors when using custom fonts.

What it intentional to drop `string` from `FontType`? If built-in fonts need to be exposed as a type, then perhaps something like this would work better?

```ts
export type StandardFontType = 'helvetica' | 'times' | 'courier'
export type CustomFontType = string
export type FontType = StandardFontType | CustomFontType
```

**Comment by simonbengtsson** [comment]
Not intentional and suggested solution sounds great! If you submit a PR I'll merge and release a hotfix right away 👌
