### ISSUE TITLE
New version 4 upcoming. Some insight into it? :-)

### ISSUE THREAD

**Issue by jabidof** [simonbengtsson/jsPDF-AutoTable#938]
@simonbengtsson 

First of all, thank you so much for this professional plugin!

I saw an upcoming version 4 in some issues. Can you give us some insight into the changes and features you'll integrate?

Thanks,
J.

**Comment by simonbengtsson** [comment]
Thank you! It will mostly be about making esm modules the first class API and remove some deprecated features to make the library leaner.

**Comment by jabidof** [comment]
Great!
Stay slim and lean makes it easier to jump ahead
Enjoy XMas.
J.

**Comment by simonbengtsson** [comment]
Merry christmas! 🎄
