### ISSUE TITLE
Cannot Display Arabic Font in Auto Table

### ISSUE THREAD

**Issue by callme-MJ** [simonbengtsson/jsPDF-AutoTable#940]
my autotable in jspdf doesn't display the Arabic contents in it, it shows some special characters. pls  help

**Comment by farhankarim** [comment]
[amiri font.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/10369424/amiri.font.zip)
Arabic font is not supported in jspdf. You can use amiri font. Follow instructions below

1. Extract this file in your project folder(it has two variants regular and bold).
2. Import in ur project. For my case it was reactjs
```
import "./calibri-regular-normal";
import "./calibri-bold-bold";
```
3. Set font using function before the text
`doc.setFont("Amiri-Bold", "bold");`
or
`doc.setFont("Amiri-Bold", "normal");`
4. Mark this issue as resolved :wink:

**Comment by mirajhad** [comment]
There can be several reasons why Arabic font is not displaying correctly in an Auto Table. One possible cause is that the font being used is not fully compatible with the Auto Table software. Another possible cause is that the encoding of the text being used is not set correctly. If the text is being copy-pasted, it could have been copied with the wrong encoding. Additionally, the way the text is being rendered in the table could be causing issues with the display of the Arabic font. It is recommended to check the font compatibility, encoding settings and the way the text is being rendered in the table.
