### ISSUE TITLE
EndY funcionality

### ISSUE THREAD

**Issue by 0xM1gu3l** [simonbengtsson/jsPDF-AutoTable#941]
Good Afternoon!
I'm making a application that generates the pdf via api and user input, there's an input that receive the products, and it can be more than one product, the problem is, in the bottom of every page, there is a text, and the table is coliding with the text, causing this: 
<img width="1120" alt="Screenshot 2023-01-16 at 2 17 13 PM" src="https://user-images.githubusercontent.com/63756297/212743747-812b2423-7037-4ddc-b220-69a3477d69bb.png">  I tried to set a height limit using didDrawPage, but I had no luck, so I was wondering exists a height limit, like an EndY param or a footer class, and how could I use it

**Comment by simonbengtsson** [comment]
Hi! What you need is likely the `doc.lastAutoTable.finalY` property. You can look at the "content" example for how it can be used.

**Comment by 0xM1gu3l** [comment]
I'll give a try!

**Comment by 0xM1gu3l** [comment]
solved the problem using the foot param, and then with ``willDrawCell``, I hid the foot and then it looked like this:
<img width="1118" alt="Screenshot 2023-01-16 at 7 28 10 PM" src="https://user-images.githubusercontent.com/63756297/212779795-b43e7519-48dc-475a-8ecc-6e32453c5706.png">
the code for who is with the same problem:
``
willDrawCell(HookData) {
if (HookData.section === 'foot') {
          return false
        }
      },
``
