### ISSUE TITLE
Add image to table

### ISSUE THREAD

**Issue by xandeturf** [simonbengtsson/jsPDF-AutoTable#95]
hello, is possible add image in table row ?
 rowsTable = ["data:image/jpeg;base64,/9j/4A ........", "text","text"

**Comment by simonbengtsson** [comment]
No, not at the moment. You can do it with hooks however. Here is an example http://codepen.io/someatoms/pen/vLYXWB?editors=101

**Comment by xandeturf** [comment]
thank you.

**Comment by xandeturf** [comment]
this method is bug in multiple page , http://codepen.io/anon/pen/ZQYxJY?editors=101

**Comment by xandeturf** [comment]
solvid,         
for (var i = 0; i < images.length; i++) {
                    if(!images[i].usado){
                        doc.addImage(images[i].elem, 'jpg', images[i].x, images[i].y);
                        images[i].usado = true;
                    }
                }

**Comment by simonbengtsson** [comment]
Glad you solved your problem.

**Comment by poohsasne** [comment]
What should i do if i want to add .png image in autotable? i tried with angular-base64-min.js but it accepts only jpeg format. i'm unable to add png formatted image in header,
doc.addImage(headerImgData., 'png', 40, doc.autoTableEndPosY() + 10, height, width);
can you suggest me for this

**Comment by viraj4422** [comment]
@simonbengtsson This functionality is not there yet right ?

**Comment by simonbengtsson** [comment]
Which feature?

**Comment by viraj4422** [comment]
@simonbengtsson  Adding an image in table row. Codepen link that you mentioned in previous comments, does not seem to display images http://codepen.io/someatoms/pen/vLYXWB

**Comment by simonbengtsson** [comment]
I pointed that codepen to `v2.3.5` so it should work now. Adding images to cells should be a lot easier now with v3 though with the hook `didDrawCell` instead of `drawCell`.
