### ISSUE TITLE
Text under image not printed properly if the td contains an image. 

### ISSUE THREAD

**Issue by vijinvj** [simonbengtsson/jsPDF-AutoTable#950]
The text under of before image inside a td is not rendered in autotable when using image rendering using didDrawCell.

**Comment by simonbengtsson** [comment]
Code you post some sample code and preferably screenshot?

**Comment by vijinvj** [comment]
![image](https://user-images.githubusercontent.com/102153023/218312808-f8ba6083-0924-45eb-97ef-fb8aa0df7f02.png)
![image](https://user-images.githubusercontent.com/102153023/218312811-7aebe68c-00ec-449b-9b06-b88cbccc808d.png)
You can refer the below screenshots. One is the table I have where there is text under image. And the other one is the generated pdf,  where the image is overlapping the text.  didDrawCell: function(data) {
                                    if (data.column.index === 3 && data.cell.section === 'body') {
                                        var td = data.cell.raw;
                                        var img = td.getElementsByTagName('img')[0];
                                        var dim = data.cell.height - data.cell.padding('vertical');
                                        var textPos = data.cell.textPos;
                                        if(img){
                                            doc.addImage(img.src, textPos.x,  textPos.y, dim+40, dim);
                                        }
                                    }
                                }, this is my didDrawCell

**Comment by vijinvj** [comment]
@simonbengtsson I have included the screenshots and sample code.

**Comment by simonbengtsson** [comment]
Autotable does not automatically place text below potential images etc drawn in a cell. You would have to either place the image below the text or draw the text yourself below the image.

**Comment by vijinvj** [comment]
@simonbengtsson could you please give an example to draw the text below the image?

**Comment by vijinvj** [comment]
https://codepen.io/someatoms/pen/vLYXWB?editors=1010 @simonbengtsson  may be you can show an example in this codepen by you.
