### ISSUE TITLE
HTML comments in Table stop render pdf

### ISSUE THREAD

**Issue by sklicek** [simonbengtsson/jsPDF-AutoTable#951]
If you put HTML comments with  in your table, the Pdf does not render the numbers in the columns

```
<table class="table table-hover" id="budget_projet">
<thead>
  <tr> 
     <th>Column1</th>
     <th>Column2</th>
</thead>
<tbody>
   <tr>
     <td>
         <?=$value1;?>&euro;
     </td>
     <td>
         <!-- this is a comment for column2 -->
         <?=$value2;?>&euro;
     </td>
   </tr>
</tbody>
</table>

<script type="text/javascript">
function exportPdf(){
// generate PDF
var doc = new jspdf.jsPDF({orientation: 'l', format: 'a4'});
         var id='budget_projet';
		doc.autoTable({ 
		    html: '#'+id,
			theme: 'striped',
			startY: finalY,
			styles: { overflow: 'hidden', fontSize: 8 },
			margin: { right: 5 },
			columnStyles: {
				0: { columnWidth; 20 }, 
				1: { columnWidth: 10 },
			}			
		});
}
</script>
```

In the resulting PDF, the value2 does not appear in the column2.

**Comment by simonbengtsson** [comment]
Tried with a comment now with one of the examples which worked. Could you try a simpler example with only a few values without php and see if that works? If it does it is likely some other issues with how the data is fetched etc.

**Comment by sklicek** [comment]
Hello 
The following table:
<table class="table table-hover" id="budget_projet">
<thead>
  <tr> 
     <th>Col1</th>
     <th>Col2</th>
     <th>Col3</th>
     <th>Col4</th>
     <th>Col5</th>
     <th>Col6</th>
     <th>Col7</th>
     <th>Col8</th>
     <th>Col9</th>
     <th>Col10</th>
</thead>
<tbody>
<tr>
		 <td style="padding-left:<?=$niveau;?>em">
                        (1)&nbsp;Test
                    </td>
                    <td style="text-align:right">
						
                        1,00&euro;
                    </td>
                    <td style="text-align:right">
                        
                        0,00&euro;
                    </td>
                    <td style="text-align:right; border-right:1px solid black">
						
                        1,00&euro;
                    </td>
                    <td style="text-align:right;">
                    	<a class="btn btn-primary btn-sm pull-left" href="#" title="Title of the link"><span class="glyphicon glyphicon-edit"></span> Link</a>
                    </td>
					<td style="text-align:right;">
						
                        1.000,00&euro;
                    </td>
                    <td style="text-align:right">
						
						1.000,00&euro;
                    </td>
                    <td style="text-align:right; border-right:1px solid black">
						
					    1.000,00&euro;
                    </td>
                    <td style="text-align:right; border-right:1px solid black">
						
                        500,00&euro;
                    </td>
                    <td style="text-align:right; border-right:1px solid black">
						
                    	1.000,00&euro;
                    </td>
                    <td style="text-align:right">
						
	                    &euro;
                    </td>
                
		</tr>
</tbody>
</table>

<script type="text/javascript">
function exportPdf(){
// generate PDF
var doc = new jspdf.jsPDF({orientation: 'l', format: 'a4'});
         var id='budget_projet';
		doc.autoTable({ 
		    html: '#'+id,
			theme: 'striped',
			startY: finalY,
			styles: { overflow: 'hidden', fontSize: 8 },
			margin: { right: 5 },
			columnStyles: {
				0: { overflow: 'linebreak' }, 
				4: { columnWidth: 0.01 },
			}			
		});
}
</script>

It produces this:
Col1     | Col2   | Col3   | Col4  |  Col5         | Col6               | Col7               | Col8       | Col9     | Col10    
(1) Test | 1,00€ | 0,00€ | 1,00€ | 1.000,00€ | <blank here> | <blank here> | 500,00€ | 1.000 € | €

I think the hyperlink is the problem?

**Comment by sklicek** [comment]
If you only remove the  the table is correctly rendered
