### ISSUE TITLE
When tables from HTML are converted to pdf using jspdf,autotable borders are not drawn properly when the browser zooming over 100%

### ISSUE THREAD

**Issue by tz-thantzin** [simonbengtsson/jsPDF-AutoTable#952]
I converted html form to pdf by using jspdf.autotable.

when browser is 100% and lower, the jspdf.autoTable can converted to pdf with border properly but when browser is over 100%, the table cannot be shown any border.

**Comment by simonbengtsson** [comment]
I tried with a both higher and lower zoom in the examples now and it seems to work. Do you have a small example I can look at?
