### ISSUE TITLE
Prevent linebreak over multiple pages

### ISSUE THREAD

**Issue by Jorritboer** [simonbengtsson/jsPDF-AutoTable#954]
Is there a way to prefer a new page over a linebreak? So when a linebreak would cause a new page, instead the entire row is put on the new page? 

So to prevent this:
<img width="760" alt="Scherm­afbeelding 2023-02-18 om 17 51 00" src="https://user-images.githubusercontent.com/45050184/221201361-15795c9c-8fe0-4afd-b788-a4e94ce786b8.png">

**Comment by simonbengtsson** [comment]
Yes! Take a look at the rowPageBreak option.

**Comment by Jorritboer** [comment]
Thanks! Don't know how I missed this...
