### ISSUE TITLE
textPayload: "autoTable is not a function"

### ISSUE THREAD

**Issue by EdnGG** [simonbengtsson/jsPDF-AutoTable#955]
Why i got this error when I'm trying to create a pdf when a new collection is created in firestore

`const { jsPDF } = require('jspdf');
const autoTable = require('jspdf-autotable');

const pdfGenerator2 = async (data, title = 'VSI Incoming report') => {
  const NUMBER_MAX_COLUMNS = 9;
  const headerBody = [
    'Actuator Model',
    'Actuator Serial Number',
    'Control Pack',
    'Visual',
    'Water Inspection',
    'Operational Test',
    'Wire Compartment',
    'Handwheel Bolt Pattern',
    'Observations',
  ];

  const body = await data.data.map((item) => {
    return [
      item.actuatorModel,
      item.actuatorSerialNumber,
      item.controlPack,
      item.visual,
      item.waterInspection,
      item.operationalTest,
      item.wireCompartment,
      item.handwheelBoltPattern,
      item.observaciones,
    ];
  });

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const tableData = [
    [
      {
        content: title,
        colSpan: 9,
        styles: { halign: 'center', fontSize: 16 },
      },
    ],
    [
      { content: `Number: ${data.id}`, colSpan: NUMBER_MAX_COLUMNS / 3 },
      { content: `Date: ${data.date}`, colSpan: NUMBER_MAX_COLUMNS / 3 },
      {
        content: `Technical: ${data.technical}`,
        colSpan: NUMBER_MAX_COLUMNS / 3,
      },
    ],
    headerBody,
    ...body,
    [
      {
        content: 'Final notes:',
        colSpan: 2,
        styles: {
          fillColor: 'green',
          textColor: '#ffffff',
        },
      },
      { content: data.observaciones, colSpan: NUMBER_MAX_COLUMNS - 2 },
    ],
  ];

  const tableConfig = {
    theme: 'grid',
    fontStyle: 'helvetica',
    headerStyles: { fillColor: '#f2f2f2' },
    bodyStyles: { valign: 'top' },
    columnStyles: { 8: { cellWidth: 'auto' } },
  };

  autoTable(doc, {
    head: tableData[2],
    body: tableData.slice(3),
    startY: 50,
    styles: tableConfig,
    tableWidth: 'auto',
  });

  const pdfContent = doc.output('arraybuffer');

  return pdfContent;
};

module.exports = pdfGenerator2;`

**Comment by simonbengtsson** [comment]
Try only the pdf generation by passing in the data manually and see if you still have an issue

**Comment by EdnGG** [comment]
Hi Simon thanks for replying, to give you some context, i dont think
passing the data manually will fix the problem, the reason i said that its
because im using the same function on frontend side and it works, basically
what im trying to do is creating a pdf and attached to the email, but it
seems like its something about the declaration of "autotable".
