### ISSUE TITLE
Headers don't respect alignment in columnStyles

### ISSUE THREAD

**Issue by gabrielnvian** [simonbengtsson/jsPDF-AutoTable#958]
Hello everyone,

I just started using this plugin today, and I noticed that when an alignment is specified in columnStyles, the header does not folllow that.

I think that if all the data is right-aligned, for example, the header should be right-aligned too.

**Comment by simonbengtsson** [comment]
Reasonable expectation. However how it works currently is that styles are only applied to the body of the table when using columnStyles. To apply it for all cells in a column you would need to use hooks. See the custom styles example for sample code.
