### ISSUE TITLE
Header cells wrapping breaks inside words instead of between words. Acts like CSS word-wrap: break-word

### ISSUE THREAD

**Issue by bhamscott** [simonbengtsson/jsPDF-AutoTable#960]
Hello! We are using this plugin and it works great. However, there is a use case where when we have a high column count, the text wrap algorithm in splitTextToSize() ends up breaking words apart instead of doing the linebreak at empty spaces between words - we are using the linebreak overflow rule to allow the header cell text to wrap. When this happens some of the header cells end up placing a single character of the last word on the next available line instead of wrapping the whole word to the last line.

Is this a known issue?

**Comment by bhamscott** [comment]
For what it's worth, here are our settings. This works perfectly except for the issue with linebreak wrapping in the middle of words instead of between words:

`doc.autoTable({
			head: this.buildHeader(columns, extensions),
			body: this.getBody(extensions, columns, gridRows),
			theme: 'grid',
			startY: pageXY.pageY + 10,
			margin: pageOption.getOptions('margin') as number,
			horizontalPageBreak: true,
			tableLineColor: [255, 255, 255],
			// tableLineWidth: 1,
			styles: {
				lineColor: [44, 62, 80],
				lineWidth: 1,
				textColor: 'black',
				fontSize: pageOption.getOptions('tableContentFontSize') as number,
				cellPadding: { left: 5, right: 5, top: 5, bottom: 5 }
			},
			headStyles: {
				fillColor: [255, 255, 255],
				fontSize: pageOption.getOptions('tableHeaderFontSize') as number,
				textColor: 'black',
				overflow: 'linebreak', //'linebreak'|'ellipsize'|'visible'|'hidden' = 'linebreak'
				cellWidth: 'auto',
				valign: 'middle'
			},
			columnStyles: this.getColumnStyles(extensions),`

**Comment by simonbengtsson** [comment]
Interesting! I don't think this is a known issue. Could you reduce the  code only to what is needed to reproduce the issue and include dummy data so the code can be run?

**Comment by bhamscott** [comment]
> Interesting! I don't think this is a known issue. Could you reduce the code only to what is needed to reproduce the issue and include dummy data so the code can be run?

Here are a few examples from here:
https://user-images.githubusercontent.com/17080107/165751806-53f8049e-ab11-4132-b663-0df45cdf3357.png
