### ISSUE TITLE
table.pageStartY missing in new version

### ISSUE THREAD

**Issue by Shuktika15** [simonbengtsson/jsPDF-AutoTable#963]
I have stumbled upon a breaking change but couldn't find any documentation anywhere.

I migrated AutoTable from 3.2.11 to 3.5.28. After doing so ```data.table.pageStartY``` this property started returning undefined in didDrawPage(data) callback. What should be the correct way to migrate @simonbengtsson?

I found out that in v3.2.11 the property was present in Table definition in models.ts but it is not present anymore in latest version.

**Comment by simonbengtsson** [comment]
It was never considered part of the public API so was removed without notice. I understand it could cause confusion however. As a replacement you can get the coordinates before calling the autoTable method.
