### ISSUE TITLE
Schemas doesn't exists

### ISSUE THREAD

**Issue by PatricioAguilarVargas** [simonbengtsson/jsPDF-AutoTable#965]
Hi, i want to report a problem. when i ask for security issues in my company, they tell me about url doesn't exist 
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/94617663/7a430be0-d398-40e4-864f-cd89199e2880)
those url are the schemas from http://schemas.openxmlformats.org/

I ask if this issues can fix

Thanks

**Comment by simonbengtsson** [comment]
Hi! I don't think this is related to this plugin? If it is could you give me some additonal info?
