### ISSUE TITLE
lineWidth as object causes invalid arguments

### ISSUE THREAD

**Issue by mauricewegner** [simonbengtsson/jsPDF-AutoTable#966]
### Description

Since #961 providing the `lineWidth` as an object is causing `Error: Invalid arguments passed to jsPDF.rect`.

### Error example

```ts
lineWidth: {
  top: 1
}
```

### Working example

```ts
lineWidth: 1
```

This is not providing the expected behaviour whatsoever.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-d7tq9j?file=src%2Futil.ts)

### Temporary workaround:

Downgrading to `3.5.28`

**Comment by MikeDabrowski-EQM** [comment]
@simonbengtsson I'll take a look later today. However in my project I used it without any errors.

**Comment by MikeDabrowski** [comment]
I checked out master, updated deps and rebuilt and started examples demo. There we have an example table that has `lineWidth` in different configs (headStyles/cell styles/row styles etc). 

Here is the relevant config bit:
https://github.com/simonbengtsson/jsPDF-AutoTable/blob/03033b12bc022258184b6018bc070dc44b29a51d/examples/examples.js#L512-L606

I also added this locally. In all cases I see no errors
```
headStyles: {
      fillColor: [241, 196, 15],
      fontSize: 15,
      lineWidth: {
        top: 1,
      },
    },
```
Output: (gray top borders)  
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/17836911/6a5c649f-2af9-416d-ae59-81635fee9575)

@mauricewegner (and anyone who +1 this bug) Could you add more details? Maybe full config or a repro project?
I need to know what was passed to the rect function. I suspect something wrong with the color parameter. Did you use colors for lines/borders in your config?

**Comment by mauricewegner** [comment]
> @mauricewegner (and anyone who +1 this bug) Could you add more details? Maybe full config or a repro project? I need to know what was passed to the rect function. I suspect something wrong with the color parameter. Did you use colors for lines/borders in your config?

It turns out that the issue only occurs when using the `fillColor` property simultaneously. I have added a small reproduction to the issue

**Comment by MikeDabrowski** [comment]
@mauricewegner Thanks! For a quick workaround you can convert the hex to rgb array. The fix is on its way.
