### ISSUE TITLE
More than 1 style format inside a cell

### ISSUE THREAD

**Issue by AlexGoMa** [simonbengtsson/jsPDF-AutoTable#968]
I create a table dynamically from JavaScript code. In one point, some cells receive this type of content: ``${data} ${isOutOfRangeFlag}\n${range}`` and it is needed to change font color only in `${range}` part of content. 

I have read it is not possible to have more than 1 style format in 1 cell, and I do not know how to do it without breaking all the table structure and how it is dynamically generated.

Any way to do it?

**Comment by AlexGoMa** [comment]
I think is a bugfix and not only a question. In an array content inside a cell, if in didDrawCell force to change the cell text color for the second array position for example, and this content is long to enough to continue in the following page, in first page the color is not changed, and in the following page it is changed.

**Comment by simonbengtsson** [comment]
May I misunderstood. It sounded like you asked about how to style cell content inside a cell using hooks?

**Comment by AlexGoMa** [comment]
Sorry, maybe I mixed things:

I have a problem styling the content inside a cell using hooks: Using direct JavaScript data I can't show the cell content with 2 different styles.  I haven't found the way to do it in the documentation and examples. Yes, I asked for help.

Trying to solve it, if I use didParseCell to add style to one part of the array that is inside a cell, and then didDrawCell to add another style to the other part of the array inside the same cell, I found the behaviour that I described in the previous message. Maybe I should create another issue and don't mix things.

**Comment by simonbengtsson** [comment]
I'm Still not sure I understand. The plugin always style text in a cell the same. If you want to have multiple text styles in a cell you would have to draw the text yourself with the hooks as you mentionened and the custom styles example I think have an example of using the didParseCell hook for this.

Did you run into issues using the didParseCell hook?
