### ISSUE TITLE
Column Header Title overflow to next column

### ISSUE THREAD

**Issue by nithingit** [simonbengtsson/jsPDF-AutoTable#97]
I want the column header title to continue to the next column if the width of it increases instead of moving to the next line or ellipsize.Is there a way to achieve this,I tried using overflow:'visible' but it is not working.

Thanks

**Comment by simonbengtsson** [comment]
The plugin has no built in feature to do this. You might however to make a hack with the drawCell and afterContent hooks. What is your use case? Wouldn't the title cover the title of the following column?

**Comment by nithingit** [comment]
Actually the following column doesn't have any title .This header is like for both the columns

**Comment by simonbengtsson** [comment]
Aha, so like colspan? Unfortunately the plugin doesn't directly support that either. However check the [rowspan and colspan](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/examples/examples.js#L258) example in examples.js ([demo](https://simonbengtsson.github.io/jsPDF-AutoTable/#spans)). It's not for the header, but it idea should be transferrable to the header.

**Comment by nithingit** [comment]
I have implemented this using colspan,I have two issues 

1.I need to fill the rectangle(doc.rect)with specific color [same color I used for header]
2.if the text inside rectangle exceeds the size of rectangle it should break[overflow:'linebreak']

  doc.rect(data.settings.margin.left, row.y, data.table.width+25, 20, 'S');
                doc.autoTableText("Sl No:"+objcount+"\n"+"text" + data.text, 40 , row.y, {
                    valign: 'top'
                });

**Comment by simonbengtsson** [comment]
Did you solve your issue or are you still having problem?

**Comment by simonbengtsson** [comment]
Closing this for now. Feel free to reopen if you are still having issues.
