### ISSUE TITLE
JavaScript string+\n not fitting well cell space using JavaScript data

### ISSUE THREAD

**Issue by AlexGoMa** [simonbengtsson/jsPDF-AutoTable#979]
I have an issue when filling cell data from an API: In some cells text content is above 40 characters long sometimes, and to structure it has a `\n` to add a new line. 

When PDF is created, in some columns: 
* if style is set to `halign: "left"` data is shown right and fills the cell, but `\n` is omitted, loosing structure and cohesion.
* If style is set to `halign: "center"` new lines are not omitted, but in some lines data overwrites itself inside the cell.

I have tried to add `overflow: 'linebreak'` in those cells but it does not solve it. Also tried converting `\n` to `\r\n` as I read somewhere solves problem, but that doesn't work either.

**Comment by simonbengtsson** [comment]
Sounds like a bug. Can you reproduce it with test data? If so it would be very useful if you could post a small example that reproduced the issue.

**Comment by AlexGoMa** [comment]
Looking at fitcontent function in widthCalculator.ts, in the overflow: 'linebreak' option it is called splitTextToSize:

```
if (cell.styles.overflow === 'linebreak') {
        // Add one pt to textSpace to fix rounding error
        cell.text = doc.splitTextToSize(
          cell.text,
          textSpace + 1 / doc.scaleFactor(),
          { fontSize: cell.styles.fontSize },
        )
      }
```

From what I have read in jspdf documentation, **splitTextToSize** doesn't have in consideration \n , so maybe that's the reason  why when halign="center" is set, the text occupies the vertical space without line breaks, but if there are line breaks, the content is overwritten.

What I have not still found, is why if halign = "left" is applied to styles, the text overrides \n and fits content.
