### ISSUE TITLE
Unable to import autoTable function

### ISSUE THREAD

**Issue by SLeAsian** [simonbengtsson/jsPDF-AutoTable#980]
I tried several different ways of importing autoTable:
- `import {autoTable} from 'jspdf-autotable'`: error shows `Uncaught SyntaxError: The requested module './node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js' does not provide an export named 'autoTable' (at dashboard.js:48:10)`
- `import autoTable from 'jspdf-autotable'`: error shows `Uncaught SyntaxError: The requested module './node_modules/jspdf-autotable/dist/jspdf.plugin.autotable.js' does not provide an export named 'default' (at dashboard.js:48:8)`
- `import 'jspdf-autotable'` and calling `require('jspdf-autotable')`: `require not defined`
- If I do
  `import jsPDF from 'jspdf'`
  `import 'jspdf-autotable'`
  `const doc = new jsPDF()`
  `doc.autoTable({ html: '#my-table' })`
  `doc.save('table.pdf')` error shows `doc.autoTable is not a function`

I am out of importing ideas at this point. What should I do? Thanks in advance!

**Comment by simonbengtsson** [comment]
What environment and config are you using?
