### ISSUE TITLE
Manual Pagebreak

### ISSUE THREAD

**Issue by sirius210** [simonbengtsson/jsPDF-AutoTable#99]
Hi,

First I would like to thank you for this great plugin which makes Pdf printing much more easier. I actually use a table which can have a child row: 
![capture d ecran 2015-12-24 a 14 00 53](https://cloud.githubusercontent.com/assets/16427376/11994879/cb60dea4-aa46-11e5-90cb-1d6509e6dc4d.png)

So the content is created dynamically and I manually create a rect with doc.rect to place the content inside it. When I arrive at the bottom of my page, the area I have created can be too high for my page. Like this : 

![capture d ecran 2015-12-24 a 14 12 05](https://cloud.githubusercontent.com/assets/16427376/11994954/5a27964a-aa48-11e5-9d55-847bf72b6a56.png)

I have seen in the src that there is a function pageBreak. Is it possible to call it manually ? I would like to use a "pageBreak" and not a "addPage" because I would like to draw again the header and the footer of my page.

Thank you for your answer,

Regards.

**Comment by simonbengtsson** [comment]
Thanks! I'm not completely sure I understand what you are looking for. Do you want to split the table in multiple pieces on the same page? That is something that is not supported but it might be a good idea to add to the plugin if that is what you were looking for.

**Comment by sirius210** [comment]
Hi Simon and thank you for your answer.

That's not exaclty what I am looking for. I will try to explain more precisely...

I have a table with, for example, 8 columns and I want to print it with your plugin. However my last column can contain a lot of HTML text so it is impossible to add my long text directly in the last column (I w

My solution was to make a "simple" row with the text of the 7th first column and to add under a "big" row with my big HTML text. So what you can see on my printscreen is : 

-A "simple" row with 4 columns. 
- A "big" row with long HTML text (to manage easyly colours, font parameters, font type ....)

Because I add customized rows, your plugin can not calculate when to make a new page. I manually calculate where is my table bottom and say where I have to add a page. Here is my question : I don't want to use a "addPage" but a "pageBreak" which can create a table header, a new page, ....

**Comment by sirius210** [comment]
My situation is like your example "Col and row span". In my case I don't make a "header" row (priority group, other groups), but I make a "footer" row with a dynamic height and not the initial row height. My row height will depend of my HTML text (big text = higher row).

If you need more details to try to help me, just ask :)

**Comment by simonbengtsson** [comment]
Okey! So you want to be able to manually choose when to add a new page as the built in height calculations doesn't work for your use case. Shouldn't be too hard to add, but it might be hard to make it work correctly. I'll see what I can do anyhow!

**Comment by sirius210** [comment]
Yes exactly. That's complicated but it can be usefull for people like me who doesn't use arrays with only short text but sometimes arrays which can contain a bigger formated text in a rect. Thank you !

**Comment by simonbengtsson** [comment]
I marked this as future work in the readme so I'll be closing this issue for now. I have no timeplan for when I'll be doing it, but will probably done at some point. If someone else feels up for it, I will gladly accept a pull request.
