### ISSUE TITLE
lineWidth for one side is applying on all side

### ISSUE THREAD

**Issue by TimothyAtChain** [simonbengtsson/jsPDF-AutoTable#990]
I set the lineWidth as {bottom: 0.5} for a cell in header, and the cell had a line width of 0.5 for four sides
I am now using the latest version of this library

**Comment by simonbengtsson** [comment]
Does the border example work for you?

**Comment by TimothyAtChain** [comment]
I think I found the reason
I have to set the fillColor for the cell also
