### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by tovornik** [simonbengtsson/jsPDF-AutoTable#995]
Hello, great plugin, love it, but I've stumbled upon a missing header issue.

I'm using the latest version of the plugin ↓
```html
<script src="https://unpkg.com/jspdf@latest/dist/jspdf.umd.min.js"></script>
<script src="https://unpkg.com/jspdf-autotable@3.6.0/dist/jspdf.plugin.autotable.js"></script>
```

I have a fairly simple HTML table ↓
```html
<table class="table reportTable">
    <thead>
        <th>First header</th>
        <th>Second header</th>
        <th>Third header</th>
    </thead>
    <tbody class="table-group-divider">
        <tr>
            <td>First row</td>
            <td>Second row</td>
            <td>Third row</td>
        </tr>
    </tbody>
</table>
```

which I try to save to PDF with this Javascript function ↓
```js
function createPDF(reportName) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    doc.text(reportName, 10, 10);
    doc.autoTable({ startY: 15, html: '.reportTable' });
    
    doc.save(`${reportName}.pdf`);
}
```

but the headers are missing in the PDF file. I also tried with element IDs instead of classes but it didn't help.

**Comment by mmghv** [comment]
Just tested it, headers are present, can you create a codepen that reproduces the problem?

**Comment by tovornik** [comment]
You're right. This (https://codepen.io/Jan-Tovornik/pen/vYvjMJb) is 99% of my original code and it works on Codepen while the actual code doesn't work. I don't know what could be affecting this. Sorry for wasting your time.

**Comment by mmghv** [comment]
Feel free to leave an update if you manage to reproduce the problem in a codepen.

**Comment by tovornik** [comment]
@mmghv I got the reproduce. Due to some app demands, I had to switch from a hardcoded table in HTML to generating HTML tables with JS. Here's an example of creating an HTML table with headers and two rows using JS → https://codepen.io/Jan-Tovornik/pen/vYvjMJb.

Result: missing headers ↓
![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/18674006/1f14bbf6-6b92-4028-9a32-031ed71ea97b)

**Comment by mmghv** [comment]
The problem came out to be a missing `<tr>` in `<thead>`, apparently it only causes a problem when the html table is generated from js.

So just wrap your header's `<th>`s in a `<tr>` and it will show in the PDF.

**Comment by tovornik** [comment]
@mmghv that indeed solved it, thank you!
