### ISSUE TITLE
Images overlapping with each other while inserting them

### ISSUE THREAD

**Issue by codingmickey** [simonbengtsson/jsPDF-AutoTable#996]
Here is the below generated table.. I'm first passing the image URL in the body parameters and also set a minRowHeight of the specified value as well as colWidth of the image column I want to as the width, then using did `didParseCell` to clear the image URL before inserting it into the pdf, and using `didDrawCell` to draw the image in that specified cell.. everything was running fine until now and I was getting the proper results. But don't know how these images are overlapping with each other.. literally no idea why this is happening when it was and is properly working for others..

![image](https://github.com/simonbengtsson/jsPDF-AutoTable/assets/42518907/5fb6ae3d-8466-47dc-9e7b-cb50b8c4a717)

I'm using:
```json
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.6.0",
```

**Comment by codingmickey** [comment]
Or maybe I am wrong and this issue could be of `js-pdf`?

**Comment by mmghv** [comment]
Please reproduce it in a codepen with a minimal example.

**Comment by codingmickey** [comment]
Hey @mmghv, sure once I'm done delivering this project to the client
(as this bug is avoidable for now, as I think there is some format issue `.png` files give this issue.. )
