### ISSUE TITLE
jspdf_autotable__WEBPACK_IMPORTED_MODULE_0__ is not a function

### ISSUE THREAD

**Issue by bharat947** [simonbengtsson/jsPDF-AutoTable#998]
I created bk-export libraries in angular 15 for pdf downloads in our application. If I point to my local project folder, then it's working fine, but it's not working through libraries.
<img width="413" alt="image" src="https://github.com/simonbengtsson/jsPDF-AutoTable/assets/34002852/686f69da-a2a9-4766-86c6-77b95df171ea">
bk-export libraries code below:- npm i bk-export@0.0.4
```
import autoTable from 'jspdf-autotable';
import { jsPDF } from 'jspdf';
export function exportPDF(tableHeader:any,screenName:any,pageHeader:any,rows:any){
   let header=tableHeader
   var img = new Image();
   img.src = 'assets/logo.png'
   let doc = new jsPDF('p', 'mm', 'A4')
   let col: any = [];
   col = [header];
   doc.setFillColor(255, 128,0);
   doc.rect(5, 24, 200, 8, "F");
   doc.setFontSize(14); 
   doc.text(pageHeader, 86, 30);
   doc.addImage(img, 'gif', 170, 5, 30, 15);
   autoTable(doc, {
     head: col,
     body: rows,
     showHead: "everyPage",
     startY: 35,
     margin: {right:5,left:5},
     tableWidth: 'auto',
     didDrawPage: (dataArg:any) => {
       doc.text('', dataArg.settings.margin.left, 20);
     }
   });
   doc.save(screenName + '.pdf');
}
```

**Comment by mmghv** [comment]
I think that's a problem with your setup, make sure `jspdf-autotable` is installed.

**Comment by bharat947** [comment]
> I think that's a problem with your setup, make sure `jspdf-autotable` is installed.

Yeah. Its already installed that why its working in local

**Comment by mmghv** [comment]
> but it's not working through libraries

Don't exactly know what you mean by that!

You need to do some debugging locally with your setup, see if the module is loaded at all, and where is that `jspdf_autotable__WEBPACK_IMPORTED_MODULE_0__ ` function coming from, from the look of it could be misconfiguration.
